#![doc = include_str!("../../../../crates/libs/bindgen/readme.md")]
#![doc = include_str!("../../../../crates/libs/core/readme.md")]
#![doc = include_str!("../../../../crates/libs/metadata/readme.md")]
#![doc = include_str!("../../../../crates/libs/sys/readme.md")]
#![doc = include_str!("../../../../crates/libs/targets/readme.md")]
#![doc = include_str!("../../../../crates/libs/windows/readme.md")]
