#[repr(transparent)]
#[derive(Clone, Copy, Debug, Default, Eq, PartialEq)]
pub struct CONDITION_OPERATION(pub i32);
#[repr(transparent)]
#[derive(Clone, Copy, Debug, Default, Eq, PartialEq)]
pub struct CONDITION_TYPE(pub i32);
pub const COP_APPLICATION_SPECIFIC: CONDITION_OPERATION = CONDITION_OPERATION(14);
pub const COP_DOSWILDCARDS: CONDITION_OPERATION = CONDITION_OPERATION(11);
pub const COP_EQUAL: CONDITION_OPERATION = CONDITION_OPERATION(1);
pub const COP_GREATERTHAN: CONDITION_OPERATION = CONDITION_OPERATION(4);
pub const COP_GREATERTHANOREQUAL: CONDITION_OPERATION = CONDITION_OPERATION(6);
pub const COP_IMPLICIT: CONDITION_OPERATION = CONDITION_OPERATION(0);
pub const COP_LESSTHAN: CONDITION_OPERATION = CONDITION_OPERATION(3);
pub const COP_LESSTHANOREQUAL: CONDITION_OPERATION = CONDITION_OPERATION(5);
pub const COP_NOTEQUAL: CONDITION_OPERATION = CONDITION_OPERATION(2);
pub const COP_VALUE_CONTAINS: CONDITION_OPERATION = CONDITION_OPERATION(9);
pub const COP_VALUE_ENDSWITH: CONDITION_OPERATION = CONDITION_OPERATION(8);
pub const COP_VALUE_NOTCONTAINS: CONDITION_OPERATION = CONDITION_OPERATION(10);
pub const COP_VALUE_STARTSWITH: CONDITION_OPERATION = CONDITION_OPERATION(7);
pub const COP_WORD_EQUAL: CONDITION_OPERATION = CONDITION_OPERATION(12);
pub const COP_WORD_STARTSWITH: CONDITION_OPERATION = CONDITION_OPERATION(13);
pub const CT_AND_CONDITION: CONDITION_TYPE = CONDITION_TYPE(0);
pub const CT_LEAF_CONDITION: CONDITION_TYPE = CONDITION_TYPE(3);
pub const CT_NOT_CONDITION: CONDITION_TYPE = CONDITION_TYPE(2);
pub const CT_OR_CONDITION: CONDITION_TYPE = CONDITION_TYPE(1);
