[package]
name = "windows-default"
version = "0.100.0"
edition = "2024"
rust-version = "1.95"
license = "MIT OR Apache-2.0"
description = "Default Windows metadata"
repository = "https://github.com/microsoft/windows-rs"
categories = ["os::windows-apis"]
readme = "readme.md"
include = [
    "src/**/*.rs",
    "Windows.winmd",
    "Windows.Win32.winmd",
    "readme.md",
    "license-*",
]

[lints]
workspace = true

[package.metadata.docs.rs]
targets = []
