[package]
name = "windows-tracing"
version = "0.100.0"
edition = "2024"
rust-version = "1.95"
license = "MIT OR Apache-2.0"
description = "TraceLogging events for Event Tracing for Windows"
repository = "https://github.com/microsoft/windows-rs"
categories = ["os::windows-apis"]
readme = "readme.md"

[dependencies]
windows-core = { workspace = true }
windows-link = { workspace = true }
windows-result = { workspace = true }
windows-tracing-macros = { workspace = true }

[lints]
workspace = true

[package.metadata.docs.rs]
default-target = "x86_64-pc-windows-msvc"
targets = []
