cargo publish windows_aarch64_msvc
cargo publish windows_i686_gnu
cargo publish windows_i686_msvc
cargo publish windows_x86_64_gnu
cargo publish windows_x86_64_msvc
cargo publish windows-tokens
cargo publish windows-metadata
cargo publish windows-interface
cargo publish windows-implement
cargo publish windows-bindgen
cargo publish windows
