windows_link::link!("opengl32.dll" "system" fn glAccum(op : GLenum, value : f32));
windows_link::link!("opengl32.dll" "system" fn glAlphaFunc(func : GLenum, r#ref : f32));
windows_link::link!("opengl32.dll" "system" fn glAreTexturesResident(n : GLsizei, textures : *const GLuint, residences : *mut GLboolean) -> GLboolean);
windows_link::link!("opengl32.dll" "system" fn glArrayElement(i : GLint));
windows_link::link!("opengl32.dll" "system" fn glBegin(mode : GLenum));
windows_link::link!("opengl32.dll" "system" fn glBindTexture(target : GLenum, texture : GLuint));
windows_link::link!("opengl32.dll" "system" fn glBitmap(width : GLsizei, height : GLsizei, xorig : f32, yorig : f32, xmove : f32, ymove : f32, bitmap : *const GLubyte));
windows_link::link!("opengl32.dll" "system" fn glBlendFunc(sfactor : GLenum, dfactor : GLenum));
windows_link::link!("opengl32.dll" "system" fn glCallList(list : GLuint));
windows_link::link!("opengl32.dll" "system" fn glCallLists(n : GLsizei, r#type : GLenum, lists : *const GLvoid));
windows_link::link!("opengl32.dll" "system" fn glClear(mask : GLbitfield));
windows_link::link!("opengl32.dll" "system" fn glClearAccum(red : f32, green : f32, blue : f32, alpha : f32));
windows_link::link!("opengl32.dll" "system" fn glClearColor(red : f32, green : f32, blue : f32, alpha : f32));
windows_link::link!("opengl32.dll" "system" fn glClearDepth(depth : f64));
windows_link::link!("opengl32.dll" "system" fn glClearIndex(c : f32));
windows_link::link!("opengl32.dll" "system" fn glClearStencil(s : GLint));
windows_link::link!("opengl32.dll" "system" fn glClipPlane(plane : GLenum, equation : *const f64));
windows_link::link!("opengl32.dll" "system" fn glColor3b(red : GLbyte, green : GLbyte, blue : GLbyte));
windows_link::link!("opengl32.dll" "system" fn glColor3bv(v : *const GLbyte));
windows_link::link!("opengl32.dll" "system" fn glColor3d(red : f64, green : f64, blue : f64));
windows_link::link!("opengl32.dll" "system" fn glColor3dv(v : *const f64));
windows_link::link!("opengl32.dll" "system" fn glColor3f(red : f32, green : f32, blue : f32));
windows_link::link!("opengl32.dll" "system" fn glColor3fv(v : *const f32));
windows_link::link!("opengl32.dll" "system" fn glColor3i(red : GLint, green : GLint, blue : GLint));
windows_link::link!("opengl32.dll" "system" fn glColor3iv(v : *const GLint));
windows_link::link!("opengl32.dll" "system" fn glColor3s(red : GLshort, green : GLshort, blue : GLshort));
windows_link::link!("opengl32.dll" "system" fn glColor3sv(v : *const GLshort));
windows_link::link!("opengl32.dll" "system" fn glColor3ub(red : GLubyte, green : GLubyte, blue : GLubyte));
windows_link::link!("opengl32.dll" "system" fn glColor3ubv(v : *const GLubyte));
windows_link::link!("opengl32.dll" "system" fn glColor3ui(red : GLuint, green : GLuint, blue : GLuint));
windows_link::link!("opengl32.dll" "system" fn glColor3uiv(v : *const GLuint));
windows_link::link!("opengl32.dll" "system" fn glColor3us(red : GLushort, green : GLushort, blue : GLushort));
windows_link::link!("opengl32.dll" "system" fn glColor3usv(v : *const GLushort));
windows_link::link!("opengl32.dll" "system" fn glColor4b(red : GLbyte, green : GLbyte, blue : GLbyte, alpha : GLbyte));
windows_link::link!("opengl32.dll" "system" fn glColor4bv(v : *const GLbyte));
windows_link::link!("opengl32.dll" "system" fn glColor4d(red : f64, green : f64, blue : f64, alpha : f64));
windows_link::link!("opengl32.dll" "system" fn glColor4dv(v : *const f64));
windows_link::link!("opengl32.dll" "system" fn glColor4f(red : f32, green : f32, blue : f32, alpha : f32));
windows_link::link!("opengl32.dll" "system" fn glColor4fv(v : *const f32));
windows_link::link!("opengl32.dll" "system" fn glColor4i(red : GLint, green : GLint, blue : GLint, alpha : GLint));
windows_link::link!("opengl32.dll" "system" fn glColor4iv(v : *const GLint));
windows_link::link!("opengl32.dll" "system" fn glColor4s(red : GLshort, green : GLshort, blue : GLshort, alpha : GLshort));
windows_link::link!("opengl32.dll" "system" fn glColor4sv(v : *const GLshort));
windows_link::link!("opengl32.dll" "system" fn glColor4ub(red : GLubyte, green : GLubyte, blue : GLubyte, alpha : GLubyte));
windows_link::link!("opengl32.dll" "system" fn glColor4ubv(v : *const GLubyte));
windows_link::link!("opengl32.dll" "system" fn glColor4ui(red : GLuint, green : GLuint, blue : GLuint, alpha : GLuint));
windows_link::link!("opengl32.dll" "system" fn glColor4uiv(v : *const GLuint));
windows_link::link!("opengl32.dll" "system" fn glColor4us(red : GLushort, green : GLushort, blue : GLushort, alpha : GLushort));
windows_link::link!("opengl32.dll" "system" fn glColor4usv(v : *const GLushort));
windows_link::link!("opengl32.dll" "system" fn glColorMask(red : GLboolean, green : GLboolean, blue : GLboolean, alpha : GLboolean));
windows_link::link!("opengl32.dll" "system" fn glColorMaterial(face : GLenum, mode : GLenum));
windows_link::link!("opengl32.dll" "system" fn glColorPointer(size : GLint, r#type : GLenum, stride : GLsizei, pointer : *const GLvoid));
windows_link::link!("opengl32.dll" "system" fn glCopyPixels(x : GLint, y : GLint, width : GLsizei, height : GLsizei, r#type : GLenum));
windows_link::link!("opengl32.dll" "system" fn glCopyTexImage1D(target : GLenum, level : GLint, internalformat : GLenum, x : GLint, y : GLint, width : GLsizei, border : GLint));
windows_link::link!("opengl32.dll" "system" fn glCopyTexImage2D(target : GLenum, level : GLint, internalformat : GLenum, x : GLint, y : GLint, width : GLsizei, height : GLsizei, border : GLint));
windows_link::link!("opengl32.dll" "system" fn glCopyTexSubImage1D(target : GLenum, level : GLint, xoffset : GLint, x : GLint, y : GLint, width : GLsizei));
windows_link::link!("opengl32.dll" "system" fn glCopyTexSubImage2D(target : GLenum, level : GLint, xoffset : GLint, yoffset : GLint, x : GLint, y : GLint, width : GLsizei, height : GLsizei));
windows_link::link!("opengl32.dll" "system" fn glCullFace(mode : GLenum));
windows_link::link!("opengl32.dll" "system" fn glDeleteLists(list : GLuint, range : GLsizei));
windows_link::link!("opengl32.dll" "system" fn glDeleteTextures(n : GLsizei, textures : *const GLuint));
windows_link::link!("opengl32.dll" "system" fn glDepthFunc(func : GLenum));
windows_link::link!("opengl32.dll" "system" fn glDepthMask(flag : GLboolean));
windows_link::link!("opengl32.dll" "system" fn glDepthRange(znear : f64, zfar : f64));
windows_link::link!("opengl32.dll" "system" fn glDisable(cap : GLenum));
windows_link::link!("opengl32.dll" "system" fn glDisableClientState(array : GLenum));
windows_link::link!("opengl32.dll" "system" fn glDrawArrays(mode : GLenum, first : GLint, count : GLsizei));
windows_link::link!("opengl32.dll" "system" fn glDrawBuffer(mode : GLenum));
windows_link::link!("opengl32.dll" "system" fn glDrawElements(mode : GLenum, count : GLsizei, r#type : GLenum, indices : *const GLvoid));
windows_link::link!("opengl32.dll" "system" fn glDrawPixels(width : GLsizei, height : GLsizei, format : GLenum, r#type : GLenum, pixels : *const GLvoid));
windows_link::link!("opengl32.dll" "system" fn glEdgeFlag(flag : GLboolean));
windows_link::link!("opengl32.dll" "system" fn glEdgeFlagPointer(stride : GLsizei, pointer : *const GLvoid));
windows_link::link!("opengl32.dll" "system" fn glEdgeFlagv(flag : *const GLboolean));
windows_link::link!("opengl32.dll" "system" fn glEnable(cap : GLenum));
windows_link::link!("opengl32.dll" "system" fn glEnableClientState(array : GLenum));
windows_link::link!("opengl32.dll" "system" fn glEnd());
windows_link::link!("opengl32.dll" "system" fn glEndList());
windows_link::link!("opengl32.dll" "system" fn glEvalCoord1d(u : f64));
windows_link::link!("opengl32.dll" "system" fn glEvalCoord1dv(u : *const f64));
windows_link::link!("opengl32.dll" "system" fn glEvalCoord1f(u : f32));
windows_link::link!("opengl32.dll" "system" fn glEvalCoord1fv(u : *const f32));
windows_link::link!("opengl32.dll" "system" fn glEvalCoord2d(u : f64, v : f64));
windows_link::link!("opengl32.dll" "system" fn glEvalCoord2dv(u : *const f64));
windows_link::link!("opengl32.dll" "system" fn glEvalCoord2f(u : f32, v : f32));
windows_link::link!("opengl32.dll" "system" fn glEvalCoord2fv(u : *const f32));
windows_link::link!("opengl32.dll" "system" fn glEvalMesh1(mode : GLenum, i1 : GLint, i2 : GLint));
windows_link::link!("opengl32.dll" "system" fn glEvalMesh2(mode : GLenum, i1 : GLint, i2 : GLint, j1 : GLint, j2 : GLint));
windows_link::link!("opengl32.dll" "system" fn glEvalPoint1(i : GLint));
windows_link::link!("opengl32.dll" "system" fn glEvalPoint2(i : GLint, j : GLint));
windows_link::link!("opengl32.dll" "system" fn glFeedbackBuffer(size : GLsizei, r#type : GLenum, buffer : *mut f32));
windows_link::link!("opengl32.dll" "system" fn glFinish());
windows_link::link!("opengl32.dll" "system" fn glFlush());
windows_link::link!("opengl32.dll" "system" fn glFogf(pname : GLenum, param : f32));
windows_link::link!("opengl32.dll" "system" fn glFogfv(pname : GLenum, params : *const f32));
windows_link::link!("opengl32.dll" "system" fn glFogi(pname : GLenum, param : GLint));
windows_link::link!("opengl32.dll" "system" fn glFogiv(pname : GLenum, params : *const GLint));
windows_link::link!("opengl32.dll" "system" fn glFrontFace(mode : GLenum));
windows_link::link!("opengl32.dll" "system" fn glFrustum(left : f64, right : f64, bottom : f64, top : f64, znear : f64, zfar : f64));
windows_link::link!("opengl32.dll" "system" fn glGenLists(range : GLsizei) -> GLuint);
windows_link::link!("opengl32.dll" "system" fn glGenTextures(n : GLsizei, textures : *mut GLuint));
windows_link::link!("opengl32.dll" "system" fn glGetBooleanv(pname : GLenum, params : *mut GLboolean));
windows_link::link!("opengl32.dll" "system" fn glGetClipPlane(plane : GLenum, equation : *mut f64));
windows_link::link!("opengl32.dll" "system" fn glGetDoublev(pname : GLenum, params : *mut f64));
windows_link::link!("opengl32.dll" "system" fn glGetError() -> GLenum);
windows_link::link!("opengl32.dll" "system" fn glGetFloatv(pname : GLenum, params : *mut f32));
windows_link::link!("opengl32.dll" "system" fn glGetIntegerv(pname : GLenum, params : *mut GLint));
windows_link::link!("opengl32.dll" "system" fn glGetLightfv(light : GLenum, pname : GLenum, params : *mut f32));
windows_link::link!("opengl32.dll" "system" fn glGetLightiv(light : GLenum, pname : GLenum, params : *mut GLint));
windows_link::link!("opengl32.dll" "system" fn glGetMapdv(target : GLenum, query : GLenum, v : *mut f64));
windows_link::link!("opengl32.dll" "system" fn glGetMapfv(target : GLenum, query : GLenum, v : *mut f32));
windows_link::link!("opengl32.dll" "system" fn glGetMapiv(target : GLenum, query : GLenum, v : *mut GLint));
windows_link::link!("opengl32.dll" "system" fn glGetMaterialfv(face : GLenum, pname : GLenum, params : *mut f32));
windows_link::link!("opengl32.dll" "system" fn glGetMaterialiv(face : GLenum, pname : GLenum, params : *mut GLint));
windows_link::link!("opengl32.dll" "system" fn glGetPixelMapfv(map : GLenum, values : *mut f32));
windows_link::link!("opengl32.dll" "system" fn glGetPixelMapuiv(map : GLenum, values : *mut GLuint));
windows_link::link!("opengl32.dll" "system" fn glGetPixelMapusv(map : GLenum, values : *mut GLushort));
windows_link::link!("opengl32.dll" "system" fn glGetPointerv(pname : GLenum, params : *mut *mut GLvoid));
windows_link::link!("opengl32.dll" "system" fn glGetPolygonStipple(mask : *mut GLubyte));
windows_link::link!("opengl32.dll" "system" fn glGetString(name : GLenum) -> *const GLubyte);
windows_link::link!("opengl32.dll" "system" fn glGetTexEnvfv(target : GLenum, pname : GLenum, params : *mut f32));
windows_link::link!("opengl32.dll" "system" fn glGetTexEnviv(target : GLenum, pname : GLenum, params : *mut GLint));
windows_link::link!("opengl32.dll" "system" fn glGetTexGendv(coord : GLenum, pname : GLenum, params : *mut f64));
windows_link::link!("opengl32.dll" "system" fn glGetTexGenfv(coord : GLenum, pname : GLenum, params : *mut f32));
windows_link::link!("opengl32.dll" "system" fn glGetTexGeniv(coord : GLenum, pname : GLenum, params : *mut GLint));
windows_link::link!("opengl32.dll" "system" fn glGetTexImage(target : GLenum, level : GLint, format : GLenum, r#type : GLenum, pixels : *mut GLvoid));
windows_link::link!("opengl32.dll" "system" fn glGetTexLevelParameterfv(target : GLenum, level : GLint, pname : GLenum, params : *mut f32));
windows_link::link!("opengl32.dll" "system" fn glGetTexLevelParameteriv(target : GLenum, level : GLint, pname : GLenum, params : *mut GLint));
windows_link::link!("opengl32.dll" "system" fn glGetTexParameterfv(target : GLenum, pname : GLenum, params : *mut f32));
windows_link::link!("opengl32.dll" "system" fn glGetTexParameteriv(target : GLenum, pname : GLenum, params : *mut GLint));
windows_link::link!("opengl32.dll" "system" fn glHint(target : GLenum, mode : GLenum));
windows_link::link!("opengl32.dll" "system" fn glIndexMask(mask : GLuint));
windows_link::link!("opengl32.dll" "system" fn glIndexPointer(r#type : GLenum, stride : GLsizei, pointer : *const GLvoid));
windows_link::link!("opengl32.dll" "system" fn glIndexd(c : f64));
windows_link::link!("opengl32.dll" "system" fn glIndexdv(c : *const f64));
windows_link::link!("opengl32.dll" "system" fn glIndexf(c : f32));
windows_link::link!("opengl32.dll" "system" fn glIndexfv(c : *const f32));
windows_link::link!("opengl32.dll" "system" fn glIndexi(c : GLint));
windows_link::link!("opengl32.dll" "system" fn glIndexiv(c : *const GLint));
windows_link::link!("opengl32.dll" "system" fn glIndexs(c : GLshort));
windows_link::link!("opengl32.dll" "system" fn glIndexsv(c : *const GLshort));
windows_link::link!("opengl32.dll" "system" fn glIndexub(c : GLubyte));
windows_link::link!("opengl32.dll" "system" fn glIndexubv(c : *const GLubyte));
windows_link::link!("opengl32.dll" "system" fn glInitNames());
windows_link::link!("opengl32.dll" "system" fn glInterleavedArrays(format : GLenum, stride : GLsizei, pointer : *const GLvoid));
windows_link::link!("opengl32.dll" "system" fn glIsEnabled(cap : GLenum) -> GLboolean);
windows_link::link!("opengl32.dll" "system" fn glIsList(list : GLuint) -> GLboolean);
windows_link::link!("opengl32.dll" "system" fn glIsTexture(texture : GLuint) -> GLboolean);
windows_link::link!("opengl32.dll" "system" fn glLightModelf(pname : GLenum, param : f32));
windows_link::link!("opengl32.dll" "system" fn glLightModelfv(pname : GLenum, params : *const f32));
windows_link::link!("opengl32.dll" "system" fn glLightModeli(pname : GLenum, param : GLint));
windows_link::link!("opengl32.dll" "system" fn glLightModeliv(pname : GLenum, params : *const GLint));
windows_link::link!("opengl32.dll" "system" fn glLightf(light : GLenum, pname : GLenum, param : f32));
windows_link::link!("opengl32.dll" "system" fn glLightfv(light : GLenum, pname : GLenum, params : *const f32));
windows_link::link!("opengl32.dll" "system" fn glLighti(light : GLenum, pname : GLenum, param : GLint));
windows_link::link!("opengl32.dll" "system" fn glLightiv(light : GLenum, pname : GLenum, params : *const GLint));
windows_link::link!("opengl32.dll" "system" fn glLineStipple(factor : GLint, pattern : GLushort));
windows_link::link!("opengl32.dll" "system" fn glLineWidth(width : f32));
windows_link::link!("opengl32.dll" "system" fn glListBase(base : GLuint));
windows_link::link!("opengl32.dll" "system" fn glLoadIdentity());
windows_link::link!("opengl32.dll" "system" fn glLoadMatrixd(m : *const f64));
windows_link::link!("opengl32.dll" "system" fn glLoadMatrixf(m : *const f32));
windows_link::link!("opengl32.dll" "system" fn glLoadName(name : GLuint));
windows_link::link!("opengl32.dll" "system" fn glLogicOp(opcode : GLenum));
windows_link::link!("opengl32.dll" "system" fn glMap1d(target : GLenum, u1 : f64, u2 : f64, stride : GLint, order : GLint, points : *const f64));
windows_link::link!("opengl32.dll" "system" fn glMap1f(target : GLenum, u1 : f32, u2 : f32, stride : GLint, order : GLint, points : *const f32));
windows_link::link!("opengl32.dll" "system" fn glMap2d(target : GLenum, u1 : f64, u2 : f64, ustride : GLint, uorder : GLint, v1 : f64, v2 : f64, vstride : GLint, vorder : GLint, points : *const f64));
windows_link::link!("opengl32.dll" "system" fn glMap2f(target : GLenum, u1 : f32, u2 : f32, ustride : GLint, uorder : GLint, v1 : f32, v2 : f32, vstride : GLint, vorder : GLint, points : *const f32));
windows_link::link!("opengl32.dll" "system" fn glMapGrid1d(un : GLint, u1 : f64, u2 : f64));
windows_link::link!("opengl32.dll" "system" fn glMapGrid1f(un : GLint, u1 : f32, u2 : f32));
windows_link::link!("opengl32.dll" "system" fn glMapGrid2d(un : GLint, u1 : f64, u2 : f64, vn : GLint, v1 : f64, v2 : f64));
windows_link::link!("opengl32.dll" "system" fn glMapGrid2f(un : GLint, u1 : f32, u2 : f32, vn : GLint, v1 : f32, v2 : f32));
windows_link::link!("opengl32.dll" "system" fn glMaterialf(face : GLenum, pname : GLenum, param : f32));
windows_link::link!("opengl32.dll" "system" fn glMaterialfv(face : GLenum, pname : GLenum, params : *const f32));
windows_link::link!("opengl32.dll" "system" fn glMateriali(face : GLenum, pname : GLenum, param : GLint));
windows_link::link!("opengl32.dll" "system" fn glMaterialiv(face : GLenum, pname : GLenum, params : *const GLint));
windows_link::link!("opengl32.dll" "system" fn glMatrixMode(mode : GLenum));
windows_link::link!("opengl32.dll" "system" fn glMultMatrixd(m : *const f64));
windows_link::link!("opengl32.dll" "system" fn glMultMatrixf(m : *const f32));
windows_link::link!("opengl32.dll" "system" fn glNewList(list : GLuint, mode : GLenum));
windows_link::link!("opengl32.dll" "system" fn glNormal3b(nx : GLbyte, ny : GLbyte, nz : GLbyte));
windows_link::link!("opengl32.dll" "system" fn glNormal3bv(v : *const GLbyte));
windows_link::link!("opengl32.dll" "system" fn glNormal3d(nx : f64, ny : f64, nz : f64));
windows_link::link!("opengl32.dll" "system" fn glNormal3dv(v : *const f64));
windows_link::link!("opengl32.dll" "system" fn glNormal3f(nx : f32, ny : f32, nz : f32));
windows_link::link!("opengl32.dll" "system" fn glNormal3fv(v : *const f32));
windows_link::link!("opengl32.dll" "system" fn glNormal3i(nx : GLint, ny : GLint, nz : GLint));
windows_link::link!("opengl32.dll" "system" fn glNormal3iv(v : *const GLint));
windows_link::link!("opengl32.dll" "system" fn glNormal3s(nx : GLshort, ny : GLshort, nz : GLshort));
windows_link::link!("opengl32.dll" "system" fn glNormal3sv(v : *const GLshort));
windows_link::link!("opengl32.dll" "system" fn glNormalPointer(r#type : GLenum, stride : GLsizei, pointer : *const GLvoid));
windows_link::link!("opengl32.dll" "system" fn glOrtho(left : f64, right : f64, bottom : f64, top : f64, znear : f64, zfar : f64));
windows_link::link!("opengl32.dll" "system" fn glPassThrough(token : f32));
windows_link::link!("opengl32.dll" "system" fn glPixelMapfv(map : GLenum, mapsize : GLsizei, values : *const f32));
windows_link::link!("opengl32.dll" "system" fn glPixelMapuiv(map : GLenum, mapsize : GLsizei, values : *const GLuint));
windows_link::link!("opengl32.dll" "system" fn glPixelMapusv(map : GLenum, mapsize : GLsizei, values : *const GLushort));
windows_link::link!("opengl32.dll" "system" fn glPixelStoref(pname : GLenum, param : f32));
windows_link::link!("opengl32.dll" "system" fn glPixelStorei(pname : GLenum, param : GLint));
windows_link::link!("opengl32.dll" "system" fn glPixelTransferf(pname : GLenum, param : f32));
windows_link::link!("opengl32.dll" "system" fn glPixelTransferi(pname : GLenum, param : GLint));
windows_link::link!("opengl32.dll" "system" fn glPixelZoom(xfactor : f32, yfactor : f32));
windows_link::link!("opengl32.dll" "system" fn glPointSize(size : f32));
windows_link::link!("opengl32.dll" "system" fn glPolygonMode(face : GLenum, mode : GLenum));
windows_link::link!("opengl32.dll" "system" fn glPolygonOffset(factor : f32, units : f32));
windows_link::link!("opengl32.dll" "system" fn glPolygonStipple(mask : *const GLubyte));
windows_link::link!("opengl32.dll" "system" fn glPopAttrib());
windows_link::link!("opengl32.dll" "system" fn glPopClientAttrib());
windows_link::link!("opengl32.dll" "system" fn glPopMatrix());
windows_link::link!("opengl32.dll" "system" fn glPopName());
windows_link::link!("opengl32.dll" "system" fn glPrioritizeTextures(n : GLsizei, textures : *const GLuint, priorities : *const f32));
windows_link::link!("opengl32.dll" "system" fn glPushAttrib(mask : GLbitfield));
windows_link::link!("opengl32.dll" "system" fn glPushClientAttrib(mask : GLbitfield));
windows_link::link!("opengl32.dll" "system" fn glPushMatrix());
windows_link::link!("opengl32.dll" "system" fn glPushName(name : GLuint));
windows_link::link!("opengl32.dll" "system" fn glRasterPos2d(x : f64, y : f64));
windows_link::link!("opengl32.dll" "system" fn glRasterPos2dv(v : *const f64));
windows_link::link!("opengl32.dll" "system" fn glRasterPos2f(x : f32, y : f32));
windows_link::link!("opengl32.dll" "system" fn glRasterPos2fv(v : *const f32));
windows_link::link!("opengl32.dll" "system" fn glRasterPos2i(x : GLint, y : GLint));
windows_link::link!("opengl32.dll" "system" fn glRasterPos2iv(v : *const GLint));
windows_link::link!("opengl32.dll" "system" fn glRasterPos2s(x : GLshort, y : GLshort));
windows_link::link!("opengl32.dll" "system" fn glRasterPos2sv(v : *const GLshort));
windows_link::link!("opengl32.dll" "system" fn glRasterPos3d(x : f64, y : f64, z : f64));
windows_link::link!("opengl32.dll" "system" fn glRasterPos3dv(v : *const f64));
windows_link::link!("opengl32.dll" "system" fn glRasterPos3f(x : f32, y : f32, z : f32));
windows_link::link!("opengl32.dll" "system" fn glRasterPos3fv(v : *const f32));
windows_link::link!("opengl32.dll" "system" fn glRasterPos3i(x : GLint, y : GLint, z : GLint));
windows_link::link!("opengl32.dll" "system" fn glRasterPos3iv(v : *const GLint));
windows_link::link!("opengl32.dll" "system" fn glRasterPos3s(x : GLshort, y : GLshort, z : GLshort));
windows_link::link!("opengl32.dll" "system" fn glRasterPos3sv(v : *const GLshort));
windows_link::link!("opengl32.dll" "system" fn glRasterPos4d(x : f64, y : f64, z : f64, w : f64));
windows_link::link!("opengl32.dll" "system" fn glRasterPos4dv(v : *const f64));
windows_link::link!("opengl32.dll" "system" fn glRasterPos4f(x : f32, y : f32, z : f32, w : f32));
windows_link::link!("opengl32.dll" "system" fn glRasterPos4fv(v : *const f32));
windows_link::link!("opengl32.dll" "system" fn glRasterPos4i(x : GLint, y : GLint, z : GLint, w : GLint));
windows_link::link!("opengl32.dll" "system" fn glRasterPos4iv(v : *const GLint));
windows_link::link!("opengl32.dll" "system" fn glRasterPos4s(x : GLshort, y : GLshort, z : GLshort, w : GLshort));
windows_link::link!("opengl32.dll" "system" fn glRasterPos4sv(v : *const GLshort));
windows_link::link!("opengl32.dll" "system" fn glReadBuffer(mode : GLenum));
windows_link::link!("opengl32.dll" "system" fn glReadPixels(x : GLint, y : GLint, width : GLsizei, height : GLsizei, format : GLenum, r#type : GLenum, pixels : *mut GLvoid));
windows_link::link!("opengl32.dll" "system" fn glRectd(x1 : f64, y1 : f64, x2 : f64, y2 : f64));
windows_link::link!("opengl32.dll" "system" fn glRectdv(v1 : *const f64, v2 : *const f64));
windows_link::link!("opengl32.dll" "system" fn glRectf(x1 : f32, y1 : f32, x2 : f32, y2 : f32));
windows_link::link!("opengl32.dll" "system" fn glRectfv(v1 : *const f32, v2 : *const f32));
windows_link::link!("opengl32.dll" "system" fn glRecti(x1 : GLint, y1 : GLint, x2 : GLint, y2 : GLint));
windows_link::link!("opengl32.dll" "system" fn glRectiv(v1 : *const GLint, v2 : *const GLint));
windows_link::link!("opengl32.dll" "system" fn glRects(x1 : GLshort, y1 : GLshort, x2 : GLshort, y2 : GLshort));
windows_link::link!("opengl32.dll" "system" fn glRectsv(v1 : *const GLshort, v2 : *const GLshort));
windows_link::link!("opengl32.dll" "system" fn glRenderMode(mode : GLenum) -> GLint);
windows_link::link!("opengl32.dll" "system" fn glRotated(angle : f64, x : f64, y : f64, z : f64));
windows_link::link!("opengl32.dll" "system" fn glRotatef(angle : f32, x : f32, y : f32, z : f32));
windows_link::link!("opengl32.dll" "system" fn glScaled(x : f64, y : f64, z : f64));
windows_link::link!("opengl32.dll" "system" fn glScalef(x : f32, y : f32, z : f32));
windows_link::link!("opengl32.dll" "system" fn glScissor(x : GLint, y : GLint, width : GLsizei, height : GLsizei));
windows_link::link!("opengl32.dll" "system" fn glSelectBuffer(size : GLsizei, buffer : *mut GLuint));
windows_link::link!("opengl32.dll" "system" fn glShadeModel(mode : GLenum));
windows_link::link!("opengl32.dll" "system" fn glStencilFunc(func : GLenum, r#ref : GLint, mask : GLuint));
windows_link::link!("opengl32.dll" "system" fn glStencilMask(mask : GLuint));
windows_link::link!("opengl32.dll" "system" fn glStencilOp(fail : GLenum, zfail : GLenum, zpass : GLenum));
windows_link::link!("opengl32.dll" "system" fn glTexCoord1d(s : f64));
windows_link::link!("opengl32.dll" "system" fn glTexCoord1dv(v : *const f64));
windows_link::link!("opengl32.dll" "system" fn glTexCoord1f(s : f32));
windows_link::link!("opengl32.dll" "system" fn glTexCoord1fv(v : *const f32));
windows_link::link!("opengl32.dll" "system" fn glTexCoord1i(s : GLint));
windows_link::link!("opengl32.dll" "system" fn glTexCoord1iv(v : *const GLint));
windows_link::link!("opengl32.dll" "system" fn glTexCoord1s(s : GLshort));
windows_link::link!("opengl32.dll" "system" fn glTexCoord1sv(v : *const GLshort));
windows_link::link!("opengl32.dll" "system" fn glTexCoord2d(s : f64, t : f64));
windows_link::link!("opengl32.dll" "system" fn glTexCoord2dv(v : *const f64));
windows_link::link!("opengl32.dll" "system" fn glTexCoord2f(s : f32, t : f32));
windows_link::link!("opengl32.dll" "system" fn glTexCoord2fv(v : *const f32));
windows_link::link!("opengl32.dll" "system" fn glTexCoord2i(s : GLint, t : GLint));
windows_link::link!("opengl32.dll" "system" fn glTexCoord2iv(v : *const GLint));
windows_link::link!("opengl32.dll" "system" fn glTexCoord2s(s : GLshort, t : GLshort));
windows_link::link!("opengl32.dll" "system" fn glTexCoord2sv(v : *const GLshort));
windows_link::link!("opengl32.dll" "system" fn glTexCoord3d(s : f64, t : f64, r : f64));
windows_link::link!("opengl32.dll" "system" fn glTexCoord3dv(v : *const f64));
windows_link::link!("opengl32.dll" "system" fn glTexCoord3f(s : f32, t : f32, r : f32));
windows_link::link!("opengl32.dll" "system" fn glTexCoord3fv(v : *const f32));
windows_link::link!("opengl32.dll" "system" fn glTexCoord3i(s : GLint, t : GLint, r : GLint));
windows_link::link!("opengl32.dll" "system" fn glTexCoord3iv(v : *const GLint));
windows_link::link!("opengl32.dll" "system" fn glTexCoord3s(s : GLshort, t : GLshort, r : GLshort));
windows_link::link!("opengl32.dll" "system" fn glTexCoord3sv(v : *const GLshort));
windows_link::link!("opengl32.dll" "system" fn glTexCoord4d(s : f64, t : f64, r : f64, q : f64));
windows_link::link!("opengl32.dll" "system" fn glTexCoord4dv(v : *const f64));
windows_link::link!("opengl32.dll" "system" fn glTexCoord4f(s : f32, t : f32, r : f32, q : f32));
windows_link::link!("opengl32.dll" "system" fn glTexCoord4fv(v : *const f32));
windows_link::link!("opengl32.dll" "system" fn glTexCoord4i(s : GLint, t : GLint, r : GLint, q : GLint));
windows_link::link!("opengl32.dll" "system" fn glTexCoord4iv(v : *const GLint));
windows_link::link!("opengl32.dll" "system" fn glTexCoord4s(s : GLshort, t : GLshort, r : GLshort, q : GLshort));
windows_link::link!("opengl32.dll" "system" fn glTexCoord4sv(v : *const GLshort));
windows_link::link!("opengl32.dll" "system" fn glTexCoordPointer(size : GLint, r#type : GLenum, stride : GLsizei, pointer : *const GLvoid));
windows_link::link!("opengl32.dll" "system" fn glTexEnvf(target : GLenum, pname : GLenum, param : f32));
windows_link::link!("opengl32.dll" "system" fn glTexEnvfv(target : GLenum, pname : GLenum, params : *const f32));
windows_link::link!("opengl32.dll" "system" fn glTexEnvi(target : GLenum, pname : GLenum, param : GLint));
windows_link::link!("opengl32.dll" "system" fn glTexEnviv(target : GLenum, pname : GLenum, params : *const GLint));
windows_link::link!("opengl32.dll" "system" fn glTexGend(coord : GLenum, pname : GLenum, param : f64));
windows_link::link!("opengl32.dll" "system" fn glTexGendv(coord : GLenum, pname : GLenum, params : *const f64));
windows_link::link!("opengl32.dll" "system" fn glTexGenf(coord : GLenum, pname : GLenum, param : f32));
windows_link::link!("opengl32.dll" "system" fn glTexGenfv(coord : GLenum, pname : GLenum, params : *const f32));
windows_link::link!("opengl32.dll" "system" fn glTexGeni(coord : GLenum, pname : GLenum, param : GLint));
windows_link::link!("opengl32.dll" "system" fn glTexGeniv(coord : GLenum, pname : GLenum, params : *const GLint));
windows_link::link!("opengl32.dll" "system" fn glTexImage1D(target : GLenum, level : GLint, internalformat : GLint, width : GLsizei, border : GLint, format : GLenum, r#type : GLenum, pixels : *const GLvoid));
windows_link::link!("opengl32.dll" "system" fn glTexImage2D(target : GLenum, level : GLint, internalformat : GLint, width : GLsizei, height : GLsizei, border : GLint, format : GLenum, r#type : GLenum, pixels : *const GLvoid));
windows_link::link!("opengl32.dll" "system" fn glTexParameterf(target : GLenum, pname : GLenum, param : f32));
windows_link::link!("opengl32.dll" "system" fn glTexParameterfv(target : GLenum, pname : GLenum, params : *const f32));
windows_link::link!("opengl32.dll" "system" fn glTexParameteri(target : GLenum, pname : GLenum, param : GLint));
windows_link::link!("opengl32.dll" "system" fn glTexParameteriv(target : GLenum, pname : GLenum, params : *const GLint));
windows_link::link!("opengl32.dll" "system" fn glTexSubImage1D(target : GLenum, level : GLint, xoffset : GLint, width : GLsizei, format : GLenum, r#type : GLenum, pixels : *const GLvoid));
windows_link::link!("opengl32.dll" "system" fn glTexSubImage2D(target : GLenum, level : GLint, xoffset : GLint, yoffset : GLint, width : GLsizei, height : GLsizei, format : GLenum, r#type : GLenum, pixels : *const GLvoid));
windows_link::link!("opengl32.dll" "system" fn glTranslated(x : f64, y : f64, z : f64));
windows_link::link!("opengl32.dll" "system" fn glTranslatef(x : f32, y : f32, z : f32));
windows_link::link!("opengl32.dll" "system" fn glVertex2d(x : f64, y : f64));
windows_link::link!("opengl32.dll" "system" fn glVertex2dv(v : *const f64));
windows_link::link!("opengl32.dll" "system" fn glVertex2f(x : f32, y : f32));
windows_link::link!("opengl32.dll" "system" fn glVertex2fv(v : *const f32));
windows_link::link!("opengl32.dll" "system" fn glVertex2i(x : GLint, y : GLint));
windows_link::link!("opengl32.dll" "system" fn glVertex2iv(v : *const GLint));
windows_link::link!("opengl32.dll" "system" fn glVertex2s(x : GLshort, y : GLshort));
windows_link::link!("opengl32.dll" "system" fn glVertex2sv(v : *const GLshort));
windows_link::link!("opengl32.dll" "system" fn glVertex3d(x : f64, y : f64, z : f64));
windows_link::link!("opengl32.dll" "system" fn glVertex3dv(v : *const f64));
windows_link::link!("opengl32.dll" "system" fn glVertex3f(x : f32, y : f32, z : f32));
windows_link::link!("opengl32.dll" "system" fn glVertex3fv(v : *const f32));
windows_link::link!("opengl32.dll" "system" fn glVertex3i(x : GLint, y : GLint, z : GLint));
windows_link::link!("opengl32.dll" "system" fn glVertex3iv(v : *const GLint));
windows_link::link!("opengl32.dll" "system" fn glVertex3s(x : GLshort, y : GLshort, z : GLshort));
windows_link::link!("opengl32.dll" "system" fn glVertex3sv(v : *const GLshort));
windows_link::link!("opengl32.dll" "system" fn glVertex4d(x : f64, y : f64, z : f64, w : f64));
windows_link::link!("opengl32.dll" "system" fn glVertex4dv(v : *const f64));
windows_link::link!("opengl32.dll" "system" fn glVertex4f(x : f32, y : f32, z : f32, w : f32));
windows_link::link!("opengl32.dll" "system" fn glVertex4fv(v : *const f32));
windows_link::link!("opengl32.dll" "system" fn glVertex4i(x : GLint, y : GLint, z : GLint, w : GLint));
windows_link::link!("opengl32.dll" "system" fn glVertex4iv(v : *const GLint));
windows_link::link!("opengl32.dll" "system" fn glVertex4s(x : GLshort, y : GLshort, z : GLshort, w : GLshort));
windows_link::link!("opengl32.dll" "system" fn glVertex4sv(v : *const GLshort));
windows_link::link!("opengl32.dll" "system" fn glVertexPointer(size : GLint, r#type : GLenum, stride : GLsizei, pointer : *const GLvoid));
windows_link::link!("opengl32.dll" "system" fn glViewport(x : GLint, y : GLint, width : GLsizei, height : GLsizei));
pub const GL_2D: i32 = 1536;
pub const GL_2_BYTES: i32 = 5127;
pub const GL_3D: i32 = 1537;
pub const GL_3D_COLOR: i32 = 1538;
pub const GL_3D_COLOR_TEXTURE: i32 = 1539;
pub const GL_3_BYTES: i32 = 5128;
pub const GL_4D_COLOR_TEXTURE: i32 = 1540;
pub const GL_4_BYTES: i32 = 5129;
pub const GL_ACCUM: i32 = 256;
pub const GL_ACCUM_ALPHA_BITS: i32 = 3419;
pub const GL_ACCUM_BLUE_BITS: i32 = 3418;
pub const GL_ACCUM_BUFFER_BIT: i32 = 512;
pub const GL_ACCUM_CLEAR_VALUE: i32 = 2944;
pub const GL_ACCUM_GREEN_BITS: i32 = 3417;
pub const GL_ACCUM_RED_BITS: i32 = 3416;
pub const GL_ADD: i32 = 260;
pub const GL_ALL_ATTRIB_BITS: i32 = 1048575;
pub const GL_ALPHA: i32 = 6406;
pub const GL_ALPHA12: i32 = 32829;
pub const GL_ALPHA16: i32 = 32830;
pub const GL_ALPHA4: i32 = 32827;
pub const GL_ALPHA8: i32 = 32828;
pub const GL_ALPHA_BIAS: i32 = 3357;
pub const GL_ALPHA_BITS: i32 = 3413;
pub const GL_ALPHA_SCALE: i32 = 3356;
pub const GL_ALPHA_TEST: i32 = 3008;
pub const GL_ALPHA_TEST_FUNC: i32 = 3009;
pub const GL_ALPHA_TEST_REF: i32 = 3010;
pub const GL_ALWAYS: i32 = 519;
pub const GL_AMBIENT: i32 = 4608;
pub const GL_AMBIENT_AND_DIFFUSE: i32 = 5634;
pub const GL_AND: i32 = 5377;
pub const GL_AND_INVERTED: i32 = 5380;
pub const GL_AND_REVERSE: i32 = 5378;
pub const GL_ATTRIB_STACK_DEPTH: i32 = 2992;
pub const GL_AUTO_NORMAL: i32 = 3456;
pub const GL_AUX0: i32 = 1033;
pub const GL_AUX1: i32 = 1034;
pub const GL_AUX2: i32 = 1035;
pub const GL_AUX3: i32 = 1036;
pub const GL_AUX_BUFFERS: i32 = 3072;
pub const GL_BACK: i32 = 1029;
pub const GL_BACK_LEFT: i32 = 1026;
pub const GL_BACK_RIGHT: i32 = 1027;
pub const GL_BGRA_EXT: i32 = 32993;
pub const GL_BGR_EXT: i32 = 32992;
pub const GL_BITMAP: i32 = 6656;
pub const GL_BITMAP_TOKEN: i32 = 1796;
pub const GL_BLEND: i32 = 3042;
pub const GL_BLEND_DST: i32 = 3040;
pub const GL_BLEND_SRC: i32 = 3041;
pub const GL_BLUE: i32 = 6405;
pub const GL_BLUE_BIAS: i32 = 3355;
pub const GL_BLUE_BITS: i32 = 3412;
pub const GL_BLUE_SCALE: i32 = 3354;
pub const GL_BYTE: i32 = 5120;
pub const GL_C3F_V3F: i32 = 10788;
pub const GL_C4F_N3F_V3F: i32 = 10790;
pub const GL_C4UB_V2F: i32 = 10786;
pub const GL_C4UB_V3F: i32 = 10787;
pub const GL_CCW: i32 = 2305;
pub const GL_CLAMP: i32 = 10496;
pub const GL_CLEAR: i32 = 5376;
pub const GL_CLIENT_ALL_ATTRIB_BITS: u32 = 4294967295;
pub const GL_CLIENT_ATTRIB_STACK_DEPTH: i32 = 2993;
pub const GL_CLIENT_PIXEL_STORE_BIT: i32 = 1;
pub const GL_CLIENT_VERTEX_ARRAY_BIT: i32 = 2;
pub const GL_CLIP_PLANE0: i32 = 12288;
pub const GL_CLIP_PLANE1: i32 = 12289;
pub const GL_CLIP_PLANE2: i32 = 12290;
pub const GL_CLIP_PLANE3: i32 = 12291;
pub const GL_CLIP_PLANE4: i32 = 12292;
pub const GL_CLIP_PLANE5: i32 = 12293;
pub const GL_COEFF: i32 = 2560;
pub const GL_COLOR: i32 = 6144;
pub const GL_COLOR_ARRAY: i32 = 32886;
pub const GL_COLOR_ARRAY_COUNT_EXT: i32 = 32900;
pub const GL_COLOR_ARRAY_EXT: i32 = 32886;
pub const GL_COLOR_ARRAY_POINTER: i32 = 32912;
pub const GL_COLOR_ARRAY_POINTER_EXT: i32 = 32912;
pub const GL_COLOR_ARRAY_SIZE: i32 = 32897;
pub const GL_COLOR_ARRAY_SIZE_EXT: i32 = 32897;
pub const GL_COLOR_ARRAY_STRIDE: i32 = 32899;
pub const GL_COLOR_ARRAY_STRIDE_EXT: i32 = 32899;
pub const GL_COLOR_ARRAY_TYPE: i32 = 32898;
pub const GL_COLOR_ARRAY_TYPE_EXT: i32 = 32898;
pub const GL_COLOR_BUFFER_BIT: i32 = 16384;
pub const GL_COLOR_CLEAR_VALUE: i32 = 3106;
pub const GL_COLOR_INDEX: i32 = 6400;
pub const GL_COLOR_INDEX12_EXT: i32 = 32998;
pub const GL_COLOR_INDEX16_EXT: i32 = 32999;
pub const GL_COLOR_INDEX1_EXT: i32 = 32994;
pub const GL_COLOR_INDEX2_EXT: i32 = 32995;
pub const GL_COLOR_INDEX4_EXT: i32 = 32996;
pub const GL_COLOR_INDEX8_EXT: i32 = 32997;
pub const GL_COLOR_INDEXES: i32 = 5635;
pub const GL_COLOR_LOGIC_OP: i32 = 3058;
pub const GL_COLOR_MATERIAL: i32 = 2903;
pub const GL_COLOR_MATERIAL_FACE: i32 = 2901;
pub const GL_COLOR_MATERIAL_PARAMETER: i32 = 2902;
pub const GL_COLOR_TABLE_ALPHA_SIZE_EXT: i32 = 32989;
pub const GL_COLOR_TABLE_BLUE_SIZE_EXT: i32 = 32988;
pub const GL_COLOR_TABLE_FORMAT_EXT: i32 = 32984;
pub const GL_COLOR_TABLE_GREEN_SIZE_EXT: i32 = 32987;
pub const GL_COLOR_TABLE_INTENSITY_SIZE_EXT: i32 = 32991;
pub const GL_COLOR_TABLE_LUMINANCE_SIZE_EXT: i32 = 32990;
pub const GL_COLOR_TABLE_RED_SIZE_EXT: i32 = 32986;
pub const GL_COLOR_TABLE_WIDTH_EXT: i32 = 32985;
pub const GL_COLOR_WRITEMASK: i32 = 3107;
pub const GL_COMPILE: i32 = 4864;
pub const GL_COMPILE_AND_EXECUTE: i32 = 4865;
pub const GL_CONSTANT_ATTENUATION: i32 = 4615;
pub const GL_COPY: i32 = 5379;
pub const GL_COPY_INVERTED: i32 = 5388;
pub const GL_COPY_PIXEL_TOKEN: i32 = 1798;
pub const GL_CULL_FACE: i32 = 2884;
pub const GL_CULL_FACE_MODE: i32 = 2885;
pub const GL_CURRENT_BIT: i32 = 1;
pub const GL_CURRENT_COLOR: i32 = 2816;
pub const GL_CURRENT_INDEX: i32 = 2817;
pub const GL_CURRENT_NORMAL: i32 = 2818;
pub const GL_CURRENT_RASTER_COLOR: i32 = 2820;
pub const GL_CURRENT_RASTER_DISTANCE: i32 = 2825;
pub const GL_CURRENT_RASTER_INDEX: i32 = 2821;
pub const GL_CURRENT_RASTER_POSITION: i32 = 2823;
pub const GL_CURRENT_RASTER_POSITION_VALID: i32 = 2824;
pub const GL_CURRENT_RASTER_TEXTURE_COORDS: i32 = 2822;
pub const GL_CURRENT_TEXTURE_COORDS: i32 = 2819;
pub const GL_CW: i32 = 2304;
pub const GL_DECAL: i32 = 8449;
pub const GL_DECR: i32 = 7683;
pub const GL_DEPTH: i32 = 6145;
pub const GL_DEPTH_BIAS: i32 = 3359;
pub const GL_DEPTH_BITS: i32 = 3414;
pub const GL_DEPTH_BUFFER_BIT: i32 = 256;
pub const GL_DEPTH_CLEAR_VALUE: i32 = 2931;
pub const GL_DEPTH_COMPONENT: i32 = 6402;
pub const GL_DEPTH_FUNC: i32 = 2932;
pub const GL_DEPTH_RANGE: i32 = 2928;
pub const GL_DEPTH_SCALE: i32 = 3358;
pub const GL_DEPTH_TEST: i32 = 2929;
pub const GL_DEPTH_WRITEMASK: i32 = 2930;
pub const GL_DIFFUSE: i32 = 4609;
pub const GL_DITHER: i32 = 3024;
pub const GL_DOMAIN: i32 = 2562;
pub const GL_DONT_CARE: i32 = 4352;
pub const GL_DOUBLE: i32 = 5130;
pub const GL_DOUBLEBUFFER: i32 = 3122;
pub const GL_DOUBLE_EXT: i32 = 5130;
pub const GL_DRAW_BUFFER: i32 = 3073;
pub const GL_DRAW_PIXEL_TOKEN: i32 = 1797;
pub const GL_DST_ALPHA: i32 = 772;
pub const GL_DST_COLOR: i32 = 774;
pub const GL_EDGE_FLAG: i32 = 2883;
pub const GL_EDGE_FLAG_ARRAY: i32 = 32889;
pub const GL_EDGE_FLAG_ARRAY_COUNT_EXT: i32 = 32909;
pub const GL_EDGE_FLAG_ARRAY_EXT: i32 = 32889;
pub const GL_EDGE_FLAG_ARRAY_POINTER: i32 = 32915;
pub const GL_EDGE_FLAG_ARRAY_POINTER_EXT: i32 = 32915;
pub const GL_EDGE_FLAG_ARRAY_STRIDE: i32 = 32908;
pub const GL_EDGE_FLAG_ARRAY_STRIDE_EXT: i32 = 32908;
pub const GL_EMISSION: i32 = 5632;
pub const GL_ENABLE_BIT: i32 = 8192;
pub const GL_EQUAL: i32 = 514;
pub const GL_EQUIV: i32 = 5385;
pub const GL_EVAL_BIT: i32 = 65536;
pub const GL_EXP: i32 = 2048;
pub const GL_EXP2: i32 = 2049;
pub const GL_EXTENSIONS: i32 = 7939;
pub const GL_EXT_bgra: i32 = 1;
pub const GL_EXT_paletted_texture: i32 = 1;
pub const GL_EXT_vertex_array: i32 = 1;
pub const GL_EYE_LINEAR: i32 = 9216;
pub const GL_EYE_PLANE: i32 = 9474;
pub const GL_FALSE: i32 = 0;
pub const GL_FASTEST: i32 = 4353;
pub const GL_FEEDBACK: i32 = 7169;
pub const GL_FEEDBACK_BUFFER_POINTER: i32 = 3568;
pub const GL_FEEDBACK_BUFFER_SIZE: i32 = 3569;
pub const GL_FEEDBACK_BUFFER_TYPE: i32 = 3570;
pub const GL_FILL: i32 = 6914;
pub const GL_FLAT: i32 = 7424;
pub const GL_FLOAT: i32 = 5126;
pub const GL_FOG: i32 = 2912;
pub const GL_FOG_BIT: i32 = 128;
pub const GL_FOG_COLOR: i32 = 2918;
pub const GL_FOG_DENSITY: i32 = 2914;
pub const GL_FOG_END: i32 = 2916;
pub const GL_FOG_HINT: i32 = 3156;
pub const GL_FOG_INDEX: i32 = 2913;
pub const GL_FOG_MODE: i32 = 2917;
pub const GL_FOG_SPECULAR_TEXTURE_WIN: i32 = 33004;
pub const GL_FOG_START: i32 = 2915;
pub const GL_FRONT: i32 = 1028;
pub const GL_FRONT_AND_BACK: i32 = 1032;
pub const GL_FRONT_FACE: i32 = 2886;
pub const GL_FRONT_LEFT: i32 = 1024;
pub const GL_FRONT_RIGHT: i32 = 1025;
pub const GL_GEQUAL: i32 = 518;
pub const GL_GREATER: i32 = 516;
pub const GL_GREEN: i32 = 6404;
pub const GL_GREEN_BIAS: i32 = 3353;
pub const GL_GREEN_BITS: i32 = 3411;
pub const GL_GREEN_SCALE: i32 = 3352;
pub const GL_HINT_BIT: i32 = 32768;
pub const GL_INCR: i32 = 7682;
pub const GL_INDEX_ARRAY: i32 = 32887;
pub const GL_INDEX_ARRAY_COUNT_EXT: i32 = 32903;
pub const GL_INDEX_ARRAY_EXT: i32 = 32887;
pub const GL_INDEX_ARRAY_POINTER: i32 = 32913;
pub const GL_INDEX_ARRAY_POINTER_EXT: i32 = 32913;
pub const GL_INDEX_ARRAY_STRIDE: i32 = 32902;
pub const GL_INDEX_ARRAY_STRIDE_EXT: i32 = 32902;
pub const GL_INDEX_ARRAY_TYPE: i32 = 32901;
pub const GL_INDEX_ARRAY_TYPE_EXT: i32 = 32901;
pub const GL_INDEX_BITS: i32 = 3409;
pub const GL_INDEX_CLEAR_VALUE: i32 = 3104;
pub const GL_INDEX_LOGIC_OP: i32 = 3057;
pub const GL_INDEX_MODE: i32 = 3120;
pub const GL_INDEX_OFFSET: i32 = 3347;
pub const GL_INDEX_SHIFT: i32 = 3346;
pub const GL_INDEX_WRITEMASK: i32 = 3105;
pub const GL_INT: i32 = 5124;
pub const GL_INTENSITY: i32 = 32841;
pub const GL_INTENSITY12: i32 = 32844;
pub const GL_INTENSITY16: i32 = 32845;
pub const GL_INTENSITY4: i32 = 32842;
pub const GL_INTENSITY8: i32 = 32843;
pub const GL_INVALID_ENUM: i32 = 1280;
pub const GL_INVALID_OPERATION: i32 = 1282;
pub const GL_INVALID_VALUE: i32 = 1281;
pub const GL_INVERT: i32 = 5386;
pub const GL_KEEP: i32 = 7680;
pub const GL_LEFT: i32 = 1030;
pub const GL_LEQUAL: i32 = 515;
pub const GL_LESS: i32 = 513;
pub const GL_LIGHT0: i32 = 16384;
pub const GL_LIGHT1: i32 = 16385;
pub const GL_LIGHT2: i32 = 16386;
pub const GL_LIGHT3: i32 = 16387;
pub const GL_LIGHT4: i32 = 16388;
pub const GL_LIGHT5: i32 = 16389;
pub const GL_LIGHT6: i32 = 16390;
pub const GL_LIGHT7: i32 = 16391;
pub const GL_LIGHTING: i32 = 2896;
pub const GL_LIGHTING_BIT: i32 = 64;
pub const GL_LIGHT_MODEL_AMBIENT: i32 = 2899;
pub const GL_LIGHT_MODEL_LOCAL_VIEWER: i32 = 2897;
pub const GL_LIGHT_MODEL_TWO_SIDE: i32 = 2898;
pub const GL_LINE: i32 = 6913;
pub const GL_LINEAR: i32 = 9729;
pub const GL_LINEAR_ATTENUATION: i32 = 4616;
pub const GL_LINEAR_MIPMAP_LINEAR: i32 = 9987;
pub const GL_LINEAR_MIPMAP_NEAREST: i32 = 9985;
pub const GL_LINES: i32 = 1;
pub const GL_LINE_BIT: i32 = 4;
pub const GL_LINE_LOOP: i32 = 2;
pub const GL_LINE_RESET_TOKEN: i32 = 1799;
pub const GL_LINE_SMOOTH: i32 = 2848;
pub const GL_LINE_SMOOTH_HINT: i32 = 3154;
pub const GL_LINE_STIPPLE: i32 = 2852;
pub const GL_LINE_STIPPLE_PATTERN: i32 = 2853;
pub const GL_LINE_STIPPLE_REPEAT: i32 = 2854;
pub const GL_LINE_STRIP: i32 = 3;
pub const GL_LINE_TOKEN: i32 = 1794;
pub const GL_LINE_WIDTH: i32 = 2849;
pub const GL_LINE_WIDTH_GRANULARITY: i32 = 2851;
pub const GL_LINE_WIDTH_RANGE: i32 = 2850;
pub const GL_LIST_BASE: i32 = 2866;
pub const GL_LIST_BIT: i32 = 131072;
pub const GL_LIST_INDEX: i32 = 2867;
pub const GL_LIST_MODE: i32 = 2864;
pub const GL_LOAD: i32 = 257;
pub const GL_LOGIC_OP: i32 = 3057;
pub const GL_LOGIC_OP_MODE: i32 = 3056;
pub const GL_LUMINANCE: i32 = 6409;
pub const GL_LUMINANCE12: i32 = 32833;
pub const GL_LUMINANCE12_ALPHA12: i32 = 32839;
pub const GL_LUMINANCE12_ALPHA4: i32 = 32838;
pub const GL_LUMINANCE16: i32 = 32834;
pub const GL_LUMINANCE16_ALPHA16: i32 = 32840;
pub const GL_LUMINANCE4: i32 = 32831;
pub const GL_LUMINANCE4_ALPHA4: i32 = 32835;
pub const GL_LUMINANCE6_ALPHA2: i32 = 32836;
pub const GL_LUMINANCE8: i32 = 32832;
pub const GL_LUMINANCE8_ALPHA8: i32 = 32837;
pub const GL_LUMINANCE_ALPHA: i32 = 6410;
pub const GL_MAP1_COLOR_4: i32 = 3472;
pub const GL_MAP1_GRID_DOMAIN: i32 = 3536;
pub const GL_MAP1_GRID_SEGMENTS: i32 = 3537;
pub const GL_MAP1_INDEX: i32 = 3473;
pub const GL_MAP1_NORMAL: i32 = 3474;
pub const GL_MAP1_TEXTURE_COORD_1: i32 = 3475;
pub const GL_MAP1_TEXTURE_COORD_2: i32 = 3476;
pub const GL_MAP1_TEXTURE_COORD_3: i32 = 3477;
pub const GL_MAP1_TEXTURE_COORD_4: i32 = 3478;
pub const GL_MAP1_VERTEX_3: i32 = 3479;
pub const GL_MAP1_VERTEX_4: i32 = 3480;
pub const GL_MAP2_COLOR_4: i32 = 3504;
pub const GL_MAP2_GRID_DOMAIN: i32 = 3538;
pub const GL_MAP2_GRID_SEGMENTS: i32 = 3539;
pub const GL_MAP2_INDEX: i32 = 3505;
pub const GL_MAP2_NORMAL: i32 = 3506;
pub const GL_MAP2_TEXTURE_COORD_1: i32 = 3507;
pub const GL_MAP2_TEXTURE_COORD_2: i32 = 3508;
pub const GL_MAP2_TEXTURE_COORD_3: i32 = 3509;
pub const GL_MAP2_TEXTURE_COORD_4: i32 = 3510;
pub const GL_MAP2_VERTEX_3: i32 = 3511;
pub const GL_MAP2_VERTEX_4: i32 = 3512;
pub const GL_MAP_COLOR: i32 = 3344;
pub const GL_MAP_STENCIL: i32 = 3345;
pub const GL_MATRIX_MODE: i32 = 2976;
pub const GL_MAX_ATTRIB_STACK_DEPTH: i32 = 3381;
pub const GL_MAX_CLIENT_ATTRIB_STACK_DEPTH: i32 = 3387;
pub const GL_MAX_CLIP_PLANES: i32 = 3378;
pub const GL_MAX_ELEMENTS_INDICES_WIN: i32 = 33001;
pub const GL_MAX_ELEMENTS_VERTICES_WIN: i32 = 33000;
pub const GL_MAX_EVAL_ORDER: i32 = 3376;
pub const GL_MAX_LIGHTS: i32 = 3377;
pub const GL_MAX_LIST_NESTING: i32 = 2865;
pub const GL_MAX_MODELVIEW_STACK_DEPTH: i32 = 3382;
pub const GL_MAX_NAME_STACK_DEPTH: i32 = 3383;
pub const GL_MAX_PIXEL_MAP_TABLE: i32 = 3380;
pub const GL_MAX_PROJECTION_STACK_DEPTH: i32 = 3384;
pub const GL_MAX_TEXTURE_SIZE: i32 = 3379;
pub const GL_MAX_TEXTURE_STACK_DEPTH: i32 = 3385;
pub const GL_MAX_VIEWPORT_DIMS: i32 = 3386;
pub const GL_MODELVIEW: i32 = 5888;
pub const GL_MODELVIEW_MATRIX: i32 = 2982;
pub const GL_MODELVIEW_STACK_DEPTH: i32 = 2979;
pub const GL_MODULATE: i32 = 8448;
pub const GL_MULT: i32 = 259;
pub const GL_N3F_V3F: i32 = 10789;
pub const GL_NAME_STACK_DEPTH: i32 = 3440;
pub const GL_NAND: i32 = 5390;
pub const GL_NEAREST: i32 = 9728;
pub const GL_NEAREST_MIPMAP_LINEAR: i32 = 9986;
pub const GL_NEAREST_MIPMAP_NEAREST: i32 = 9984;
pub const GL_NEVER: i32 = 512;
pub const GL_NICEST: i32 = 4354;
pub const GL_NONE: i32 = 0;
pub const GL_NOOP: i32 = 5381;
pub const GL_NOR: i32 = 5384;
pub const GL_NORMALIZE: i32 = 2977;
pub const GL_NORMAL_ARRAY: i32 = 32885;
pub const GL_NORMAL_ARRAY_COUNT_EXT: i32 = 32896;
pub const GL_NORMAL_ARRAY_EXT: i32 = 32885;
pub const GL_NORMAL_ARRAY_POINTER: i32 = 32911;
pub const GL_NORMAL_ARRAY_POINTER_EXT: i32 = 32911;
pub const GL_NORMAL_ARRAY_STRIDE: i32 = 32895;
pub const GL_NORMAL_ARRAY_STRIDE_EXT: i32 = 32895;
pub const GL_NORMAL_ARRAY_TYPE: i32 = 32894;
pub const GL_NORMAL_ARRAY_TYPE_EXT: i32 = 32894;
pub const GL_NOTEQUAL: i32 = 517;
pub const GL_NO_ERROR: i32 = 0;
pub const GL_OBJECT_LINEAR: i32 = 9217;
pub const GL_OBJECT_PLANE: i32 = 9473;
pub const GL_ONE: i32 = 1;
pub const GL_ONE_MINUS_DST_ALPHA: i32 = 773;
pub const GL_ONE_MINUS_DST_COLOR: i32 = 775;
pub const GL_ONE_MINUS_SRC_ALPHA: i32 = 771;
pub const GL_ONE_MINUS_SRC_COLOR: i32 = 769;
pub const GL_OR: i32 = 5383;
pub const GL_ORDER: i32 = 2561;
pub const GL_OR_INVERTED: i32 = 5389;
pub const GL_OR_REVERSE: i32 = 5387;
pub const GL_OUT_OF_MEMORY: i32 = 1285;
pub const GL_PACK_ALIGNMENT: i32 = 3333;
pub const GL_PACK_LSB_FIRST: i32 = 3329;
pub const GL_PACK_ROW_LENGTH: i32 = 3330;
pub const GL_PACK_SKIP_PIXELS: i32 = 3332;
pub const GL_PACK_SKIP_ROWS: i32 = 3331;
pub const GL_PACK_SWAP_BYTES: i32 = 3328;
pub const GL_PASS_THROUGH_TOKEN: i32 = 1792;
pub const GL_PERSPECTIVE_CORRECTION_HINT: i32 = 3152;
pub const GL_PHONG_HINT_WIN: i32 = 33003;
pub const GL_PHONG_WIN: i32 = 33002;
pub const GL_PIXEL_MAP_A_TO_A: i32 = 3193;
pub const GL_PIXEL_MAP_A_TO_A_SIZE: i32 = 3257;
pub const GL_PIXEL_MAP_B_TO_B: i32 = 3192;
pub const GL_PIXEL_MAP_B_TO_B_SIZE: i32 = 3256;
pub const GL_PIXEL_MAP_G_TO_G: i32 = 3191;
pub const GL_PIXEL_MAP_G_TO_G_SIZE: i32 = 3255;
pub const GL_PIXEL_MAP_I_TO_A: i32 = 3189;
pub const GL_PIXEL_MAP_I_TO_A_SIZE: i32 = 3253;
pub const GL_PIXEL_MAP_I_TO_B: i32 = 3188;
pub const GL_PIXEL_MAP_I_TO_B_SIZE: i32 = 3252;
pub const GL_PIXEL_MAP_I_TO_G: i32 = 3187;
pub const GL_PIXEL_MAP_I_TO_G_SIZE: i32 = 3251;
pub const GL_PIXEL_MAP_I_TO_I: i32 = 3184;
pub const GL_PIXEL_MAP_I_TO_I_SIZE: i32 = 3248;
pub const GL_PIXEL_MAP_I_TO_R: i32 = 3186;
pub const GL_PIXEL_MAP_I_TO_R_SIZE: i32 = 3250;
pub const GL_PIXEL_MAP_R_TO_R: i32 = 3190;
pub const GL_PIXEL_MAP_R_TO_R_SIZE: i32 = 3254;
pub const GL_PIXEL_MAP_S_TO_S: i32 = 3185;
pub const GL_PIXEL_MAP_S_TO_S_SIZE: i32 = 3249;
pub const GL_PIXEL_MODE_BIT: i32 = 32;
pub const GL_POINT: i32 = 6912;
pub const GL_POINTS: i32 = 0;
pub const GL_POINT_BIT: i32 = 2;
pub const GL_POINT_SIZE: i32 = 2833;
pub const GL_POINT_SIZE_GRANULARITY: i32 = 2835;
pub const GL_POINT_SIZE_RANGE: i32 = 2834;
pub const GL_POINT_SMOOTH: i32 = 2832;
pub const GL_POINT_SMOOTH_HINT: i32 = 3153;
pub const GL_POINT_TOKEN: i32 = 1793;
pub const GL_POLYGON: i32 = 9;
pub const GL_POLYGON_BIT: i32 = 8;
pub const GL_POLYGON_MODE: i32 = 2880;
pub const GL_POLYGON_OFFSET_FACTOR: i32 = 32824;
pub const GL_POLYGON_OFFSET_FILL: i32 = 32823;
pub const GL_POLYGON_OFFSET_LINE: i32 = 10754;
pub const GL_POLYGON_OFFSET_POINT: i32 = 10753;
pub const GL_POLYGON_OFFSET_UNITS: i32 = 10752;
pub const GL_POLYGON_SMOOTH: i32 = 2881;
pub const GL_POLYGON_SMOOTH_HINT: i32 = 3155;
pub const GL_POLYGON_STIPPLE: i32 = 2882;
pub const GL_POLYGON_STIPPLE_BIT: i32 = 16;
pub const GL_POLYGON_TOKEN: i32 = 1795;
pub const GL_POSITION: i32 = 4611;
pub const GL_PROJECTION: i32 = 5889;
pub const GL_PROJECTION_MATRIX: i32 = 2983;
pub const GL_PROJECTION_STACK_DEPTH: i32 = 2980;
pub const GL_PROXY_TEXTURE_1D: i32 = 32867;
pub const GL_PROXY_TEXTURE_2D: i32 = 32868;
pub const GL_Q: i32 = 8195;
pub const GL_QUADRATIC_ATTENUATION: i32 = 4617;
pub const GL_QUADS: i32 = 7;
pub const GL_QUAD_STRIP: i32 = 8;
pub const GL_R: i32 = 8194;
pub const GL_R3_G3_B2: i32 = 10768;
pub const GL_READ_BUFFER: i32 = 3074;
pub const GL_RED: i32 = 6403;
pub const GL_RED_BIAS: i32 = 3349;
pub const GL_RED_BITS: i32 = 3410;
pub const GL_RED_SCALE: i32 = 3348;
pub const GL_RENDER: i32 = 7168;
pub const GL_RENDERER: i32 = 7937;
pub const GL_RENDER_MODE: i32 = 3136;
pub const GL_REPEAT: i32 = 10497;
pub const GL_REPLACE: i32 = 7681;
pub const GL_RETURN: i32 = 258;
pub const GL_RGB: i32 = 6407;
pub const GL_RGB10: i32 = 32850;
pub const GL_RGB10_A2: i32 = 32857;
pub const GL_RGB12: i32 = 32851;
pub const GL_RGB16: i32 = 32852;
pub const GL_RGB4: i32 = 32847;
pub const GL_RGB5: i32 = 32848;
pub const GL_RGB5_A1: i32 = 32855;
pub const GL_RGB8: i32 = 32849;
pub const GL_RGBA: i32 = 6408;
pub const GL_RGBA12: i32 = 32858;
pub const GL_RGBA16: i32 = 32859;
pub const GL_RGBA2: i32 = 32853;
pub const GL_RGBA4: i32 = 32854;
pub const GL_RGBA8: i32 = 32856;
pub const GL_RGBA_MODE: i32 = 3121;
pub const GL_RIGHT: i32 = 1031;
pub const GL_S: i32 = 8192;
pub const GL_SCISSOR_BIT: i32 = 524288;
pub const GL_SCISSOR_BOX: i32 = 3088;
pub const GL_SCISSOR_TEST: i32 = 3089;
pub const GL_SELECT: i32 = 7170;
pub const GL_SELECTION_BUFFER_POINTER: i32 = 3571;
pub const GL_SELECTION_BUFFER_SIZE: i32 = 3572;
pub const GL_SET: i32 = 5391;
pub const GL_SHADE_MODEL: i32 = 2900;
pub const GL_SHININESS: i32 = 5633;
pub const GL_SHORT: i32 = 5122;
pub const GL_SMOOTH: i32 = 7425;
pub const GL_SPECULAR: i32 = 4610;
pub const GL_SPHERE_MAP: i32 = 9218;
pub const GL_SPOT_CUTOFF: i32 = 4614;
pub const GL_SPOT_DIRECTION: i32 = 4612;
pub const GL_SPOT_EXPONENT: i32 = 4613;
pub const GL_SRC_ALPHA: i32 = 770;
pub const GL_SRC_ALPHA_SATURATE: i32 = 776;
pub const GL_SRC_COLOR: i32 = 768;
pub const GL_STACK_OVERFLOW: i32 = 1283;
pub const GL_STACK_UNDERFLOW: i32 = 1284;
pub const GL_STENCIL: i32 = 6146;
pub const GL_STENCIL_BITS: i32 = 3415;
pub const GL_STENCIL_BUFFER_BIT: i32 = 1024;
pub const GL_STENCIL_CLEAR_VALUE: i32 = 2961;
pub const GL_STENCIL_FAIL: i32 = 2964;
pub const GL_STENCIL_FUNC: i32 = 2962;
pub const GL_STENCIL_INDEX: i32 = 6401;
pub const GL_STENCIL_PASS_DEPTH_FAIL: i32 = 2965;
pub const GL_STENCIL_PASS_DEPTH_PASS: i32 = 2966;
pub const GL_STENCIL_REF: i32 = 2967;
pub const GL_STENCIL_TEST: i32 = 2960;
pub const GL_STENCIL_VALUE_MASK: i32 = 2963;
pub const GL_STENCIL_WRITEMASK: i32 = 2968;
pub const GL_STEREO: i32 = 3123;
pub const GL_SUBPIXEL_BITS: i32 = 3408;
pub const GL_T: i32 = 8193;
pub const GL_T2F_C3F_V3F: i32 = 10794;
pub const GL_T2F_C4F_N3F_V3F: i32 = 10796;
pub const GL_T2F_C4UB_V3F: i32 = 10793;
pub const GL_T2F_N3F_V3F: i32 = 10795;
pub const GL_T2F_V3F: i32 = 10791;
pub const GL_T4F_C4F_N3F_V4F: i32 = 10797;
pub const GL_T4F_V4F: i32 = 10792;
pub const GL_TEXTURE: i32 = 5890;
pub const GL_TEXTURE_1D: i32 = 3552;
pub const GL_TEXTURE_2D: i32 = 3553;
pub const GL_TEXTURE_ALPHA_SIZE: i32 = 32863;
pub const GL_TEXTURE_BINDING_1D: i32 = 32872;
pub const GL_TEXTURE_BINDING_2D: i32 = 32873;
pub const GL_TEXTURE_BIT: i32 = 262144;
pub const GL_TEXTURE_BLUE_SIZE: i32 = 32862;
pub const GL_TEXTURE_BORDER: i32 = 4101;
pub const GL_TEXTURE_BORDER_COLOR: i32 = 4100;
pub const GL_TEXTURE_COMPONENTS: i32 = 4099;
pub const GL_TEXTURE_COORD_ARRAY: i32 = 32888;
pub const GL_TEXTURE_COORD_ARRAY_COUNT_EXT: i32 = 32907;
pub const GL_TEXTURE_COORD_ARRAY_EXT: i32 = 32888;
pub const GL_TEXTURE_COORD_ARRAY_POINTER: i32 = 32914;
pub const GL_TEXTURE_COORD_ARRAY_POINTER_EXT: i32 = 32914;
pub const GL_TEXTURE_COORD_ARRAY_SIZE: i32 = 32904;
pub const GL_TEXTURE_COORD_ARRAY_SIZE_EXT: i32 = 32904;
pub const GL_TEXTURE_COORD_ARRAY_STRIDE: i32 = 32906;
pub const GL_TEXTURE_COORD_ARRAY_STRIDE_EXT: i32 = 32906;
pub const GL_TEXTURE_COORD_ARRAY_TYPE: i32 = 32905;
pub const GL_TEXTURE_COORD_ARRAY_TYPE_EXT: i32 = 32905;
pub const GL_TEXTURE_ENV: i32 = 8960;
pub const GL_TEXTURE_ENV_COLOR: i32 = 8705;
pub const GL_TEXTURE_ENV_MODE: i32 = 8704;
pub const GL_TEXTURE_GEN_MODE: i32 = 9472;
pub const GL_TEXTURE_GEN_Q: i32 = 3171;
pub const GL_TEXTURE_GEN_R: i32 = 3170;
pub const GL_TEXTURE_GEN_S: i32 = 3168;
pub const GL_TEXTURE_GEN_T: i32 = 3169;
pub const GL_TEXTURE_GREEN_SIZE: i32 = 32861;
pub const GL_TEXTURE_HEIGHT: i32 = 4097;
pub const GL_TEXTURE_INTENSITY_SIZE: i32 = 32865;
pub const GL_TEXTURE_INTERNAL_FORMAT: i32 = 4099;
pub const GL_TEXTURE_LUMINANCE_SIZE: i32 = 32864;
pub const GL_TEXTURE_MAG_FILTER: i32 = 10240;
pub const GL_TEXTURE_MATRIX: i32 = 2984;
pub const GL_TEXTURE_MIN_FILTER: i32 = 10241;
pub const GL_TEXTURE_PRIORITY: i32 = 32870;
pub const GL_TEXTURE_RED_SIZE: i32 = 32860;
pub const GL_TEXTURE_RESIDENT: i32 = 32871;
pub const GL_TEXTURE_STACK_DEPTH: i32 = 2981;
pub const GL_TEXTURE_WIDTH: i32 = 4096;
pub const GL_TEXTURE_WRAP_S: i32 = 10242;
pub const GL_TEXTURE_WRAP_T: i32 = 10243;
pub const GL_TRANSFORM_BIT: i32 = 4096;
pub const GL_TRIANGLES: i32 = 4;
pub const GL_TRIANGLE_FAN: i32 = 6;
pub const GL_TRIANGLE_STRIP: i32 = 5;
pub const GL_TRUE: i32 = 1;
pub const GL_UNPACK_ALIGNMENT: i32 = 3317;
pub const GL_UNPACK_LSB_FIRST: i32 = 3313;
pub const GL_UNPACK_ROW_LENGTH: i32 = 3314;
pub const GL_UNPACK_SKIP_PIXELS: i32 = 3316;
pub const GL_UNPACK_SKIP_ROWS: i32 = 3315;
pub const GL_UNPACK_SWAP_BYTES: i32 = 3312;
pub const GL_UNSIGNED_BYTE: i32 = 5121;
pub const GL_UNSIGNED_INT: i32 = 5125;
pub const GL_UNSIGNED_SHORT: i32 = 5123;
pub const GL_V2F: i32 = 10784;
pub const GL_V3F: i32 = 10785;
pub const GL_VENDOR: i32 = 7936;
pub const GL_VERSION: i32 = 7938;
pub const GL_VERSION_1_1: i32 = 1;
pub const GL_VERTEX_ARRAY: i32 = 32884;
pub const GL_VERTEX_ARRAY_COUNT_EXT: i32 = 32893;
pub const GL_VERTEX_ARRAY_EXT: i32 = 32884;
pub const GL_VERTEX_ARRAY_POINTER: i32 = 32910;
pub const GL_VERTEX_ARRAY_POINTER_EXT: i32 = 32910;
pub const GL_VERTEX_ARRAY_SIZE: i32 = 32890;
pub const GL_VERTEX_ARRAY_SIZE_EXT: i32 = 32890;
pub const GL_VERTEX_ARRAY_STRIDE: i32 = 32892;
pub const GL_VERTEX_ARRAY_STRIDE_EXT: i32 = 32892;
pub const GL_VERTEX_ARRAY_TYPE: i32 = 32891;
pub const GL_VERTEX_ARRAY_TYPE_EXT: i32 = 32891;
pub const GL_VIEWPORT: i32 = 2978;
pub const GL_VIEWPORT_BIT: i32 = 2048;
pub const GL_WIN_draw_range_elements: i32 = 1;
pub const GL_WIN_swap_hint: i32 = 1;
pub const GL_XOR: i32 = 5382;
pub const GL_ZERO: i32 = 0;
pub const GL_ZOOM_X: i32 = 3350;
pub const GL_ZOOM_Y: i32 = 3351;
pub type GLbitfield = u32;
pub type GLboolean = u8;
pub type GLbyte = i8;
pub type GLenum = u32;
pub type GLint = i32;
pub type GLshort = i16;
pub type GLsizei = i32;
pub type GLubyte = u8;
pub type GLuint = u32;
pub type GLushort = u16;
pub type GLvoid = core::ffi::c_void;
pub type PFNGLADDSWAPHINTRECTWINPROC = Option<unsafe extern "system" fn(x: GLint, y: GLint, width: GLsizei, height: GLsizei)>;
pub type PFNGLARRAYELEMENTARRAYEXTPROC = Option<unsafe extern "system" fn(mode: GLenum, count: GLsizei, pi: *const GLvoid)>;
pub type PFNGLARRAYELEMENTEXTPROC = Option<unsafe extern "system" fn(i: GLint)>;
pub type PFNGLCOLORPOINTEREXTPROC = Option<unsafe extern "system" fn(size: GLint, r#type: GLenum, stride: GLsizei, count: GLsizei, pointer: *const GLvoid)>;
pub type PFNGLCOLORSUBTABLEEXTPROC = Option<unsafe extern "system" fn(target: GLenum, start: GLsizei, count: GLsizei, format: GLenum, r#type: GLenum, data: *const GLvoid)>;
pub type PFNGLCOLORTABLEEXTPROC = Option<unsafe extern "system" fn(target: GLenum, internalformat: GLenum, width: GLsizei, format: GLenum, r#type: GLenum, data: *const GLvoid)>;
pub type PFNGLDRAWARRAYSEXTPROC = Option<unsafe extern "system" fn(mode: GLenum, first: GLint, count: GLsizei)>;
pub type PFNGLDRAWRANGEELEMENTSWINPROC = Option<unsafe extern "system" fn(mode: GLenum, start: GLuint, end: GLuint, count: GLsizei, r#type: GLenum, indices: *const GLvoid)>;
pub type PFNGLEDGEFLAGPOINTEREXTPROC = Option<unsafe extern "system" fn(stride: GLsizei, count: GLsizei, pointer: *const GLboolean)>;
pub type PFNGLGETCOLORTABLEEXTPROC = Option<unsafe extern "system" fn(target: GLenum, format: GLenum, r#type: GLenum, data: *mut GLvoid)>;
pub type PFNGLGETCOLORTABLEPARAMETERFVEXTPROC = Option<unsafe extern "system" fn(target: GLenum, pname: GLenum, params: *mut f32)>;
pub type PFNGLGETCOLORTABLEPARAMETERIVEXTPROC = Option<unsafe extern "system" fn(target: GLenum, pname: GLenum, params: *mut GLint)>;
pub type PFNGLGETPOINTERVEXTPROC = Option<unsafe extern "system" fn(pname: GLenum, params: *mut *mut GLvoid)>;
pub type PFNGLINDEXPOINTEREXTPROC = Option<unsafe extern "system" fn(r#type: GLenum, stride: GLsizei, count: GLsizei, pointer: *const GLvoid)>;
pub type PFNGLNORMALPOINTEREXTPROC = Option<unsafe extern "system" fn(r#type: GLenum, stride: GLsizei, count: GLsizei, pointer: *const GLvoid)>;
pub type PFNGLTEXCOORDPOINTEREXTPROC = Option<unsafe extern "system" fn(size: GLint, r#type: GLenum, stride: GLsizei, count: GLsizei, pointer: *const GLvoid)>;
pub type PFNGLVERTEXPOINTEREXTPROC = Option<unsafe extern "system" fn(size: GLint, r#type: GLenum, stride: GLsizei, count: GLsizei, pointer: *const GLvoid)>;
