[package]
name = "tool-reactor-metadata"
version = "0.0.0"
edition = "2024"
rust-version = "1.95"
publish = false

[dependencies]
helpers = { workspace = true }
roxmltree = "0.21"
windows-default = { workspace = true }
windows-metadata = { workspace = true }
windows-rdl = { workspace = true }

[lints]
workspace = true
