pub type DOCMISC = i32;
pub const DOCMISC_CANCREATEMULTIPLEVIEWS: DOCMISC = 1;
pub const DOCMISC_CANTOPENEDIT: DOCMISC = 4;
pub const DOCMISC_NOFILESUPPORT: DOCMISC = 8;
pub const DOCMISC_SUPPORTCOMPLEXRECTANGLES: DOCMISC = 2;
pub type IGNOREMIME = i32;
pub const IGNOREMIME_PROMPT: IGNOREMIME = 1;
pub const IGNOREMIME_TEXT: IGNOREMIME = 2;
pub const INSTALL_SCOPE_INVALID: u32 = 0;
pub const INSTALL_SCOPE_MACHINE: u32 = 1;
pub const INSTALL_SCOPE_USER: u32 = 2;
pub const MEDIAPLAYBACK_PAUSE: MEDIAPLAYBACK_STATE = 1;
pub const MEDIAPLAYBACK_PAUSE_AND_SUSPEND: MEDIAPLAYBACK_STATE = 2;
pub const MEDIAPLAYBACK_RESUME: MEDIAPLAYBACK_STATE = 0;
pub const MEDIAPLAYBACK_RESUME_FROM_SUSPEND: MEDIAPLAYBACK_STATE = 3;
pub type MEDIAPLAYBACK_STATE = i32;
pub const MSOCMDERR_E_CANCELED: i32 = -2147221245;
pub const MSOCMDERR_E_DISABLED: i32 = -2147221247;
pub const MSOCMDERR_E_FIRST: i32 = -2147221248;
pub const MSOCMDERR_E_NOHELP: i32 = -2147221246;
pub const MSOCMDERR_E_NOTSUPPORTED: i32 = -2147221248;
pub const MSOCMDERR_E_UNKNOWNGROUP: i32 = -2147221244;
pub const MSOCMDEXECOPT_DODEFAULT: u32 = 0;
pub const MSOCMDEXECOPT_DONTPROMPTUSER: u32 = 2;
pub const MSOCMDEXECOPT_PROMPTUSER: u32 = 1;
pub const MSOCMDEXECOPT_SHOWHELP: u32 = 3;
pub const MSOCMDF_ENABLED: u32 = 2;
pub const MSOCMDF_LATCHED: u32 = 4;
pub const MSOCMDF_NINCHED: u32 = 8;
pub const MSOCMDF_SUPPORTED: u32 = 1;
pub const MSOCMDID_CLEARSELECTION: u32 = 18;
pub const MSOCMDID_COPY: u32 = 12;
pub const MSOCMDID_CUT: u32 = 11;
pub const MSOCMDID_GETZOOMRANGE: u32 = 20;
pub const MSOCMDID_NEW: u32 = 2;
pub const MSOCMDID_OPEN: u32 = 1;
pub const MSOCMDID_PAGESETUP: u32 = 8;
pub const MSOCMDID_PASTE: u32 = 13;
pub const MSOCMDID_PASTESPECIAL: u32 = 14;
pub const MSOCMDID_PRINT: u32 = 6;
pub const MSOCMDID_PRINTPREVIEW: u32 = 7;
pub const MSOCMDID_PROPERTIES: u32 = 10;
pub const MSOCMDID_REDO: u32 = 16;
pub const MSOCMDID_SAVE: u32 = 3;
pub const MSOCMDID_SAVEAS: u32 = 4;
pub const MSOCMDID_SAVECOPYAS: u32 = 5;
pub const MSOCMDID_SELECTALL: u32 = 17;
pub const MSOCMDID_SPELL: u32 = 9;
pub const MSOCMDID_UNDO: u32 = 15;
pub const MSOCMDID_ZOOM: u32 = 19;
pub const MSOCMDTEXTF_NAME: u32 = 1;
pub const MSOCMDTEXTF_NONE: u32 = 0;
pub const MSOCMDTEXTF_STATUS: u32 = 2;
#[repr(C)]
#[derive(Clone, Copy, Default)]
pub struct OLECMD {
    pub cmdID: u32,
    pub cmdf: u32,
}
pub const OLECMDARGINDEX_ACTIVEXINSTALL_CLSID: u32 = 2;
pub const OLECMDARGINDEX_ACTIVEXINSTALL_DISPLAYNAME: u32 = 1;
pub const OLECMDARGINDEX_ACTIVEXINSTALL_INSTALLSCOPE: u32 = 3;
pub const OLECMDARGINDEX_ACTIVEXINSTALL_PUBLISHER: u32 = 0;
pub const OLECMDARGINDEX_ACTIVEXINSTALL_SOURCEURL: u32 = 4;
pub const OLECMDARGINDEX_SHOWPAGEACTIONMENU_HWND: u32 = 0;
pub const OLECMDARGINDEX_SHOWPAGEACTIONMENU_X: u32 = 1;
pub const OLECMDARGINDEX_SHOWPAGEACTIONMENU_Y: u32 = 2;
pub const OLECMDERR_E_CANCELED: i32 = -2147221245;
pub const OLECMDERR_E_DISABLED: i32 = -2147221247;
pub const OLECMDERR_E_FIRST: i32 = -2147221248;
pub const OLECMDERR_E_NOHELP: i32 = -2147221246;
pub const OLECMDERR_E_NOTSUPPORTED: i32 = -2147221248;
pub const OLECMDERR_E_UNKNOWNGROUP: i32 = -2147221244;
pub type OLECMDEXECOPT = i32;
pub const OLECMDEXECOPT_DODEFAULT: OLECMDEXECOPT = 0;
pub const OLECMDEXECOPT_DONTPROMPTUSER: OLECMDEXECOPT = 2;
pub const OLECMDEXECOPT_PROMPTUSER: OLECMDEXECOPT = 1;
pub const OLECMDEXECOPT_SHOWHELP: OLECMDEXECOPT = 3;
pub type OLECMDF = i32;
pub const OLECMDF_DEFHIDEONCTXTMENU: OLECMDF = 32;
pub const OLECMDF_ENABLED: OLECMDF = 2;
pub const OLECMDF_INVISIBLE: OLECMDF = 16;
pub const OLECMDF_LATCHED: OLECMDF = 4;
pub const OLECMDF_NINCHED: OLECMDF = 8;
pub const OLECMDF_SUPPORTED: OLECMDF = 1;
pub type OLECMDID = i32;
pub const OLECMDIDF_BROWSERSTATE_BLOCKEDVERSION: OLECMDID_BROWSERSTATEFLAG = 64;
pub const OLECMDIDF_BROWSERSTATE_DESKTOPHTMLDIALOG: OLECMDID_BROWSERSTATEFLAG = 32;
pub const OLECMDIDF_BROWSERSTATE_EXTENSIONSOFF: OLECMDID_BROWSERSTATEFLAG = 1;
pub const OLECMDIDF_BROWSERSTATE_IESECURITY: OLECMDID_BROWSERSTATEFLAG = 2;
pub const OLECMDIDF_BROWSERSTATE_PROTECTEDMODE_OFF: OLECMDID_BROWSERSTATEFLAG = 4;
pub const OLECMDIDF_BROWSERSTATE_REQUIRESACTIVEX: OLECMDID_BROWSERSTATEFLAG = 16;
pub const OLECMDIDF_BROWSERSTATE_RESET: OLECMDID_BROWSERSTATEFLAG = 8;
pub const OLECMDIDF_OPTICAL_ZOOM_NOLAYOUT: OLECMDID_OPTICAL_ZOOMFLAG = 16;
pub const OLECMDIDF_OPTICAL_ZOOM_NOPERSIST: OLECMDID_OPTICAL_ZOOMFLAG = 1;
pub const OLECMDIDF_OPTICAL_ZOOM_NOTRANSIENT: OLECMDID_OPTICAL_ZOOMFLAG = 32;
pub const OLECMDIDF_OPTICAL_ZOOM_RELOADFORNEWTAB: OLECMDID_OPTICAL_ZOOMFLAG = 64;
pub const OLECMDIDF_PAGEACTION_ACTIVEXDISALLOW: OLECMDID_PAGEACTIONFLAG = 16;
pub const OLECMDIDF_PAGEACTION_ACTIVEXINSTALL: OLECMDID_PAGEACTIONFLAG = 2;
pub const OLECMDIDF_PAGEACTION_ACTIVEXTRUSTFAIL: OLECMDID_PAGEACTIONFLAG = 4;
pub const OLECMDIDF_PAGEACTION_ACTIVEXUNSAFE: OLECMDID_PAGEACTIONFLAG = 32;
pub const OLECMDIDF_PAGEACTION_ACTIVEXUSERAPPROVAL: OLECMDID_PAGEACTIONFLAG = 262144;
pub const OLECMDIDF_PAGEACTION_ACTIVEXUSERDISABLE: OLECMDID_PAGEACTIONFLAG = 8;
pub const OLECMDIDF_PAGEACTION_ACTIVEX_EPM_INCOMPATIBLE: OLECMDID_PAGEACTIONFLAG = 16777216;
pub const OLECMDIDF_PAGEACTION_EXTENSION_COMPAT_BLOCKED: OLECMDID_PAGEACTIONFLAG = 268435456;
pub const OLECMDIDF_PAGEACTION_FILEDOWNLOAD: OLECMDID_PAGEACTIONFLAG = 1;
pub const OLECMDIDF_PAGEACTION_GENERIC_STATE: OLECMDID_PAGEACTIONFLAG = 1073741824;
pub const OLECMDIDF_PAGEACTION_INTRANETZONEREQUEST: OLECMDID_PAGEACTIONFLAG = 2097152;
pub const OLECMDIDF_PAGEACTION_INVALID_CERT: OLECMDID_PAGEACTIONFLAG = 1048576;
pub const OLECMDIDF_PAGEACTION_LOCALMACHINE: OLECMDID_PAGEACTIONFLAG = 128;
pub const OLECMDIDF_PAGEACTION_MIMETEXTPLAIN: OLECMDID_PAGEACTIONFLAG = 256;
pub const OLECMDIDF_PAGEACTION_MIXEDCONTENT: OLECMDID_PAGEACTIONFLAG = 524288;
pub const OLECMDIDF_PAGEACTION_NORESETACTIVEX: OLECMDID_PAGEACTIONFLAG = 536870912;
pub const OLECMDIDF_PAGEACTION_POPUPALLOWED: OLECMDID_PAGEACTIONFLAG = 65536;
pub const OLECMDIDF_PAGEACTION_POPUPWINDOW: OLECMDID_PAGEACTIONFLAG = 64;
pub const OLECMDIDF_PAGEACTION_PROTLOCKDOWNDENY: OLECMDID_PAGEACTIONFLAG = 32768;
pub const OLECMDIDF_PAGEACTION_PROTLOCKDOWNINTERNET: OLECMDID_PAGEACTIONFLAG = 8192;
pub const OLECMDIDF_PAGEACTION_PROTLOCKDOWNINTRANET: OLECMDID_PAGEACTIONFLAG = 4096;
pub const OLECMDIDF_PAGEACTION_PROTLOCKDOWNLOCALMACHINE: OLECMDID_PAGEACTIONFLAG = 1024;
pub const OLECMDIDF_PAGEACTION_PROTLOCKDOWNRESTRICTED: OLECMDID_PAGEACTIONFLAG = 16384;
pub const OLECMDIDF_PAGEACTION_PROTLOCKDOWNTRUSTED: OLECMDID_PAGEACTIONFLAG = 2048;
pub const OLECMDIDF_PAGEACTION_RESET: OLECMDID_PAGEACTIONFLAG = -2147483648;
pub const OLECMDIDF_PAGEACTION_SCRIPTNAVIGATE: OLECMDID_PAGEACTIONFLAG = 512;
pub const OLECMDIDF_PAGEACTION_SCRIPTNAVIGATE_ACTIVEXINSTALL: OLECMDID_PAGEACTIONFLAG = 512;
pub const OLECMDIDF_PAGEACTION_SCRIPTNAVIGATE_ACTIVEXUSERAPPROVAL: OLECMDID_PAGEACTIONFLAG = 33554432;
pub const OLECMDIDF_PAGEACTION_SCRIPTPROMPT: OLECMDID_PAGEACTIONFLAG = 131072;
pub const OLECMDIDF_PAGEACTION_SPOOFABLEIDNHOST: OLECMDID_PAGEACTIONFLAG = 8388608;
pub const OLECMDIDF_PAGEACTION_WPCBLOCKED: OLECMDID_PAGEACTIONFLAG = 67108864;
pub const OLECMDIDF_PAGEACTION_WPCBLOCKED_ACTIVEX: OLECMDID_PAGEACTIONFLAG = 134217728;
pub const OLECMDIDF_PAGEACTION_XSSFILTERED: OLECMDID_PAGEACTIONFLAG = 4194304;
pub const OLECMDIDF_REFRESH_CLEARUSERINPUT: OLECMDID_REFRESHFLAG = 4096;
pub const OLECMDIDF_REFRESH_COMPLETELY: OLECMDID_REFRESHFLAG = 3;
pub const OLECMDIDF_REFRESH_CONTINUE: OLECMDID_REFRESHFLAG = 2;
pub const OLECMDIDF_REFRESH_IFEXPIRED: OLECMDID_REFRESHFLAG = 1;
pub const OLECMDIDF_REFRESH_LEVELMASK: OLECMDID_REFRESHFLAG = 255;
pub const OLECMDIDF_REFRESH_NORMAL: OLECMDID_REFRESHFLAG = 0;
pub const OLECMDIDF_REFRESH_NO_CACHE: OLECMDID_REFRESHFLAG = 4;
pub const OLECMDIDF_REFRESH_PAGEACTION_ACTIVEXINSTALL: OLECMDID_REFRESHFLAG = 65536;
pub const OLECMDIDF_REFRESH_PAGEACTION_ALLOW_VERSION: OLECMDID_REFRESHFLAG = 134217728;
pub const OLECMDIDF_REFRESH_PAGEACTION_FILEDOWNLOAD: OLECMDID_REFRESHFLAG = 131072;
pub const OLECMDIDF_REFRESH_PAGEACTION_INVALID_CERT: OLECMDID_REFRESHFLAG = 67108864;
pub const OLECMDIDF_REFRESH_PAGEACTION_LOCALMACHINE: OLECMDID_REFRESHFLAG = 262144;
pub const OLECMDIDF_REFRESH_PAGEACTION_MIXEDCONTENT: OLECMDID_REFRESHFLAG = 33554432;
pub const OLECMDIDF_REFRESH_PAGEACTION_POPUPWINDOW: OLECMDID_REFRESHFLAG = 524288;
pub const OLECMDIDF_REFRESH_PAGEACTION_PROTLOCKDOWNINTERNET: OLECMDID_REFRESHFLAG = 8388608;
pub const OLECMDIDF_REFRESH_PAGEACTION_PROTLOCKDOWNINTRANET: OLECMDID_REFRESHFLAG = 4194304;
pub const OLECMDIDF_REFRESH_PAGEACTION_PROTLOCKDOWNLOCALMACHINE: OLECMDID_REFRESHFLAG = 1048576;
pub const OLECMDIDF_REFRESH_PAGEACTION_PROTLOCKDOWNRESTRICTED: OLECMDID_REFRESHFLAG = 16777216;
pub const OLECMDIDF_REFRESH_PAGEACTION_PROTLOCKDOWNTRUSTED: OLECMDID_REFRESHFLAG = 2097152;
pub const OLECMDIDF_REFRESH_PROMPTIFOFFLINE: OLECMDID_REFRESHFLAG = 8192;
pub const OLECMDIDF_REFRESH_RELOAD: OLECMDID_REFRESHFLAG = 5;
pub const OLECMDIDF_REFRESH_SKIPBEFOREUNLOADEVENT: OLECMDID_REFRESHFLAG = 32768;
pub const OLECMDIDF_REFRESH_THROUGHSCRIPT: OLECMDID_REFRESHFLAG = 16384;
pub const OLECMDIDF_VIEWPORTMODE_EXCLUDE_VISUAL_BOTTOM: OLECMDID_VIEWPORT_MODE_FLAG = 2;
pub const OLECMDIDF_VIEWPORTMODE_EXCLUDE_VISUAL_BOTTOM_VALID: OLECMDID_VIEWPORT_MODE_FLAG = 131072;
pub const OLECMDIDF_VIEWPORTMODE_FIXED_LAYOUT_WIDTH: OLECMDID_VIEWPORT_MODE_FLAG = 1;
pub const OLECMDIDF_VIEWPORTMODE_FIXED_LAYOUT_WIDTH_VALID: OLECMDID_VIEWPORT_MODE_FLAG = 65536;
pub const OLECMDIDF_WINDOWSTATE_ENABLED: OLECMDID_WINDOWSTATE_FLAG = 2;
pub const OLECMDIDF_WINDOWSTATE_ENABLED_VALID: OLECMDID_WINDOWSTATE_FLAG = 131072;
pub const OLECMDIDF_WINDOWSTATE_USERVISIBLE: OLECMDID_WINDOWSTATE_FLAG = 1;
pub const OLECMDIDF_WINDOWSTATE_USERVISIBLE_VALID: OLECMDID_WINDOWSTATE_FLAG = 65536;
pub const OLECMDID_ACTIVEXINSTALLSCOPE: OLECMDID = 66;
pub const OLECMDID_ADDTRAVELENTRY: OLECMDID = 60;
pub const OLECMDID_ALLOWUILESSSAVEAS: OLECMDID = 46;
pub type OLECMDID_BROWSERSTATEFLAG = i32;
pub const OLECMDID_CLEARSELECTION: OLECMDID = 18;
pub const OLECMDID_CLOSE: OLECMDID = 45;
pub const OLECMDID_COPY: OLECMDID = 12;
pub const OLECMDID_CUT: OLECMDID = 11;
pub const OLECMDID_DELETE: OLECMDID = 33;
pub const OLECMDID_DONTDOWNLOADCSS: OLECMDID = 47;
pub const OLECMDID_ENABLE_INTERACTION: OLECMDID = 36;
pub const OLECMDID_ENABLE_VISIBILITY: OLECMDID = 77;
pub const OLECMDID_EXITFULLSCREEN: OLECMDID = 81;
pub const OLECMDID_FIND: OLECMDID = 32;
pub const OLECMDID_FOCUSVIEWCONTROLS: OLECMDID = 57;
pub const OLECMDID_FOCUSVIEWCONTROLSQUERY: OLECMDID = 58;
pub const OLECMDID_GETPRINTTEMPLATE: OLECMDID = 52;
pub const OLECMDID_GETUSERSCALABLE: OLECMDID = 75;
pub const OLECMDID_GETZOOMRANGE: OLECMDID = 20;
pub const OLECMDID_HIDETOOLBARS: OLECMDID = 24;
pub const OLECMDID_HTTPEQUIV: OLECMDID = 34;
pub const OLECMDID_HTTPEQUIV_DONE: OLECMDID = 35;
pub const OLECMDID_LAYOUT_VIEWPORT_WIDTH: OLECMDID = 71;
pub const OLECMDID_MEDIA_PLAYBACK: OLECMDID = 78;
pub const OLECMDID_NEW: OLECMDID = 2;
pub const OLECMDID_ONBEFOREUNLOAD: OLECMDID = 83;
pub const OLECMDID_ONTOOLBARACTIVATED: OLECMDID = 31;
pub const OLECMDID_ONUNLOAD: OLECMDID = 37;
pub const OLECMDID_OPEN: OLECMDID = 1;
pub const OLECMDID_OPTICAL_GETZOOMRANGE: OLECMDID = 64;
pub const OLECMDID_OPTICAL_ZOOM: OLECMDID = 63;
pub type OLECMDID_OPTICAL_ZOOMFLAG = i32;
pub const OLECMDID_PAGEACTIONBLOCKED: OLECMDID = 55;
pub type OLECMDID_PAGEACTIONFLAG = i32;
pub const OLECMDID_PAGEACTIONUIQUERY: OLECMDID = 56;
pub const OLECMDID_PAGEAVAILABLE: OLECMDID = 74;
pub const OLECMDID_PAGESETUP: OLECMDID = 8;
pub const OLECMDID_PASTE: OLECMDID = 13;
pub const OLECMDID_PASTESPECIAL: OLECMDID = 14;
pub const OLECMDID_POPSTATEEVENT: OLECMDID = 69;
pub const OLECMDID_PREREFRESH: OLECMDID = 39;
pub const OLECMDID_PRINT: OLECMDID = 6;
pub const OLECMDID_PRINT2: OLECMDID = 49;
pub const OLECMDID_PRINTPREVIEW: OLECMDID = 7;
pub const OLECMDID_PRINTPREVIEW2: OLECMDID = 50;
pub const OLECMDID_PROPERTIES: OLECMDID = 10;
pub const OLECMDID_PROPERTYBAG2: OLECMDID = 38;
pub const OLECMDID_REDO: OLECMDID = 16;
pub const OLECMDID_REFRESH: OLECMDID = 22;
pub type OLECMDID_REFRESHFLAG = i32;
pub const OLECMDID_SAVE: OLECMDID = 3;
pub const OLECMDID_SAVEAS: OLECMDID = 4;
pub const OLECMDID_SAVECOPYAS: OLECMDID = 5;
pub const OLECMDID_SCROLLCOMPLETE: OLECMDID = 82;
pub const OLECMDID_SELECTALL: OLECMDID = 17;
pub const OLECMDID_SETDOWNLOADSTATE: OLECMDID = 29;
pub const OLECMDID_SETFAVICON: OLECMDID = 79;
pub const OLECMDID_SETPRINTTEMPLATE: OLECMDID = 51;
pub const OLECMDID_SETPROGRESSMAX: OLECMDID = 25;
pub const OLECMDID_SETPROGRESSPOS: OLECMDID = 26;
pub const OLECMDID_SETPROGRESSTEXT: OLECMDID = 27;
pub const OLECMDID_SETTITLE: OLECMDID = 28;
pub const OLECMDID_SET_HOST_FULLSCREENMODE: OLECMDID = 80;
pub const OLECMDID_SHOWFIND: OLECMDID = 42;
pub const OLECMDID_SHOWMESSAGE: OLECMDID = 41;
pub const OLECMDID_SHOWMESSAGE_BLOCKABLE: OLECMDID = 84;
pub const OLECMDID_SHOWPAGEACTIONMENU: OLECMDID = 59;
pub const OLECMDID_SHOWPAGESETUP: OLECMDID = 43;
pub const OLECMDID_SHOWPRINT: OLECMDID = 44;
pub const OLECMDID_SHOWSCRIPTERROR: OLECMDID = 40;
pub const OLECMDID_SHOWTASKDLG: OLECMDID = 68;
pub const OLECMDID_SHOWTASKDLG_BLOCKABLE: OLECMDID = 85;
pub const OLECMDID_SPELL: OLECMDID = 9;
pub const OLECMDID_STOP: OLECMDID = 23;
pub const OLECMDID_STOPDOWNLOAD: OLECMDID = 30;
pub const OLECMDID_UNDO: OLECMDID = 15;
pub const OLECMDID_UPDATEBACKFORWARDSTATE: OLECMDID = 62;
pub const OLECMDID_UPDATECOMMANDS: OLECMDID = 21;
pub const OLECMDID_UPDATEPAGESTATUS: OLECMDID = 48;
pub const OLECMDID_UPDATETRAVELENTRY: OLECMDID = 61;
pub const OLECMDID_UPDATETRAVELENTRY_DATARECOVERY: OLECMDID = 67;
pub const OLECMDID_UPDATE_CARET: OLECMDID = 76;
pub const OLECMDID_USER_OPTICAL_ZOOM: OLECMDID = 73;
pub const OLECMDID_VIEWPORT_MODE: OLECMDID = 70;
pub type OLECMDID_VIEWPORT_MODE_FLAG = i32;
pub const OLECMDID_VISUAL_VIEWPORT_EXCLUDE_BOTTOM: OLECMDID = 72;
pub const OLECMDID_WINDOWSTATECHANGED: OLECMDID = 65;
pub type OLECMDID_WINDOWSTATE_FLAG = i32;
pub const OLECMDID_ZOOM: OLECMDID = 19;
#[repr(C)]
#[derive(Clone, Copy)]
pub struct OLECMDTEXT {
    pub cmdtextf: u32,
    pub cwActual: u32,
    pub cwBuf: u32,
    pub rgwz: [u16; 1],
}
impl Default for OLECMDTEXT {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
pub type OLECMDTEXTF = i32;
pub const OLECMDTEXTF_NAME: OLECMDTEXTF = 1;
pub const OLECMDTEXTF_NONE: OLECMDTEXTF = 0;
pub const OLECMDTEXTF_STATUS: OLECMDTEXTF = 2;
pub const OLECMD_TASKDLGID_ONBEFOREUNLOAD: u32 = 1;
pub type PAGEACTION_UI = i32;
pub const PAGEACTION_UI_DEFAULT: PAGEACTION_UI = 0;
pub const PAGEACTION_UI_MODAL: PAGEACTION_UI = 1;
pub const PAGEACTION_UI_MODELESS: PAGEACTION_UI = 2;
pub const PAGEACTION_UI_SILENT: PAGEACTION_UI = 3;
#[repr(C)]
#[derive(Clone, Copy, Default)]
pub struct PAGERANGE {
    pub nFromPage: i32,
    pub nToPage: i32,
}
#[repr(C)]
#[derive(Clone, Copy)]
pub struct PAGESET {
    pub cbStruct: u32,
    pub fOddPages: windows_sys::core::BOOL,
    pub fEvenPages: windows_sys::core::BOOL,
    pub cPageRange: u32,
    pub rgPages: [PAGERANGE; 1],
}
impl Default for PAGESET {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
pub const PAGESET_TOLASTPAGE: u32 = 65535;
pub type PRINTFLAG = i32;
pub const PRINTFLAG_DONTACTUALLYPRINT: PRINTFLAG = 16;
pub const PRINTFLAG_FORCEPROPERTIES: PRINTFLAG = 32;
pub const PRINTFLAG_MAYBOTHERUSER: PRINTFLAG = 1;
pub const PRINTFLAG_PRINTTOFILE: PRINTFLAG = 64;
pub const PRINTFLAG_PROMPTUSER: PRINTFLAG = 2;
pub const PRINTFLAG_RECOMPOSETODEVICE: PRINTFLAG = 8;
pub const PRINTFLAG_USERMAYCHANGEPRINTER: PRINTFLAG = 4;
pub type WPCSETTING = i32;
pub const WPCSETTING_FILEDOWNLOAD_BLOCKED: WPCSETTING = 2;
pub const WPCSETTING_LOGGING_ENABLED: WPCSETTING = 1;
