pub const CSTORAGEPROPERTY: u32 = 23;
#[cfg(feature = "wtypes")]
pub const PID_STG_ACCESSTIME: super::PROPID = super::PROPID(16);
#[cfg(feature = "wtypes")]
pub const PID_STG_ALLOCSIZE: super::PROPID = super::PROPID(18);
#[cfg(feature = "wtypes")]
pub const PID_STG_ATTRIBUTES: super::PROPID = super::PROPID(13);
#[cfg(feature = "wtypes")]
pub const PID_STG_CHANGETIME: super::PROPID = super::PROPID(17);
#[cfg(feature = "wtypes")]
pub const PID_STG_CLASSID: super::PROPID = super::PROPID(3);
#[cfg(feature = "wtypes")]
pub const PID_STG_CONTENTS: super::PROPID = super::PROPID(19);
#[cfg(feature = "wtypes")]
pub const PID_STG_CREATETIME: super::PROPID = super::PROPID(15);
#[cfg(feature = "wtypes")]
pub const PID_STG_DIRECTORY: super::PROPID = super::PROPID(2);
#[cfg(feature = "wtypes")]
pub const PID_STG_FILEINDEX: super::PROPID = super::PROPID(8);
#[cfg(feature = "wtypes")]
pub const PID_STG_FRN: super::PROPID = super::PROPID(21);
#[cfg(feature = "wtypes")]
pub const PID_STG_LASTCHANGEUSN: super::PROPID = super::PROPID(9);
pub const PID_STG_MAX: u32 = 22;
#[cfg(feature = "wtypes")]
pub const PID_STG_NAME: super::PROPID = super::PROPID(10);
#[cfg(feature = "wtypes")]
pub const PID_STG_PARENT_WORKID: super::PROPID = super::PROPID(6);
#[cfg(feature = "wtypes")]
pub const PID_STG_PATH: super::PROPID = super::PROPID(11);
#[cfg(feature = "wtypes")]
pub const PID_STG_SCOPE: super::PROPID = super::PROPID(22);
#[cfg(feature = "wtypes")]
pub const PID_STG_SECONDARYSTORE: super::PROPID = super::PROPID(7);
#[cfg(feature = "wtypes")]
pub const PID_STG_SHORTNAME: super::PROPID = super::PROPID(20);
#[cfg(feature = "wtypes")]
pub const PID_STG_SIZE: super::PROPID = super::PROPID(12);
#[cfg(feature = "wtypes")]
pub const PID_STG_STORAGETYPE: super::PROPID = super::PROPID(4);
#[cfg(feature = "wtypes")]
pub const PID_STG_VOLUME_ID: super::PROPID = super::PROPID(5);
#[cfg(feature = "wtypes")]
pub const PID_STG_WRITETIME: super::PROPID = super::PROPID(14);
