// This package was generated by `tool_bindgen`.

pub mod cpp_fn_associated_enum_sys;
pub mod cpp_fn_associated_enum_win;
pub mod cpp_fn_return_none;
pub mod cpp_fn_return_void;
pub mod cpp_interface;
pub mod cpp_interface2;
pub mod deps;
pub mod deps2;
pub mod deps3;
pub mod iota;
pub mod winrt_class_with_handler;
pub mod winrt_class_without_handler;
pub mod winrt_delegate;
pub mod winrt_delegate_generic;
pub mod winrt_enum;
pub mod winrt_interface;
pub mod winrt_interface_generic;
pub mod winrt_interface_generic2;
pub mod winrt_interface_no_status;
pub mod winrt_interface_required;
pub mod winrt_interface_status;
pub mod winrt_struct;
pub mod winrt_struct_with_generic;
