[package]
name = "reactor_samples"
version = "0.0.0"
edition = "2024"
publish = false

[dependencies]
windows-core.workspace = true
windows-canvas.workspace = true
windows-composition = { workspace = true, features = ["reactor"] }
windows-reactor = { workspace = true, features = ["canvas", "webview"] }

[build-dependencies]
windows-reactor-setup = { workspace = true }

[lints]
workspace = true
