pub type ACTIVATIONTYPE = i32;
pub const ACTIVATIONTYPE_FROM_DATA: ACTIVATIONTYPE = 2;
pub const ACTIVATIONTYPE_FROM_FILE: ACTIVATIONTYPE = 16;
pub const ACTIVATIONTYPE_FROM_MONIKER: ACTIVATIONTYPE = 1;
pub const ACTIVATIONTYPE_FROM_STORAGE: ACTIVATIONTYPE = 4;
pub const ACTIVATIONTYPE_FROM_STREAM: ACTIVATIONTYPE = 8;
pub const ACTIVATIONTYPE_UNCATEGORIZED: ACTIVATIONTYPE = 0;
pub type APARTMENTID = u32;
pub type APTTYPE = i32;
pub type APTTYPEQUALIFIER = i32;
pub const APTTYPEQUALIFIER_APPLICATION_STA: APTTYPEQUALIFIER = 6;
pub const APTTYPEQUALIFIER_IMPLICIT_MTA: APTTYPEQUALIFIER = 1;
pub const APTTYPEQUALIFIER_NA_ON_IMPLICIT_MTA: APTTYPEQUALIFIER = 4;
pub const APTTYPEQUALIFIER_NA_ON_MAINSTA: APTTYPEQUALIFIER = 5;
pub const APTTYPEQUALIFIER_NA_ON_MTA: APTTYPEQUALIFIER = 2;
pub const APTTYPEQUALIFIER_NA_ON_STA: APTTYPEQUALIFIER = 3;
pub const APTTYPEQUALIFIER_NONE: APTTYPEQUALIFIER = 0;
pub const APTTYPEQUALIFIER_RESERVED_1: APTTYPEQUALIFIER = 7;
pub const APTTYPE_CURRENT: APTTYPE = -1;
pub const APTTYPE_MAINSTA: APTTYPE = 3;
pub const APTTYPE_MTA: APTTYPE = 1;
pub const APTTYPE_NA: APTTYPE = 2;
pub const APTTYPE_STA: APTTYPE = 0;
pub const COMBND_RESERVED1: RPCOPT_PROPERTIES = 4;
pub const COMBND_RESERVED2: RPCOPT_PROPERTIES = 5;
pub const COMBND_RESERVED3: RPCOPT_PROPERTIES = 8;
pub const COMBND_RESERVED4: RPCOPT_PROPERTIES = 16;
pub const COMBND_RPCTIMEOUT: RPCOPT_PROPERTIES = 1;
pub const COMBND_SERVER_LOCALITY: RPCOPT_PROPERTIES = 2;
pub const COMGLB_APPID: GLOBALOPT_PROPERTIES = 2;
pub const COMGLB_EXCEPTION_DONOT_HANDLE: GLOBALOPT_EH_VALUES = 1;
pub const COMGLB_EXCEPTION_DONOT_HANDLE_ANY: GLOBALOPT_EH_VALUES = 2;
pub const COMGLB_EXCEPTION_DONOT_HANDLE_FATAL: GLOBALOPT_EH_VALUES = 1;
pub const COMGLB_EXCEPTION_HANDLE: GLOBALOPT_EH_VALUES = 0;
pub const COMGLB_EXCEPTION_HANDLING: GLOBALOPT_PROPERTIES = 1;
pub const COMGLB_FAST_RUNDOWN: GLOBALOPT_RO_FLAGS = 8;
pub const COMGLB_PROPERTIES_RESERVED1: GLOBALOPT_PROPERTIES = 6;
pub const COMGLB_PROPERTIES_RESERVED2: GLOBALOPT_PROPERTIES = 7;
pub const COMGLB_PROPERTIES_RESERVED3: GLOBALOPT_PROPERTIES = 8;
pub const COMGLB_RESERVED1: GLOBALOPT_RO_FLAGS = 16;
pub const COMGLB_RESERVED2: GLOBALOPT_RO_FLAGS = 32;
pub const COMGLB_RESERVED3: GLOBALOPT_RO_FLAGS = 64;
pub const COMGLB_RESERVED4: GLOBALOPT_RO_FLAGS = 256;
pub const COMGLB_RESERVED5: GLOBALOPT_RO_FLAGS = 512;
pub const COMGLB_RESERVED6: GLOBALOPT_RO_FLAGS = 1024;
pub const COMGLB_RO_SETTINGS: GLOBALOPT_PROPERTIES = 4;
pub const COMGLB_RPC_THREADPOOL_SETTING: GLOBALOPT_PROPERTIES = 3;
pub const COMGLB_RPC_THREADPOOL_SETTING_DEFAULT_POOL: GLOBALOPT_RPCTP_VALUES = 0;
pub const COMGLB_RPC_THREADPOOL_SETTING_PRIVATE_POOL: GLOBALOPT_RPCTP_VALUES = 1;
pub const COMGLB_STA_MODALLOOP_REMOVE_TOUCH_MESSAGES: GLOBALOPT_RO_FLAGS = 1;
pub const COMGLB_STA_MODALLOOP_SHARED_QUEUE_DONOT_REMOVE_INPUT_MESSAGES: GLOBALOPT_RO_FLAGS = 4;
pub const COMGLB_STA_MODALLOOP_SHARED_QUEUE_REMOVE_INPUT_MESSAGES: GLOBALOPT_RO_FLAGS = 2;
pub const COMGLB_STA_MODALLOOP_SHARED_QUEUE_REORDER_POINTER_MESSAGES: GLOBALOPT_RO_FLAGS = 128;
pub const COMGLB_UNMARSHALING_POLICY: GLOBALOPT_PROPERTIES = 5;
pub const COMGLB_UNMARSHALING_POLICY_HYBRID: GLOBALOPT_UNMARSHALING_POLICY_VALUES = 2;
pub const COMGLB_UNMARSHALING_POLICY_NORMAL: GLOBALOPT_UNMARSHALING_POLICY_VALUES = 0;
pub const COMGLB_UNMARSHALING_POLICY_STRONG: GLOBALOPT_UNMARSHALING_POLICY_VALUES = 1;
#[repr(C)]
#[cfg(feature = "wtypesbase")]
#[derive(Clone, Copy)]
pub struct COSERVERINFO {
    pub dwReserved1: u32,
    pub pwszName: windows_sys::core::PWSTR,
    pub pAuthInfo: *mut super::wtypesbase::COAUTHINFO,
    pub dwReserved2: u32,
}
#[cfg(feature = "wtypesbase")]
impl Default for COSERVERINFO {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
pub type CO_MARSHALING_CONTEXT_ATTRIBUTES = i32;
pub const CO_MARSHALING_CONTEXT_ATTRIBUTE_RESERVED_1: CO_MARSHALING_CONTEXT_ATTRIBUTES = -2147483648;
pub const CO_MARSHALING_CONTEXT_ATTRIBUTE_RESERVED_10: CO_MARSHALING_CONTEXT_ATTRIBUTES = -2147483639;
pub const CO_MARSHALING_CONTEXT_ATTRIBUTE_RESERVED_11: CO_MARSHALING_CONTEXT_ATTRIBUTES = -2147483638;
pub const CO_MARSHALING_CONTEXT_ATTRIBUTE_RESERVED_12: CO_MARSHALING_CONTEXT_ATTRIBUTES = -2147483637;
pub const CO_MARSHALING_CONTEXT_ATTRIBUTE_RESERVED_13: CO_MARSHALING_CONTEXT_ATTRIBUTES = -2147483636;
pub const CO_MARSHALING_CONTEXT_ATTRIBUTE_RESERVED_14: CO_MARSHALING_CONTEXT_ATTRIBUTES = -2147483635;
pub const CO_MARSHALING_CONTEXT_ATTRIBUTE_RESERVED_15: CO_MARSHALING_CONTEXT_ATTRIBUTES = -2147483634;
pub const CO_MARSHALING_CONTEXT_ATTRIBUTE_RESERVED_16: CO_MARSHALING_CONTEXT_ATTRIBUTES = -2147483633;
pub const CO_MARSHALING_CONTEXT_ATTRIBUTE_RESERVED_17: CO_MARSHALING_CONTEXT_ATTRIBUTES = -2147483632;
pub const CO_MARSHALING_CONTEXT_ATTRIBUTE_RESERVED_18: CO_MARSHALING_CONTEXT_ATTRIBUTES = -2147483631;
pub const CO_MARSHALING_CONTEXT_ATTRIBUTE_RESERVED_2: CO_MARSHALING_CONTEXT_ATTRIBUTES = -2147483647;
pub const CO_MARSHALING_CONTEXT_ATTRIBUTE_RESERVED_3: CO_MARSHALING_CONTEXT_ATTRIBUTES = -2147483646;
pub const CO_MARSHALING_CONTEXT_ATTRIBUTE_RESERVED_4: CO_MARSHALING_CONTEXT_ATTRIBUTES = -2147483645;
pub const CO_MARSHALING_CONTEXT_ATTRIBUTE_RESERVED_5: CO_MARSHALING_CONTEXT_ATTRIBUTES = -2147483644;
pub const CO_MARSHALING_CONTEXT_ATTRIBUTE_RESERVED_6: CO_MARSHALING_CONTEXT_ATTRIBUTES = -2147483643;
pub const CO_MARSHALING_CONTEXT_ATTRIBUTE_RESERVED_7: CO_MARSHALING_CONTEXT_ATTRIBUTES = -2147483642;
pub const CO_MARSHALING_CONTEXT_ATTRIBUTE_RESERVED_8: CO_MARSHALING_CONTEXT_ATTRIBUTES = -2147483641;
pub const CO_MARSHALING_CONTEXT_ATTRIBUTE_RESERVED_9: CO_MARSHALING_CONTEXT_ATTRIBUTES = -2147483640;
pub const CO_MARSHALING_SOURCE_IS_APP_CONTAINER: CO_MARSHALING_CONTEXT_ATTRIBUTES = 0;
pub const DCOM_CALL_CANCELED: DCOM_CALL_STATE = 2;
pub const DCOM_CALL_COMPLETE: DCOM_CALL_STATE = 1;
pub type DCOM_CALL_STATE = i32;
pub const DCOM_NONE: DCOM_CALL_STATE = 0;
pub const EOAC_ACCESS_CONTROL: EOLE_AUTHENTICATION_CAPABILITIES = 4;
pub const EOAC_ANY_AUTHORITY: EOLE_AUTHENTICATION_CAPABILITIES = 128;
pub const EOAC_APPID: EOLE_AUTHENTICATION_CAPABILITIES = 8;
pub const EOAC_AUTO_IMPERSONATE: EOLE_AUTHENTICATION_CAPABILITIES = 1024;
pub const EOAC_DEFAULT: EOLE_AUTHENTICATION_CAPABILITIES = 2048;
pub const EOAC_DISABLE_AAA: EOLE_AUTHENTICATION_CAPABILITIES = 4096;
pub const EOAC_DYNAMIC: EOLE_AUTHENTICATION_CAPABILITIES = 16;
pub const EOAC_DYNAMIC_CLOAKING: EOLE_AUTHENTICATION_CAPABILITIES = 64;
pub const EOAC_MAKE_FULLSIC: EOLE_AUTHENTICATION_CAPABILITIES = 256;
pub const EOAC_MUTUAL_AUTH: EOLE_AUTHENTICATION_CAPABILITIES = 1;
pub const EOAC_NONE: EOLE_AUTHENTICATION_CAPABILITIES = 0;
pub const EOAC_NO_CUSTOM_MARSHAL: EOLE_AUTHENTICATION_CAPABILITIES = 8192;
pub const EOAC_REQUIRE_FULLSIC: EOLE_AUTHENTICATION_CAPABILITIES = 512;
pub const EOAC_RESERVED1: EOLE_AUTHENTICATION_CAPABILITIES = 16384;
pub const EOAC_SECURE_REFS: EOLE_AUTHENTICATION_CAPABILITIES = 2;
pub const EOAC_STATIC_CLOAKING: EOLE_AUTHENTICATION_CAPABILITIES = 32;
pub type EOLE_AUTHENTICATION_CAPABILITIES = i32;
pub type EXTCONN = i32;
pub const EXTCONN_CALLABLE: EXTCONN = 4;
pub const EXTCONN_STRONG: EXTCONN = 1;
pub const EXTCONN_WEAK: EXTCONN = 2;
pub type GLOBALOPT_EH_VALUES = i32;
pub type GLOBALOPT_PROPERTIES = i32;
pub type GLOBALOPT_RO_FLAGS = i32;
pub type GLOBALOPT_RPCTP_VALUES = i32;
pub type GLOBALOPT_UNMARSHALING_POLICY_VALUES = i32;
#[repr(C)]
#[derive(Clone, Copy, Default)]
pub struct IContext(pub u8);
#[repr(C)]
#[derive(Clone, Copy, Default)]
pub struct IEnumContextProps(pub u8);
#[repr(C)]
#[derive(Clone, Copy, Default)]
pub struct IObjContext(pub u8);
pub type LOCKTYPE = i32;
pub const LOCK_EXCLUSIVE: LOCKTYPE = 2;
pub const LOCK_ONLYONCE: LOCKTYPE = 4;
pub const LOCK_WRITE: LOCKTYPE = 1;
#[repr(C)]
#[derive(Clone, Copy)]
pub struct MULTI_QI {
    pub pIID: *const windows_sys::core::GUID,
    pub pItf: *mut core::ffi::c_void,
    pub hr: windows_sys::core::HRESULT,
}
impl Default for MULTI_QI {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
pub type MachineGlobalObjectTableRegistrationToken = *mut core::ffi::c_void;
pub type PRPCOLEMESSAGE = *mut RPCOLEMESSAGE;
pub type PSOLE_AUTHENTICATION_INFO = *mut SOLE_AUTHENTICATION_INFO;
pub type PSOLE_AUTHENTICATION_LIST = *mut SOLE_AUTHENTICATION_LIST;
#[cfg(feature = "wtypesbase")]
pub type PSOLE_AUTHENTICATION_SERVICE = *mut SOLE_AUTHENTICATION_SERVICE;
pub type RPCOLEDATAREP = u32;
#[repr(C)]
#[derive(Clone, Copy)]
pub struct RPCOLEMESSAGE {
    pub reserved1: *mut core::ffi::c_void,
    pub dataRepresentation: RPCOLEDATAREP,
    pub Buffer: *mut core::ffi::c_void,
    pub cbBuffer: u32,
    pub iMethod: u32,
    pub reserved2: [*mut core::ffi::c_void; 5],
    pub rpcFlags: u32,
}
impl Default for RPCOLEMESSAGE {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
pub type RPCOPT_PROPERTIES = i32;
pub type RPCOPT_SERVER_LOCALITY_VALUES = i32;
#[repr(C)]
#[derive(Clone, Copy)]
pub struct SChannelHookCallInfo {
    pub iid: windows_sys::core::GUID,
    pub cbSize: u32,
    pub uCausality: windows_sys::core::GUID,
    pub dwServerPid: u32,
    pub iMethod: u32,
    pub pObject: *mut core::ffi::c_void,
}
impl Default for SChannelHookCallInfo {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
pub const SERVER_LOCALITY_MACHINE_LOCAL: RPCOPT_SERVER_LOCALITY_VALUES = 1;
pub const SERVER_LOCALITY_PROCESS_LOCAL: RPCOPT_SERVER_LOCALITY_VALUES = 0;
pub const SERVER_LOCALITY_REMOTE: RPCOPT_SERVER_LOCALITY_VALUES = 2;
#[repr(C)]
#[derive(Clone, Copy)]
pub struct SOLE_AUTHENTICATION_INFO {
    pub dwAuthnSvc: u32,
    pub dwAuthzSvc: u32,
    pub pAuthInfo: *mut core::ffi::c_void,
}
impl Default for SOLE_AUTHENTICATION_INFO {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
#[repr(C)]
#[derive(Clone, Copy)]
pub struct SOLE_AUTHENTICATION_LIST {
    pub cAuthInfo: u32,
    pub aAuthInfo: *mut SOLE_AUTHENTICATION_INFO,
}
impl Default for SOLE_AUTHENTICATION_LIST {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
#[repr(C)]
#[cfg(feature = "wtypesbase")]
#[derive(Clone, Copy)]
pub struct SOLE_AUTHENTICATION_SERVICE {
    pub dwAuthnSvc: u32,
    pub dwAuthzSvc: u32,
    pub pPrincipalName: *mut super::wtypesbase::OLECHAR,
    pub hr: windows_sys::core::HRESULT,
}
#[cfg(feature = "wtypesbase")]
impl Default for SOLE_AUTHENTICATION_SERVICE {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
#[repr(C)]
#[cfg(feature = "minwindef")]
#[derive(Clone, Copy)]
pub struct STATSTG {
    pub pwcsName: windows_sys::core::PWSTR,
    pub r#type: u32,
    pub cbSize: u64,
    pub mtime: super::minwindef::FILETIME,
    pub ctime: super::minwindef::FILETIME,
    pub atime: super::minwindef::FILETIME,
    pub grfMode: u32,
    pub grfLocksSupported: u32,
    pub clsid: windows_sys::core::GUID,
    pub grfStateBits: u32,
    pub reserved: u32,
}
#[cfg(feature = "minwindef")]
impl Default for STATSTG {
    fn default() -> Self {
        unsafe { core::mem::zeroed() }
    }
}
pub type STGTY = i32;
pub const STGTY_LOCKBYTES: STGTY = 3;
pub const STGTY_PROPERTY: STGTY = 4;
pub const STGTY_STORAGE: STGTY = 1;
pub const STGTY_STREAM: STGTY = 2;
pub type STREAM_SEEK = i32;
pub const STREAM_SEEK_CUR: STREAM_SEEK = 1;
pub const STREAM_SEEK_END: STREAM_SEEK = 2;
pub const STREAM_SEEK_SET: STREAM_SEEK = 0;
pub type THDTYPE = i32;
pub const THDTYPE_BLOCKMESSAGES: THDTYPE = 0;
pub const THDTYPE_PROCESSMESSAGES: THDTYPE = 1;
