[package]
name = "sample_reactor_next_counter"
version = "0.0.0"
edition = "2024"
publish = false

[[bin]]
name = "component"
path = "src/component.rs"

[dependencies]
windows-reactor-next = { workspace = true }

[build-dependencies]
windows-reactor-setup = { workspace = true }

[lints]
workspace = true
