[package]
name = "test_numerics"
version = "0.0.0"
edition = "2024"
publish = false

[lib]
doc = false
doctest = false

[dev-dependencies.windows-numerics]
workspace = true
features = ["std"]

[dependencies.windows-link]
workspace = true

[dev-dependencies.windows-sys]
workspace = true
features = ["d3d9", "dcommon"]

[lints]
workspace = true
