[package]
name = "test_tracing"
version = "0.0.0"
edition = "2024"
publish = false

[lib]
doc = false
doctest = false

[dependencies.windows]
workspace = true
features = [
    "evntcons",
    "evntprov",
    "evntrace",
    "minwinbase",
    "minwindef",
    "tdh",
    "timezoneapi",
    "winnt",
    "wmistr",
]

[dependencies.windows-tracing]
workspace = true

[lints]
workspace = true
