pub type TrackerHandle = *mut core::ffi::c_void;
pub type XAML_REFERENCETRACKER_DISCONNECT = i32;
pub const XAML_REFERENCETRACKER_DISCONNECT_DEFAULT: XAML_REFERENCETRACKER_DISCONNECT = 0;
pub const XAML_REFERENCETRACKER_DISCONNECT_SUSPEND: XAML_REFERENCETRACKER_DISCONNECT = 1;
