// This file is auto-generated by tool_reactor_codegen. Do not edit.

use super::convert::string_as_textblock;
use super::*;
use crate::bindings as Xaml;
#[doc = r" Try to handle a `set_prop` call via generated dispatch."]
#[doc = r" Returns `Ok(true)` if handled, `Ok(false)` to fall through."]
pub(crate) fn dispatch(
    handle: &Handle,
    prop: Prop,
    value: &PropValue,
) -> windows_core::Result<bool> {
    match (prop, value, handle) {
        (Prop::Header, PropValue::Str(v), Handle::AutoSuggestBox(h)) => {
            let insp = windows_reference::IReference::from(v.as_str());
            h.cast::<Xaml::IAutoSuggestBox>()?.put_Header(&insp)?;
        }
        (Prop::Header, PropValue::Unset, Handle::AutoSuggestBox(h)) => {
            h.cast::<Xaml::IAutoSuggestBox>()?.put_Header(None)?;
        }
        (Prop::IsEnabled, PropValue::Bool(v), Handle::AutoSuggestBox(h)) => {
            h.cast::<Xaml::IControl>()?.put_IsEnabled(*v)?;
        }
        (Prop::IsEnabled, PropValue::Unset, Handle::AutoSuggestBox(h)) => {
            h.cast::<Xaml::IControl>()?.put_IsEnabled(true)?;
        }
        (Prop::PlaceholderText, PropValue::Str(v), Handle::AutoSuggestBox(h)) => {
            h.cast::<Xaml::IAutoSuggestBox>()?
                .put_PlaceholderText(v.as_str())?;
        }
        (Prop::IsEnabled, PropValue::Bool(v), Handle::Button(h)) => {
            h.cast::<Xaml::IControl>()?.put_IsEnabled(*v)?;
        }
        (Prop::IsEnabled, PropValue::Unset, Handle::Button(h)) => {
            h.cast::<Xaml::IControl>()?.put_IsEnabled(true)?;
        }
        (Prop::Header, PropValue::Str(v), Handle::CalendarDatePicker(h)) => {
            let tb = string_as_textblock(v.as_str())?;
            h.cast::<Xaml::ICalendarDatePicker>()?.put_Header(&tb)?;
        }
        (Prop::Header, PropValue::Unset, Handle::CalendarDatePicker(h)) => {
            h.cast::<Xaml::ICalendarDatePicker>()?.put_Header(None)?;
        }
        (Prop::IsCalendarOpen, PropValue::Bool(v), Handle::CalendarDatePicker(h)) => {
            h.cast::<Xaml::ICalendarDatePicker>()?
                .put_IsCalendarOpen(*v)?;
        }
        (Prop::IsEnabled, PropValue::Bool(v), Handle::CalendarDatePicker(h)) => {
            h.cast::<Xaml::IControl>()?.put_IsEnabled(*v)?;
        }
        (Prop::IsEnabled, PropValue::Unset, Handle::CalendarDatePicker(h)) => {
            h.cast::<Xaml::IControl>()?.put_IsEnabled(true)?;
        }
        (Prop::IsTodayHighlighted, PropValue::Bool(v), Handle::CalendarDatePicker(h)) => {
            h.cast::<Xaml::ICalendarDatePicker>()?
                .put_IsTodayHighlighted(*v)?;
        }
        (Prop::PlaceholderText, PropValue::Str(v), Handle::CalendarDatePicker(h)) => {
            h.cast::<Xaml::ICalendarDatePicker>()?
                .put_PlaceholderText(v.as_str())?;
        }
        (Prop::PlaceholderText, PropValue::Unset, Handle::CalendarDatePicker(h)) => {
            h.cast::<Xaml::ICalendarDatePicker>()?
                .put_PlaceholderText("")?;
        }
        (Prop::IsEnabled, PropValue::Bool(v), Handle::CalendarView(h)) => {
            h.cast::<Xaml::IControl>()?.put_IsEnabled(*v)?;
        }
        (Prop::IsEnabled, PropValue::Unset, Handle::CalendarView(h)) => {
            h.cast::<Xaml::IControl>()?.put_IsEnabled(true)?;
        }
        (Prop::IsGroupLabelVisible, PropValue::Bool(v), Handle::CalendarView(h)) => {
            h.cast::<Xaml::ICalendarView>()?
                .put_IsGroupLabelVisible(*v)?;
        }
        (Prop::IsTodayHighlighted, PropValue::Bool(v), Handle::CalendarView(h)) => {
            h.cast::<Xaml::ICalendarView>()?
                .put_IsTodayHighlighted(*v)?;
        }
        (Prop::Content, PropValue::Str(v), Handle::CheckBox(h)) => {
            let tb = string_as_textblock(v.as_str())?;
            h.cast::<Xaml::IContentControl>()?.put_Content(&tb)?;
        }
        (Prop::Content, PropValue::Unset, Handle::CheckBox(h)) => {
            h.cast::<Xaml::IContentControl>()?.put_Content(None)?;
        }
        (Prop::IsChecked, PropValue::Bool(v), Handle::CheckBox(h)) => {
            h.cast::<Xaml::IToggleButton>()?.put_IsChecked(Some(*v))?;
        }
        (Prop::IsChecked, PropValue::Unset, Handle::CheckBox(h)) => {
            h.cast::<Xaml::IToggleButton>()?.put_IsChecked(None)?;
        }
        (Prop::IsEnabled, PropValue::Bool(v), Handle::CheckBox(h)) => {
            h.cast::<Xaml::IControl>()?.put_IsEnabled(*v)?;
        }
        (Prop::IsEnabled, PropValue::Unset, Handle::CheckBox(h)) => {
            h.cast::<Xaml::IControl>()?.put_IsEnabled(true)?;
        }
        (Prop::IsAlphaEnabled, PropValue::Bool(v), Handle::ColorPicker(h)) => {
            h.cast::<Xaml::IColorPicker>()?.put_IsAlphaEnabled(*v)?;
        }
        (Prop::IsColorChannelTextInputVisible, PropValue::Bool(v), Handle::ColorPicker(h)) => {
            h.cast::<Xaml::IColorPicker>()?
                .put_IsColorChannelTextInputVisible(*v)?;
        }
        (Prop::IsColorSliderVisible, PropValue::Bool(v), Handle::ColorPicker(h)) => {
            h.cast::<Xaml::IColorPicker>()?
                .put_IsColorSliderVisible(*v)?;
        }
        (Prop::IsHexInputVisible, PropValue::Bool(v), Handle::ColorPicker(h)) => {
            h.cast::<Xaml::IColorPicker>()?.put_IsHexInputVisible(*v)?;
        }
        (Prop::Header, PropValue::Str(v), Handle::ComboBox(h)) => {
            let tb = string_as_textblock(v.as_str())?;
            h.cast::<Xaml::IComboBox>()?.put_Header(&tb)?;
        }
        (Prop::Header, PropValue::Unset, Handle::ComboBox(h)) => {
            h.cast::<Xaml::IComboBox>()?.put_Header(None)?;
        }
        (Prop::IsEditable, PropValue::Bool(v), Handle::ComboBox(h)) => {
            h.cast::<Xaml::IComboBox>()?.put_IsEditable(*v)?;
        }
        (Prop::IsEnabled, PropValue::Bool(v), Handle::ComboBox(h)) => {
            h.cast::<Xaml::IControl>()?.put_IsEnabled(*v)?;
        }
        (Prop::IsEnabled, PropValue::Unset, Handle::ComboBox(h)) => {
            h.cast::<Xaml::IControl>()?.put_IsEnabled(true)?;
        }
        (Prop::PlaceholderText, PropValue::Str(v), Handle::ComboBox(h)) => {
            h.cast::<Xaml::IComboBox>()?
                .put_PlaceholderText(v.as_str())?;
        }
        (Prop::PlaceholderText, PropValue::Unset, Handle::ComboBox(h)) => {
            h.cast::<Xaml::IComboBox>()?.put_PlaceholderText("")?;
        }
        (Prop::SelectedIndex, PropValue::I32(v), Handle::ComboBox(h)) => {
            h.cast::<Xaml::ISelector>()?.put_SelectedIndex(*v)?;
        }
        (
            Prop::DefaultLabelPosition,
            PropValue::CommandBarLabelPosition(v),
            Handle::CommandBar(h),
        ) => {
            let mapped = match v {
                CommandBarLabelPos::Bottom => Xaml::CommandBarDefaultLabelPosition::Bottom,
                CommandBarLabelPos::Right => Xaml::CommandBarDefaultLabelPosition::Right,
                CommandBarLabelPos::Collapsed => Xaml::CommandBarDefaultLabelPosition::Collapsed,
            };
            h.cast::<Xaml::ICommandBar>()?
                .put_DefaultLabelPosition(mapped)?;
        }
        (Prop::CloseButtonText, PropValue::Str(v), Handle::ContentDialog(h)) => {
            h.cast::<Xaml::IContentDialog>()?
                .put_CloseButtonText(v.as_str())?;
        }
        (Prop::CloseButtonText, PropValue::Unset, Handle::ContentDialog(h)) => {
            h.cast::<Xaml::IContentDialog>()?.put_CloseButtonText("")?;
        }
        (Prop::Content, PropValue::Str(v), Handle::ContentDialog(h)) => {
            let tb = string_as_textblock(v.as_str())?;
            h.cast::<Xaml::IContentControl>()?.put_Content(&tb)?;
        }
        (Prop::Content, PropValue::Unset, Handle::ContentDialog(h)) => {
            h.cast::<Xaml::IContentControl>()?.put_Content(None)?;
        }
        (Prop::IsPrimaryButtonEnabled, PropValue::Bool(v), Handle::ContentDialog(h)) => {
            h.cast::<Xaml::IContentDialog>()?
                .put_IsPrimaryButtonEnabled(*v)?;
        }
        (Prop::IsSecondaryButtonEnabled, PropValue::Bool(v), Handle::ContentDialog(h)) => {
            h.cast::<Xaml::IContentDialog>()?
                .put_IsSecondaryButtonEnabled(*v)?;
        }
        (Prop::PrimaryButtonText, PropValue::Str(v), Handle::ContentDialog(h)) => {
            h.cast::<Xaml::IContentDialog>()?
                .put_PrimaryButtonText(v.as_str())?;
        }
        (Prop::PrimaryButtonText, PropValue::Unset, Handle::ContentDialog(h)) => {
            h.cast::<Xaml::IContentDialog>()?
                .put_PrimaryButtonText("")?;
        }
        (Prop::SecondaryButtonText, PropValue::Str(v), Handle::ContentDialog(h)) => {
            h.cast::<Xaml::IContentDialog>()?
                .put_SecondaryButtonText(v.as_str())?;
        }
        (Prop::SecondaryButtonText, PropValue::Unset, Handle::ContentDialog(h)) => {
            h.cast::<Xaml::IContentDialog>()?
                .put_SecondaryButtonText("")?;
        }
        (Prop::Title, PropValue::Str(v), Handle::ContentDialog(h)) => {
            let insp = windows_reference::IReference::from(v.as_str());
            h.cast::<Xaml::IContentDialog>()?.put_Title(&insp)?;
        }
        (Prop::Title, PropValue::Unset, Handle::ContentDialog(h)) => {
            h.cast::<Xaml::IContentDialog>()?.put_Title(None)?;
        }
        (Prop::DayVisible, PropValue::Bool(v), Handle::DatePicker(h)) => {
            h.cast::<Xaml::IDatePicker>()?.put_DayVisible(*v)?;
        }
        (Prop::Header, PropValue::Str(v), Handle::DatePicker(h)) => {
            let tb = string_as_textblock(v.as_str())?;
            h.cast::<Xaml::IDatePicker>()?.put_Header(&tb)?;
        }
        (Prop::Header, PropValue::Unset, Handle::DatePicker(h)) => {
            h.cast::<Xaml::IDatePicker>()?.put_Header(None)?;
        }
        (Prop::IsEnabled, PropValue::Bool(v), Handle::DatePicker(h)) => {
            h.cast::<Xaml::IControl>()?.put_IsEnabled(*v)?;
        }
        (Prop::IsEnabled, PropValue::Unset, Handle::DatePicker(h)) => {
            h.cast::<Xaml::IControl>()?.put_IsEnabled(true)?;
        }
        (Prop::MonthVisible, PropValue::Bool(v), Handle::DatePicker(h)) => {
            h.cast::<Xaml::IDatePicker>()?.put_MonthVisible(*v)?;
        }
        (Prop::YearVisible, PropValue::Bool(v), Handle::DatePicker(h)) => {
            h.cast::<Xaml::IDatePicker>()?.put_YearVisible(*v)?;
        }
        (Prop::Content, PropValue::Str(v), Handle::DropDownButton(h)) => {
            let insp = windows_reference::IReference::from(v.as_str());
            h.cast::<Xaml::IContentControl>()?.put_Content(&insp)?;
        }
        (Prop::Content, PropValue::Unset, Handle::DropDownButton(h)) => {
            h.cast::<Xaml::IContentControl>()?.put_Content(None)?;
        }
        (Prop::IsEnabled, PropValue::Bool(v), Handle::DropDownButton(h)) => {
            h.cast::<Xaml::IControl>()?.put_IsEnabled(*v)?;
        }
        (Prop::IsEnabled, PropValue::Unset, Handle::DropDownButton(h)) => {
            h.cast::<Xaml::IControl>()?.put_IsEnabled(true)?;
        }
        (Prop::IsExpanded, PropValue::Bool(v), Handle::Expander(h)) => {
            h.cast::<Xaml::IExpander>()?.put_IsExpanded(*v)?;
        }
        (Prop::ColumnSpacing, PropValue::F64(v), Handle::Grid(h)) => {
            h.cast::<Xaml::IGrid>()?.put_ColumnSpacing(*v)?;
        }
        (Prop::ColumnSpacing, PropValue::Unset, Handle::Grid(h)) => {
            h.cast::<Xaml::IGrid>()?.put_ColumnSpacing(0.0)?;
        }
        (Prop::RowSpacing, PropValue::F64(v), Handle::Grid(h)) => {
            h.cast::<Xaml::IGrid>()?.put_RowSpacing(*v)?;
        }
        (Prop::RowSpacing, PropValue::Unset, Handle::Grid(h)) => {
            h.cast::<Xaml::IGrid>()?.put_RowSpacing(0.0)?;
        }
        (Prop::Content, PropValue::Str(v), Handle::HyperlinkButton(h)) => {
            let tb = string_as_textblock(v.as_str())?;
            h.cast::<Xaml::IContentControl>()?.put_Content(&tb)?;
        }
        (Prop::Content, PropValue::Unset, Handle::HyperlinkButton(h)) => {
            h.cast::<Xaml::IContentControl>()?.put_Content(None)?;
        }
        (Prop::IsEnabled, PropValue::Bool(v), Handle::HyperlinkButton(h)) => {
            h.cast::<Xaml::IControl>()?.put_IsEnabled(*v)?;
        }
        (Prop::IsEnabled, PropValue::Unset, Handle::HyperlinkButton(h)) => {
            h.cast::<Xaml::IControl>()?.put_IsEnabled(true)?;
        }
        (Prop::Stretch, PropValue::ImageStretch(v), Handle::Image(h)) => {
            let mapped = match v {
                ImageStretch::Uniform => Xaml::Stretch::Uniform,
                ImageStretch::UniformToFill => Xaml::Stretch::UniformToFill,
                ImageStretch::Fill => Xaml::Stretch::Fill,
                ImageStretch::None => Xaml::Stretch::None,
            };
            h.cast::<Xaml::IImage>()?.put_Stretch(mapped)?;
        }
        (Prop::IsClosable, PropValue::Bool(v), Handle::InfoBar(h)) => {
            h.cast::<Xaml::IInfoBar>()?.put_IsClosable(*v)?;
        }
        (Prop::IsOpen, PropValue::Bool(v), Handle::InfoBar(h)) => {
            h.cast::<Xaml::IInfoBar>()?.put_IsOpen(*v)?;
        }
        (Prop::Message, PropValue::Str(v), Handle::InfoBar(h)) => {
            h.cast::<Xaml::IInfoBar>()?.put_Message(v.as_str())?;
        }
        (Prop::Message, PropValue::Unset, Handle::InfoBar(h)) => {
            h.cast::<Xaml::IInfoBar>()?.put_Message("")?;
        }
        (Prop::Severity, PropValue::InfoBarSev(v), Handle::InfoBar(h)) => {
            let mapped = match v {
                InfoBarSeverity::Informational => Xaml::InfoBarSeverity::Informational,
                InfoBarSeverity::Success => Xaml::InfoBarSeverity::Success,
                InfoBarSeverity::Warning => Xaml::InfoBarSeverity::Warning,
                InfoBarSeverity::Error => Xaml::InfoBarSeverity::Error,
            };
            h.cast::<Xaml::IInfoBar>()?.put_Severity(mapped)?;
        }
        (Prop::Title, PropValue::Str(v), Handle::InfoBar(h)) => {
            h.cast::<Xaml::IInfoBar>()?.put_Title(v.as_str())?;
        }
        (Prop::Title, PropValue::Unset, Handle::InfoBar(h)) => {
            h.cast::<Xaml::IInfoBar>()?.put_Title("")?;
        }
        (Prop::IsEnabled, PropValue::Bool(v), Handle::ListBox(h)) => {
            h.cast::<Xaml::IControl>()?.put_IsEnabled(*v)?;
        }
        (Prop::IsEnabled, PropValue::Unset, Handle::ListBox(h)) => {
            h.cast::<Xaml::IControl>()?.put_IsEnabled(true)?;
        }
        (Prop::SelectedIndex, PropValue::I32(v), Handle::ListBox(h)) => {
            h.cast::<Xaml::ISelector>()?.put_SelectedIndex(*v)?;
        }
        (Prop::Header, PropValue::Str(v), Handle::NavigationView(h)) => {
            let tb = string_as_textblock(v.as_str())?;
            h.cast::<Xaml::INavigationView>()?.put_Header(&tb)?;
        }
        (Prop::Header, PropValue::Unset, Handle::NavigationView(h)) => {
            h.cast::<Xaml::INavigationView>()?.put_Header(None)?;
        }
        (Prop::IsBackEnabled, PropValue::Bool(v), Handle::NavigationView(h)) => {
            h.cast::<Xaml::INavigationView2>()?.put_IsBackEnabled(*v)?;
        }
        (Prop::IsPaneOpen, PropValue::Bool(v), Handle::NavigationView(h)) => {
            h.cast::<Xaml::INavigationView>()?.put_IsPaneOpen(*v)?;
        }
        (Prop::IsPaneToggleButtonVisible, PropValue::Bool(v), Handle::NavigationView(h)) => {
            h.cast::<Xaml::INavigationView>()?
                .put_IsPaneToggleButtonVisible(*v)?;
        }
        (Prop::IsSettingsVisible, PropValue::Bool(v), Handle::NavigationView(h)) => {
            h.cast::<Xaml::INavigationView>()?
                .put_IsSettingsVisible(*v)?;
        }
        (Prop::PaneDisplayMode, PropValue::NavPaneDisplayMode(v), Handle::NavigationView(h)) => {
            let mapped = match v {
                NavViewPaneDisplayMode::Auto => Xaml::NavigationViewPaneDisplayMode::Auto,
                NavViewPaneDisplayMode::Left => Xaml::NavigationViewPaneDisplayMode::Left,
                NavViewPaneDisplayMode::Top => Xaml::NavigationViewPaneDisplayMode::Top,
                NavViewPaneDisplayMode::LeftCompact => {
                    Xaml::NavigationViewPaneDisplayMode::LeftCompact
                }
                NavViewPaneDisplayMode::LeftMinimal => {
                    Xaml::NavigationViewPaneDisplayMode::LeftMinimal
                }
            };
            h.cast::<Xaml::INavigationView2>()?
                .put_PaneDisplayMode(mapped)?;
        }
        (Prop::PaneTitle, PropValue::Str(v), Handle::NavigationView(h)) => {
            h.cast::<Xaml::INavigationView2>()?
                .put_PaneTitle(v.as_str())?;
        }
        (Prop::PaneTitle, PropValue::Unset, Handle::NavigationView(h)) => {
            h.cast::<Xaml::INavigationView2>()?.put_PaneTitle("")?;
        }
        (Prop::Header, PropValue::Str(v), Handle::NumberBox(h)) => {
            let tb = string_as_textblock(v.as_str())?;
            h.cast::<Xaml::INumberBox>()?.put_Header(&tb)?;
        }
        (Prop::Header, PropValue::Unset, Handle::NumberBox(h)) => {
            h.cast::<Xaml::INumberBox>()?.put_Header(None)?;
        }
        (Prop::IsEnabled, PropValue::Bool(v), Handle::NumberBox(h)) => {
            h.cast::<Xaml::IControl>()?.put_IsEnabled(*v)?;
        }
        (Prop::IsEnabled, PropValue::Unset, Handle::NumberBox(h)) => {
            h.cast::<Xaml::IControl>()?.put_IsEnabled(true)?;
        }
        (Prop::Maximum, PropValue::F64(v), Handle::NumberBox(h)) => {
            h.cast::<Xaml::INumberBox>()?.put_Maximum(*v)?;
        }
        (Prop::Minimum, PropValue::F64(v), Handle::NumberBox(h)) => {
            h.cast::<Xaml::INumberBox>()?.put_Minimum(*v)?;
        }
        (Prop::Value, PropValue::F64(v), Handle::NumberBox(h)) => {
            h.cast::<Xaml::INumberBox>()?.put_Value(*v)?;
        }
        (Prop::Header, PropValue::Str(v), Handle::PasswordBox(h)) => {
            let tb = string_as_textblock(v.as_str())?;
            h.cast::<Xaml::IPasswordBox>()?.put_Header(&tb)?;
        }
        (Prop::Header, PropValue::Unset, Handle::PasswordBox(h)) => {
            h.cast::<Xaml::IPasswordBox>()?.put_Header(None)?;
        }
        (Prop::IsEnabled, PropValue::Bool(v), Handle::PasswordBox(h)) => {
            h.cast::<Xaml::IControl>()?.put_IsEnabled(*v)?;
        }
        (Prop::IsEnabled, PropValue::Unset, Handle::PasswordBox(h)) => {
            h.cast::<Xaml::IControl>()?.put_IsEnabled(true)?;
        }
        (Prop::IsPasswordRevealButtonEnabled, PropValue::Bool(v), Handle::PasswordBox(h)) => {
            h.cast::<Xaml::IPasswordBox>()?
                .put_IsPasswordRevealButtonEnabled(*v)?;
        }
        (Prop::IsPasswordRevealButtonEnabled, PropValue::Unset, Handle::PasswordBox(h)) => {
            h.cast::<Xaml::IPasswordBox>()?
                .put_IsPasswordRevealButtonEnabled(true)?;
        }
        (Prop::PasswordRevealMode, PropValue::PasswordRevealMode(v), Handle::PasswordBox(h)) => {
            let mapped = match v {
                PasswordRevealMode::Peek => Xaml::PasswordRevealMode::Peek,
                PasswordRevealMode::Hidden => Xaml::PasswordRevealMode::Hidden,
                PasswordRevealMode::Visible => Xaml::PasswordRevealMode::Visible,
            };
            h.cast::<Xaml::IPasswordBox>()?
                .put_PasswordRevealMode(mapped)?;
        }
        (Prop::PlaceholderText, PropValue::Str(v), Handle::PasswordBox(h)) => {
            h.cast::<Xaml::IPasswordBox>()?
                .put_PlaceholderText(v.as_str())?;
        }
        (Prop::PlaceholderText, PropValue::Unset, Handle::PasswordBox(h)) => {
            h.cast::<Xaml::IPasswordBox>()?.put_PlaceholderText("")?;
        }
        (Prop::DisplayName, PropValue::Str(v), Handle::PersonPicture(h)) => {
            h.cast::<Xaml::IPersonPicture>()?
                .put_DisplayName(v.as_str())?;
        }
        (Prop::Initials, PropValue::Str(v), Handle::PersonPicture(h)) => {
            h.cast::<Xaml::IPersonPicture>()?.put_Initials(v.as_str())?;
        }
        (Prop::SelectedIndex, PropValue::I32(v), Handle::Pivot(h)) => {
            h.cast::<Xaml::IPivot>()?.put_SelectedIndex(*v)?;
        }
        (Prop::Title, PropValue::Str(v), Handle::Pivot(h)) => {
            let tb = string_as_textblock(v.as_str())?;
            h.cast::<Xaml::IPivot>()?.put_Title(&tb)?;
        }
        (Prop::Title, PropValue::Unset, Handle::Pivot(h)) => {
            h.cast::<Xaml::IPivot>()?.put_Title(None)?;
        }
        (Prop::Content, PropValue::Str(v), Handle::RepeatButton(h)) => {
            let tb = string_as_textblock(v.as_str())?;
            h.cast::<Xaml::IContentControl>()?.put_Content(&tb)?;
        }
        (Prop::Content, PropValue::Unset, Handle::RepeatButton(h)) => {
            h.cast::<Xaml::IContentControl>()?.put_Content(None)?;
        }
        (Prop::Delay, PropValue::I32(v), Handle::RepeatButton(h)) => {
            h.cast::<Xaml::IRepeatButton>()?.put_Delay(*v)?;
        }
        (Prop::Interval, PropValue::I32(v), Handle::RepeatButton(h)) => {
            h.cast::<Xaml::IRepeatButton>()?.put_Interval(*v)?;
        }
        (Prop::IsEnabled, PropValue::Bool(v), Handle::RepeatButton(h)) => {
            h.cast::<Xaml::IControl>()?.put_IsEnabled(*v)?;
        }
        (Prop::IsEnabled, PropValue::Unset, Handle::RepeatButton(h)) => {
            h.cast::<Xaml::IControl>()?.put_IsEnabled(true)?;
        }
        (Prop::Content, PropValue::Str(v), Handle::ToggleButton(h)) => {
            let tb = string_as_textblock(v.as_str())?;
            h.cast::<Xaml::IContentControl>()?.put_Content(&tb)?;
        }
        (Prop::Content, PropValue::Unset, Handle::ToggleButton(h)) => {
            h.cast::<Xaml::IContentControl>()?.put_Content(None)?;
        }
        (Prop::IsChecked, PropValue::Bool(v), Handle::ToggleButton(h)) => {
            h.cast::<Xaml::IToggleButton>()?.put_IsChecked(Some(*v))?;
        }
        (Prop::IsChecked, PropValue::Unset, Handle::ToggleButton(h)) => {
            h.cast::<Xaml::IToggleButton>()?.put_IsChecked(None)?;
        }
        (Prop::IsEnabled, PropValue::Bool(v), Handle::ToggleButton(h)) => {
            h.cast::<Xaml::IControl>()?.put_IsEnabled(*v)?;
        }
        (Prop::IsEnabled, PropValue::Unset, Handle::ToggleButton(h)) => {
            h.cast::<Xaml::IControl>()?.put_IsEnabled(true)?;
        }
        (Prop::IsIndeterminate, PropValue::Bool(v), Handle::ProgressBar(h)) => {
            h.cast::<Xaml::IProgressBar>()?.put_IsIndeterminate(*v)?;
        }
        (Prop::IsIndeterminate, PropValue::Unset, Handle::ProgressBar(h)) => {
            h.cast::<Xaml::IProgressBar>()?.put_IsIndeterminate(false)?;
        }
        (Prop::Maximum, PropValue::F64(v), Handle::ProgressBar(h)) => {
            h.cast::<Xaml::IRangeBase>()?.put_Maximum(*v)?;
        }
        (Prop::Minimum, PropValue::F64(v), Handle::ProgressBar(h)) => {
            h.cast::<Xaml::IRangeBase>()?.put_Minimum(*v)?;
        }
        (Prop::Value, PropValue::F64(v), Handle::ProgressBar(h)) => {
            h.cast::<Xaml::IRangeBase>()?.put_Value(*v)?;
        }
        (Prop::IsActive, PropValue::Bool(v), Handle::ProgressRing(h)) => {
            h.cast::<Xaml::IProgressRing>()?.put_IsActive(*v)?;
        }
        (Prop::IsActive, PropValue::Unset, Handle::ProgressRing(h)) => {
            h.cast::<Xaml::IProgressRing>()?.put_IsActive(false)?;
        }
        (Prop::IsIndeterminate, PropValue::Bool(v), Handle::ProgressRing(h)) => {
            h.cast::<Xaml::IProgressRing>()?.put_IsIndeterminate(*v)?;
        }
        (Prop::IsIndeterminate, PropValue::Unset, Handle::ProgressRing(h)) => {
            h.cast::<Xaml::IProgressRing>()?
                .put_IsIndeterminate(false)?;
        }
        (Prop::Maximum, PropValue::F64(v), Handle::ProgressRing(h)) => {
            h.cast::<Xaml::IProgressRing>()?.put_Maximum(*v)?;
        }
        (Prop::Minimum, PropValue::F64(v), Handle::ProgressRing(h)) => {
            h.cast::<Xaml::IProgressRing>()?.put_Minimum(*v)?;
        }
        (Prop::Value, PropValue::F64(v), Handle::ProgressRing(h)) => {
            h.cast::<Xaml::IProgressRing>()?.put_Value(*v)?;
        }
        (Prop::Content, PropValue::Str(v), Handle::RadioButton(h)) => {
            let tb = string_as_textblock(v.as_str())?;
            h.cast::<Xaml::IContentControl>()?.put_Content(&tb)?;
        }
        (Prop::Content, PropValue::Unset, Handle::RadioButton(h)) => {
            h.cast::<Xaml::IContentControl>()?.put_Content(None)?;
        }
        (Prop::GroupName, PropValue::Str(v), Handle::RadioButton(h)) => {
            h.cast::<Xaml::IRadioButton>()?.put_GroupName(v.as_str())?;
        }
        (Prop::GroupName, PropValue::Unset, Handle::RadioButton(h)) => {
            h.cast::<Xaml::IRadioButton>()?.put_GroupName("")?;
        }
        (Prop::IsChecked, PropValue::Bool(v), Handle::RadioButton(h)) => {
            h.cast::<Xaml::IToggleButton>()?.put_IsChecked(Some(*v))?;
        }
        (Prop::IsChecked, PropValue::Unset, Handle::RadioButton(h)) => {
            h.cast::<Xaml::IToggleButton>()?.put_IsChecked(None)?;
        }
        (Prop::IsEnabled, PropValue::Bool(v), Handle::RadioButton(h)) => {
            h.cast::<Xaml::IControl>()?.put_IsEnabled(*v)?;
        }
        (Prop::IsEnabled, PropValue::Unset, Handle::RadioButton(h)) => {
            h.cast::<Xaml::IControl>()?.put_IsEnabled(true)?;
        }
        (Prop::Header, PropValue::Str(v), Handle::RadioButtons(h)) => {
            let tb = string_as_textblock(v.as_str())?;
            h.cast::<Xaml::IRadioButtons>()?.put_Header(&tb)?;
        }
        (Prop::Header, PropValue::Unset, Handle::RadioButtons(h)) => {
            h.cast::<Xaml::IRadioButtons>()?.put_Header(None)?;
        }
        (Prop::MaxColumns, PropValue::I32(v), Handle::RadioButtons(h)) => {
            h.cast::<Xaml::IRadioButtons>()?.put_MaxColumns(*v)?;
        }
        (Prop::SelectedIndex, PropValue::I32(v), Handle::RadioButtons(h)) => {
            h.cast::<Xaml::IRadioButtons>()?.put_SelectedIndex(*v)?;
        }
        (Prop::Caption, PropValue::Str(v), Handle::RatingControl(h)) => {
            h.cast::<Xaml::IRatingControl>()?.put_Caption(v.as_str())?;
        }
        (Prop::Caption, PropValue::Unset, Handle::RatingControl(h)) => {
            h.cast::<Xaml::IRatingControl>()?.put_Caption("")?;
        }
        (Prop::IsReadOnly, PropValue::Bool(v), Handle::RatingControl(h)) => {
            h.cast::<Xaml::IRatingControl>()?.put_IsReadOnly(*v)?;
        }
        (Prop::MaxRating, PropValue::I32(v), Handle::RatingControl(h)) => {
            h.cast::<Xaml::IRatingControl>()?.put_MaxRating(*v)?;
        }
        (Prop::PlaceholderValue, PropValue::F64(v), Handle::RatingControl(h)) => {
            h.cast::<Xaml::IRatingControl>()?.put_PlaceholderValue(*v)?;
        }
        (Prop::Value, PropValue::F64(v), Handle::RatingControl(h)) => {
            h.cast::<Xaml::IRatingControl>()?.put_Value(*v)?;
        }
        (Prop::Header, PropValue::Str(v), Handle::RichEditBox(h)) => {
            let tb = string_as_textblock(v.as_str())?;
            h.cast::<Xaml::IRichEditBox>()?.put_Header(&tb)?;
        }
        (Prop::Header, PropValue::Unset, Handle::RichEditBox(h)) => {
            h.cast::<Xaml::IRichEditBox>()?.put_Header(None)?;
        }
        (Prop::IsReadOnly, PropValue::Bool(v), Handle::RichEditBox(h)) => {
            h.cast::<Xaml::IRichEditBox>()?.put_IsReadOnly(*v)?;
        }
        (Prop::PlaceholderText, PropValue::Str(v), Handle::RichEditBox(h)) => {
            h.cast::<Xaml::IRichEditBox>()?
                .put_PlaceholderText(v.as_str())?;
        }
        (Prop::PlaceholderText, PropValue::Unset, Handle::RichEditBox(h)) => {
            h.cast::<Xaml::IRichEditBox>()?.put_PlaceholderText("")?;
        }
        (
            Prop::HorizontalScrollBarVisibility,
            PropValue::ScrollViewScrollBarVis(v),
            Handle::ScrollView(h),
        ) => {
            let mapped = match v {
                ScrollViewScrollBarVisibility::Auto => Xaml::ScrollingScrollBarVisibility::Auto,
                ScrollViewScrollBarVisibility::Visible => {
                    Xaml::ScrollingScrollBarVisibility::Visible
                }
                ScrollViewScrollBarVisibility::Hidden => Xaml::ScrollingScrollBarVisibility::Hidden,
            };
            h.cast::<Xaml::IScrollView>()?
                .put_HorizontalScrollBarVisibility(mapped)?;
        }
        (
            Prop::VerticalScrollBarVisibility,
            PropValue::ScrollViewScrollBarVis(v),
            Handle::ScrollView(h),
        ) => {
            let mapped = match v {
                ScrollViewScrollBarVisibility::Auto => Xaml::ScrollingScrollBarVisibility::Auto,
                ScrollViewScrollBarVisibility::Visible => {
                    Xaml::ScrollingScrollBarVisibility::Visible
                }
                ScrollViewScrollBarVisibility::Hidden => Xaml::ScrollingScrollBarVisibility::Hidden,
            };
            h.cast::<Xaml::IScrollView>()?
                .put_VerticalScrollBarVisibility(mapped)?;
        }
        (
            Prop::HorizontalScrollBarVisibility,
            PropValue::ScrollBarVisibility(v),
            Handle::ScrollViewer(h),
        ) => {
            let mapped = match v {
                ScrollBarVisibility::Disabled => Xaml::ScrollBarVisibility::Disabled,
                ScrollBarVisibility::Auto => Xaml::ScrollBarVisibility::Auto,
                ScrollBarVisibility::Hidden => Xaml::ScrollBarVisibility::Hidden,
                ScrollBarVisibility::Visible => Xaml::ScrollBarVisibility::Visible,
            };
            h.cast::<Xaml::IScrollViewer>()?
                .put_HorizontalScrollBarVisibility(mapped)?;
        }
        (
            Prop::VerticalScrollBarVisibility,
            PropValue::ScrollBarVisibility(v),
            Handle::ScrollViewer(h),
        ) => {
            let mapped = match v {
                ScrollBarVisibility::Disabled => Xaml::ScrollBarVisibility::Disabled,
                ScrollBarVisibility::Auto => Xaml::ScrollBarVisibility::Auto,
                ScrollBarVisibility::Hidden => Xaml::ScrollBarVisibility::Hidden,
                ScrollBarVisibility::Visible => Xaml::ScrollBarVisibility::Visible,
            };
            h.cast::<Xaml::IScrollViewer>()?
                .put_VerticalScrollBarVisibility(mapped)?;
        }
        (Prop::Header, PropValue::Str(v), Handle::Slider(h)) => {
            let tb = string_as_textblock(v.as_str())?;
            h.cast::<Xaml::ISlider>()?.put_Header(&tb)?;
        }
        (Prop::Header, PropValue::Unset, Handle::Slider(h)) => {
            h.cast::<Xaml::ISlider>()?.put_Header(None)?;
        }
        (Prop::IsEnabled, PropValue::Bool(v), Handle::Slider(h)) => {
            h.cast::<Xaml::IControl>()?.put_IsEnabled(*v)?;
        }
        (Prop::IsEnabled, PropValue::Unset, Handle::Slider(h)) => {
            h.cast::<Xaml::IControl>()?.put_IsEnabled(true)?;
        }
        (Prop::Maximum, PropValue::F64(v), Handle::Slider(h)) => {
            h.cast::<Xaml::IRangeBase>()?.put_Maximum(*v)?;
        }
        (Prop::Minimum, PropValue::F64(v), Handle::Slider(h)) => {
            h.cast::<Xaml::IRangeBase>()?.put_Minimum(*v)?;
        }
        (Prop::Orientation, PropValue::Vertical(v), Handle::Slider(h)) => {
            let val = if *v {
                Xaml::Orientation::Vertical
            } else {
                Xaml::Orientation::Horizontal
            };
            h.cast::<Xaml::ISlider>()?.put_Orientation(val)?;
        }
        (Prop::Orientation, PropValue::Unset, Handle::Slider(h)) => {
            h.cast::<Xaml::ISlider>()?
                .put_Orientation(Xaml::Orientation::Horizontal)?;
        }
        (Prop::Value, PropValue::F64(v), Handle::Slider(h)) => {
            h.cast::<Xaml::IRangeBase>()?.put_Value(*v)?;
        }
        (Prop::Content, PropValue::Str(v), Handle::SplitButton(h)) => {
            let insp = windows_reference::IReference::from(v.as_str());
            h.cast::<Xaml::IContentControl>()?.put_Content(&insp)?;
        }
        (Prop::Content, PropValue::Unset, Handle::SplitButton(h)) => {
            h.cast::<Xaml::IContentControl>()?.put_Content(None)?;
        }
        (Prop::IsEnabled, PropValue::Bool(v), Handle::SplitButton(h)) => {
            h.cast::<Xaml::IControl>()?.put_IsEnabled(*v)?;
        }
        (Prop::IsEnabled, PropValue::Unset, Handle::SplitButton(h)) => {
            h.cast::<Xaml::IControl>()?.put_IsEnabled(true)?;
        }
        (Prop::CompactPaneLength, PropValue::F64(v), Handle::SplitView(h)) => {
            h.cast::<Xaml::ISplitView>()?.put_CompactPaneLength(*v)?;
        }
        (Prop::IsPaneOpen, PropValue::Bool(v), Handle::SplitView(h)) => {
            h.cast::<Xaml::ISplitView>()?.put_IsPaneOpen(*v)?;
        }
        (Prop::OpenPaneLength, PropValue::F64(v), Handle::SplitView(h)) => {
            h.cast::<Xaml::ISplitView>()?.put_OpenPaneLength(*v)?;
        }
        (Prop::Orientation, PropValue::Vertical(v), Handle::StackPanel(h)) => {
            let val = if *v {
                Xaml::Orientation::Vertical
            } else {
                Xaml::Orientation::Horizontal
            };
            h.cast::<Xaml::IStackPanel>()?.put_Orientation(val)?;
        }
        (Prop::Orientation, PropValue::Unset, Handle::StackPanel(h)) => {
            h.cast::<Xaml::IStackPanel>()?
                .put_Orientation(Xaml::Orientation::Horizontal)?;
        }
        (Prop::Spacing, PropValue::F64(v), Handle::StackPanel(h)) => {
            h.cast::<Xaml::IStackPanel>()?.put_Spacing(*v)?;
        }
        (Prop::Spacing, PropValue::Unset, Handle::StackPanel(h)) => {
            h.cast::<Xaml::IStackPanel>()?.put_Spacing(0.0)?;
        }
        (Prop::CanReorderTabs, PropValue::Bool(v), Handle::TabView(h)) => {
            h.cast::<Xaml::ITabView>()?.put_CanReorderTabs(*v)?;
        }
        (Prop::IsAddTabButtonVisible, PropValue::Bool(v), Handle::TabView(h)) => {
            h.cast::<Xaml::ITabView>()?.put_IsAddTabButtonVisible(*v)?;
        }
        (Prop::SelectedIndex, PropValue::I32(v), Handle::TabView(h)) => {
            h.cast::<Xaml::ITabView>()?.put_SelectedIndex(*v)?;
        }
        (Prop::IsLightDismissEnabled, PropValue::Bool(v), Handle::TeachingTip(h)) => {
            h.cast::<Xaml::ITeachingTip>()?
                .put_IsLightDismissEnabled(*v)?;
        }
        (Prop::IsOpen, PropValue::Bool(v), Handle::TeachingTip(h)) => {
            h.cast::<Xaml::ITeachingTip>()?.put_IsOpen(*v)?;
        }
        (Prop::PreferredPlacement, PropValue::TeachingTipPlacement(v), Handle::TeachingTip(h)) => {
            let mapped = match v {
                TeachingTipPlacement::Auto => Xaml::TeachingTipPlacementMode::Auto,
                TeachingTipPlacement::Top => Xaml::TeachingTipPlacementMode::Top,
                TeachingTipPlacement::Bottom => Xaml::TeachingTipPlacementMode::Bottom,
                TeachingTipPlacement::Left => Xaml::TeachingTipPlacementMode::Left,
                TeachingTipPlacement::Right => Xaml::TeachingTipPlacementMode::Right,
                TeachingTipPlacement::TopRight => Xaml::TeachingTipPlacementMode::TopRight,
                TeachingTipPlacement::TopLeft => Xaml::TeachingTipPlacementMode::TopLeft,
                TeachingTipPlacement::BottomRight => Xaml::TeachingTipPlacementMode::BottomRight,
                TeachingTipPlacement::BottomLeft => Xaml::TeachingTipPlacementMode::BottomLeft,
                TeachingTipPlacement::LeftTop => Xaml::TeachingTipPlacementMode::LeftTop,
                TeachingTipPlacement::LeftBottom => Xaml::TeachingTipPlacementMode::LeftBottom,
                TeachingTipPlacement::RightTop => Xaml::TeachingTipPlacementMode::RightTop,
                TeachingTipPlacement::RightBottom => Xaml::TeachingTipPlacementMode::RightBottom,
                TeachingTipPlacement::Center => Xaml::TeachingTipPlacementMode::Center,
            };
            h.cast::<Xaml::ITeachingTip>()?
                .put_PreferredPlacement(mapped)?;
        }
        (Prop::Subtitle, PropValue::Str(v), Handle::TeachingTip(h)) => {
            h.cast::<Xaml::ITeachingTip>()?.put_Subtitle(v.as_str())?;
        }
        (Prop::Title, PropValue::Str(v), Handle::TeachingTip(h)) => {
            h.cast::<Xaml::ITeachingTip>()?.put_Title(v.as_str())?;
        }
        (Prop::FontSize, PropValue::F64(v), Handle::TextBlock(h)) => {
            h.cast::<Xaml::ITextBlock>()?.put_FontSize(*v)?;
        }
        (Prop::FontSize, PropValue::Unset, Handle::TextBlock(h)) => {
            h.cast::<Xaml::ITextBlock>()?.put_FontSize(14.0)?;
        }
        (Prop::IsTextSelectionEnabled, PropValue::Bool(v), Handle::TextBlock(h)) => {
            h.cast::<Xaml::ITextBlock>()?
                .put_IsTextSelectionEnabled(*v)?;
        }
        (Prop::IsTextSelectionEnabled, PropValue::Unset, Handle::TextBlock(h)) => {
            h.cast::<Xaml::ITextBlock>()?
                .put_IsTextSelectionEnabled(false)?;
        }
        (Prop::Text, PropValue::Str(v), Handle::TextBlock(h)) => {
            h.cast::<Xaml::ITextBlock>()?.put_Text(v.as_str())?;
        }
        (Prop::Text, PropValue::Unset, Handle::TextBlock(h)) => {
            h.cast::<Xaml::ITextBlock>()?.put_Text("")?;
        }
        (Prop::TextWrapping, PropValue::Bool(v), Handle::TextBlock(h)) => {
            let val = if *v {
                Xaml::TextWrapping::Wrap
            } else {
                Xaml::TextWrapping::NoWrap
            };
            h.cast::<Xaml::ITextBlock>()?.put_TextWrapping(val)?;
        }
        (Prop::TextWrapping, PropValue::Unset, Handle::TextBlock(h)) => {
            h.cast::<Xaml::ITextBlock>()?
                .put_TextWrapping(Xaml::TextWrapping::NoWrap)?;
        }
        (Prop::AcceptsReturn, PropValue::Bool(v), Handle::TextBox(h)) => {
            h.cast::<Xaml::ITextBox>()?.put_AcceptsReturn(*v)?;
        }
        (Prop::AcceptsReturn, PropValue::Unset, Handle::TextBox(h)) => {
            h.cast::<Xaml::ITextBox>()?.put_AcceptsReturn(false)?;
        }
        (Prop::Header, PropValue::Str(v), Handle::TextBox(h)) => {
            let tb = string_as_textblock(v.as_str())?;
            h.cast::<Xaml::ITextBox>()?.put_Header(&tb)?;
        }
        (Prop::Header, PropValue::Unset, Handle::TextBox(h)) => {
            h.cast::<Xaml::ITextBox>()?.put_Header(None)?;
        }
        (Prop::IsEnabled, PropValue::Bool(v), Handle::TextBox(h)) => {
            h.cast::<Xaml::IControl>()?.put_IsEnabled(*v)?;
        }
        (Prop::IsEnabled, PropValue::Unset, Handle::TextBox(h)) => {
            h.cast::<Xaml::IControl>()?.put_IsEnabled(true)?;
        }
        (Prop::PlaceholderText, PropValue::Str(v), Handle::TextBox(h)) => {
            h.cast::<Xaml::ITextBox>()?
                .put_PlaceholderText(v.as_str())?;
        }
        (Prop::PlaceholderText, PropValue::Unset, Handle::TextBox(h)) => {
            h.cast::<Xaml::ITextBox>()?.put_PlaceholderText("")?;
        }
        (Prop::TextWrapping, PropValue::Bool(v), Handle::TextBox(h)) => {
            let val = if *v {
                Xaml::TextWrapping::Wrap
            } else {
                Xaml::TextWrapping::NoWrap
            };
            h.cast::<Xaml::ITextBox>()?.put_TextWrapping(val)?;
        }
        (Prop::TextWrapping, PropValue::Unset, Handle::TextBox(h)) => {
            h.cast::<Xaml::ITextBox>()?
                .put_TextWrapping(Xaml::TextWrapping::NoWrap)?;
        }
        (Prop::ClockIdentifier, PropValue::Str(v), Handle::TimePicker(h)) => {
            h.cast::<Xaml::ITimePicker>()?
                .put_ClockIdentifier(v.as_str())?;
        }
        (Prop::Header, PropValue::Str(v), Handle::TimePicker(h)) => {
            let tb = string_as_textblock(v.as_str())?;
            h.cast::<Xaml::ITimePicker>()?.put_Header(&tb)?;
        }
        (Prop::Header, PropValue::Unset, Handle::TimePicker(h)) => {
            h.cast::<Xaml::ITimePicker>()?.put_Header(None)?;
        }
        (Prop::IsEnabled, PropValue::Bool(v), Handle::TimePicker(h)) => {
            h.cast::<Xaml::IControl>()?.put_IsEnabled(*v)?;
        }
        (Prop::IsEnabled, PropValue::Unset, Handle::TimePicker(h)) => {
            h.cast::<Xaml::IControl>()?.put_IsEnabled(true)?;
        }
        (Prop::MinuteIncrement, PropValue::I32(v), Handle::TimePicker(h)) => {
            h.cast::<Xaml::ITimePicker>()?.put_MinuteIncrement(*v)?;
        }
        (Prop::IsBackButtonEnabled, PropValue::Bool(v), Handle::TitleBar(h)) => {
            h.cast::<Xaml::ITitleBar>()?.put_IsBackButtonEnabled(*v)?;
        }
        (Prop::IsBackButtonVisible, PropValue::Bool(v), Handle::TitleBar(h)) => {
            h.cast::<Xaml::ITitleBar>()?.put_IsBackButtonVisible(*v)?;
        }
        (Prop::IsPaneToggleButtonVisible, PropValue::Bool(v), Handle::TitleBar(h)) => {
            h.cast::<Xaml::ITitleBar>()?
                .put_IsPaneToggleButtonVisible(*v)?;
        }
        (Prop::Subtitle, PropValue::Str(v), Handle::TitleBar(h)) => {
            h.cast::<Xaml::ITitleBar>()?.put_Subtitle(v.as_str())?;
        }
        (Prop::Subtitle, PropValue::Unset, Handle::TitleBar(h)) => {
            h.cast::<Xaml::ITitleBar>()?.put_Subtitle("")?;
        }
        (Prop::Title, PropValue::Str(v), Handle::TitleBar(h)) => {
            h.cast::<Xaml::ITitleBar>()?.put_Title(v.as_str())?;
        }
        (Prop::Header, PropValue::Str(v), Handle::ToggleSwitch(h)) => {
            let tb = string_as_textblock(v.as_str())?;
            h.cast::<Xaml::IToggleSwitch>()?.put_Header(&tb)?;
        }
        (Prop::Header, PropValue::Unset, Handle::ToggleSwitch(h)) => {
            h.cast::<Xaml::IToggleSwitch>()?.put_Header(None)?;
        }
        (Prop::IsEnabled, PropValue::Bool(v), Handle::ToggleSwitch(h)) => {
            h.cast::<Xaml::IControl>()?.put_IsEnabled(*v)?;
        }
        (Prop::IsEnabled, PropValue::Unset, Handle::ToggleSwitch(h)) => {
            h.cast::<Xaml::IControl>()?.put_IsEnabled(true)?;
        }
        (Prop::IsOn, PropValue::Bool(v), Handle::ToggleSwitch(h)) => {
            h.cast::<Xaml::IToggleSwitch>()?.put_IsOn(*v)?;
        }
        (Prop::OffContent, PropValue::Str(v), Handle::ToggleSwitch(h)) => {
            let tb = string_as_textblock(v.as_str())?;
            h.cast::<Xaml::IToggleSwitch>()?.put_OffContent(&tb)?;
        }
        (Prop::OffContent, PropValue::Unset, Handle::ToggleSwitch(h)) => {
            h.cast::<Xaml::IToggleSwitch>()?.put_OffContent(None)?;
        }
        (Prop::OnContent, PropValue::Str(v), Handle::ToggleSwitch(h)) => {
            let tb = string_as_textblock(v.as_str())?;
            h.cast::<Xaml::IToggleSwitch>()?.put_OnContent(&tb)?;
        }
        (Prop::OnContent, PropValue::Unset, Handle::ToggleSwitch(h)) => {
            h.cast::<Xaml::IToggleSwitch>()?.put_OnContent(None)?;
        }
        (Prop::SelectionMode, PropValue::TreeViewSelectionMode(v), Handle::TreeView(h)) => {
            let mapped = match v {
                TreeSelectionMode::None => Xaml::TreeViewSelectionMode::None,
                TreeSelectionMode::Single => Xaml::TreeViewSelectionMode::Single,
                TreeSelectionMode::Multiple => Xaml::TreeViewSelectionMode::Multiple,
            };
            h.cast::<Xaml::ITreeView>()?.put_SelectionMode(mapped)?;
        }
        (Prop::Stretch, PropValue::ImageStretch(v), Handle::Viewbox(h)) => {
            let mapped = match v {
                ImageStretch::Uniform => Xaml::Stretch::Uniform,
                ImageStretch::UniformToFill => Xaml::Stretch::UniformToFill,
                ImageStretch::Fill => Xaml::Stretch::Fill,
                ImageStretch::None => Xaml::Stretch::None,
            };
            h.cast::<Xaml::IViewbox>()?.put_Stretch(mapped)?;
        }
        _ => return Ok(false),
    }
    Ok(true)
}
