//! Typed mount/diff dispatch generated by the `widget_map!` macro.
//!
//! Each widget entry declares field→COM-setter mappings. The macro generates
//! `try_mount` and `try_diff` functions that downcast `&dyn Any` to concrete
//! widget types and call setters directly — no `Prop`/`PropValue` indirection.

use std::any::Any;

use windows_collections::IVector;
use windows_core::Interface;

use super::Handle;
use super::convert::*;
use crate::bindings as Xaml;
use crate::core::widgets;
use Xaml::FontWeight as WinFontWeight;
use widgets::BrushBinding;
use widgets::PasswordRevealMode;
use widgets::ScrollViewScrollBarVisibility;

type R = windows_core::Result<()>;

/// Generate typed mount/diff dispatch from per-widget mount/diff blocks.
///
/// Each widget provides two blocks: `mount` and `diff`. The macro generates
/// `try_mount` and `try_diff` functions that downcast to the concrete widget
/// type and run the appropriate block.
///
/// Variables are named by the user in the macro invocation (no hygiene issues).
macro_rules! widget_map {
    (
        $(
            $Widget:ty {
                mount($mw:ident, $mh:ident) $mount:block
                diff($do:ident, $dw:ident, $dh:ident) $diff:block
            }
        )*
    ) => {
        pub(super) fn try_mount(widget: &dyn Any, handle: &Handle) -> Option<R> {
            $(
                if let Some($mw) = widget.downcast_ref::<$Widget>() {
                    let $mh = handle;
                    return Some((|| -> R { $mount })());
                }
            )*
            let _ = (widget, handle);
            None
        }

        pub(super) fn try_diff(old_any: &dyn Any, new_any: &dyn Any, handle: &Handle) -> Option<R> {
            $(
                if let Some($dw) = new_any.downcast_ref::<$Widget>() {
                    let $do = old_any.downcast_ref::<$Widget>().unwrap();
                    let $dh = handle;
                    return Some((|| -> R { $diff })());
                }
            )*
            let _ = (old_any, new_any, handle);
            None
        }
    };
}

/// Diff guard: only run body if field changed.
macro_rules! changed {
    ($old:ident, $new:ident, $field:ident, $body:block) => {
        if $old.$field != $new.$field $body
    };
}

fn map_stretch(s: widgets::ImageStretch) -> Xaml::Stretch {
    use Xaml::Stretch as X;
    use widgets::ImageStretch as E;

    match s {
        E::Uniform => X::Uniform,
        E::UniformToFill => X::UniformToFill,
        E::Fill => X::Fill,
        E::None => X::None,
    }
}

fn map_scroll_view_scroll_bar_visibility(
    v: ScrollViewScrollBarVisibility,
) -> Xaml::ScrollingScrollBarVisibility {
    use Xaml::ScrollingScrollBarVisibility as W;

    match v {
        ScrollViewScrollBarVisibility::Auto => W::Auto,
        ScrollViewScrollBarVisibility::Visible => W::Visible,
        ScrollViewScrollBarVisibility::Hidden => W::Hidden,
    }
}

fn set_image_source(h: &Xaml::IImage, source: &str) -> R {
    if source.is_empty() {
        h.put_Source(None)
    } else {
        let uri = Xaml::Uri::CreateUri(source)?;
        let bmp = Xaml::BitmapImage::new()?;
        bmp.cast::<Xaml::IBitmapImage>()?.put_UriSource(&uri)?;
        h.put_Source(&bmp.cast::<Xaml::ImageSource>()?)
    }
}

// ── Widget declarations ──────────────────────────────────────────────────────

widget_map! {
    // ── TextBlock (prop-only, no events) ─────────────────────────────────
    widgets::TextBlock {
        mount(w, handle) {
            let h = handle.cast_inner::<Xaml::ITextBlock>()?;
            h.put_Text(w.content.as_str())?;
            if let Some(fs) = w.font_size { h.put_FontSize(fs)?; }
            if let Some(fw) = w.font_weight { h.put_FontWeight(WinFontWeight { Weight: fw })?; }
            if w.wrap_text {
                h.put_TextWrapping(Xaml::TextWrapping::Wrap)?;
            }
            if w.is_text_selection_enabled {
                h.put_IsTextSelectionEnabled(true)?;
            }
            Ok(())
        }
        diff(old, w, handle) {
            let h = handle.cast_inner::<Xaml::ITextBlock>()?;
            changed!(old, w, content, { h.put_Text(w.content.as_str())?; });
            changed!(old, w, font_size, { h.put_FontSize(w.font_size.unwrap_or(14.0))?; });
            changed!(old, w, font_weight, { h.put_FontWeight(WinFontWeight { Weight: w.font_weight.unwrap_or(400) })?; });
            changed!(old, w, wrap_text, {
                h.put_TextWrapping(if w.wrap_text { Xaml::TextWrapping::Wrap } else { Xaml::TextWrapping::NoWrap })?;
            });
            changed!(old, w, is_text_selection_enabled, { h.put_IsTextSelectionEnabled(w.is_text_selection_enabled)?; });
            Ok(())
        }
    }

    // ── TextBox (get-before-set, events, optionals) ──────────────────────
    widgets::TextBox {
        mount(w, handle) {
            let h = handle.cast_inner::<Xaml::ITextBox>()?;
            h.put_Text(w.value.as_str())?;
            if let Some(ref s) = w.placeholder { h.put_PlaceholderText(s.as_str())?; }
            if let Some(ref s) = w.header { h.put_Header(&string_as_textblock(s)?)?; }
            if !w.is_enabled { handle.cast_inner::<Xaml::IControl>()?.put_IsEnabled(false)?; }
            if w.accepts_return { h.put_AcceptsReturn(true)?; }
            if w.text_wrapping_wrap {
                h.put_TextWrapping(Xaml::TextWrapping::Wrap)?;
            }
            Ok(())
        }
        diff(old, w, handle) {
            let h = handle.cast_inner::<Xaml::ITextBox>()?;
            // get-before-set to avoid cursor reset
            changed!(old, w, value, {
                if h.get_Text().ok().as_deref() != Some(w.value.as_str()) {
                    h.put_Text(w.value.as_str())?;
                }
            });
            changed!(old, w, placeholder, {
                h.put_PlaceholderText(w.placeholder.as_deref().unwrap_or(""))?;
            });
            changed!(old, w, header, {
                match &w.header {
                    Some(s) => h.put_Header(&string_as_textblock(s)?)?,
                    None => h.put_Header(None)?,
                }
            });
            changed!(old, w, is_enabled, {
                handle.cast_inner::<Xaml::IControl>()?.put_IsEnabled(w.is_enabled)?;
            });
            changed!(old, w, accepts_return, { h.put_AcceptsReturn(w.accepts_return)?; });
            changed!(old, w, text_wrapping_wrap, {
                h.put_TextWrapping(if w.text_wrapping_wrap { Xaml::TextWrapping::Wrap } else { Xaml::TextWrapping::NoWrap })?;
            });
            Ok(())
        }
    }

    // ── CheckBox (events + multi-interface) ─────────────────────────────
    widgets::CheckBox {
        mount(w, handle) {
            let tb = handle.cast_inner::<Xaml::IToggleButton>()?;
            tb.put_IsChecked(Some(w.is_checked))?;
            if let Some(ref s) = w.label {
                handle
                    .cast_inner::<Xaml::IContentControl>()?
                    .put_Content(&string_as_textblock(s)?)?;
            }
            if !w.is_enabled {
                handle
                    .cast_inner::<Xaml::IControl>()?
                    .put_IsEnabled(false)?;
            }
            Ok(())
        }
        diff(old, w, handle) {
            changed!(old, w, is_checked, {
                handle
                    .cast_inner::<Xaml::IToggleButton>()?
                    .put_IsChecked(Some(w.is_checked))?;
            });
            changed!(old, w, label, {
                match &w.label {
                    Some(s) => handle
                        .cast_inner::<Xaml::IContentControl>()?
                        .put_Content(&string_as_textblock(s)?)?,
                    None => handle
                        .cast_inner::<Xaml::IContentControl>()?
                        .put_Content(None)?,
                }
            });
            changed!(old, w, is_enabled, {
                handle
                    .cast_inner::<Xaml::IControl>()?
                    .put_IsEnabled(w.is_enabled)?;
            });
            Ok(())
        }
    }

    widgets::StackPanel {
        mount(w, handle) {
            let h = handle.cast_inner::<Xaml::IStackPanel>()?;
            h.put_Orientation(if w.vertical {
                Xaml::Orientation::Vertical
            } else {
                Xaml::Orientation::Horizontal
            })?;
            if let Some(spacing) = w.spacing {
                h.put_Spacing(spacing)?;
            }
            Ok(())
        }
        diff(old, w, handle) {
            let h = handle.cast_inner::<Xaml::IStackPanel>()?;
            changed!(old, w, vertical, {
                h.put_Orientation(if w.vertical {
                    Xaml::Orientation::Vertical
                } else {
                    Xaml::Orientation::Horizontal
                })?;
            });
            changed!(old, w, spacing, {
                h.put_Spacing(w.spacing.unwrap_or(0.0))?;
            });
            Ok(())
        }
    }

    widgets::ProgressBar {
        mount(w, handle) {
            let range = handle.cast_inner::<Xaml::IRangeBase>()?;
            let h = handle.cast_inner::<Xaml::IProgressBar>()?;
            range.put_Value(w.value)?;
            range.put_Minimum(w.minimum)?;
            range.put_Maximum(w.maximum)?;
            h.put_IsIndeterminate(w.is_indeterminate)?;
            Ok(())
        }
        diff(old, w, handle) {
            let range = handle.cast_inner::<Xaml::IRangeBase>()?;
            let h = handle.cast_inner::<Xaml::IProgressBar>()?;
            changed!(old, w, value, { range.put_Value(w.value)?; });
            changed!(old, w, minimum, { range.put_Minimum(w.minimum)?; });
            changed!(old, w, maximum, { range.put_Maximum(w.maximum)?; });
            changed!(old, w, is_indeterminate, { h.put_IsIndeterminate(w.is_indeterminate)?; });
            Ok(())
        }
    }

    widgets::ProgressRing {
        mount(w, handle) {
            let range = handle.cast_inner::<Xaml::IRangeBase>()?;
            let h = handle.cast_inner::<Xaml::IProgressRing>()?;
            range.put_Value(w.value)?;
            h.put_Minimum(w.minimum)?;
            h.put_Maximum(w.maximum)?;
            h.put_IsIndeterminate(w.is_indeterminate)?;
            h.put_IsActive(w.is_active)?;
            Ok(())
        }
        diff(old, w, handle) {
            let range = handle.cast_inner::<Xaml::IRangeBase>()?;
            let h = handle.cast_inner::<Xaml::IProgressRing>()?;
            changed!(old, w, value, { range.put_Value(w.value)?; });
            changed!(old, w, minimum, { h.put_Minimum(w.minimum)?; });
            changed!(old, w, maximum, { h.put_Maximum(w.maximum)?; });
            changed!(old, w, is_indeterminate, { h.put_IsIndeterminate(w.is_indeterminate)?; });
            changed!(old, w, is_active, { h.put_IsActive(w.is_active)?; });
            Ok(())
        }
    }

    widgets::Border {
        mount(w, handle) {
            let h = handle.cast_inner::<Xaml::IBorder>()?;
            if let Some(v) = w.corner_radius {
                h.put_CornerRadius(Xaml::CornerRadius {
                    TopLeft: v,
                    TopRight: v,
                    BottomRight: v,
                    BottomLeft: v,
                })?;
            }
            if let Some(BrushBinding::Direct(br)) = &w.border_brush {
                h.put_BorderBrush(&brush_of(br)?)?;
            }
            if let Some(t) = w.border_thickness {
                h.put_BorderThickness(to_xaml_thickness(t))?;
            }
            Ok(())
        }
        diff(old, w, handle) {
            let h = handle.cast_inner::<Xaml::IBorder>()?;
            changed!(old, w, corner_radius, {
                match w.corner_radius {
                    Some(v) => h.put_CornerRadius(Xaml::CornerRadius {
                        TopLeft: v,
                        TopRight: v,
                        BottomRight: v,
                        BottomLeft: v,
                    })?,
                    None => h.put_CornerRadius(Xaml::CornerRadius::default())?,
                }
            });
            changed!(old, w, border_brush, {
                match &w.border_brush {
                    Some(BrushBinding::Direct(br)) => h.put_BorderBrush(&brush_of(br)?)?,
                    _ => h.put_BorderBrush(None)?,
                }
            });
            changed!(old, w, border_thickness, {
                h.put_BorderThickness(to_xaml_thickness(w.border_thickness.unwrap_or_default()))?;
            });
            Ok(())
        }
    }

    widgets::Image {
        mount(w, handle) {
            let h = handle.cast_inner::<Xaml::IImage>()?;
            set_image_source(&h, w.source.as_str())?;
            h.put_Stretch(map_stretch(w.stretch))?;
            Ok(())
        }
        diff(old, w, handle) {
            let h = handle.cast_inner::<Xaml::IImage>()?;
            changed!(old, w, source, {
                set_image_source(&h, w.source.as_str())?;
            });
            changed!(old, w, stretch, {
                h.put_Stretch(map_stretch(w.stretch))?;
            });
            Ok(())
        }
    }

    widgets::PersonPicture {
        mount(w, handle) {
            let h = handle.cast_inner::<Xaml::IPersonPicture>()?;
            if let Some(display_name) = &w.display_name {
                h.put_DisplayName(display_name.as_str())?;
            }
            if let Some(initials) = &w.initials {
                h.put_Initials(initials.as_str())?;
            }
            Ok(())
        }
        diff(old, w, handle) {
            let h = handle.cast_inner::<Xaml::IPersonPicture>()?;
            changed!(old, w, display_name, {
                h.put_DisplayName(w.display_name.as_deref().unwrap_or(""))?;
            });
            changed!(old, w, initials, {
                h.put_Initials(w.initials.as_deref().unwrap_or(""))?;
            });
            Ok(())
        }
    }

    widgets::InfoBadge {
        mount(w, handle) {
            let h = handle.cast_inner::<Xaml::IInfoBadge>()?;
            h.put_Value(w.value.unwrap_or(-1))?;
            Ok(())
        }
        diff(old, w, handle) {
            let h = handle.cast_inner::<Xaml::IInfoBadge>()?;
            changed!(old, w, value, {
                h.put_Value(w.value.unwrap_or(-1))?;
            });
            Ok(())
        }
    }

    widgets::Viewbox {
        mount(w, handle) {
            let h = handle.cast_inner::<Xaml::IViewbox>()?;
            h.put_Stretch(map_stretch(w.stretch))?;
            Ok(())
        }
        diff(old, w, handle) {
            let h = handle.cast_inner::<Xaml::IViewbox>()?;
            changed!(old, w, stretch, {
                h.put_Stretch(map_stretch(w.stretch))?;
            });
            Ok(())
        }
    }

    widgets::ScrollViewer {
        mount(w, handle) {
            let h = handle.cast_inner::<Xaml::IScrollViewer>()?;
            h.put_HorizontalScrollBarVisibility(to_xaml_scroll_visibility(w.horizontal_scroll_bar_visibility))?;
            h.put_VerticalScrollBarVisibility(to_xaml_scroll_visibility(w.vertical_scroll_bar_visibility))?;
            Ok(())
        }
        diff(old, w, handle) {
            let h = handle.cast_inner::<Xaml::IScrollViewer>()?;
            changed!(old, w, horizontal_scroll_bar_visibility, {
                h.put_HorizontalScrollBarVisibility(to_xaml_scroll_visibility(w.horizontal_scroll_bar_visibility))?;
            });
            changed!(old, w, vertical_scroll_bar_visibility, {
                h.put_VerticalScrollBarVisibility(to_xaml_scroll_visibility(w.vertical_scroll_bar_visibility))?;
            });
            Ok(())
        }
    }

    widgets::Grid {
        mount(w, handle) {
            let h = handle.cast_inner::<Xaml::IGrid>()?;
            if !w.rows.is_empty() {
                let defs = h.get_RowDefinitions()?;
                let defs = defs.cast::<IVector<Xaml::RowDefinition>>()?;
                defs.Clear()?;
                for r in &w.rows {
                    let rd = Xaml::RowDefinition::new()?;
                    rd.cast::<Xaml::IRowDefinition>()?
                        .put_Height(to_xaml_gridlength(*r)?)?;
                    defs.Append(&rd)?;
                }
            }
            if !w.columns.is_empty() {
                let defs = h.get_ColumnDefinitions()?;
                let defs = defs.cast::<IVector<Xaml::ColumnDefinition>>()?;
                defs.Clear()?;
                for c in &w.columns {
                    let cd = Xaml::ColumnDefinition::new()?;
                    cd.cast::<Xaml::IColumnDefinition>()?
                        .put_Width(to_xaml_gridlength(*c)?)?;
                    defs.Append(&cd)?;
                }
            }
            if let Some(v) = w.row_spacing {
                h.put_RowSpacing(v)?;
            }
            if let Some(v) = w.column_spacing {
                h.put_ColumnSpacing(v)?;
            }
            Ok(())
        }
        diff(old, w, handle) {
            let h = handle.cast_inner::<Xaml::IGrid>()?;
            changed!(old, w, rows, {
                let defs = h.get_RowDefinitions()?;
                let defs = defs.cast::<IVector<Xaml::RowDefinition>>()?;
                defs.Clear()?;
                for r in &w.rows {
                    let rd = Xaml::RowDefinition::new()?;
                    rd.cast::<Xaml::IRowDefinition>()?
                        .put_Height(to_xaml_gridlength(*r)?)?;
                    defs.Append(&rd)?;
                }
            });
            changed!(old, w, columns, {
                let defs = h.get_ColumnDefinitions()?;
                let defs = defs.cast::<IVector<Xaml::ColumnDefinition>>()?;
                defs.Clear()?;
                for c in &w.columns {
                    let cd = Xaml::ColumnDefinition::new()?;
                    cd.cast::<Xaml::IColumnDefinition>()?
                        .put_Width(to_xaml_gridlength(*c)?)?;
                    defs.Append(&cd)?;
                }
            });
            changed!(old, w, row_spacing, {
                h.put_RowSpacing(w.row_spacing.unwrap_or(0.0))?;
            });
            changed!(old, w, column_spacing, {
                h.put_ColumnSpacing(w.column_spacing.unwrap_or(0.0))?;
            });
            Ok(())
        }
    }

    widgets::ScrollViewWidget {
        mount(w, handle) {
            let h = handle.cast_inner::<Xaml::IScrollView>()?;
            h.put_HorizontalScrollBarVisibility(map_scroll_view_scroll_bar_visibility(w.horizontal_scroll_bar_visibility))?;
            h.put_VerticalScrollBarVisibility(map_scroll_view_scroll_bar_visibility(w.vertical_scroll_bar_visibility))?;
            Ok(())
        }
        diff(old, w, handle) {
            let h = handle.cast_inner::<Xaml::IScrollView>()?;
            changed!(old, w, horizontal_scroll_bar_visibility, {
                h.put_HorizontalScrollBarVisibility(map_scroll_view_scroll_bar_visibility(w.horizontal_scroll_bar_visibility))?;
            });
            changed!(old, w, vertical_scroll_bar_visibility, {
                h.put_VerticalScrollBarVisibility(map_scroll_view_scroll_bar_visibility(w.vertical_scroll_bar_visibility))?;
            });
            Ok(())
        }
    }

    widgets::ToggleSwitch {
        mount(w, handle) {
            let h = handle.cast_inner::<Xaml::IToggleSwitch>()?;
            h.put_IsOn(w.is_on)?;
            if let Some(s) = &w.on_content { h.put_OnContent(&string_as_textblock(s)?)?; }
            if let Some(s) = &w.off_content { h.put_OffContent(&string_as_textblock(s)?)?; }
            if let Some(s) = &w.header { h.put_Header(&string_as_textblock(s)?)?; }
            if !w.is_enabled { handle.cast_inner::<Xaml::IControl>()?.put_IsEnabled(false)?; }
            Ok(())
        }
        diff(old, w, handle) {
            let h = handle.cast_inner::<Xaml::IToggleSwitch>()?;
            changed!(old, w, is_on, { h.put_IsOn(w.is_on)?; });
            changed!(old, w, on_content, {
                match &w.on_content {
                    Some(s) => h.put_OnContent(&string_as_textblock(s)?)?,
                    None => h.put_OnContent(None)?,
                }
            });
            changed!(old, w, off_content, {
                match &w.off_content {
                    Some(s) => h.put_OffContent(&string_as_textblock(s)?)?,
                    None => h.put_OffContent(None)?,
                }
            });
            changed!(old, w, header, {
                match &w.header {
                    Some(s) => h.put_Header(&string_as_textblock(s)?)?,
                    None => h.put_Header(None)?,
                }
            });
            changed!(old, w, is_enabled, {
                handle.cast_inner::<Xaml::IControl>()?.put_IsEnabled(w.is_enabled)?;
            });
            Ok(())
        }
    }

    widgets::Slider {
        mount(w, handle) {
            let range = handle.cast_inner::<Xaml::IRangeBase>()?;
            let h = handle.cast_inner::<Xaml::ISlider>()?;
            range.put_Minimum(w.minimum)?;
            range.put_Maximum(w.maximum)?;
            range.put_Value(w.value)?;
            if let Some(step) = w.step {
                h.put_StepFrequency(step)?;
                range.put_SmallChange(step)?;
            }
            if let Some(s) = &w.header { h.put_Header(&string_as_textblock(s)?)?; }
            if w.vertical { h.put_Orientation(Xaml::Orientation::Vertical)?; }
            if !w.is_enabled { handle.cast_inner::<Xaml::IControl>()?.put_IsEnabled(false)?; }
            Ok(())
        }
        diff(old, w, handle) {
            let range = handle.cast_inner::<Xaml::IRangeBase>()?;
            let h = handle.cast_inner::<Xaml::ISlider>()?;
            changed!(old, w, minimum, { range.put_Minimum(w.minimum)?; });
            changed!(old, w, maximum, { range.put_Maximum(w.maximum)?; });
            changed!(old, w, value, { range.put_Value(w.value)?; });
            changed!(old, w, step, {
                let step = w.step.unwrap_or(1.0);
                h.put_StepFrequency(step)?;
                range.put_SmallChange(step)?;
            });
            changed!(old, w, header, {
                match &w.header {
                    Some(s) => h.put_Header(&string_as_textblock(s)?)?,
                    None => h.put_Header(None)?,
                }
            });
            changed!(old, w, vertical, {
                h.put_Orientation(if w.vertical {
                    Xaml::Orientation::Vertical
                } else {
                    Xaml::Orientation::Horizontal
                })?;
            });
            changed!(old, w, is_enabled, {
                handle.cast_inner::<Xaml::IControl>()?.put_IsEnabled(w.is_enabled)?;
            });
            Ok(())
        }
    }

    widgets::NumberBox {
        mount(w, handle) {
            let h = handle.cast_inner::<Xaml::INumberBox>()?;
            h.put_Value(w.value)?;
            if let Some(min) = w.minimum { h.put_Minimum(min)?; }
            if let Some(max) = w.maximum { h.put_Maximum(max)?; }
            if let Some(s) = &w.header { h.put_Header(&string_as_textblock(s)?)?; }
            if !w.is_enabled { handle.cast_inner::<Xaml::IControl>()?.put_IsEnabled(false)?; }
            Ok(())
        }
        diff(old, w, handle) {
            let h = handle.cast_inner::<Xaml::INumberBox>()?;
            changed!(old, w, value, { h.put_Value(w.value)?; });
            changed!(old, w, minimum, { h.put_Minimum(w.minimum.unwrap_or(f64::MIN))?; });
            changed!(old, w, maximum, { h.put_Maximum(w.maximum.unwrap_or(f64::MAX))?; });
            changed!(old, w, header, {
                match &w.header {
                    Some(s) => h.put_Header(&string_as_textblock(s)?)?,
                    None => h.put_Header(None)?,
                }
            });
            changed!(old, w, is_enabled, {
                handle.cast_inner::<Xaml::IControl>()?.put_IsEnabled(w.is_enabled)?;
            });
            Ok(())
        }
    }

    widgets::RadioButton {
        mount(w, handle) {
            if let Some(s) = &w.label {
                handle.cast_inner::<Xaml::IContentControl>()?.put_Content(&string_as_textblock(s)?)?;
            }
            handle.cast_inner::<Xaml::IToggleButton>()?.put_IsChecked(Some(w.is_checked))?;
            if let Some(s) = &w.group_name { handle.cast_inner::<Xaml::IRadioButton>()?.put_GroupName(s.as_str())?; }
            if !w.is_enabled { handle.cast_inner::<Xaml::IControl>()?.put_IsEnabled(false)?; }
            Ok(())
        }
        diff(old, w, handle) {
            changed!(old, w, label, {
                match &w.label {
                    Some(s) => handle.cast_inner::<Xaml::IContentControl>()?.put_Content(&string_as_textblock(s)?)?,
                    None => handle.cast_inner::<Xaml::IContentControl>()?.put_Content(None)?,
                }
            });
            changed!(old, w, is_checked, {
                handle.cast_inner::<Xaml::IToggleButton>()?.put_IsChecked(Some(w.is_checked))?;
            });
            changed!(old, w, group_name, {
                handle.cast_inner::<Xaml::IRadioButton>()?.put_GroupName(w.group_name.as_deref().unwrap_or(""))?;
            });
            changed!(old, w, is_enabled, {
                handle.cast_inner::<Xaml::IControl>()?.put_IsEnabled(w.is_enabled)?;
            });
            Ok(())
        }
    }

    widgets::HyperlinkButton {
        mount(w, handle) {
            handle.cast_inner::<Xaml::IContentControl>()?.put_Content(&string_as_textblock(&w.label)?)?;
            let h = handle.cast_inner::<Xaml::IHyperlinkButton>()?;
            if let Some(s) = &w.navigate_uri {
                let uri = Xaml::Uri::CreateUri(s.as_str())?;
                h.put_NavigateUri(&uri)?;
            }
            if !w.is_enabled { handle.cast_inner::<Xaml::IControl>()?.put_IsEnabled(false)?; }
            Ok(())
        }
        diff(old, w, handle) {
            let h = handle.cast_inner::<Xaml::IHyperlinkButton>()?;
            changed!(old, w, label, {
                handle.cast_inner::<Xaml::IContentControl>()?.put_Content(&string_as_textblock(&w.label)?)?;
            });
            changed!(old, w, navigate_uri, {
                match &w.navigate_uri {
                    Some(s) => {
                        let uri = Xaml::Uri::CreateUri(s.as_str())?;
                        h.put_NavigateUri(&uri)?;
                    }
                    None => h.put_NavigateUri(None)?,
                }
            });
            changed!(old, w, is_enabled, {
                handle.cast_inner::<Xaml::IControl>()?.put_IsEnabled(w.is_enabled)?;
            });
            Ok(())
        }
    }

    widgets::PasswordBox {
        mount(w, handle) {
            let h = handle.cast_inner::<Xaml::IPasswordBox>()?;
            h.put_Password(w.value.as_str())?;
            if let Some(s) = &w.placeholder { h.put_PlaceholderText(s.as_str())?; }
            if let Some(s) = &w.header { h.put_Header(&string_as_textblock(s)?)?; }
            if !w.is_enabled { handle.cast_inner::<Xaml::IControl>()?.put_IsEnabled(false)?; }
            h.put_PasswordRevealMode(match w.reveal_mode {
                PasswordRevealMode::Peek => Xaml::PasswordRevealMode::Peek,
                PasswordRevealMode::Hidden => Xaml::PasswordRevealMode::Hidden,
                PasswordRevealMode::Visible => Xaml::PasswordRevealMode::Visible,
            })?;
            if !w.is_password_reveal_button_enabled {
                h.put_IsPasswordRevealButtonEnabled(false)?;
            }
            Ok(())
        }
        diff(old, w, handle) {
            let h = handle.cast_inner::<Xaml::IPasswordBox>()?;
            changed!(old, w, value, {
                if h.get_Password().ok().as_deref() != Some(w.value.as_str()) {
                    h.put_Password(w.value.as_str())?;
                }
            });
            changed!(old, w, placeholder, {
                h.put_PlaceholderText(w.placeholder.as_deref().unwrap_or(""))?;
            });
            changed!(old, w, header, {
                match &w.header {
                    Some(s) => h.put_Header(&string_as_textblock(s)?)?,
                    None => h.put_Header(None)?,
                }
            });
            changed!(old, w, is_enabled, {
                handle.cast_inner::<Xaml::IControl>()?.put_IsEnabled(w.is_enabled)?;
            });
            changed!(old, w, reveal_mode, {
                h.put_PasswordRevealMode(match w.reveal_mode {
                    PasswordRevealMode::Peek => Xaml::PasswordRevealMode::Peek,
                    PasswordRevealMode::Hidden => Xaml::PasswordRevealMode::Hidden,
                    PasswordRevealMode::Visible => Xaml::PasswordRevealMode::Visible,
                })?;
            });
            changed!(old, w, is_password_reveal_button_enabled, {
                h.put_IsPasswordRevealButtonEnabled(w.is_password_reveal_button_enabled)?;
            });
            Ok(())
        }
    }
}
