// The tool_bindgen crate generates the modules for this crate
// while this build script generates the lib file that includes
// those modules.

fn main() {
    let mut mods: Vec<String> = std::fs::read_dir("src")
        .unwrap()
        .flatten()
        .filter_map(|entry| {
            let path = entry.path();
            if path.is_file() {
                let path = path.file_name().unwrap().to_string_lossy();

                if path == "lib.rs" {
                    None
                } else {
                    Some(format!("\npub mod {};", path.strip_suffix(".rs").unwrap()))
                }
            } else {
                None
            }
        })
        .collect();

    mods.sort();

    let mut lib_rs = "// This file was generated by the build script.\n".to_string();
    lib_rs.extend(mods);
    lib_rs.push('\n');
    std::fs::write("src/lib.rs", lib_rs).unwrap();
}
