[package]
name = "sample_reactor_next_gallery"
version = "0.0.0"
edition = "2024"
publish = false

[dependencies]
windows-reactor-next = { workspace = true }

[dev-dependencies]
windows-reactor-next = { workspace = true, features = ["test"] }

[build-dependencies]
windows-reactor-setup = { workspace = true }

[lints]
workspace = true
