[package]
name = "test_csharp"
version = "0.0.0"
edition = "2024"
publish = false

[lib]
doctest = false

[dependencies]
test_bench_component = { path = "../../../samples/test_bench/component" }

[dev-dependencies]
windows-rdl = { workspace = true }
windows-csharp = { workspace = true }

[lints]
workspace = true
