// This file is auto-generated by tool_reactor. Do not edit.

use super::*;
#[doc = r" Try to handle an `attach_event` call via generated dispatch."]
#[doc = r" Returns `Some(revokers)` if handled, `None` to fall through."]
pub fn dispatch(
    handle: &Handle,
    event: Event,
    handler: &EventHandler,
) -> Option<Vec<windows_core::EventRevoker>> {
    let mut revokers = Vec::new();
    match (event, handle) {
        (Event::ItemClicked, Handle::BreadcrumbBar(h)) => {
            let handler = handler.clone();
            revokers.push(
                h.ItemClicked(move |_sender, args| {
                    if let Some(a) = args.as_ref()
                        && let Ok(v) = a.Index()
                    {
                        handler.invoke_i32(v);
                    }
                })
                .unwrap(),
            );
        }
        (Event::Click, Handle::Button(h)) => {
            let handler = handler.clone();
            revokers.push(
                h.cast::<bindings::IButtonBase>()
                    .unwrap()
                    .Click(move |_sender, _args| {
                        handler.invoke();
                    })
                    .unwrap(),
            );
        }
        (Event::SelectedDatesChanged, Handle::CalendarView(h)) => {
            let handler = handler.clone();
            revokers.push(
                h.SelectedDatesChanged(move |_sender, _args| {
                    handler.invoke();
                })
                .unwrap(),
            );
        }
        (Event::Checked, Handle::CheckBox(h)) => {
            let true_handler = handler.clone();
            revokers.push(
                h.cast::<bindings::IToggleButton>()
                    .unwrap()
                    .Checked(move |_sender, _args| {
                        true_handler.invoke_bool(true);
                    })
                    .unwrap(),
            );
            let false_handler = handler.clone();
            revokers.push(
                h.cast::<bindings::IToggleButton>()
                    .unwrap()
                    .Unchecked(move |_sender, _args| {
                        false_handler.invoke_bool(false);
                    })
                    .unwrap(),
            );
        }
        (Event::Click, Handle::DropDownButton(h)) => {
            let handler = handler.clone();
            revokers.push(
                h.cast::<bindings::IButtonBase>()
                    .unwrap()
                    .Click(move |_sender, _args| {
                        handler.invoke();
                    })
                    .unwrap(),
            );
        }
        (Event::Expanding, Handle::Expander(h)) => {
            let true_handler = handler.clone();
            revokers.push(
                h.Expanding(move |_sender, _args| {
                    true_handler.invoke_bool(true);
                })
                .unwrap(),
            );
            let false_handler = handler.clone();
            revokers.push(
                h.Collapsed(move |_sender, _args| {
                    false_handler.invoke_bool(false);
                })
                .unwrap(),
            );
        }
        (Event::Click, Handle::HyperlinkButton(h)) => {
            let handler = handler.clone();
            revokers.push(
                h.cast::<bindings::IButtonBase>()
                    .unwrap()
                    .Click(move |_sender, _args| {
                        handler.invoke();
                    })
                    .unwrap(),
            );
        }
        (Event::Closed, Handle::InfoBar(h)) => {
            let handler = handler.clone();
            revokers.push(
                h.Closed(move |_sender, _args| {
                    handler.invoke();
                })
                .unwrap(),
            );
        }
        (Event::BackRequested, Handle::NavigationView(h)) => {
            let handler = handler.clone();
            revokers.push(
                h.cast::<bindings::INavigationView2>()
                    .unwrap()
                    .BackRequested(move |_sender, _args| {
                        handler.invoke();
                    })
                    .unwrap(),
            );
        }
        (Event::ValueChanged, Handle::NumberBox(h)) => {
            let handler = handler.clone();
            revokers.push(
                h.ValueChanged(move |_sender, args| {
                    if let Some(a) = args.as_ref()
                        && let Ok(v) = a.NewValue()
                    {
                        handler.invoke_f64(v);
                    }
                })
                .unwrap(),
            );
        }
        (Event::PasswordChanged, Handle::PasswordBox(h)) => {
            let handler = handler.clone();
            revokers.push(
                h.PasswordChanged(move |sender, _args| {
                    let v = sender
                        .as_ref()
                        .and_then(|s| s.cast::<bindings::PasswordBox>().ok())
                        .and_then(|s| s.Password().ok())
                        .unwrap_or(Default::default());
                    handler.invoke_string(v);
                })
                .unwrap(),
            );
        }
        (Event::Click, Handle::RepeatButton(h)) => {
            let handler = handler.clone();
            revokers.push(
                h.cast::<bindings::IButtonBase>()
                    .unwrap()
                    .Click(move |_sender, _args| {
                        handler.invoke();
                    })
                    .unwrap(),
            );
        }
        (Event::Checked, Handle::ToggleButton(h)) => {
            let true_handler = handler.clone();
            revokers.push(
                h.Checked(move |_sender, _args| {
                    true_handler.invoke_bool(true);
                })
                .unwrap(),
            );
            let false_handler = handler.clone();
            revokers.push(
                h.Unchecked(move |_sender, _args| {
                    false_handler.invoke_bool(false);
                })
                .unwrap(),
            );
        }
        (Event::Checked, Handle::RadioButton(h)) => {
            let handler = handler.clone();
            revokers.push(
                h.cast::<bindings::IToggleButton>()
                    .unwrap()
                    .Checked(move |_sender, _args| {
                        handler.invoke();
                    })
                    .unwrap(),
            );
        }
        (Event::SelectionChanged, Handle::RadioButtons(h)) => {
            let handler = handler.clone();
            revokers.push(
                h.SelectionChanged(move |sender, _args| {
                    let v = sender
                        .as_ref()
                        .and_then(|s| s.cast::<bindings::RadioButtons>().ok())
                        .and_then(|s| s.SelectedIndex().ok())
                        .unwrap_or(-1);
                    handler.invoke_i32(v);
                })
                .unwrap(),
            );
        }
        (Event::ValueChanged, Handle::RatingControl(h)) => {
            let handler = handler.clone();
            revokers.push(
                h.ValueChanged(move |sender, _args| {
                    let v = sender
                        .as_ref()
                        .and_then(|s| s.cast::<bindings::RatingControl>().ok())
                        .and_then(|s| s.Value().ok())
                        .unwrap_or(-1.0);
                    handler.invoke_f64(v);
                })
                .unwrap(),
            );
        }
        (Event::ValueChanged, Handle::Slider(h)) => {
            let handler = handler.clone();
            revokers.push(
                h.cast::<bindings::IRangeBase>()
                    .unwrap()
                    .ValueChanged(move |_sender, args| {
                        if let Some(a) = args.as_ref()
                            && let Ok(v) = a.NewValue()
                        {
                            handler.invoke_f64(v);
                        }
                    })
                    .unwrap(),
            );
        }
        (Event::Click, Handle::SplitButton(h)) => {
            let handler = handler.clone();
            revokers.push(
                h.Click(move |_sender, _args| {
                    handler.invoke();
                })
                .unwrap(),
            );
        }
        (Event::PaneClosed, Handle::SplitView(h)) => {
            let handler = handler.clone();
            revokers.push(
                h.PaneClosed(move |_sender, _args| {
                    handler.invoke();
                })
                .unwrap(),
            );
        }
        (Event::AddTabButtonClick, Handle::TabView(h)) => {
            let handler = handler.clone();
            revokers.push(
                h.AddTabButtonClick(move |_sender, _args| {
                    handler.invoke();
                })
                .unwrap(),
            );
        }
        (Event::ActionButtonClick, Handle::TeachingTip(h)) => {
            let handler = handler.clone();
            revokers.push(
                h.ActionButtonClick(move |_sender, _args| {
                    handler.invoke();
                })
                .unwrap(),
            );
        }
        (Event::Closed, Handle::TeachingTip(h)) => {
            let handler = handler.clone();
            revokers.push(
                h.Closed(move |_sender, _args| {
                    handler.invoke();
                })
                .unwrap(),
            );
        }
        (Event::TextChanged, Handle::TextBox(h)) => {
            let handler = handler.clone();
            revokers.push(
                h.TextChanged(move |sender, _args| {
                    let v = sender
                        .as_ref()
                        .and_then(|s| s.cast::<bindings::TextBox>().ok())
                        .and_then(|s| s.Text().ok())
                        .unwrap_or(Default::default());
                    handler.invoke_string(v);
                })
                .unwrap(),
            );
        }
        (Event::BackRequested, Handle::TitleBar(h)) => {
            let handler = handler.clone();
            revokers.push(
                h.BackRequested(move |_sender, _args| {
                    handler.invoke();
                })
                .unwrap(),
            );
        }
        (Event::PaneToggleRequested, Handle::TitleBar(h)) => {
            let handler = handler.clone();
            revokers.push(
                h.PaneToggleRequested(move |_sender, _args| {
                    handler.invoke();
                })
                .unwrap(),
            );
        }
        (Event::Toggled, Handle::ToggleSwitch(h)) => {
            let handler = handler.clone();
            revokers.push(
                h.Toggled(move |sender, _args| {
                    let v = sender
                        .as_ref()
                        .and_then(|s| s.cast::<bindings::ToggleSwitch>().ok())
                        .and_then(|s| s.IsOn().ok())
                        .unwrap_or(false);
                    handler.invoke_bool(v);
                })
                .unwrap(),
            );
        }
        _ => return None,
    }
    Some(revokers)
}
