windows_link::link!("evr.dll" "C" fn MFCreateVideoMixer(powner : *mut core::ffi::c_void, riiddevice : *const windows_sys::core::GUID, riid : *const windows_sys::core::GUID, ppv : *mut *mut core::ffi::c_void) -> windows_sys::core::HRESULT);
windows_link::link!("evr.dll" "C" fn MFCreateVideoMixerAndPresenter(pmixerowner : *mut core::ffi::c_void, ppresenterowner : *mut core::ffi::c_void, riidmixer : *const windows_sys::core::GUID, ppvvideomixer : *mut *mut core::ffi::c_void, riidpresenter : *const windows_sys::core::GUID, ppvvideopresenter : *mut *mut core::ffi::c_void) -> windows_sys::core::HRESULT);
windows_link::link!("evr.dll" "C" fn MFCreateVideoPresenter(powner : *mut core::ffi::c_void, riiddevice : *const windows_sys::core::GUID, riid : *const windows_sys::core::GUID, ppvideopresenter : *mut *mut core::ffi::c_void) -> windows_sys::core::HRESULT);
windows_link::link!("mf.dll" "C" fn MFCreateVideoRenderer(riidrenderer : *const windows_sys::core::GUID, ppvideorenderer : *mut *mut core::ffi::c_void) -> windows_sys::core::HRESULT);
windows_link::link!("evr.dll" "C" fn MFCreateVideoSampleAllocator(riid : *const windows_sys::core::GUID, ppsampleallocator : *mut *mut core::ffi::c_void) -> windows_sys::core::HRESULT);
#[cfg(feature = "mfobjects")]
windows_link::link!("evr.dll" "C" fn MFCreateVideoSampleFromSurface(punksurface : *mut core::ffi::c_void, ppsample : *mut *mut core::ffi::c_void) -> windows_sys::core::HRESULT);
pub type EVRFilterConfigPrefs = i32;
pub const EVRFilterConfigPrefs_EnableQoS: EVRFilterConfigPrefs = 1;
pub const EVRFilterConfigPrefs_Mask: EVRFilterConfigPrefs = 1;
pub const MFEVRDLL: u32 = 0;
pub const MFVP_MESSAGE_BEGINSTREAMING: MFVP_MESSAGE_TYPE = 3;
pub const MFVP_MESSAGE_CANCELSTEP: MFVP_MESSAGE_TYPE = 7;
pub const MFVP_MESSAGE_ENDOFSTREAM: MFVP_MESSAGE_TYPE = 5;
pub const MFVP_MESSAGE_ENDSTREAMING: MFVP_MESSAGE_TYPE = 4;
pub const MFVP_MESSAGE_FLUSH: MFVP_MESSAGE_TYPE = 0;
pub const MFVP_MESSAGE_INVALIDATEMEDIATYPE: MFVP_MESSAGE_TYPE = 1;
pub const MFVP_MESSAGE_PROCESSINPUTNOTIFY: MFVP_MESSAGE_TYPE = 2;
pub const MFVP_MESSAGE_STEP: MFVP_MESSAGE_TYPE = 6;
pub type MFVP_MESSAGE_TYPE = i32;
pub const MFVideoARMode_Mask: MFVideoAspectRatioMode = 7;
pub const MFVideoARMode_NonLinearStretch: MFVideoAspectRatioMode = 4;
pub const MFVideoARMode_None: MFVideoAspectRatioMode = 0;
pub const MFVideoARMode_PreservePicture: MFVideoAspectRatioMode = 1;
pub const MFVideoARMode_PreservePixel: MFVideoAspectRatioMode = 2;
pub type MFVideoAspectRatioMode = i32;
pub type MFVideoMixPrefs = i32;
pub const MFVideoMixPrefs_AllowDropToBob: MFVideoMixPrefs = 4;
pub const MFVideoMixPrefs_AllowDropToHalfInterlace: MFVideoMixPrefs = 2;
pub const MFVideoMixPrefs_EnableRotation: MFVideoMixPrefs = 16;
pub const MFVideoMixPrefs_ForceBob: MFVideoMixPrefs = 8;
pub const MFVideoMixPrefs_ForceHalfInterlace: MFVideoMixPrefs = 1;
pub const MFVideoMixPrefs_Mask: MFVideoMixPrefs = 31;
pub type MFVideoRenderPrefs = i32;
pub const MFVideoRenderPrefs_AllowBatching: MFVideoRenderPrefs = 32;
pub const MFVideoRenderPrefs_AllowOutputThrottling: MFVideoRenderPrefs = 4;
pub const MFVideoRenderPrefs_AllowScaling: MFVideoRenderPrefs = 128;
pub const MFVideoRenderPrefs_DoNotClipToDevice: MFVideoRenderPrefs = 2;
pub const MFVideoRenderPrefs_DoNotRenderBorder: MFVideoRenderPrefs = 1;
pub const MFVideoRenderPrefs_DoNotRepaintOnStop: MFVideoRenderPrefs = 256;
pub const MFVideoRenderPrefs_ForceBatching: MFVideoRenderPrefs = 16;
pub const MFVideoRenderPrefs_ForceOutputThrottling: MFVideoRenderPrefs = 8;
pub const MFVideoRenderPrefs_ForceScaling: MFVideoRenderPrefs = 64;
pub const MFVideoRenderPrefs_Mask: MFVideoRenderPrefs = 511;
pub const MF_SERVICE_LOOKUP_ALL: MF_SERVICE_LOOKUP_TYPE = 4;
pub const MF_SERVICE_LOOKUP_DOWNSTREAM: MF_SERVICE_LOOKUP_TYPE = 2;
pub const MF_SERVICE_LOOKUP_DOWNSTREAM_DIRECT: MF_SERVICE_LOOKUP_TYPE = 3;
pub const MF_SERVICE_LOOKUP_GLOBAL: MF_SERVICE_LOOKUP_TYPE = 5;
pub type MF_SERVICE_LOOKUP_TYPE = i32;
pub const MF_SERVICE_LOOKUP_UPSTREAM: MF_SERVICE_LOOKUP_TYPE = 0;
pub const MF_SERVICE_LOOKUP_UPSTREAM_DIRECT: MF_SERVICE_LOOKUP_TYPE = 1;
pub const MR_BUFFER_SERVICE: windows_sys::core::GUID = windows_sys::core::GUID::from_u128(0xa562248c_9ac6_4ffc_9fba_3af8f8ad1a4d);
pub const MR_VIDEO_ACCELERATION_SERVICE: windows_sys::core::GUID = windows_sys::core::GUID::from_u128(0xefef5175_5c7d_4ce2_bbbd_34ff8bca6554);
pub const MR_VIDEO_MIXER_SERVICE: windows_sys::core::GUID = windows_sys::core::GUID::from_u128(0x073cd2fc_6cf4_40b7_8859_e89552c841f8);
pub const MR_VIDEO_RENDER_SERVICE: windows_sys::core::GUID = windows_sys::core::GUID::from_u128(0x1092a86c_ab1a_459a_a336_831fbc4d11ff);
pub const VIDEO_ZOOM_RECT: windows_sys::core::GUID = windows_sys::core::GUID::from_u128(0x7aaa1638_1b7f_4c93_bd89_5b9c9fb6fcf0);
