[build]
rustflags = [
    "-D", "warnings",

    # "--cfg", "windows_raw_dylib",
    # "--cfg", "windows_slim_errors",
    # "-C", "target-feature=+crt-static",
]

[target.x86_64-pc-windows-gnu]
rustflags = ["-C", "link-arg=-Wl,--allow-multiple-definition"]
