// This file is generated by tool-reactor2.
#[non_exhaustive]
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum Orientation {
    Vertical,
    Horizontal,
}
impl Orientation {
    fn property_value(self) -> PropertyValue {
        match self {
            Self::Vertical => PropertyValue::Enum {
                kind: "Orientation",
                variant: "Vertical",
            },
            Self::Horizontal => PropertyValue::Enum {
                kind: "Orientation",
                variant: "Horizontal",
            },
        }
    }
}
#[derive(Clone, Debug, PartialEq)]
pub struct TextBlock(Declaration);
impl TextBlock {
    pub fn new(text: impl Into<Rc<str>>) -> Self {
        let declaration = Declaration::new(ObjectType::TextBlock);
        let declaration =
            declaration.property(PropertyId::Text, PropertyValue::String(text.into()));
        Self(declaration)
    }
    pub fn canvas_left(mut self, canvas_left: f64) -> Self {
        self.0 = self
            .0
            .property(PropertyId::CanvasLeft, PropertyValue::F64(canvas_left));
        self
    }
    pub fn canvas_top(mut self, canvas_top: f64) -> Self {
        self.0 = self
            .0
            .property(PropertyId::CanvasTop, PropertyValue::F64(canvas_top));
        self
    }
}
impl From<TextBlock> for Visual {
    fn from(value: TextBlock) -> Self {
        Self(value.0)
    }
}
#[derive(Clone, Debug, PartialEq)]
pub struct TextBox(Declaration);
impl TextBox {
    pub fn new(text: impl Into<Rc<str>>) -> Self {
        let declaration = Declaration::new(ObjectType::TextBox);
        let declaration =
            declaration.property(PropertyId::Text, PropertyValue::String(text.into()));
        Self(declaration)
    }
    pub fn canvas_left(mut self, canvas_left: f64) -> Self {
        self.0 = self
            .0
            .property(PropertyId::CanvasLeft, PropertyValue::F64(canvas_left));
        self
    }
    pub fn canvas_top(mut self, canvas_top: f64) -> Self {
        self.0 = self
            .0
            .property(PropertyId::CanvasTop, PropertyValue::F64(canvas_top));
        self
    }
    pub fn on_text_changed(self, callback: impl Fn(Rc<str>) + 'static) -> Self {
        self.on_text_changed_callback(Callback::new(callback))
    }
    pub fn on_text_changed_callback(mut self, callback: Callback<Rc<str>>) -> Self {
        self.0 = self
            .0
            .event(EventId::TextChanged, EventValue::String(callback));
        self
    }
}
impl From<TextBox> for Visual {
    fn from(value: TextBox) -> Self {
        Self(value.0)
    }
}
#[derive(Clone, Debug, PartialEq)]
pub struct Button(Declaration);
impl Button {
    pub fn new() -> Self {
        let declaration = Declaration::new(ObjectType::Button);
        Self(declaration)
    }
    pub fn canvas_left(mut self, canvas_left: f64) -> Self {
        self.0 = self
            .0
            .property(PropertyId::CanvasLeft, PropertyValue::F64(canvas_left));
        self
    }
    pub fn canvas_top(mut self, canvas_top: f64) -> Self {
        self.0 = self
            .0
            .property(PropertyId::CanvasTop, PropertyValue::F64(canvas_top));
        self
    }
    /// Rejects values outside this relation's generated type contract.
    ///
    /// ```compile_fail
    /// use windows_reactor2::*;
    /// let _ = Button::new().content(TreeNode::new("node", "Node"));
    /// ```
    pub fn content(mut self, content: impl Into<Visual>) -> Self {
        self.0 = self.0.relation(
            RelationId::Content,
            RelationValue::One(Some(Rc::new(content.into().0))),
        );
        self
    }
    pub fn on_click(self, callback: impl Fn() + 'static) -> Self {
        self.on_click_callback(Callback::new(move |()| callback()))
    }
    pub fn on_click_callback(mut self, callback: Callback<()>) -> Self {
        self.0 = self.0.event(EventId::Click, EventValue::Unit(callback));
        self
    }
}
impl Default for Button {
    fn default() -> Self {
        Self::new()
    }
}
impl From<Button> for Visual {
    fn from(value: Button) -> Self {
        Self(value.0)
    }
}
#[derive(Clone, Debug, PartialEq)]
pub struct CheckBox(Declaration);
impl CheckBox {
    pub fn new() -> Self {
        let declaration = Declaration::new(ObjectType::CheckBox);
        Self(declaration)
    }
    pub fn is_checked(mut self, is_checked: Option<bool>) -> Self {
        self.0 = self.0.property(
            PropertyId::IsChecked,
            PropertyValue::OptionalBool(is_checked),
        );
        self
    }
    pub fn canvas_left(mut self, canvas_left: f64) -> Self {
        self.0 = self
            .0
            .property(PropertyId::CanvasLeft, PropertyValue::F64(canvas_left));
        self
    }
    pub fn canvas_top(mut self, canvas_top: f64) -> Self {
        self.0 = self
            .0
            .property(PropertyId::CanvasTop, PropertyValue::F64(canvas_top));
        self
    }
    /// Rejects values outside this relation's generated type contract.
    ///
    /// ```compile_fail
    /// use windows_reactor2::*;
    /// let _ = CheckBox::new().content(TreeNode::new("node", "Node"));
    /// ```
    pub fn content(mut self, content: impl Into<Visual>) -> Self {
        self.0 = self.0.relation(
            RelationId::Content,
            RelationValue::One(Some(Rc::new(content.into().0))),
        );
        self
    }
    pub fn on_click(self, callback: impl Fn() + 'static) -> Self {
        self.on_click_callback(Callback::new(move |()| callback()))
    }
    pub fn on_click_callback(mut self, callback: Callback<()>) -> Self {
        self.0 = self.0.event(EventId::Click, EventValue::Unit(callback));
        self
    }
}
impl Default for CheckBox {
    fn default() -> Self {
        Self::new()
    }
}
impl From<CheckBox> for Visual {
    fn from(value: CheckBox) -> Self {
        Self(value.0)
    }
}
#[derive(Clone, Debug, PartialEq)]
pub struct Border(Declaration);
impl Border {
    pub fn new() -> Self {
        let declaration = Declaration::new(ObjectType::Border);
        Self(declaration)
    }
    pub fn canvas_left(mut self, canvas_left: f64) -> Self {
        self.0 = self
            .0
            .property(PropertyId::CanvasLeft, PropertyValue::F64(canvas_left));
        self
    }
    pub fn canvas_top(mut self, canvas_top: f64) -> Self {
        self.0 = self
            .0
            .property(PropertyId::CanvasTop, PropertyValue::F64(canvas_top));
        self
    }
    /// Rejects values outside this relation's generated type contract.
    ///
    /// ```compile_fail
    /// use windows_reactor2::*;
    /// let _ = Border::new().content(TreeNode::new("node", "Node"));
    /// ```
    pub fn content(mut self, content: impl Into<Visual>) -> Self {
        self.0 = self.0.relation(
            RelationId::Content,
            RelationValue::One(Some(Rc::new(content.into().0))),
        );
        self
    }
}
impl Default for Border {
    fn default() -> Self {
        Self::new()
    }
}
impl From<Border> for Visual {
    fn from(value: Border) -> Self {
        Self(value.0)
    }
}
#[derive(Clone, Debug, PartialEq)]
pub struct Grid(Declaration);
impl Grid {
    pub fn new() -> Self {
        let declaration = Declaration::new(ObjectType::Grid);
        Self(declaration)
    }
    pub fn canvas_left(mut self, canvas_left: f64) -> Self {
        self.0 = self
            .0
            .property(PropertyId::CanvasLeft, PropertyValue::F64(canvas_left));
        self
    }
    pub fn canvas_top(mut self, canvas_top: f64) -> Self {
        self.0 = self
            .0
            .property(PropertyId::CanvasTop, PropertyValue::F64(canvas_top));
        self
    }
    /// Rejects values outside this relation's generated type contract.
    ///
    /// ```compile_fail
    /// use windows_reactor2::*;
    /// let _ = Grid::new().children([TextBlock::new("Text")]);
    /// ```
    pub fn children(mut self, children: impl IntoIterator<Item = KeyedVisual>) -> Self {
        self.0 = self.0.relation(
            RelationId::Children,
            RelationValue::Many(Rc::new(
                children.into_iter().map(|child| child.0.0).collect(),
            )),
        );
        self
    }
}
impl Default for Grid {
    fn default() -> Self {
        Self::new()
    }
}
impl From<Grid> for Visual {
    fn from(value: Grid) -> Self {
        Self(value.0)
    }
}
#[derive(Clone, Debug, PartialEq)]
pub struct StackPanel(Declaration);
impl StackPanel {
    pub fn new() -> Self {
        let declaration = Declaration::new(ObjectType::StackPanel);
        Self(declaration)
    }
    pub fn spacing(mut self, spacing: f64) -> Self {
        self.0 = self
            .0
            .property(PropertyId::Spacing, PropertyValue::F64(spacing));
        self
    }
    pub fn orientation(mut self, orientation: Orientation) -> Self {
        self.0 = self
            .0
            .property(PropertyId::Orientation, orientation.property_value());
        self
    }
    pub fn canvas_left(mut self, canvas_left: f64) -> Self {
        self.0 = self
            .0
            .property(PropertyId::CanvasLeft, PropertyValue::F64(canvas_left));
        self
    }
    pub fn canvas_top(mut self, canvas_top: f64) -> Self {
        self.0 = self
            .0
            .property(PropertyId::CanvasTop, PropertyValue::F64(canvas_top));
        self
    }
    /// Rejects values outside this relation's generated type contract.
    ///
    /// ```compile_fail
    /// use windows_reactor2::*;
    /// let _ = StackPanel::new().children([keyed("text", TextBlock::new("Text"))]);
    /// ```
    pub fn children(mut self, children: impl IntoIterator<Item = Visual>) -> Self {
        self.0 = self.0.relation(
            RelationId::Children,
            RelationValue::Many(Rc::new(children.into_iter().map(|child| child.0).collect())),
        );
        self
    }
}
impl Default for StackPanel {
    fn default() -> Self {
        Self::new()
    }
}
impl From<StackPanel> for Visual {
    fn from(value: StackPanel) -> Self {
        Self(value.0)
    }
}
#[derive(Clone, Debug, PartialEq)]
pub struct Canvas(Declaration);
impl Canvas {
    pub fn new() -> Self {
        let declaration = Declaration::new(ObjectType::Canvas);
        Self(declaration)
    }
    pub fn canvas_left(mut self, canvas_left: f64) -> Self {
        self.0 = self
            .0
            .property(PropertyId::CanvasLeft, PropertyValue::F64(canvas_left));
        self
    }
    pub fn canvas_top(mut self, canvas_top: f64) -> Self {
        self.0 = self
            .0
            .property(PropertyId::CanvasTop, PropertyValue::F64(canvas_top));
        self
    }
    /// Rejects values outside this relation's generated type contract.
    ///
    /// ```compile_fail
    /// use windows_reactor2::*;
    /// let _ = Canvas::new().children([keyed("text", TextBlock::new("Text"))]);
    /// ```
    pub fn children(mut self, children: impl IntoIterator<Item = Visual>) -> Self {
        self.0 = self.0.relation(
            RelationId::Children,
            RelationValue::Many(Rc::new(children.into_iter().map(|child| child.0).collect())),
        );
        self
    }
}
impl Default for Canvas {
    fn default() -> Self {
        Self::new()
    }
}
impl From<Canvas> for Visual {
    fn from(value: Canvas) -> Self {
        Self(value.0)
    }
}
#[derive(Clone, Debug, PartialEq)]
pub struct ScrollViewer(Declaration);
impl ScrollViewer {
    pub fn new() -> Self {
        let declaration = Declaration::new(ObjectType::ScrollViewer);
        Self(declaration)
    }
    pub fn canvas_left(mut self, canvas_left: f64) -> Self {
        self.0 = self
            .0
            .property(PropertyId::CanvasLeft, PropertyValue::F64(canvas_left));
        self
    }
    pub fn canvas_top(mut self, canvas_top: f64) -> Self {
        self.0 = self
            .0
            .property(PropertyId::CanvasTop, PropertyValue::F64(canvas_top));
        self
    }
    /// Rejects values outside this relation's generated type contract.
    ///
    /// ```compile_fail
    /// use windows_reactor2::*;
    /// let _ = ScrollViewer::new().content(TreeNode::new("node", "Node"));
    /// ```
    pub fn content(mut self, content: impl Into<Visual>) -> Self {
        self.0 = self.0.relation(
            RelationId::Content,
            RelationValue::One(Some(Rc::new(content.into().0))),
        );
        self
    }
}
impl Default for ScrollViewer {
    fn default() -> Self {
        Self::new()
    }
}
impl From<ScrollViewer> for Visual {
    fn from(value: ScrollViewer) -> Self {
        Self(value.0)
    }
}
#[derive(Clone, Debug, PartialEq)]
pub struct Slider(Declaration);
impl Slider {
    pub fn new() -> Self {
        let declaration = Declaration::new(ObjectType::Slider);
        Self(declaration)
    }
    pub fn minimum(mut self, minimum: f64) -> Self {
        self.0 = self
            .0
            .property(PropertyId::Minimum, PropertyValue::F64(minimum));
        self
    }
    pub fn maximum(mut self, maximum: f64) -> Self {
        self.0 = self
            .0
            .property(PropertyId::Maximum, PropertyValue::F64(maximum));
        self
    }
    pub fn value(mut self, value: f64) -> Self {
        self.0 = self
            .0
            .property(PropertyId::Value, PropertyValue::F64(value));
        self
    }
    pub fn canvas_left(mut self, canvas_left: f64) -> Self {
        self.0 = self
            .0
            .property(PropertyId::CanvasLeft, PropertyValue::F64(canvas_left));
        self
    }
    pub fn canvas_top(mut self, canvas_top: f64) -> Self {
        self.0 = self
            .0
            .property(PropertyId::CanvasTop, PropertyValue::F64(canvas_top));
        self
    }
    pub fn on_value_changed(self, callback: impl Fn(f64) + 'static) -> Self {
        self.on_value_changed_callback(Callback::new(callback))
    }
    pub fn on_value_changed_callback(mut self, callback: Callback<f64>) -> Self {
        self.0 = self
            .0
            .event(EventId::ValueChanged, EventValue::F64(callback));
        self
    }
}
impl Default for Slider {
    fn default() -> Self {
        Self::new()
    }
}
impl From<Slider> for Visual {
    fn from(value: Slider) -> Self {
        Self(value.0)
    }
}
#[derive(Clone, Debug, PartialEq)]
pub struct TreeView(Declaration);
impl TreeView {
    pub fn new() -> Self {
        let declaration = Declaration::new(ObjectType::TreeView);
        Self(declaration)
    }
    pub fn canvas_left(mut self, canvas_left: f64) -> Self {
        self.0 = self
            .0
            .property(PropertyId::CanvasLeft, PropertyValue::F64(canvas_left));
        self
    }
    pub fn canvas_top(mut self, canvas_top: f64) -> Self {
        self.0 = self
            .0
            .property(PropertyId::CanvasTop, PropertyValue::F64(canvas_top));
        self
    }
    /// Rejects values outside this relation's generated type contract.
    ///
    /// ```compile_fail
    /// use windows_reactor2::*;
    /// let _ = TreeView::new().nodes([TextBlock::new("Text")]);
    /// ```
    pub fn nodes(mut self, children: impl IntoIterator<Item = TreeNode>) -> Self {
        self.0 = self.0.relation(
            RelationId::Roots,
            RelationValue::Many(Rc::new(children.into_iter().map(|child| child.0).collect())),
        );
        self
    }
}
impl Default for TreeView {
    fn default() -> Self {
        Self::new()
    }
}
impl From<TreeView> for Visual {
    fn from(value: TreeView) -> Self {
        Self(value.0)
    }
}
#[derive(Clone, Debug, PartialEq)]
pub struct TreeNode(Declaration);
impl TreeNode {
    pub fn new(key: impl Into<Key>, text: impl Into<Rc<str>>) -> Self {
        let declaration = Declaration::new(ObjectType::TreeNode);
        let declaration = declaration.key(key);
        let declaration =
            declaration.property(PropertyId::Text, PropertyValue::String(text.into()));
        Self(declaration)
    }
    pub fn expanded(mut self, expanded: bool) -> Self {
        self.0 = self
            .0
            .property(PropertyId::Expanded, PropertyValue::Bool(expanded));
        self
    }
    /// Rejects values outside this relation's generated type contract.
    ///
    /// ```compile_fail
    /// use windows_reactor2::*;
    /// let _ = TreeNode::new("key", "Text").content(TreeNode::new("node", "Node"));
    /// ```
    pub fn content(mut self, content: impl Into<Visual>) -> Self {
        self.0 = self.0.relation(
            RelationId::Content,
            RelationValue::One(Some(Rc::new(content.into().0))),
        );
        self
    }
    /// Rejects values outside this relation's generated type contract.
    ///
    /// ```compile_fail
    /// use windows_reactor2::*;
    /// let _ = TreeNode::new("key", "Text").children([TextBlock::new("Text")]);
    /// ```
    pub fn children(mut self, children: impl IntoIterator<Item = Self>) -> Self {
        self.0 = self.0.relation(
            RelationId::Children,
            RelationValue::Many(Rc::new(children.into_iter().map(|child| child.0).collect())),
        );
        self
    }
}
#[derive(Clone, Debug, PartialEq)]
pub struct ListView(Declaration);
impl ListView {
    pub fn new() -> Self {
        let declaration = Declaration::new(ObjectType::ListView);
        Self(declaration)
    }
    pub fn canvas_left(mut self, canvas_left: f64) -> Self {
        self.0 = self
            .0
            .property(PropertyId::CanvasLeft, PropertyValue::F64(canvas_left));
        self
    }
    pub fn canvas_top(mut self, canvas_top: f64) -> Self {
        self.0 = self
            .0
            .property(PropertyId::CanvasTop, PropertyValue::F64(canvas_top));
        self
    }
    /// Rejects values outside this relation's generated type contract.
    ///
    /// ```compile_fail
    /// use windows_reactor2::*;
    /// let _ = ListView::new().items([TextBlock::new("Text")]);
    /// ```
    pub fn items(mut self, children: impl IntoIterator<Item = DataItem>) -> Self {
        self.0 = self.0.relation(
            RelationId::Items,
            RelationValue::Many(Rc::new(children.into_iter().map(|child| child.0).collect())),
        );
        self
    }
}
impl Default for ListView {
    fn default() -> Self {
        Self::new()
    }
}
impl From<ListView> for Visual {
    fn from(value: ListView) -> Self {
        Self(value.0)
    }
}
#[derive(Clone, Debug, PartialEq)]
pub struct DataItem(Declaration);
impl DataItem {
    pub fn new(key: impl Into<Key>, text: impl Into<Rc<str>>) -> Self {
        let declaration = Declaration::new(ObjectType::DataItem);
        let declaration = declaration.key(key);
        let declaration =
            declaration.property(PropertyId::Text, PropertyValue::String(text.into()));
        Self(declaration)
    }
}
