fn main() {
    winrt::build!(
        windows::ai::machine_learning::*
        windows::ai::machine_learning::preview::*
        windows::application_model::*
        windows::application_model::activation::*
        windows::application_model::app_extensions::*
        windows::application_model::app_service::*
        windows::application_model::appointments::*
        windows::application_model::appointments::appointments_provider::*
        windows::application_model::appointments::data_provider::*
        windows::application_model::background::*
        windows::application_model::calls::*
        windows::application_model::calls::background::*
        windows::application_model::calls::provider::*
        windows::application_model::chat::*
        windows::application_model::communication_blocking::*
        windows::application_model::contacts::*
        windows::application_model::contacts::data_provider::*
        windows::application_model::contacts::provider::*
        windows::application_model::conversational_agent::*
        windows::application_model::core::*
        windows::application_model::data_transfer::*
        windows::application_model::data_transfer::drag_drop::*
        windows::application_model::data_transfer::drag_drop::core::*
        windows::application_model::data_transfer::share_target::*
        windows::application_model::email::*
        windows::application_model::email::data_provider::*
        windows::application_model::extended_execution::*
        windows::application_model::extended_execution::foreground::*
        windows::application_model::lock_screen::*
        windows::application_model::payments::*
        windows::application_model::payments::provider::*
        windows::application_model::preview::holographic::*
        windows::application_model::preview::ink_workspace::*
        windows::application_model::preview::notes::*
        windows::application_model::resources::*
        windows::application_model::resources::core::*
        windows::application_model::resources::management::*
        windows::application_model::search::*
        windows::application_model::search::core::*
        windows::application_model::social_info::*
        windows::application_model::social_info::provider::*
        windows::application_model::store::*
        windows::application_model::store::license_management::*
        windows::application_model::store::preview::*
        windows::application_model::store::preview::install_control::*
        windows::application_model::user_activities::*
        windows::application_model::user_activities::core::*
        windows::application_model::user_data_accounts::*
        windows::application_model::user_data_accounts::provider::*
        windows::application_model::user_data_accounts::system_access::*
        windows::application_model::user_data_tasks::*
        windows::application_model::user_data_tasks::data_provider::*
        windows::application_model::voice_commands::*
        windows::application_model::wallet::*
        windows::application_model::wallet::system::*
        windows::data::html::*
        windows::data::json::*
        windows::data::pdf::*
        windows::data::text::*
        windows::data::xml::dom::*
        windows::data::xml::xsl::*
        windows::devices::*
        windows::devices::adc::*
        windows::devices::adc::provider::*
        windows::devices::all_joyn::*
        windows::devices::background::*
        windows::devices::bluetooth::*
        windows::devices::bluetooth::advertisement::*
        windows::devices::bluetooth::background::*
        windows::devices::bluetooth::generic_attribute_profile::*
        windows::devices::bluetooth::rfcomm::*
        windows::devices::custom::*
        windows::devices::display::*
        windows::devices::display::core::*
        windows::devices::enumeration::*
        windows::devices::enumeration::pnp::*
        windows::devices::geolocation::*
        windows::devices::geolocation::geofencing::*
        windows::devices::gpio::*
        windows::devices::gpio::provider::*
        windows::devices::haptics::*
        windows::devices::human_interface_device::*
        windows::devices::i2c::*
        windows::devices::i2c::provider::*
        windows::devices::input::*
        windows::devices::input::preview::*
        windows::devices::lights::*
        windows::devices::lights::effects::*
        windows::devices::midi::*
        windows::devices::perception::*
        windows::devices::perception::provider::*
        windows::devices::point_of_service::*
        windows::devices::point_of_service::provider::*
        windows::devices::portable::*
        windows::devices::power::*
        windows::devices::printers::*
        windows::devices::printers::extensions::*
        windows::devices::pwm::*
        windows::devices::pwm::provider::*
        windows::devices::radios::*
        windows::devices::scanners::*
        windows::devices::sensors::*
        windows::devices::sensors::custom::*
        windows::devices::serial_communication::*
        windows::devices::smart_cards::*
        windows::devices::sms::*
        windows::devices::spi::*
        windows::devices::spi::provider::*
        windows::devices::usb::*
        windows::devices::wi_fi::*
        windows::devices::wi_fi_direct::*
        windows::devices::wi_fi_direct::services::*
        windows::embedded::device_lockdown::*
        windows::foundation::*
        windows::foundation::collections::*
        windows::foundation::diagnostics::*
        windows::foundation::metadata::*
        windows::foundation::numerics::*
        windows::gaming::input::*
        windows::gaming::input::custom::*
        windows::gaming::input::force_feedback::*
        windows::gaming::input::preview::*
        windows::gaming::preview::*
        windows::gaming::preview::games_enumeration::*
        windows::gaming::ui::*
        windows::gaming::xbox_live::*
        windows::gaming::xbox_live::storage::*
        windows::globalization::*
        windows::globalization::collation::*
        windows::globalization::date_time_formatting::*
        windows::globalization::fonts::*
        windows::globalization::number_formatting::*
        windows::globalization::phone_number_formatting::*
        windows::graphics::*
        windows::graphics::capture::*
        windows::graphics::directx::*
        windows::graphics::directx::direct3d11::*
        windows::graphics::display::*
        windows::graphics::display::core::*
        windows::graphics::effects::*
        windows::graphics::holographic::*
        windows::graphics::imaging::*
        windows::graphics::printing::*
        windows::graphics::printing::option_details::*
        windows::graphics::printing::print_ticket::*
        windows::graphics::printing::workflow::*
        windows::graphics::printing3d::*
        windows::management::*
        windows::management::core::*
        windows::management::deployment::*
        windows::management::deployment::preview::*
        windows::management::policies::*
        windows::management::update::*
        windows::management::workplace::*
        windows::media::*
        windows::media::app_broadcasting::*
        windows::media::app_recording::*
        windows::media::audio::*
        windows::media::capture::*
        windows::media::capture::core::*
        windows::media::capture::frames::*
        windows::media::casting::*
        windows::media::closed_captioning::*
        windows::media::content_restrictions::*
        windows::media::control::*
        windows::media::core::*
        windows::media::core::preview::*
        windows::media::devices::*
        windows::media::devices::core::*
        windows::media::dial_protocol::*
        windows::media::editing::*
        windows::media::effects::*
        windows::media::face_analysis::*
        windows::media::import::*
        windows::media::media_properties::*
        windows::media::miracast::*
        windows::media::ocr::*
        windows::media::play_to::*
        windows::media::playback::*
        windows::media::playlists::*
        windows::media::protection::*
        windows::media::protection::play_ready::*
        windows::media::render::*
        windows::media::speech_recognition::*
        windows::media::speech_synthesis::*
        windows::media::streaming::adaptive::*
        windows::media::transcoding::*
        windows::networking::*
        windows::networking::background_transfer::*
        windows::networking::connectivity::*
        windows::networking::network_operators::*
        windows::networking::proximity::*
        windows::networking::push_notifications::*
        windows::networking::service_discovery::dnssd::*
        windows::networking::sockets::*
        windows::networking::vpn::*
        windows::networking::xbox_live::*
        windows::perception::*
        windows::perception::automation::core::*
        windows::perception::people::*
        windows::perception::spatial::*
        windows::perception::spatial::preview::*
        windows::perception::spatial::surfaces::*
        windows::phone::*
        windows::phone::application_model::*
        windows::phone::devices::notification::*
        windows::phone::devices::power::*
        windows::phone::management::deployment::*
        windows::phone::media::devices::*
        windows::phone::notification::management::*
        windows::phone::personal_information::*
        windows::phone::personal_information::provisioning::*
        windows::phone::speech::recognition::*
        windows::phone::system::*
        windows::phone::system::power::*
        windows::phone::system::profile::*
        windows::phone::system::user_profile::game_services::core::*
        windows::phone::ui::input::*
        windows::security::authentication::identity::*
        windows::security::authentication::identity::core::*
        windows::security::authentication::identity::provider::*
        windows::security::authentication::online_id::*
        windows::security::authentication::web::*
        windows::security::authentication::web::core::*
        windows::security::authentication::web::provider::*
        windows::security::authorization::app_capability_access::*
        windows::security::credentials::*
        windows::security::credentials::ui::*
        windows::security::cryptography::*
        windows::security::cryptography::certificates::*
        windows::security::cryptography::core::*
        windows::security::cryptography::data_protection::*
        windows::security::data_protection::*
        windows::security::enterprise_data::*
        windows::security::exchange_active_sync_provisioning::*
        windows::security::isolation::*
        windows::services::cortana::*
        windows::services::maps::*
        windows::services::maps::guidance::*
        windows::services::maps::local_search::*
        windows::services::maps::offline_maps::*
        windows::services::store::*
        windows::services::targeted_content::*
        windows::storage::*
        windows::storage::access_cache::*
        windows::storage::bulk_access::*
        windows::storage::compression::*
        windows::storage::file_properties::*
        windows::storage::pickers::*
        windows::storage::pickers::provider::*
        windows::storage::provider::*
        windows::storage::search::*
        windows::storage::streams::*
        windows::system::*
        windows::system::diagnostics::*
        windows::system::diagnostics::device_portal::*
        windows::system::diagnostics::telemetry::*
        windows::system::diagnostics::trace_reporting::*
        windows::system::display::*
        windows::system::inventory::*
        windows::system::power::*
        windows::system::power::diagnostics::*
        windows::system::preview::*
        windows::system::profile::*
        windows::system::profile::system_manufacturers::*
        windows::system::remote_desktop::*
        windows::system::remote_systems::*
        windows::system::threading::*
        windows::system::threading::core::*
        windows::system::update::*
        windows::system::user_profile::*
        windows::ui::*
        windows::ui::accessibility::*
        windows::ui::application_settings::*
        windows::ui::composition::*
        windows::ui::composition::core::*
        windows::ui::composition::desktop::*
        windows::ui::composition::diagnostics::*
        windows::ui::composition::effects::*
        windows::ui::composition::interactions::*
        windows::ui::composition::scenes::*
        windows::ui::core::*
        windows::ui::core::animation_metrics::*
        windows::ui::core::preview::*
        windows::ui::input::*
        windows::ui::input::core::*
        windows::ui::input::inking::*
        windows::ui::input::inking::analysis::*
        windows::ui::input::inking::core::*
        windows::ui::input::inking::preview::*
        windows::ui::input::preview::*
        windows::ui::input::preview::injection::*
        windows::ui::input::spatial::*
        windows::ui::notifications::*
        windows::ui::notifications::management::*
        windows::ui::popups::*
        windows::ui::shell::*
        windows::ui::start_screen::*
        windows::ui::text::*
        windows::ui::text::core::*
        windows::ui::view_management::*
        windows::ui::view_management::core::*
        windows::ui::web_ui::*
        windows::ui::web_ui::core::*
        windows::ui::window_management::*
        windows::ui::window_management::preview::*
        windows::ui::xaml::*
        windows::ui::xaml::automation::*
        windows::ui::xaml::automation::peers::*
        windows::ui::xaml::automation::provider::*
        windows::ui::xaml::automation::text::*
        windows::ui::xaml::controls::*
        windows::ui::xaml::controls::maps::*
        windows::ui::xaml::controls::primitives::*
        windows::ui::xaml::core::direct::*
        windows::ui::xaml::data::*
        windows::ui::xaml::documents::*
        windows::ui::xaml::hosting::*
        windows::ui::xaml::input::*
        windows::ui::xaml::interop::*
        windows::ui::xaml::markup::*
        windows::ui::xaml::media::*
        windows::ui::xaml::media::animation::*
        windows::ui::xaml::media::imaging::*
        windows::ui::xaml::media::media3d::*
        windows::ui::xaml::navigation::*
        windows::ui::xaml::printing::*
        windows::ui::xaml::resources::*
        windows::ui::xaml::shapes::*
        windows::web::*
        windows::web::atom_pub::*
        windows::web::http::*
        windows::web::http::diagnostics::*
        windows::web::http::filters::*
        windows::web::http::headers::*
        windows::web::syndication::*
        windows::web::ui::*
        windows::web::ui::interop::*
        windows::win32::ad::*
        windows::win32::adsi::*
        windows::win32::all_joyn::*
        windows::win32::amsi::*
        windows::win32::appx_pkg::*
        windows::win32::audio::*
        windows::win32::automation::*
        windows::win32::backup::*
        windows::win32::base::*
        windows::win32::bits::*
        windows::win32::bluetooth::*
        windows::win32::buses::*
        windows::win32::cloudapi::*
        windows::win32::cmp_api::*
        windows::win32::com::*
        windows::win32::controls::*
        windows::win32::core_audio::*
        windows::win32::cos::*
        windows::win32::dshow::*
        windows::win32::data_xchg::*
        windows::win32::debug::*
        windows::win32::dedup::*
        windows::win32::dev_inst::*
        windows::win32::dev_lic::*
        windows::win32::device_access::*
        windows::win32::dfs::*
        windows::win32::dhcp::*
        windows::win32::direct2d::*
        windows::win32::direct3d10::*
        windows::win32::direct3d11::*
        windows::win32::direct3d12::*
        windows::win32::direct3d9::*
        windows::win32::direct3d_dxgi::*
        windows::win32::direct3d_hlsl::*
        windows::win32::direct_comp::*
        windows::win32::direct_draw::*
        windows::win32::direct_manipulation::*
        windows::win32::direct_ml::*
        windows::win32::direct_write::*
        windows::win32::dlg_box::*
        windows::win32::dns::*
        windows::win32::dwm::*
        windows::win32::eap::*
        windows::win32::eap_host::*
        windows::win32::edp::*
        windows::win32::enstor::*
        windows::win32::etw::*
        windows::win32::fax::*
        windows::win32::fs::*
        windows::win32::fsrm::*
        windows::win32::fwp::*
        windows::win32::game_mode::*
        windows::win32::gaming_dvc_info::*
        windows::win32::gdi::*
        windows::win32::gpmc::*
        windows::win32::hid::*
        windows::win32::html_help::*
        windows::win32::http::*
        windows::win32::imapi::*
        windows::win32::iscsi_disc::*
        windows::win32::ics::*
        windows::win32::ifsk::*
        windows::win32::index_srv::*
        windows::win32::input_dev::*
        windows::win32::input_ink::*
        windows::win32::input_int_context::*
        windows::win32::input_radial::*
        windows::win32::intl::*
        windows::win32::ip_hlp::*
        windows::win32::ixhr2::*
        windows::win32::js::*
        windows::win32::kernel::*
        windows::win32::ldap::*
        windows::win32::lwef::*
        windows::win32::machine_learning::*
        windows::win32::mad_cap::*
        windows::win32::mag_api::*
        windows::win32::mapi::*
        windows::win32::mbn::*
        windows::win32::mdm_reg::*
        windows::win32::media_transport::*
        windows::win32::menu_rc::*
        windows::win32::mf::*
        windows::win32::mixed_reality::*
        windows::win32::mmc::*
        windows::win32::monitor::*
        windows::win32::ms_chap::*
        windows::win32::ms_cs::*
        windows::win32::ms_tv::*
        windows::win32::multimedia::*
        windows::win32::nwifi::*
        windows::win32::ncd::*
        windows::win32::ndf::*
        windows::win32::net_bios::*
        windows::win32::net_mgmt::*
        windows::win32::net_shell::*
        windows::win32::nla::*
        windows::win32::nps::*
        windows::win32::of::*
        windows::win32::opc::*
        windows::win32::p2p::*
        windows::win32::parcon::*
        windows::win32::perf::*
        windows::win32::pic_acq::*
        windows::win32::pla::*
        windows::win32::policy::*
        windows::win32::proc_snap::*
        windows::win32::proj_fs::*
        windows::win32::properties::*
        windows::win32::ps_api::*
        windows::win32::qos::*
        windows::win32::rras::*
        windows::win32::rdc::*
        windows::win32::rdp::*
        windows::win32::remote_assist::*
        windows::win32::rm::*
        windows::win32::rpc::*
        windows::win32::rst_mgr::*
        windows::win32::search::*
        windows::win32::sec_bitomet::*
        windows::win32::security::*
        windows::win32::sens::*
        windows::win32::ser_ports::*
        windows::win32::setup::*
        windows::win32::shell::*
        windows::win32::smi::*
        windows::win32::snmp::*
        windows::win32::sr::*
        windows::win32::stg::*
        windows::win32::sw_device::*
        windows::win32::tablet::*
        windows::win32::tapi3::*
        windows::win32::task_schd::*
        windows::win32::tbs::*
        windows::win32::tcui::*
        windows::win32::term_serv::*
        windows::win32::tool_help::*
        windows::win32::tsf::*
        windows::win32::ual::*
        windows::win32::ui_animation::*
        windows::win32::upnp::*
        windows::win32::vstor::*
        windows::win32::wab::*
        windows::win32::wcm::*
        windows::win32::wcn::*
        windows::win32::wcs::*
        windows::win32::wds::*
        windows::win32::web_dav::*
        windows::win32::web_sock::*
        windows::win32::wec::*
        windows::win32::wer::*
        windows::win32::wes::*
        windows::win32::wia::*
        windows::win32::wibe::*
        windows::win32::wic::*
        windows::win32::win32_tile_badge_notif::*
        windows::win32::win_auto::*
        windows::win32::win_contacts::*
        windows::win32::win_inet::*
        windows::win32::win_location::*
        windows::win32::win_prog::*
        windows::win32::winrt::*
        windows::win32::win_rm::*
        windows::win32::win_sat::*
        windows::win32::win_sensors::*
        windows::win32::win_sock::*
        windows::win32::win_sync::*
        windows::win32::win_touch::*
        windows::win32::windows_ribbon::*
        windows::win32::windows_setup_and_migration::*
        windows::win32::wm_format::*
        windows::win32::wmdm::*
        windows::win32::wmi::*
        windows::win32::wmlss::*
        windows::win32::wmp::*
        windows::win32::wnet::*
        windows::win32::wnv::*
        windows::win32::wpd_sdk::*
        windows::win32::wsb::*
        windows::win32::wsl::*
        windows::win32::wsw::*
        windows::win32::wua::*
        windows::win32::xaudio2::*
        windows::win32::xinput::*
        windows::win32::xaml_diganostics::*
        windows::win32::xblidp::*
        windows::win32::xps::*
    );
}
