[package]
name = "reactor_webview"
version = "0.0.0"
edition = "2024"
publish = false

[dependencies]
reactor_samples = { path = "../samples" }
windows-core.workspace = true
windows-reactor = { workspace = true, features = ["webview"] }

[build-dependencies]
windows-reactor-setup = { workspace = true }

[lints]
workspace = true
