pub const CSTORAGEPROPERTY: u32 = 23;
#[cfg(feature = "wtypes")]
pub const PID_STG_ACCESSTIME: super::wtypes::PROPID = super::wtypes::PROPID(16);
#[cfg(feature = "wtypes")]
pub const PID_STG_ALLOCSIZE: super::wtypes::PROPID = super::wtypes::PROPID(18);
#[cfg(feature = "wtypes")]
pub const PID_STG_ATTRIBUTES: super::wtypes::PROPID = super::wtypes::PROPID(13);
#[cfg(feature = "wtypes")]
pub const PID_STG_CHANGETIME: super::wtypes::PROPID = super::wtypes::PROPID(17);
#[cfg(feature = "wtypes")]
pub const PID_STG_CLASSID: super::wtypes::PROPID = super::wtypes::PROPID(3);
#[cfg(feature = "wtypes")]
pub const PID_STG_CONTENTS: super::wtypes::PROPID = super::wtypes::PROPID(19);
#[cfg(feature = "wtypes")]
pub const PID_STG_CREATETIME: super::wtypes::PROPID = super::wtypes::PROPID(15);
#[cfg(feature = "wtypes")]
pub const PID_STG_DIRECTORY: super::wtypes::PROPID = super::wtypes::PROPID(2);
#[cfg(feature = "wtypes")]
pub const PID_STG_FILEINDEX: super::wtypes::PROPID = super::wtypes::PROPID(8);
#[cfg(feature = "wtypes")]
pub const PID_STG_FRN: super::wtypes::PROPID = super::wtypes::PROPID(21);
#[cfg(feature = "wtypes")]
pub const PID_STG_LASTCHANGEUSN: super::wtypes::PROPID = super::wtypes::PROPID(9);
pub const PID_STG_MAX: u32 = 22;
#[cfg(feature = "wtypes")]
pub const PID_STG_NAME: super::wtypes::PROPID = super::wtypes::PROPID(10);
#[cfg(feature = "wtypes")]
pub const PID_STG_PARENT_WORKID: super::wtypes::PROPID = super::wtypes::PROPID(6);
#[cfg(feature = "wtypes")]
pub const PID_STG_PATH: super::wtypes::PROPID = super::wtypes::PROPID(11);
#[cfg(feature = "wtypes")]
pub const PID_STG_SCOPE: super::wtypes::PROPID = super::wtypes::PROPID(22);
#[cfg(feature = "wtypes")]
pub const PID_STG_SECONDARYSTORE: super::wtypes::PROPID = super::wtypes::PROPID(7);
#[cfg(feature = "wtypes")]
pub const PID_STG_SHORTNAME: super::wtypes::PROPID = super::wtypes::PROPID(20);
#[cfg(feature = "wtypes")]
pub const PID_STG_SIZE: super::wtypes::PROPID = super::wtypes::PROPID(12);
#[cfg(feature = "wtypes")]
pub const PID_STG_STORAGETYPE: super::wtypes::PROPID = super::wtypes::PROPID(4);
#[cfg(feature = "wtypes")]
pub const PID_STG_VOLUME_ID: super::wtypes::PROPID = super::wtypes::PROPID(5);
#[cfg(feature = "wtypes")]
pub const PID_STG_WRITETIME: super::wtypes::PROPID = super::wtypes::PROPID(14);
