[package]
name = "test_reactor_selftest"
version = "0.0.0"
edition = "2024"
publish = false

[features]
self-contained = []

[dependencies]
windows-canvas = { workspace = true, features = ["reactor"] }
windows-composition = { workspace = true, features = ["reactor"] }
windows-collections = { workspace = true }
windows-core = { workspace = true }
windows-reactor = { workspace = true, features = ["test"] }
windows = { workspace = true, features = ["UI_Input_Preview_Injection", "winuser"] }

[build-dependencies]
windows-reactor-setup = { workspace = true }

[lints]
workspace = true
