[package]
name = "test-reactor-selftest"
version = "0.0.0"
edition = "2024"
publish = false
default-run = "test-reactor-selftest"

[features]
self-contained = []

[dependencies]
windows-core = { workspace = true }
windows-collections = { workspace = true }
windows-reactor = { workspace = true, features = ["test"] }
windows = { workspace = true, features = ["UI_Input_Preview_Injection", "winuser"] }

[build-dependencies]
windows-reactor-setup = { workspace = true }

[lints]
workspace = true
