use std::io::prelude::*;

fn main() -> std::io::Result<()> {
    let tokens = windows_macros::generate!(
        Windows::Foundation::{IReference, IStringable, PropertyValue},
        Windows::Win32::Automation::{BSTR, GetErrorInfo, IErrorInfo, SetErrorInfo},
        Windows::Win32::WinRT::{IRestrictedErrorInfo, ILanguageExceptionErrorInfo2, IWeakReference, IWeakReferenceSource},
        Windows::Win32::Debug::{GetLastError, FormatMessageW},
        Windows::Win32::WindowsProgramming::CloseHandle,
        Windows::Win32::Com::{
            CoCreateGuid, CoTaskMemAlloc, CoTaskMemFree, CLSIDFromProgID, CoInitializeEx, CoCreateInstance,
            IAgileObject,
        },
        Windows::Win32::SystemServices::{
            CreateEventA, SetEvent, WaitForSingleObject, GetProcessHeap, HeapAlloc, HeapFree, GetProcAddress,
            LoadLibraryA, FreeLibrary, CO_E_NOTINITIALIZED, E_POINTER,
        },
    );

    let mut path = windows_gen::workspace_dir();
    path.push("src");
    path.push("bindings.rs");

    let mut file = std::fs::File::create(&path)?;
    file.write_all(
        "// This file was generated by the `windows` crate - do not edit by hand!\n\n".as_bytes(),
    )?;

    file.write_all(tokens.as_bytes())?;
    file.write_all(gen_crate_version_assert().as_bytes())?;
    drop(file);

    let mut cmd = ::std::process::Command::new("rustfmt");
    cmd.arg(&path);
    cmd.output()?;

    Ok(())
}

fn gen_crate_version_assert() -> String {
    format!(
        r#"
#[allow(dead_code)]
const CRATE_VERSION_EQUAL: () = {{
    const CURRENT_VERSION: &str = env!("CARGO_PKG_VERSION");
    const EXPECTED_VERSION: &str = "{}";
    if CURRENT_VERSION.len() != EXPECTED_VERSION.len() {{
        ["The current version of the crate does not match the version the bindings were generated against: {}."][100];
    }}
    let mut index = 0;
    while index < CURRENT_VERSION.len() {{
        if CURRENT_VERSION.as_bytes()[index] != EXPECTED_VERSION.as_bytes()[index] {{
            ["The current version of the crate does not match the version the bindings were generated against: {}."][100];
        }}
        index += 1;
    }}

    ()
}};
            "#,
        env!("CARGO_PKG_VERSION"),
        env!("CARGO_PKG_VERSION"),
        env!("CARGO_PKG_VERSION")
    )
}
