void __cdecl u_getBinaryPropertySet() {}
void __cdecl u_getIntPropertyMap() {}
void __cdecl ucal_getHostTimeZone() {}
void __cdecl ucfpos_close() {}
void __cdecl ucfpos_constrainCategory() {}
void __cdecl ucfpos_constrainField() {}
void __cdecl ucfpos_getCategory() {}
void __cdecl ucfpos_getField() {}
void __cdecl ucfpos_getIndexes() {}
void __cdecl ucfpos_getInt64IterationContext() {}
void __cdecl ucfpos_matchesField() {}
void __cdecl ucfpos_open() {}
void __cdecl ucfpos_reset() {}
void __cdecl ucfpos_setInt64IterationContext() {}
void __cdecl ucfpos_setState() {}
void __cdecl ucpmap_get() {}
void __cdecl ucpmap_getRange() {}
void __cdecl ucptrie_close() {}
void __cdecl ucptrie_get() {}
void __cdecl ucptrie_getRange() {}
void __cdecl ucptrie_getType() {}
void __cdecl ucptrie_getValueWidth() {}
void __cdecl ucptrie_internalSmallIndex() {}
void __cdecl ucptrie_internalSmallU8Index() {}
void __cdecl ucptrie_internalU8PrevIndex() {}
void __cdecl ucptrie_openFromBinary() {}
void __cdecl ucptrie_toBinary() {}
void __cdecl udatpg_getFieldDisplayName() {}
void __cdecl udtitvfmt_closeResult() {}
void __cdecl udtitvfmt_openResult() {}
void __cdecl udtitvfmt_resultAsValue() {}
void __cdecl ufmtval_getString() {}
void __cdecl ufmtval_nextPosition() {}
void __cdecl ulistfmt_closeResult() {}
void __cdecl ulistfmt_formatStringsToResult() {}
void __cdecl ulistfmt_openForType() {}
void __cdecl ulistfmt_openResult() {}
void __cdecl ulistfmt_resultAsValue() {}
void __cdecl uloc_openAvailableByType() {}
void __cdecl umutablecptrie_buildImmutable() {}
void __cdecl umutablecptrie_clone() {}
void __cdecl umutablecptrie_close() {}
void __cdecl umutablecptrie_fromUCPMap() {}
void __cdecl umutablecptrie_fromUCPTrie() {}
void __cdecl umutablecptrie_get() {}
void __cdecl umutablecptrie_getRange() {}
void __cdecl umutablecptrie_open() {}
void __cdecl umutablecptrie_set() {}
void __cdecl umutablecptrie_setRange() {}
void __cdecl unumf_close() {}
void __cdecl unumf_closeResult() {}
void __cdecl unumf_formatDecimal() {}
void __cdecl unumf_formatDouble() {}
void __cdecl unumf_formatInt() {}
void __cdecl unumf_openForSkeletonAndLocale() {}
void __cdecl unumf_openForSkeletonAndLocaleWithError() {}
void __cdecl unumf_openResult() {}
void __cdecl unumf_resultAsValue() {}
void __cdecl unumf_resultGetAllFieldPositions() {}
void __cdecl unumf_resultNextFieldPosition() {}
void __cdecl unumf_resultToString() {}
void __cdecl uplrules_selectFormatted() {}
void __cdecl ureldatefmt_closeResult() {}
void __cdecl ureldatefmt_formatNumericToResult() {}
void __cdecl ureldatefmt_formatToResult() {}
void __cdecl ureldatefmt_openResult() {}
void __cdecl ureldatefmt_resultAsValue() {}
