void __cdecl UCNV_FROM_U_CALLBACK_ESCAPE() {}
void __cdecl UCNV_FROM_U_CALLBACK_SKIP() {}
void __cdecl UCNV_FROM_U_CALLBACK_STOP() {}
void __cdecl UCNV_FROM_U_CALLBACK_SUBSTITUTE() {}
void __cdecl UCNV_TO_U_CALLBACK_ESCAPE() {}
void __cdecl UCNV_TO_U_CALLBACK_SKIP() {}
void __cdecl UCNV_TO_U_CALLBACK_STOP() {}
void __cdecl UCNV_TO_U_CALLBACK_SUBSTITUTE() {}
void __cdecl u_UCharsToChars() {}
void __cdecl u_austrcpy() {}
void __cdecl u_austrncpy() {}
void __cdecl u_catclose() {}
void __cdecl u_catgets() {}
void __cdecl u_catopen() {}
void __cdecl u_charAge() {}
void __cdecl u_charDigitValue() {}
void __cdecl u_charDirection() {}
void __cdecl u_charFromName() {}
void __cdecl u_charMirror() {}
void __cdecl u_charName() {}
void __cdecl u_charType() {}
void __cdecl u_charsToUChars() {}
void __cdecl u_cleanup() {}
void __cdecl u_countChar32() {}
void __cdecl u_digit() {}
void __cdecl u_enumCharNames() {}
void __cdecl u_enumCharTypes() {}
void __cdecl u_errorName() {}
void __cdecl u_foldCase() {}
void __cdecl u_forDigit() {}
void __cdecl u_formatMessage() {}
void __cdecl u_formatMessageWithError() {}
void __cdecl u_getBidiPairedBracket() {}
void __cdecl u_getBinaryPropertySet() {}
void __cdecl u_getCombiningClass() {}
void __cdecl u_getDataVersion() {}
void __cdecl u_getFC_NFKC_Closure() {}
void __cdecl u_getIntPropertyMap() {}
void __cdecl u_getIntPropertyMaxValue() {}
void __cdecl u_getIntPropertyMinValue() {}
void __cdecl u_getIntPropertyValue() {}
void __cdecl u_getNumericValue() {}
void __cdecl u_getPropertyEnum() {}
void __cdecl u_getPropertyName() {}
void __cdecl u_getPropertyValueEnum() {}
void __cdecl u_getPropertyValueName() {}
void __cdecl u_getUnicodeVersion() {}
void __cdecl u_getVersion() {}
void __cdecl u_hasBinaryProperty() {}
void __cdecl u_init() {}
void __cdecl u_isIDIgnorable() {}
void __cdecl u_isIDPart() {}
void __cdecl u_isIDStart() {}
void __cdecl u_isISOControl() {}
void __cdecl u_isJavaIDPart() {}
void __cdecl u_isJavaIDStart() {}
void __cdecl u_isJavaSpaceChar() {}
void __cdecl u_isMirrored() {}
void __cdecl u_isUAlphabetic() {}
void __cdecl u_isULowercase() {}
void __cdecl u_isUUppercase() {}
void __cdecl u_isUWhiteSpace() {}
void __cdecl u_isWhitespace() {}
void __cdecl u_isalnum() {}
void __cdecl u_isalpha() {}
void __cdecl u_isbase() {}
void __cdecl u_isblank() {}
void __cdecl u_iscntrl() {}
void __cdecl u_isdefined() {}
void __cdecl u_isdigit() {}
void __cdecl u_isgraph() {}
void __cdecl u_islower() {}
void __cdecl u_isprint() {}
void __cdecl u_ispunct() {}
void __cdecl u_isspace() {}
void __cdecl u_istitle() {}
void __cdecl u_isupper() {}
void __cdecl u_isxdigit() {}
void __cdecl u_memcasecmp() {}
void __cdecl u_memchr() {}
void __cdecl u_memchr32() {}
void __cdecl u_memcmp() {}
void __cdecl u_memcmpCodePointOrder() {}
void __cdecl u_memcpy() {}
void __cdecl u_memmove() {}
void __cdecl u_memrchr() {}
void __cdecl u_memrchr32() {}
void __cdecl u_memset() {}
void __cdecl u_parseMessage() {}
void __cdecl u_parseMessageWithError() {}
void __cdecl u_setMemoryFunctions() {}
void __cdecl u_shapeArabic() {}
void __cdecl u_strCaseCompare() {}
void __cdecl u_strCompare() {}
void __cdecl u_strCompareIter() {}
void __cdecl u_strFindFirst() {}
void __cdecl u_strFindLast() {}
void __cdecl u_strFoldCase() {}
void __cdecl u_strFromJavaModifiedUTF8WithSub() {}
void __cdecl u_strFromUTF32() {}
void __cdecl u_strFromUTF32WithSub() {}
void __cdecl u_strFromUTF8() {}
void __cdecl u_strFromUTF8Lenient() {}
void __cdecl u_strFromUTF8WithSub() {}
void __cdecl u_strFromWCS() {}
void __cdecl u_strHasMoreChar32Than() {}
void __cdecl u_strToJavaModifiedUTF8() {}
void __cdecl u_strToLower() {}
void __cdecl u_strToTitle() {}
void __cdecl u_strToUTF32() {}
void __cdecl u_strToUTF32WithSub() {}
void __cdecl u_strToUTF8() {}
void __cdecl u_strToUTF8WithSub() {}
void __cdecl u_strToUpper() {}
void __cdecl u_strToWCS() {}
void __cdecl u_strcasecmp() {}
void __cdecl u_strcat() {}
void __cdecl u_strchr() {}
void __cdecl u_strchr32() {}
void __cdecl u_strcmp() {}
void __cdecl u_strcmpCodePointOrder() {}
void __cdecl u_strcpy() {}
void __cdecl u_strcspn() {}
void __cdecl u_strlen() {}
void __cdecl u_strncasecmp() {}
void __cdecl u_strncat() {}
void __cdecl u_strncmp() {}
void __cdecl u_strncmpCodePointOrder() {}
void __cdecl u_strncpy() {}
void __cdecl u_strpbrk() {}
void __cdecl u_strrchr() {}
void __cdecl u_strrchr32() {}
void __cdecl u_strrstr() {}
void __cdecl u_strspn() {}
void __cdecl u_strstr() {}
void __cdecl u_strtok_r() {}
void __cdecl u_tolower() {}
void __cdecl u_totitle() {}
void __cdecl u_toupper() {}
void __cdecl u_uastrcpy() {}
void __cdecl u_uastrncpy() {}
void __cdecl u_unescape() {}
void __cdecl u_unescapeAt() {}
void __cdecl u_versionFromString() {}
void __cdecl u_versionFromUString() {}
void __cdecl u_versionToString() {}
void __cdecl u_vformatMessage() {}
void __cdecl u_vformatMessageWithError() {}
void __cdecl u_vparseMessage() {}
void __cdecl u_vparseMessageWithError() {}
void __cdecl ubidi_close() {}
void __cdecl ubidi_countParagraphs() {}
void __cdecl ubidi_countRuns() {}
void __cdecl ubidi_getBaseDirection() {}
void __cdecl ubidi_getClassCallback() {}
void __cdecl ubidi_getCustomizedClass() {}
void __cdecl ubidi_getDirection() {}
void __cdecl ubidi_getLength() {}
void __cdecl ubidi_getLevelAt() {}
void __cdecl ubidi_getLevels() {}
void __cdecl ubidi_getLogicalIndex() {}
void __cdecl ubidi_getLogicalMap() {}
void __cdecl ubidi_getLogicalRun() {}
void __cdecl ubidi_getParaLevel() {}
void __cdecl ubidi_getParagraph() {}
void __cdecl ubidi_getParagraphByIndex() {}
void __cdecl ubidi_getProcessedLength() {}
void __cdecl ubidi_getReorderingMode() {}
void __cdecl ubidi_getReorderingOptions() {}
void __cdecl ubidi_getResultLength() {}
void __cdecl ubidi_getText() {}
void __cdecl ubidi_getVisualIndex() {}
void __cdecl ubidi_getVisualMap() {}
void __cdecl ubidi_getVisualRun() {}
void __cdecl ubidi_invertMap() {}
void __cdecl ubidi_isInverse() {}
void __cdecl ubidi_isOrderParagraphsLTR() {}
void __cdecl ubidi_open() {}
void __cdecl ubidi_openSized() {}
void __cdecl ubidi_orderParagraphsLTR() {}
void __cdecl ubidi_reorderLogical() {}
void __cdecl ubidi_reorderVisual() {}
void __cdecl ubidi_setClassCallback() {}
void __cdecl ubidi_setContext() {}
void __cdecl ubidi_setInverse() {}
void __cdecl ubidi_setLine() {}
void __cdecl ubidi_setPara() {}
void __cdecl ubidi_setReorderingMode() {}
void __cdecl ubidi_setReorderingOptions() {}
void __cdecl ubidi_writeReordered() {}
void __cdecl ubidi_writeReverse() {}
void __cdecl ubiditransform_close() {}
void __cdecl ubiditransform_open() {}
void __cdecl ubiditransform_transform() {}
void __cdecl ublock_getCode() {}
void __cdecl ubrk_close() {}
void __cdecl ubrk_countAvailable() {}
void __cdecl ubrk_current() {}
void __cdecl ubrk_first() {}
void __cdecl ubrk_following() {}
void __cdecl ubrk_getAvailable() {}
void __cdecl ubrk_getBinaryRules() {}
void __cdecl ubrk_getLocaleByType() {}
void __cdecl ubrk_getRuleStatus() {}
void __cdecl ubrk_getRuleStatusVec() {}
void __cdecl ubrk_isBoundary() {}
void __cdecl ubrk_last() {}
void __cdecl ubrk_next() {}
void __cdecl ubrk_open() {}
void __cdecl ubrk_openBinaryRules() {}
void __cdecl ubrk_openRules() {}
void __cdecl ubrk_preceding() {}
void __cdecl ubrk_previous() {}
void __cdecl ubrk_refreshUText() {}
void __cdecl ubrk_safeClone() {}
void __cdecl ubrk_setText() {}
void __cdecl ubrk_setUText() {}
void __cdecl ucal_add() {}
void __cdecl ucal_clear() {}
void __cdecl ucal_clearField() {}
void __cdecl ucal_clone() {}
void __cdecl ucal_close() {}
void __cdecl ucal_countAvailable() {}
void __cdecl ucal_equivalentTo() {}
void __cdecl ucal_get() {}
void __cdecl ucal_getAttribute() {}
void __cdecl ucal_getAvailable() {}
void __cdecl ucal_getCanonicalTimeZoneID() {}
void __cdecl ucal_getDSTSavings() {}
void __cdecl ucal_getDayOfWeekType() {}
void __cdecl ucal_getDefaultTimeZone() {}
void __cdecl ucal_getFieldDifference() {}
void __cdecl ucal_getGregorianChange() {}
void __cdecl ucal_getHostTimeZone() {}
void __cdecl ucal_getKeywordValuesForLocale() {}
void __cdecl ucal_getLimit() {}
void __cdecl ucal_getLocaleByType() {}
void __cdecl ucal_getMillis() {}
void __cdecl ucal_getNow() {}
void __cdecl ucal_getTZDataVersion() {}
void __cdecl ucal_getTimeZoneDisplayName() {}
void __cdecl ucal_getTimeZoneID() {}
void __cdecl ucal_getTimeZoneIDForWindowsID() {}
void __cdecl ucal_getTimeZoneTransitionDate() {}
void __cdecl ucal_getType() {}
void __cdecl ucal_getWeekendTransition() {}
void __cdecl ucal_getWindowsTimeZoneID() {}
void __cdecl ucal_inDaylightTime() {}
void __cdecl ucal_isSet() {}
void __cdecl ucal_isWeekend() {}
void __cdecl ucal_open() {}
void __cdecl ucal_openCountryTimeZones() {}
void __cdecl ucal_openTimeZoneIDEnumeration() {}
void __cdecl ucal_openTimeZones() {}
void __cdecl ucal_roll() {}
void __cdecl ucal_set() {}
void __cdecl ucal_setAttribute() {}
void __cdecl ucal_setDate() {}
void __cdecl ucal_setDateTime() {}
void __cdecl ucal_setDefaultTimeZone() {}
void __cdecl ucal_setGregorianChange() {}
void __cdecl ucal_setMillis() {}
void __cdecl ucal_setTimeZone() {}
void __cdecl ucasemap_close() {}
void __cdecl ucasemap_getBreakIterator() {}
void __cdecl ucasemap_getLocale() {}
void __cdecl ucasemap_getOptions() {}
void __cdecl ucasemap_open() {}
void __cdecl ucasemap_setBreakIterator() {}
void __cdecl ucasemap_setLocale() {}
void __cdecl ucasemap_setOptions() {}
void __cdecl ucasemap_toTitle() {}
void __cdecl ucasemap_utf8FoldCase() {}
void __cdecl ucasemap_utf8ToLower() {}
void __cdecl ucasemap_utf8ToTitle() {}
void __cdecl ucasemap_utf8ToUpper() {}
void __cdecl ucfpos_close() {}
void __cdecl ucfpos_constrainCategory() {}
void __cdecl ucfpos_constrainField() {}
void __cdecl ucfpos_getCategory() {}
void __cdecl ucfpos_getField() {}
void __cdecl ucfpos_getIndexes() {}
void __cdecl ucfpos_getInt64IterationContext() {}
void __cdecl ucfpos_matchesField() {}
void __cdecl ucfpos_open() {}
void __cdecl ucfpos_reset() {}
void __cdecl ucfpos_setInt64IterationContext() {}
void __cdecl ucfpos_setState() {}
void __cdecl ucnv_cbFromUWriteBytes() {}
void __cdecl ucnv_cbFromUWriteSub() {}
void __cdecl ucnv_cbFromUWriteUChars() {}
void __cdecl ucnv_cbToUWriteSub() {}
void __cdecl ucnv_cbToUWriteUChars() {}
void __cdecl ucnv_close() {}
void __cdecl ucnv_compareNames() {}
void __cdecl ucnv_convert() {}
void __cdecl ucnv_convertEx() {}
void __cdecl ucnv_countAliases() {}
void __cdecl ucnv_countAvailable() {}
void __cdecl ucnv_countStandards() {}
void __cdecl ucnv_detectUnicodeSignature() {}
void __cdecl ucnv_fixFileSeparator() {}
void __cdecl ucnv_flushCache() {}
void __cdecl ucnv_fromAlgorithmic() {}
void __cdecl ucnv_fromUChars() {}
void __cdecl ucnv_fromUCountPending() {}
void __cdecl ucnv_fromUnicode() {}
void __cdecl ucnv_getAlias() {}
void __cdecl ucnv_getAliases() {}
void __cdecl ucnv_getAvailableName() {}
void __cdecl ucnv_getCCSID() {}
void __cdecl ucnv_getCanonicalName() {}
void __cdecl ucnv_getDefaultName() {}
void __cdecl ucnv_getDisplayName() {}
void __cdecl ucnv_getFromUCallBack() {}
void __cdecl ucnv_getInvalidChars() {}
void __cdecl ucnv_getInvalidUChars() {}
void __cdecl ucnv_getMaxCharSize() {}
void __cdecl ucnv_getMinCharSize() {}
void __cdecl ucnv_getName() {}
void __cdecl ucnv_getNextUChar() {}
void __cdecl ucnv_getPlatform() {}
void __cdecl ucnv_getStandard() {}
void __cdecl ucnv_getStandardName() {}
void __cdecl ucnv_getStarters() {}
void __cdecl ucnv_getSubstChars() {}
void __cdecl ucnv_getToUCallBack() {}
void __cdecl ucnv_getType() {}
void __cdecl ucnv_getUnicodeSet() {}
void __cdecl ucnv_isAmbiguous() {}
void __cdecl ucnv_isFixedWidth() {}
void __cdecl ucnv_open() {}
void __cdecl ucnv_openAllNames() {}
void __cdecl ucnv_openCCSID() {}
void __cdecl ucnv_openPackage() {}
void __cdecl ucnv_openStandardNames() {}
void __cdecl ucnv_openU() {}
void __cdecl ucnv_reset() {}
void __cdecl ucnv_resetFromUnicode() {}
void __cdecl ucnv_resetToUnicode() {}
void __cdecl ucnv_safeClone() {}
void __cdecl ucnv_setDefaultName() {}
void __cdecl ucnv_setFallback() {}
void __cdecl ucnv_setFromUCallBack() {}
void __cdecl ucnv_setSubstChars() {}
void __cdecl ucnv_setSubstString() {}
void __cdecl ucnv_setToUCallBack() {}
void __cdecl ucnv_toAlgorithmic() {}
void __cdecl ucnv_toUChars() {}
void __cdecl ucnv_toUCountPending() {}
void __cdecl ucnv_toUnicode() {}
void __cdecl ucnv_usesFallback() {}
void __cdecl ucnvsel_close() {}
void __cdecl ucnvsel_open() {}
void __cdecl ucnvsel_openFromSerialized() {}
void __cdecl ucnvsel_selectForString() {}
void __cdecl ucnvsel_selectForUTF8() {}
void __cdecl ucnvsel_serialize() {}
void __cdecl ucol_cloneBinary() {}
void __cdecl ucol_close() {}
void __cdecl ucol_closeElements() {}
void __cdecl ucol_countAvailable() {}
void __cdecl ucol_equal() {}
void __cdecl ucol_getAttribute() {}
void __cdecl ucol_getAvailable() {}
void __cdecl ucol_getBound() {}
void __cdecl ucol_getContractionsAndExpansions() {}
void __cdecl ucol_getDisplayName() {}
void __cdecl ucol_getEquivalentReorderCodes() {}
void __cdecl ucol_getFunctionalEquivalent() {}
void __cdecl ucol_getKeywordValues() {}
void __cdecl ucol_getKeywordValuesForLocale() {}
void __cdecl ucol_getKeywords() {}
void __cdecl ucol_getLocaleByType() {}
void __cdecl ucol_getMaxExpansion() {}
void __cdecl ucol_getMaxVariable() {}
void __cdecl ucol_getOffset() {}
void __cdecl ucol_getReorderCodes() {}
void __cdecl ucol_getRules() {}
void __cdecl ucol_getRulesEx() {}
void __cdecl ucol_getSortKey() {}
void __cdecl ucol_getStrength() {}
void __cdecl ucol_getTailoredSet() {}
void __cdecl ucol_getUCAVersion() {}
void __cdecl ucol_getVariableTop() {}
void __cdecl ucol_getVersion() {}
void __cdecl ucol_greater() {}
void __cdecl ucol_greaterOrEqual() {}
void __cdecl ucol_keyHashCode() {}
void __cdecl ucol_mergeSortkeys() {}
void __cdecl ucol_next() {}
void __cdecl ucol_nextSortKeyPart() {}
void __cdecl ucol_open() {}
void __cdecl ucol_openAvailableLocales() {}
void __cdecl ucol_openBinary() {}
void __cdecl ucol_openElements() {}
void __cdecl ucol_openRules() {}
void __cdecl ucol_previous() {}
void __cdecl ucol_primaryOrder() {}
void __cdecl ucol_reset() {}
void __cdecl ucol_safeClone() {}
void __cdecl ucol_secondaryOrder() {}
void __cdecl ucol_setAttribute() {}
void __cdecl ucol_setMaxVariable() {}
void __cdecl ucol_setOffset() {}
void __cdecl ucol_setReorderCodes() {}
void __cdecl ucol_setStrength() {}
void __cdecl ucol_setText() {}
void __cdecl ucol_strcoll() {}
void __cdecl ucol_strcollIter() {}
void __cdecl ucol_strcollUTF8() {}
void __cdecl ucol_tertiaryOrder() {}
void __cdecl ucpmap_get() {}
void __cdecl ucpmap_getRange() {}
void __cdecl ucptrie_close() {}
void __cdecl ucptrie_get() {}
void __cdecl ucptrie_getRange() {}
void __cdecl ucptrie_getType() {}
void __cdecl ucptrie_getValueWidth() {}
void __cdecl ucptrie_internalSmallIndex() {}
void __cdecl ucptrie_internalSmallU8Index() {}
void __cdecl ucptrie_internalU8PrevIndex() {}
void __cdecl ucptrie_openFromBinary() {}
void __cdecl ucptrie_toBinary() {}
void __cdecl ucsdet_close() {}
void __cdecl ucsdet_detect() {}
void __cdecl ucsdet_detectAll() {}
void __cdecl ucsdet_enableInputFilter() {}
void __cdecl ucsdet_getAllDetectableCharsets() {}
void __cdecl ucsdet_getConfidence() {}
void __cdecl ucsdet_getLanguage() {}
void __cdecl ucsdet_getName() {}
void __cdecl ucsdet_getUChars() {}
void __cdecl ucsdet_isInputFilterEnabled() {}
void __cdecl ucsdet_open() {}
void __cdecl ucsdet_setDeclaredEncoding() {}
void __cdecl ucsdet_setText() {}
void __cdecl ucurr_countCurrencies() {}
void __cdecl ucurr_forLocale() {}
void __cdecl ucurr_forLocaleAndDate() {}
void __cdecl ucurr_getDefaultFractionDigits() {}
void __cdecl ucurr_getDefaultFractionDigitsForUsage() {}
void __cdecl ucurr_getKeywordValuesForLocale() {}
void __cdecl ucurr_getName() {}
void __cdecl ucurr_getNumericCode() {}
void __cdecl ucurr_getPluralName() {}
void __cdecl ucurr_getRoundingIncrement() {}
void __cdecl ucurr_getRoundingIncrementForUsage() {}
void __cdecl ucurr_isAvailable() {}
void __cdecl ucurr_openISOCurrencies() {}
void __cdecl ucurr_register() {}
void __cdecl ucurr_unregister() {}
void __cdecl udat_adoptNumberFormat() {}
void __cdecl udat_adoptNumberFormatForFields() {}
void __cdecl udat_applyPattern() {}
void __cdecl udat_clone() {}
void __cdecl udat_close() {}
void __cdecl udat_countAvailable() {}
void __cdecl udat_countSymbols() {}
void __cdecl udat_format() {}
void __cdecl udat_formatCalendar() {}
void __cdecl udat_formatCalendarForFields() {}
void __cdecl udat_formatForFields() {}
void __cdecl udat_get2DigitYearStart() {}
void __cdecl udat_getAvailable() {}
void __cdecl udat_getBooleanAttribute() {}
void __cdecl udat_getCalendar() {}
void __cdecl udat_getContext() {}
void __cdecl udat_getLocaleByType() {}
void __cdecl udat_getNumberFormat() {}
void __cdecl udat_getNumberFormatForField() {}
void __cdecl udat_getSymbols() {}
void __cdecl udat_isLenient() {}
void __cdecl udat_open() {}
void __cdecl udat_parse() {}
void __cdecl udat_parseCalendar() {}
void __cdecl udat_set2DigitYearStart() {}
void __cdecl udat_setBooleanAttribute() {}
void __cdecl udat_setCalendar() {}
void __cdecl udat_setContext() {}
void __cdecl udat_setLenient() {}
void __cdecl udat_setNumberFormat() {}
void __cdecl udat_setSymbols() {}
void __cdecl udat_toCalendarDateField() {}
void __cdecl udat_toPattern() {}
void __cdecl udatpg_addPattern() {}
void __cdecl udatpg_clone() {}
void __cdecl udatpg_close() {}
void __cdecl udatpg_getAppendItemFormat() {}
void __cdecl udatpg_getAppendItemName() {}
void __cdecl udatpg_getBaseSkeleton() {}
void __cdecl udatpg_getBestPattern() {}
void __cdecl udatpg_getBestPatternWithOptions() {}
void __cdecl udatpg_getDateTimeFormat() {}
void __cdecl udatpg_getDecimal() {}
void __cdecl udatpg_getFieldDisplayName() {}
void __cdecl udatpg_getPatternForSkeleton() {}
void __cdecl udatpg_getSkeleton() {}
void __cdecl udatpg_open() {}
void __cdecl udatpg_openBaseSkeletons() {}
void __cdecl udatpg_openEmpty() {}
void __cdecl udatpg_openSkeletons() {}
void __cdecl udatpg_replaceFieldTypes() {}
void __cdecl udatpg_replaceFieldTypesWithOptions() {}
void __cdecl udatpg_setAppendItemFormat() {}
void __cdecl udatpg_setAppendItemName() {}
void __cdecl udatpg_setDateTimeFormat() {}
void __cdecl udatpg_setDecimal() {}
void __cdecl udtitvfmt_close() {}
void __cdecl udtitvfmt_closeResult() {}
void __cdecl udtitvfmt_format() {}
void __cdecl udtitvfmt_open() {}
void __cdecl udtitvfmt_openResult() {}
void __cdecl udtitvfmt_resultAsValue() {}
void __cdecl uenum_close() {}
void __cdecl uenum_count() {}
void __cdecl uenum_next() {}
void __cdecl uenum_openCharStringsEnumeration() {}
void __cdecl uenum_openUCharStringsEnumeration() {}
void __cdecl uenum_reset() {}
void __cdecl uenum_unext() {}
void __cdecl ufieldpositer_close() {}
void __cdecl ufieldpositer_next() {}
void __cdecl ufieldpositer_open() {}
void __cdecl ufmt_close() {}
void __cdecl ufmt_getArrayItemByIndex() {}
void __cdecl ufmt_getArrayLength() {}
void __cdecl ufmt_getDate() {}
void __cdecl ufmt_getDecNumChars() {}
void __cdecl ufmt_getDouble() {}
void __cdecl ufmt_getInt64() {}
void __cdecl ufmt_getLong() {}
void __cdecl ufmt_getObject() {}
void __cdecl ufmt_getType() {}
void __cdecl ufmt_getUChars() {}
void __cdecl ufmt_isNumeric() {}
void __cdecl ufmt_open() {}
void __cdecl ufmtval_getString() {}
void __cdecl ufmtval_nextPosition() {}
void __cdecl ugender_getInstance() {}
void __cdecl ugender_getListGender() {}
void __cdecl uidna_close() {}
void __cdecl uidna_labelToASCII() {}
void __cdecl uidna_labelToASCII_UTF8() {}
void __cdecl uidna_labelToUnicode() {}
void __cdecl uidna_labelToUnicodeUTF8() {}
void __cdecl uidna_nameToASCII() {}
void __cdecl uidna_nameToASCII_UTF8() {}
void __cdecl uidna_nameToUnicode() {}
void __cdecl uidna_nameToUnicodeUTF8() {}
void __cdecl uidna_openUTS46() {}
void __cdecl uiter_current32() {}
void __cdecl uiter_getState() {}
void __cdecl uiter_next32() {}
void __cdecl uiter_previous32() {}
void __cdecl uiter_setState() {}
void __cdecl uiter_setString() {}
void __cdecl uiter_setUTF16BE() {}
void __cdecl uiter_setUTF8() {}
void __cdecl uldn_close() {}
void __cdecl uldn_getContext() {}
void __cdecl uldn_getDialectHandling() {}
void __cdecl uldn_getLocale() {}
void __cdecl uldn_keyDisplayName() {}
void __cdecl uldn_keyValueDisplayName() {}
void __cdecl uldn_languageDisplayName() {}
void __cdecl uldn_localeDisplayName() {}
void __cdecl uldn_open() {}
void __cdecl uldn_openForContext() {}
void __cdecl uldn_regionDisplayName() {}
void __cdecl uldn_scriptCodeDisplayName() {}
void __cdecl uldn_scriptDisplayName() {}
void __cdecl uldn_variantDisplayName() {}
void __cdecl ulistfmt_close() {}
void __cdecl ulistfmt_closeResult() {}
void __cdecl ulistfmt_format() {}
void __cdecl ulistfmt_formatStringsToResult() {}
void __cdecl ulistfmt_open() {}
void __cdecl ulistfmt_openForType() {}
void __cdecl ulistfmt_openResult() {}
void __cdecl ulistfmt_resultAsValue() {}
void __cdecl uloc_acceptLanguage() {}
void __cdecl uloc_acceptLanguageFromHTTP() {}
void __cdecl uloc_addLikelySubtags() {}
void __cdecl uloc_canonicalize() {}
void __cdecl uloc_countAvailable() {}
void __cdecl uloc_forLanguageTag() {}
void __cdecl uloc_getAvailable() {}
void __cdecl uloc_getBaseName() {}
void __cdecl uloc_getCharacterOrientation() {}
void __cdecl uloc_getCountry() {}
void __cdecl uloc_getDefault() {}
void __cdecl uloc_getDisplayCountry() {}
void __cdecl uloc_getDisplayKeyword() {}
void __cdecl uloc_getDisplayKeywordValue() {}
void __cdecl uloc_getDisplayLanguage() {}
void __cdecl uloc_getDisplayName() {}
void __cdecl uloc_getDisplayScript() {}
void __cdecl uloc_getDisplayVariant() {}
void __cdecl uloc_getISO3Country() {}
void __cdecl uloc_getISO3Language() {}
void __cdecl uloc_getISOCountries() {}
void __cdecl uloc_getISOLanguages() {}
void __cdecl uloc_getKeywordValue() {}
void __cdecl uloc_getLCID() {}
void __cdecl uloc_getLanguage() {}
void __cdecl uloc_getLineOrientation() {}
void __cdecl uloc_getLocaleForLCID() {}
void __cdecl uloc_getName() {}
void __cdecl uloc_getParent() {}
void __cdecl uloc_getScript() {}
void __cdecl uloc_getVariant() {}
void __cdecl uloc_isRightToLeft() {}
void __cdecl uloc_minimizeSubtags() {}
void __cdecl uloc_openAvailableByType() {}
void __cdecl uloc_openKeywords() {}
void __cdecl uloc_setDefault() {}
void __cdecl uloc_setKeywordValue() {}
void __cdecl uloc_toLanguageTag() {}
void __cdecl uloc_toLegacyKey() {}
void __cdecl uloc_toLegacyType() {}
void __cdecl uloc_toUnicodeLocaleKey() {}
void __cdecl uloc_toUnicodeLocaleType() {}
void __cdecl ulocdata_close() {}
void __cdecl ulocdata_getCLDRVersion() {}
void __cdecl ulocdata_getDelimiter() {}
void __cdecl ulocdata_getExemplarSet() {}
void __cdecl ulocdata_getLocaleDisplayPattern() {}
void __cdecl ulocdata_getLocaleSeparator() {}
void __cdecl ulocdata_getMeasurementSystem() {}
void __cdecl ulocdata_getNoSubstitute() {}
void __cdecl ulocdata_getPaperSize() {}
void __cdecl ulocdata_open() {}
void __cdecl ulocdata_setNoSubstitute() {}
void __cdecl umsg_applyPattern() {}
void __cdecl umsg_autoQuoteApostrophe() {}
void __cdecl umsg_clone() {}
void __cdecl umsg_close() {}
void __cdecl umsg_format() {}
void __cdecl umsg_getLocale() {}
void __cdecl umsg_open() {}
void __cdecl umsg_parse() {}
void __cdecl umsg_setLocale() {}
void __cdecl umsg_toPattern() {}
void __cdecl umsg_vformat() {}
void __cdecl umsg_vparse() {}
void __cdecl umutablecptrie_buildImmutable() {}
void __cdecl umutablecptrie_clone() {}
void __cdecl umutablecptrie_close() {}
void __cdecl umutablecptrie_fromUCPMap() {}
void __cdecl umutablecptrie_fromUCPTrie() {}
void __cdecl umutablecptrie_get() {}
void __cdecl umutablecptrie_getRange() {}
void __cdecl umutablecptrie_open() {}
void __cdecl umutablecptrie_set() {}
void __cdecl umutablecptrie_setRange() {}
void __cdecl unorm2_append() {}
void __cdecl unorm2_close() {}
void __cdecl unorm2_composePair() {}
void __cdecl unorm2_getCombiningClass() {}
void __cdecl unorm2_getDecomposition() {}
void __cdecl unorm2_getInstance() {}
void __cdecl unorm2_getNFCInstance() {}
void __cdecl unorm2_getNFDInstance() {}
void __cdecl unorm2_getNFKCCasefoldInstance() {}
void __cdecl unorm2_getNFKCInstance() {}
void __cdecl unorm2_getNFKDInstance() {}
void __cdecl unorm2_getRawDecomposition() {}
void __cdecl unorm2_hasBoundaryAfter() {}
void __cdecl unorm2_hasBoundaryBefore() {}
void __cdecl unorm2_isInert() {}
void __cdecl unorm2_isNormalized() {}
void __cdecl unorm2_normalize() {}
void __cdecl unorm2_normalizeSecondAndAppend() {}
void __cdecl unorm2_openFiltered() {}
void __cdecl unorm2_quickCheck() {}
void __cdecl unorm2_spanQuickCheckYes() {}
void __cdecl unorm_compare() {}
void __cdecl unum_applyPattern() {}
void __cdecl unum_clone() {}
void __cdecl unum_close() {}
void __cdecl unum_countAvailable() {}
void __cdecl unum_format() {}
void __cdecl unum_formatDecimal() {}
void __cdecl unum_formatDouble() {}
void __cdecl unum_formatDoubleCurrency() {}
void __cdecl unum_formatDoubleForFields() {}
void __cdecl unum_formatInt64() {}
void __cdecl unum_formatUFormattable() {}
void __cdecl unum_getAttribute() {}
void __cdecl unum_getAvailable() {}
void __cdecl unum_getContext() {}
void __cdecl unum_getDoubleAttribute() {}
void __cdecl unum_getLocaleByType() {}
void __cdecl unum_getSymbol() {}
void __cdecl unum_getTextAttribute() {}
void __cdecl unum_open() {}
void __cdecl unum_parse() {}
void __cdecl unum_parseDecimal() {}
void __cdecl unum_parseDouble() {}
void __cdecl unum_parseDoubleCurrency() {}
void __cdecl unum_parseInt64() {}
void __cdecl unum_parseToUFormattable() {}
void __cdecl unum_setAttribute() {}
void __cdecl unum_setContext() {}
void __cdecl unum_setDoubleAttribute() {}
void __cdecl unum_setSymbol() {}
void __cdecl unum_setTextAttribute() {}
void __cdecl unum_toPattern() {}
void __cdecl unumf_close() {}
void __cdecl unumf_closeResult() {}
void __cdecl unumf_formatDecimal() {}
void __cdecl unumf_formatDouble() {}
void __cdecl unumf_formatInt() {}
void __cdecl unumf_openForSkeletonAndLocale() {}
void __cdecl unumf_openForSkeletonAndLocaleWithError() {}
void __cdecl unumf_openResult() {}
void __cdecl unumf_resultAsValue() {}
void __cdecl unumf_resultGetAllFieldPositions() {}
void __cdecl unumf_resultNextFieldPosition() {}
void __cdecl unumf_resultToString() {}
void __cdecl unumsys_close() {}
void __cdecl unumsys_getDescription() {}
void __cdecl unumsys_getName() {}
void __cdecl unumsys_getRadix() {}
void __cdecl unumsys_isAlgorithmic() {}
void __cdecl unumsys_open() {}
void __cdecl unumsys_openAvailableNames() {}
void __cdecl unumsys_openByName() {}
void __cdecl uplrules_close() {}
void __cdecl uplrules_getKeywords() {}
void __cdecl uplrules_open() {}
void __cdecl uplrules_openForType() {}
void __cdecl uplrules_select() {}
void __cdecl uplrules_selectFormatted() {}
void __cdecl uregex_appendReplacement() {}
void __cdecl uregex_appendReplacementUText() {}
void __cdecl uregex_appendTail() {}
void __cdecl uregex_appendTailUText() {}
void __cdecl uregex_clone() {}
void __cdecl uregex_close() {}
void __cdecl uregex_end() {}
void __cdecl uregex_end64() {}
void __cdecl uregex_find() {}
void __cdecl uregex_find64() {}
void __cdecl uregex_findNext() {}
void __cdecl uregex_flags() {}
void __cdecl uregex_getFindProgressCallback() {}
void __cdecl uregex_getMatchCallback() {}
void __cdecl uregex_getStackLimit() {}
void __cdecl uregex_getText() {}
void __cdecl uregex_getTimeLimit() {}
void __cdecl uregex_getUText() {}
void __cdecl uregex_group() {}
void __cdecl uregex_groupCount() {}
void __cdecl uregex_groupNumberFromCName() {}
void __cdecl uregex_groupNumberFromName() {}
void __cdecl uregex_groupUText() {}
void __cdecl uregex_hasAnchoringBounds() {}
void __cdecl uregex_hasTransparentBounds() {}
void __cdecl uregex_hitEnd() {}
void __cdecl uregex_lookingAt() {}
void __cdecl uregex_lookingAt64() {}
void __cdecl uregex_matches() {}
void __cdecl uregex_matches64() {}
void __cdecl uregex_open() {}
void __cdecl uregex_openC() {}
void __cdecl uregex_openUText() {}
void __cdecl uregex_pattern() {}
void __cdecl uregex_patternUText() {}
void __cdecl uregex_refreshUText() {}
void __cdecl uregex_regionEnd() {}
void __cdecl uregex_regionEnd64() {}
void __cdecl uregex_regionStart() {}
void __cdecl uregex_regionStart64() {}
void __cdecl uregex_replaceAll() {}
void __cdecl uregex_replaceAllUText() {}
void __cdecl uregex_replaceFirst() {}
void __cdecl uregex_replaceFirstUText() {}
void __cdecl uregex_requireEnd() {}
void __cdecl uregex_reset() {}
void __cdecl uregex_reset64() {}
void __cdecl uregex_setFindProgressCallback() {}
void __cdecl uregex_setMatchCallback() {}
void __cdecl uregex_setRegion() {}
void __cdecl uregex_setRegion64() {}
void __cdecl uregex_setRegionAndStart() {}
void __cdecl uregex_setStackLimit() {}
void __cdecl uregex_setText() {}
void __cdecl uregex_setTimeLimit() {}
void __cdecl uregex_setUText() {}
void __cdecl uregex_split() {}
void __cdecl uregex_splitUText() {}
void __cdecl uregex_start() {}
void __cdecl uregex_start64() {}
void __cdecl uregex_useAnchoringBounds() {}
void __cdecl uregex_useTransparentBounds() {}
void __cdecl uregion_areEqual() {}
void __cdecl uregion_contains() {}
void __cdecl uregion_getAvailable() {}
void __cdecl uregion_getContainedRegions() {}
void __cdecl uregion_getContainedRegionsOfType() {}
void __cdecl uregion_getContainingRegion() {}
void __cdecl uregion_getContainingRegionOfType() {}
void __cdecl uregion_getNumericCode() {}
void __cdecl uregion_getPreferredValues() {}
void __cdecl uregion_getRegionCode() {}
void __cdecl uregion_getRegionFromCode() {}
void __cdecl uregion_getRegionFromNumericCode() {}
void __cdecl uregion_getType() {}
void __cdecl ureldatefmt_close() {}
void __cdecl ureldatefmt_closeResult() {}
void __cdecl ureldatefmt_combineDateAndTime() {}
void __cdecl ureldatefmt_format() {}
void __cdecl ureldatefmt_formatNumeric() {}
void __cdecl ureldatefmt_formatNumericToResult() {}
void __cdecl ureldatefmt_formatToResult() {}
void __cdecl ureldatefmt_open() {}
void __cdecl ureldatefmt_openResult() {}
void __cdecl ureldatefmt_resultAsValue() {}
void __cdecl ures_close() {}
void __cdecl ures_getBinary() {}
void __cdecl ures_getByIndex() {}
void __cdecl ures_getByKey() {}
void __cdecl ures_getInt() {}
void __cdecl ures_getIntVector() {}
void __cdecl ures_getKey() {}
void __cdecl ures_getLocaleByType() {}
void __cdecl ures_getNextResource() {}
void __cdecl ures_getNextString() {}
void __cdecl ures_getSize() {}
void __cdecl ures_getString() {}
void __cdecl ures_getStringByIndex() {}
void __cdecl ures_getStringByKey() {}
void __cdecl ures_getType() {}
void __cdecl ures_getUInt() {}
void __cdecl ures_getUTF8String() {}
void __cdecl ures_getUTF8StringByIndex() {}
void __cdecl ures_getUTF8StringByKey() {}
void __cdecl ures_getVersion() {}
void __cdecl ures_hasNext() {}
void __cdecl ures_open() {}
void __cdecl ures_openAvailableLocales() {}
void __cdecl ures_openDirect() {}
void __cdecl ures_openU() {}
void __cdecl ures_resetIterator() {}
void __cdecl uscript_breaksBetweenLetters() {}
void __cdecl uscript_getCode() {}
void __cdecl uscript_getName() {}
void __cdecl uscript_getSampleString() {}
void __cdecl uscript_getScript() {}
void __cdecl uscript_getScriptExtensions() {}
void __cdecl uscript_getShortName() {}
void __cdecl uscript_getUsage() {}
void __cdecl uscript_hasScript() {}
void __cdecl uscript_isCased() {}
void __cdecl uscript_isRightToLeft() {}
void __cdecl usearch_close() {}
void __cdecl usearch_first() {}
void __cdecl usearch_following() {}
void __cdecl usearch_getAttribute() {}
void __cdecl usearch_getBreakIterator() {}
void __cdecl usearch_getCollator() {}
void __cdecl usearch_getMatchedLength() {}
void __cdecl usearch_getMatchedStart() {}
void __cdecl usearch_getMatchedText() {}
void __cdecl usearch_getOffset() {}
void __cdecl usearch_getPattern() {}
void __cdecl usearch_getText() {}
void __cdecl usearch_last() {}
void __cdecl usearch_next() {}
void __cdecl usearch_open() {}
void __cdecl usearch_openFromCollator() {}
void __cdecl usearch_preceding() {}
void __cdecl usearch_previous() {}
void __cdecl usearch_reset() {}
void __cdecl usearch_setAttribute() {}
void __cdecl usearch_setBreakIterator() {}
void __cdecl usearch_setCollator() {}
void __cdecl usearch_setOffset() {}
void __cdecl usearch_setPattern() {}
void __cdecl usearch_setText() {}
void __cdecl uset_add() {}
void __cdecl uset_addAll() {}
void __cdecl uset_addAllCodePoints() {}
void __cdecl uset_addRange() {}
void __cdecl uset_addString() {}
void __cdecl uset_applyIntPropertyValue() {}
void __cdecl uset_applyPattern() {}
void __cdecl uset_applyPropertyAlias() {}
void __cdecl uset_charAt() {}
void __cdecl uset_clear() {}
void __cdecl uset_clone() {}
void __cdecl uset_cloneAsThawed() {}
void __cdecl uset_close() {}
void __cdecl uset_closeOver() {}
void __cdecl uset_compact() {}
void __cdecl uset_complement() {}
void __cdecl uset_complementAll() {}
void __cdecl uset_contains() {}
void __cdecl uset_containsAll() {}
void __cdecl uset_containsAllCodePoints() {}
void __cdecl uset_containsNone() {}
void __cdecl uset_containsRange() {}
void __cdecl uset_containsSome() {}
void __cdecl uset_containsString() {}
void __cdecl uset_equals() {}
void __cdecl uset_freeze() {}
void __cdecl uset_getItem() {}
void __cdecl uset_getItemCount() {}
void __cdecl uset_getSerializedRange() {}
void __cdecl uset_getSerializedRangeCount() {}
void __cdecl uset_getSerializedSet() {}
void __cdecl uset_indexOf() {}
void __cdecl uset_isEmpty() {}
void __cdecl uset_isFrozen() {}
void __cdecl uset_open() {}
void __cdecl uset_openEmpty() {}
void __cdecl uset_openPattern() {}
void __cdecl uset_openPatternOptions() {}
void __cdecl uset_remove() {}
void __cdecl uset_removeAll() {}
void __cdecl uset_removeAllStrings() {}
void __cdecl uset_removeRange() {}
void __cdecl uset_removeString() {}
void __cdecl uset_resemblesPattern() {}
void __cdecl uset_retain() {}
void __cdecl uset_retainAll() {}
void __cdecl uset_serialize() {}
void __cdecl uset_serializedContains() {}
void __cdecl uset_set() {}
void __cdecl uset_setSerializedToOne() {}
void __cdecl uset_size() {}
void __cdecl uset_span() {}
void __cdecl uset_spanBack() {}
void __cdecl uset_spanBackUTF8() {}
void __cdecl uset_spanUTF8() {}
void __cdecl uset_toPattern() {}
void __cdecl uspoof_areConfusable() {}
void __cdecl uspoof_areConfusableUTF8() {}
void __cdecl uspoof_check() {}
void __cdecl uspoof_check2() {}
void __cdecl uspoof_check2UTF8() {}
void __cdecl uspoof_checkUTF8() {}
void __cdecl uspoof_clone() {}
void __cdecl uspoof_close() {}
void __cdecl uspoof_closeCheckResult() {}
void __cdecl uspoof_getAllowedChars() {}
void __cdecl uspoof_getAllowedLocales() {}
void __cdecl uspoof_getCheckResultChecks() {}
void __cdecl uspoof_getCheckResultNumerics() {}
void __cdecl uspoof_getCheckResultRestrictionLevel() {}
void __cdecl uspoof_getChecks() {}
void __cdecl uspoof_getInclusionSet() {}
void __cdecl uspoof_getRecommendedSet() {}
void __cdecl uspoof_getRestrictionLevel() {}
void __cdecl uspoof_getSkeleton() {}
void __cdecl uspoof_getSkeletonUTF8() {}
void __cdecl uspoof_open() {}
void __cdecl uspoof_openCheckResult() {}
void __cdecl uspoof_openFromSerialized() {}
void __cdecl uspoof_openFromSource() {}
void __cdecl uspoof_serialize() {}
void __cdecl uspoof_setAllowedChars() {}
void __cdecl uspoof_setAllowedLocales() {}
void __cdecl uspoof_setChecks() {}
void __cdecl uspoof_setRestrictionLevel() {}
void __cdecl usprep_close() {}
void __cdecl usprep_open() {}
void __cdecl usprep_openByType() {}
void __cdecl usprep_prepare() {}
void __cdecl utext_char32At() {}
void __cdecl utext_clone() {}
void __cdecl utext_close() {}
void __cdecl utext_copy() {}
void __cdecl utext_current32() {}
void __cdecl utext_equals() {}
void __cdecl utext_extract() {}
void __cdecl utext_freeze() {}
void __cdecl utext_getNativeIndex() {}
void __cdecl utext_getPreviousNativeIndex() {}
void __cdecl utext_hasMetaData() {}
void __cdecl utext_isLengthExpensive() {}
void __cdecl utext_isWritable() {}
void __cdecl utext_moveIndex32() {}
void __cdecl utext_nativeLength() {}
void __cdecl utext_next32() {}
void __cdecl utext_next32From() {}
void __cdecl utext_openUChars() {}
void __cdecl utext_openUTF8() {}
void __cdecl utext_previous32() {}
void __cdecl utext_previous32From() {}
void __cdecl utext_replace() {}
void __cdecl utext_setNativeIndex() {}
void __cdecl utext_setup() {}
void __cdecl utf8_appendCharSafeBody() {}
void __cdecl utf8_back1SafeBody() {}
void __cdecl utf8_nextCharSafeBody() {}
void __cdecl utf8_prevCharSafeBody() {}
void __cdecl utmscale_fromInt64() {}
void __cdecl utmscale_getTimeScaleValue() {}
void __cdecl utmscale_toInt64() {}
void __cdecl utrace_format() {}
void __cdecl utrace_functionName() {}
void __cdecl utrace_getFunctions() {}
void __cdecl utrace_getLevel() {}
void __cdecl utrace_setFunctions() {}
void __cdecl utrace_setLevel() {}
void __cdecl utrace_vformat() {}
void __cdecl utrans_clone() {}
void __cdecl utrans_close() {}
void __cdecl utrans_countAvailableIDs() {}
void __cdecl utrans_getSourceSet() {}
void __cdecl utrans_getUnicodeID() {}
void __cdecl utrans_openIDs() {}
void __cdecl utrans_openInverse() {}
void __cdecl utrans_openU() {}
void __cdecl utrans_register() {}
void __cdecl utrans_setFilter() {}
void __cdecl utrans_toRules() {}
void __cdecl utrans_trans() {}
void __cdecl utrans_transIncremental() {}
void __cdecl utrans_transIncrementalUChars() {}
void __cdecl utrans_transUChars() {}
void __cdecl utrans_unregisterID() {}
