void __cdecl UCNV_FROM_U_CALLBACK_ESCAPE() {}
void __cdecl UCNV_FROM_U_CALLBACK_SKIP() {}
void __cdecl UCNV_FROM_U_CALLBACK_STOP() {}
void __cdecl UCNV_FROM_U_CALLBACK_SUBSTITUTE() {}
void __cdecl UCNV_TO_U_CALLBACK_ESCAPE() {}
void __cdecl UCNV_TO_U_CALLBACK_SKIP() {}
void __cdecl UCNV_TO_U_CALLBACK_STOP() {}
void __cdecl UCNV_TO_U_CALLBACK_SUBSTITUTE() {}
void __cdecl u_UCharsToChars() {}
void __cdecl u_austrcpy() {}
void __cdecl u_austrncpy() {}
void __cdecl u_catclose() {}
void __cdecl u_catgets() {}
void __cdecl u_catopen() {}
void __cdecl u_charAge() {}
void __cdecl u_charDigitValue() {}
void __cdecl u_charDirection() {}
void __cdecl u_charFromName() {}
void __cdecl u_charMirror() {}
void __cdecl u_charName() {}
void __cdecl u_charType() {}
void __cdecl u_charsToUChars() {}
void __cdecl u_cleanup() {}
void __cdecl u_countChar32() {}
void __cdecl u_digit() {}
void __cdecl u_enumCharNames() {}
void __cdecl u_enumCharTypes() {}
void __cdecl u_errorName() {}
void __cdecl u_foldCase() {}
void __cdecl u_forDigit() {}
void __cdecl u_getBidiPairedBracket() {}
void __cdecl u_getCombiningClass() {}
void __cdecl u_getDataVersion() {}
void __cdecl u_getFC_NFKC_Closure() {}
void __cdecl u_getIntPropertyMaxValue() {}
void __cdecl u_getIntPropertyMinValue() {}
void __cdecl u_getIntPropertyValue() {}
void __cdecl u_getNumericValue() {}
void __cdecl u_getPropertyEnum() {}
void __cdecl u_getPropertyName() {}
void __cdecl u_getPropertyValueEnum() {}
void __cdecl u_getPropertyValueName() {}
void __cdecl u_getUnicodeVersion() {}
void __cdecl u_getVersion() {}
void __cdecl u_hasBinaryProperty() {}
void __cdecl u_init() {}
void __cdecl u_isIDIgnorable() {}
void __cdecl u_isIDPart() {}
void __cdecl u_isIDStart() {}
void __cdecl u_isISOControl() {}
void __cdecl u_isJavaIDPart() {}
void __cdecl u_isJavaIDStart() {}
void __cdecl u_isJavaSpaceChar() {}
void __cdecl u_isMirrored() {}
void __cdecl u_isUAlphabetic() {}
void __cdecl u_isULowercase() {}
void __cdecl u_isUUppercase() {}
void __cdecl u_isUWhiteSpace() {}
void __cdecl u_isWhitespace() {}
void __cdecl u_isalnum() {}
void __cdecl u_isalpha() {}
void __cdecl u_isbase() {}
void __cdecl u_isblank() {}
void __cdecl u_iscntrl() {}
void __cdecl u_isdefined() {}
void __cdecl u_isdigit() {}
void __cdecl u_isgraph() {}
void __cdecl u_islower() {}
void __cdecl u_isprint() {}
void __cdecl u_ispunct() {}
void __cdecl u_isspace() {}
void __cdecl u_istitle() {}
void __cdecl u_isupper() {}
void __cdecl u_isxdigit() {}
void __cdecl u_memcasecmp() {}
void __cdecl u_memchr() {}
void __cdecl u_memchr32() {}
void __cdecl u_memcmp() {}
void __cdecl u_memcmpCodePointOrder() {}
void __cdecl u_memcpy() {}
void __cdecl u_memmove() {}
void __cdecl u_memrchr() {}
void __cdecl u_memrchr32() {}
void __cdecl u_memset() {}
void __cdecl u_setMemoryFunctions() {}
void __cdecl u_shapeArabic() {}
void __cdecl u_strCaseCompare() {}
void __cdecl u_strCompare() {}
void __cdecl u_strCompareIter() {}
void __cdecl u_strFindFirst() {}
void __cdecl u_strFindLast() {}
void __cdecl u_strFoldCase() {}
void __cdecl u_strFromJavaModifiedUTF8WithSub() {}
void __cdecl u_strFromUTF32() {}
void __cdecl u_strFromUTF32WithSub() {}
void __cdecl u_strFromUTF8() {}
void __cdecl u_strFromUTF8Lenient() {}
void __cdecl u_strFromUTF8WithSub() {}
void __cdecl u_strFromWCS() {}
void __cdecl u_strHasMoreChar32Than() {}
void __cdecl u_strToJavaModifiedUTF8() {}
void __cdecl u_strToLower() {}
void __cdecl u_strToTitle() {}
void __cdecl u_strToUTF32() {}
void __cdecl u_strToUTF32WithSub() {}
void __cdecl u_strToUTF8() {}
void __cdecl u_strToUTF8WithSub() {}
void __cdecl u_strToUpper() {}
void __cdecl u_strToWCS() {}
void __cdecl u_strcasecmp() {}
void __cdecl u_strcat() {}
void __cdecl u_strchr() {}
void __cdecl u_strchr32() {}
void __cdecl u_strcmp() {}
void __cdecl u_strcmpCodePointOrder() {}
void __cdecl u_strcpy() {}
void __cdecl u_strcspn() {}
void __cdecl u_strlen() {}
void __cdecl u_strncasecmp() {}
void __cdecl u_strncat() {}
void __cdecl u_strncmp() {}
void __cdecl u_strncmpCodePointOrder() {}
void __cdecl u_strncpy() {}
void __cdecl u_strpbrk() {}
void __cdecl u_strrchr() {}
void __cdecl u_strrchr32() {}
void __cdecl u_strrstr() {}
void __cdecl u_strspn() {}
void __cdecl u_strstr() {}
void __cdecl u_strtok_r() {}
void __cdecl u_tolower() {}
void __cdecl u_totitle() {}
void __cdecl u_toupper() {}
void __cdecl u_uastrcpy() {}
void __cdecl u_uastrncpy() {}
void __cdecl u_unescape() {}
void __cdecl u_unescapeAt() {}
void __cdecl u_versionFromString() {}
void __cdecl u_versionFromUString() {}
void __cdecl u_versionToString() {}
void __cdecl ubidi_close() {}
void __cdecl ubidi_countParagraphs() {}
void __cdecl ubidi_countRuns() {}
void __cdecl ubidi_getBaseDirection() {}
void __cdecl ubidi_getClassCallback() {}
void __cdecl ubidi_getCustomizedClass() {}
void __cdecl ubidi_getDirection() {}
void __cdecl ubidi_getLength() {}
void __cdecl ubidi_getLevelAt() {}
void __cdecl ubidi_getLevels() {}
void __cdecl ubidi_getLogicalIndex() {}
void __cdecl ubidi_getLogicalMap() {}
void __cdecl ubidi_getLogicalRun() {}
void __cdecl ubidi_getParaLevel() {}
void __cdecl ubidi_getParagraph() {}
void __cdecl ubidi_getParagraphByIndex() {}
void __cdecl ubidi_getProcessedLength() {}
void __cdecl ubidi_getReorderingMode() {}
void __cdecl ubidi_getReorderingOptions() {}
void __cdecl ubidi_getResultLength() {}
void __cdecl ubidi_getText() {}
void __cdecl ubidi_getVisualIndex() {}
void __cdecl ubidi_getVisualMap() {}
void __cdecl ubidi_getVisualRun() {}
void __cdecl ubidi_invertMap() {}
void __cdecl ubidi_isInverse() {}
void __cdecl ubidi_isOrderParagraphsLTR() {}
void __cdecl ubidi_open() {}
void __cdecl ubidi_openSized() {}
void __cdecl ubidi_orderParagraphsLTR() {}
void __cdecl ubidi_reorderLogical() {}
void __cdecl ubidi_reorderVisual() {}
void __cdecl ubidi_setClassCallback() {}
void __cdecl ubidi_setContext() {}
void __cdecl ubidi_setInverse() {}
void __cdecl ubidi_setLine() {}
void __cdecl ubidi_setPara() {}
void __cdecl ubidi_setReorderingMode() {}
void __cdecl ubidi_setReorderingOptions() {}
void __cdecl ubidi_writeReordered() {}
void __cdecl ubidi_writeReverse() {}
void __cdecl ubiditransform_close() {}
void __cdecl ubiditransform_open() {}
void __cdecl ubiditransform_transform() {}
void __cdecl ublock_getCode() {}
void __cdecl ubrk_close() {}
void __cdecl ubrk_countAvailable() {}
void __cdecl ubrk_current() {}
void __cdecl ubrk_first() {}
void __cdecl ubrk_following() {}
void __cdecl ubrk_getAvailable() {}
void __cdecl ubrk_getBinaryRules() {}
void __cdecl ubrk_getLocaleByType() {}
void __cdecl ubrk_getRuleStatus() {}
void __cdecl ubrk_getRuleStatusVec() {}
void __cdecl ubrk_isBoundary() {}
void __cdecl ubrk_last() {}
void __cdecl ubrk_next() {}
void __cdecl ubrk_open() {}
void __cdecl ubrk_openBinaryRules() {}
void __cdecl ubrk_openRules() {}
void __cdecl ubrk_preceding() {}
void __cdecl ubrk_previous() {}
void __cdecl ubrk_refreshUText() {}
void __cdecl ubrk_safeClone() {}
void __cdecl ubrk_setText() {}
void __cdecl ubrk_setUText() {}
void __cdecl ucasemap_close() {}
void __cdecl ucasemap_getBreakIterator() {}
void __cdecl ucasemap_getLocale() {}
void __cdecl ucasemap_getOptions() {}
void __cdecl ucasemap_open() {}
void __cdecl ucasemap_setBreakIterator() {}
void __cdecl ucasemap_setLocale() {}
void __cdecl ucasemap_setOptions() {}
void __cdecl ucasemap_toTitle() {}
void __cdecl ucasemap_utf8FoldCase() {}
void __cdecl ucasemap_utf8ToLower() {}
void __cdecl ucasemap_utf8ToTitle() {}
void __cdecl ucasemap_utf8ToUpper() {}
void __cdecl ucnv_cbFromUWriteBytes() {}
void __cdecl ucnv_cbFromUWriteSub() {}
void __cdecl ucnv_cbFromUWriteUChars() {}
void __cdecl ucnv_cbToUWriteSub() {}
void __cdecl ucnv_cbToUWriteUChars() {}
void __cdecl ucnv_close() {}
void __cdecl ucnv_compareNames() {}
void __cdecl ucnv_convert() {}
void __cdecl ucnv_convertEx() {}
void __cdecl ucnv_countAliases() {}
void __cdecl ucnv_countAvailable() {}
void __cdecl ucnv_countStandards() {}
void __cdecl ucnv_detectUnicodeSignature() {}
void __cdecl ucnv_fixFileSeparator() {}
void __cdecl ucnv_flushCache() {}
void __cdecl ucnv_fromAlgorithmic() {}
void __cdecl ucnv_fromUChars() {}
void __cdecl ucnv_fromUCountPending() {}
void __cdecl ucnv_fromUnicode() {}
void __cdecl ucnv_getAlias() {}
void __cdecl ucnv_getAliases() {}
void __cdecl ucnv_getAvailableName() {}
void __cdecl ucnv_getCCSID() {}
void __cdecl ucnv_getCanonicalName() {}
void __cdecl ucnv_getDefaultName() {}
void __cdecl ucnv_getDisplayName() {}
void __cdecl ucnv_getFromUCallBack() {}
void __cdecl ucnv_getInvalidChars() {}
void __cdecl ucnv_getInvalidUChars() {}
void __cdecl ucnv_getMaxCharSize() {}
void __cdecl ucnv_getMinCharSize() {}
void __cdecl ucnv_getName() {}
void __cdecl ucnv_getNextUChar() {}
void __cdecl ucnv_getPlatform() {}
void __cdecl ucnv_getStandard() {}
void __cdecl ucnv_getStandardName() {}
void __cdecl ucnv_getStarters() {}
void __cdecl ucnv_getSubstChars() {}
void __cdecl ucnv_getToUCallBack() {}
void __cdecl ucnv_getType() {}
void __cdecl ucnv_getUnicodeSet() {}
void __cdecl ucnv_isAmbiguous() {}
void __cdecl ucnv_isFixedWidth() {}
void __cdecl ucnv_open() {}
void __cdecl ucnv_openAllNames() {}
void __cdecl ucnv_openCCSID() {}
void __cdecl ucnv_openPackage() {}
void __cdecl ucnv_openStandardNames() {}
void __cdecl ucnv_openU() {}
void __cdecl ucnv_reset() {}
void __cdecl ucnv_resetFromUnicode() {}
void __cdecl ucnv_resetToUnicode() {}
void __cdecl ucnv_safeClone() {}
void __cdecl ucnv_setDefaultName() {}
void __cdecl ucnv_setFallback() {}
void __cdecl ucnv_setFromUCallBack() {}
void __cdecl ucnv_setSubstChars() {}
void __cdecl ucnv_setSubstString() {}
void __cdecl ucnv_setToUCallBack() {}
void __cdecl ucnv_toAlgorithmic() {}
void __cdecl ucnv_toUChars() {}
void __cdecl ucnv_toUCountPending() {}
void __cdecl ucnv_toUnicode() {}
void __cdecl ucnv_usesFallback() {}
void __cdecl ucnvsel_close() {}
void __cdecl ucnvsel_open() {}
void __cdecl ucnvsel_openFromSerialized() {}
void __cdecl ucnvsel_selectForString() {}
void __cdecl ucnvsel_selectForUTF8() {}
void __cdecl ucnvsel_serialize() {}
void __cdecl ucurr_countCurrencies() {}
void __cdecl ucurr_forLocale() {}
void __cdecl ucurr_forLocaleAndDate() {}
void __cdecl ucurr_getDefaultFractionDigits() {}
void __cdecl ucurr_getDefaultFractionDigitsForUsage() {}
void __cdecl ucurr_getKeywordValuesForLocale() {}
void __cdecl ucurr_getName() {}
void __cdecl ucurr_getNumericCode() {}
void __cdecl ucurr_getPluralName() {}
void __cdecl ucurr_getRoundingIncrement() {}
void __cdecl ucurr_getRoundingIncrementForUsage() {}
void __cdecl ucurr_isAvailable() {}
void __cdecl ucurr_openISOCurrencies() {}
void __cdecl ucurr_register() {}
void __cdecl ucurr_unregister() {}
void __cdecl uenum_close() {}
void __cdecl uenum_count() {}
void __cdecl uenum_next() {}
void __cdecl uenum_openCharStringsEnumeration() {}
void __cdecl uenum_openUCharStringsEnumeration() {}
void __cdecl uenum_reset() {}
void __cdecl uenum_unext() {}
void __cdecl uidna_close() {}
void __cdecl uidna_labelToASCII() {}
void __cdecl uidna_labelToASCII_UTF8() {}
void __cdecl uidna_labelToUnicode() {}
void __cdecl uidna_labelToUnicodeUTF8() {}
void __cdecl uidna_nameToASCII() {}
void __cdecl uidna_nameToASCII_UTF8() {}
void __cdecl uidna_nameToUnicode() {}
void __cdecl uidna_nameToUnicodeUTF8() {}
void __cdecl uidna_openUTS46() {}
void __cdecl uiter_current32() {}
void __cdecl uiter_getState() {}
void __cdecl uiter_next32() {}
void __cdecl uiter_previous32() {}
void __cdecl uiter_setState() {}
void __cdecl uiter_setString() {}
void __cdecl uiter_setUTF16BE() {}
void __cdecl uiter_setUTF8() {}
void __cdecl uldn_close() {}
void __cdecl uldn_getContext() {}
void __cdecl uldn_getDialectHandling() {}
void __cdecl uldn_getLocale() {}
void __cdecl uldn_keyDisplayName() {}
void __cdecl uldn_keyValueDisplayName() {}
void __cdecl uldn_languageDisplayName() {}
void __cdecl uldn_localeDisplayName() {}
void __cdecl uldn_open() {}
void __cdecl uldn_openForContext() {}
void __cdecl uldn_regionDisplayName() {}
void __cdecl uldn_scriptCodeDisplayName() {}
void __cdecl uldn_scriptDisplayName() {}
void __cdecl uldn_variantDisplayName() {}
void __cdecl ulistfmt_close() {}
void __cdecl ulistfmt_format() {}
void __cdecl ulistfmt_open() {}
void __cdecl uloc_acceptLanguage() {}
void __cdecl uloc_acceptLanguageFromHTTP() {}
void __cdecl uloc_addLikelySubtags() {}
void __cdecl uloc_canonicalize() {}
void __cdecl uloc_countAvailable() {}
void __cdecl uloc_forLanguageTag() {}
void __cdecl uloc_getAvailable() {}
void __cdecl uloc_getBaseName() {}
void __cdecl uloc_getCharacterOrientation() {}
void __cdecl uloc_getCountry() {}
void __cdecl uloc_getDefault() {}
void __cdecl uloc_getDisplayCountry() {}
void __cdecl uloc_getDisplayKeyword() {}
void __cdecl uloc_getDisplayKeywordValue() {}
void __cdecl uloc_getDisplayLanguage() {}
void __cdecl uloc_getDisplayName() {}
void __cdecl uloc_getDisplayScript() {}
void __cdecl uloc_getDisplayVariant() {}
void __cdecl uloc_getISO3Country() {}
void __cdecl uloc_getISO3Language() {}
void __cdecl uloc_getISOCountries() {}
void __cdecl uloc_getISOLanguages() {}
void __cdecl uloc_getKeywordValue() {}
void __cdecl uloc_getLCID() {}
void __cdecl uloc_getLanguage() {}
void __cdecl uloc_getLineOrientation() {}
void __cdecl uloc_getLocaleForLCID() {}
void __cdecl uloc_getName() {}
void __cdecl uloc_getParent() {}
void __cdecl uloc_getScript() {}
void __cdecl uloc_getVariant() {}
void __cdecl uloc_isRightToLeft() {}
void __cdecl uloc_minimizeSubtags() {}
void __cdecl uloc_openKeywords() {}
void __cdecl uloc_setDefault() {}
void __cdecl uloc_setKeywordValue() {}
void __cdecl uloc_toLanguageTag() {}
void __cdecl uloc_toLegacyKey() {}
void __cdecl uloc_toLegacyType() {}
void __cdecl uloc_toUnicodeLocaleKey() {}
void __cdecl uloc_toUnicodeLocaleType() {}
void __cdecl unorm2_append() {}
void __cdecl unorm2_close() {}
void __cdecl unorm2_composePair() {}
void __cdecl unorm2_getCombiningClass() {}
void __cdecl unorm2_getDecomposition() {}
void __cdecl unorm2_getInstance() {}
void __cdecl unorm2_getNFCInstance() {}
void __cdecl unorm2_getNFDInstance() {}
void __cdecl unorm2_getNFKCCasefoldInstance() {}
void __cdecl unorm2_getNFKCInstance() {}
void __cdecl unorm2_getNFKDInstance() {}
void __cdecl unorm2_getRawDecomposition() {}
void __cdecl unorm2_hasBoundaryAfter() {}
void __cdecl unorm2_hasBoundaryBefore() {}
void __cdecl unorm2_isInert() {}
void __cdecl unorm2_isNormalized() {}
void __cdecl unorm2_normalize() {}
void __cdecl unorm2_normalizeSecondAndAppend() {}
void __cdecl unorm2_openFiltered() {}
void __cdecl unorm2_quickCheck() {}
void __cdecl unorm2_spanQuickCheckYes() {}
void __cdecl unorm_compare() {}
void __cdecl ures_close() {}
void __cdecl ures_getBinary() {}
void __cdecl ures_getByIndex() {}
void __cdecl ures_getByKey() {}
void __cdecl ures_getInt() {}
void __cdecl ures_getIntVector() {}
void __cdecl ures_getKey() {}
void __cdecl ures_getLocaleByType() {}
void __cdecl ures_getNextResource() {}
void __cdecl ures_getNextString() {}
void __cdecl ures_getSize() {}
void __cdecl ures_getString() {}
void __cdecl ures_getStringByIndex() {}
void __cdecl ures_getStringByKey() {}
void __cdecl ures_getType() {}
void __cdecl ures_getUInt() {}
void __cdecl ures_getUTF8String() {}
void __cdecl ures_getUTF8StringByIndex() {}
void __cdecl ures_getUTF8StringByKey() {}
void __cdecl ures_getVersion() {}
void __cdecl ures_hasNext() {}
void __cdecl ures_open() {}
void __cdecl ures_openAvailableLocales() {}
void __cdecl ures_openDirect() {}
void __cdecl ures_openU() {}
void __cdecl ures_resetIterator() {}
void __cdecl uscript_breaksBetweenLetters() {}
void __cdecl uscript_getCode() {}
void __cdecl uscript_getName() {}
void __cdecl uscript_getSampleString() {}
void __cdecl uscript_getScript() {}
void __cdecl uscript_getScriptExtensions() {}
void __cdecl uscript_getShortName() {}
void __cdecl uscript_getUsage() {}
void __cdecl uscript_hasScript() {}
void __cdecl uscript_isCased() {}
void __cdecl uscript_isRightToLeft() {}
void __cdecl uset_add() {}
void __cdecl uset_addAll() {}
void __cdecl uset_addAllCodePoints() {}
void __cdecl uset_addRange() {}
void __cdecl uset_addString() {}
void __cdecl uset_applyIntPropertyValue() {}
void __cdecl uset_applyPattern() {}
void __cdecl uset_applyPropertyAlias() {}
void __cdecl uset_charAt() {}
void __cdecl uset_clear() {}
void __cdecl uset_clone() {}
void __cdecl uset_cloneAsThawed() {}
void __cdecl uset_close() {}
void __cdecl uset_closeOver() {}
void __cdecl uset_compact() {}
void __cdecl uset_complement() {}
void __cdecl uset_complementAll() {}
void __cdecl uset_contains() {}
void __cdecl uset_containsAll() {}
void __cdecl uset_containsAllCodePoints() {}
void __cdecl uset_containsNone() {}
void __cdecl uset_containsRange() {}
void __cdecl uset_containsSome() {}
void __cdecl uset_containsString() {}
void __cdecl uset_equals() {}
void __cdecl uset_freeze() {}
void __cdecl uset_getItem() {}
void __cdecl uset_getItemCount() {}
void __cdecl uset_getSerializedRange() {}
void __cdecl uset_getSerializedRangeCount() {}
void __cdecl uset_getSerializedSet() {}
void __cdecl uset_indexOf() {}
void __cdecl uset_isEmpty() {}
void __cdecl uset_isFrozen() {}
void __cdecl uset_open() {}
void __cdecl uset_openEmpty() {}
void __cdecl uset_openPattern() {}
void __cdecl uset_openPatternOptions() {}
void __cdecl uset_remove() {}
void __cdecl uset_removeAll() {}
void __cdecl uset_removeAllStrings() {}
void __cdecl uset_removeRange() {}
void __cdecl uset_removeString() {}
void __cdecl uset_resemblesPattern() {}
void __cdecl uset_retain() {}
void __cdecl uset_retainAll() {}
void __cdecl uset_serialize() {}
void __cdecl uset_serializedContains() {}
void __cdecl uset_set() {}
void __cdecl uset_setSerializedToOne() {}
void __cdecl uset_size() {}
void __cdecl uset_span() {}
void __cdecl uset_spanBack() {}
void __cdecl uset_spanBackUTF8() {}
void __cdecl uset_spanUTF8() {}
void __cdecl uset_toPattern() {}
void __cdecl usprep_close() {}
void __cdecl usprep_open() {}
void __cdecl usprep_openByType() {}
void __cdecl usprep_prepare() {}
void __cdecl utext_char32At() {}
void __cdecl utext_clone() {}
void __cdecl utext_close() {}
void __cdecl utext_copy() {}
void __cdecl utext_current32() {}
void __cdecl utext_equals() {}
void __cdecl utext_extract() {}
void __cdecl utext_freeze() {}
void __cdecl utext_getNativeIndex() {}
void __cdecl utext_getPreviousNativeIndex() {}
void __cdecl utext_hasMetaData() {}
void __cdecl utext_isLengthExpensive() {}
void __cdecl utext_isWritable() {}
void __cdecl utext_moveIndex32() {}
void __cdecl utext_nativeLength() {}
void __cdecl utext_next32() {}
void __cdecl utext_next32From() {}
void __cdecl utext_openUChars() {}
void __cdecl utext_openUTF8() {}
void __cdecl utext_previous32() {}
void __cdecl utext_previous32From() {}
void __cdecl utext_replace() {}
void __cdecl utext_setNativeIndex() {}
void __cdecl utext_setup() {}
void __cdecl utf8_appendCharSafeBody() {}
void __cdecl utf8_back1SafeBody() {}
void __cdecl utf8_nextCharSafeBody() {}
void __cdecl utf8_prevCharSafeBody() {}
void __cdecl utrace_format() {}
void __cdecl utrace_functionName() {}
void __cdecl utrace_getFunctions() {}
void __cdecl utrace_getLevel() {}
void __cdecl utrace_setFunctions() {}
void __cdecl utrace_setLevel() {}
void __cdecl utrace_vformat() {}
