void __cdecl LdapGetLastError() {}
void __cdecl LdapMapErrorToWin32() {}
void __cdecl LdapUTF8ToUnicode() {}
void __cdecl LdapUnicodeToUTF8() {}
void __cdecl ber_alloc_t() {}
void __cdecl ber_bvdup() {}
void __cdecl ber_bvecfree() {}
void __cdecl ber_bvfree() {}
void __cdecl ber_first_element() {}
void __cdecl ber_flatten() {}
void __cdecl ber_free() {}
void __cdecl ber_init() {}
void __cdecl ber_next_element() {}
void __cdecl ber_peek_tag() {}
void __cdecl ber_printf() {}
void __cdecl ber_scanf() {}
void __cdecl ber_skip_tag() {}
void __cdecl cldap_open() {}
void __cdecl cldap_openA() {}
void __cdecl cldap_openW() {}
void __cdecl ldap_abandon() {}
void __cdecl ldap_add() {}
void __cdecl ldap_addA() {}
void __cdecl ldap_addW() {}
void __cdecl ldap_add_ext() {}
void __cdecl ldap_add_extA() {}
void __cdecl ldap_add_extW() {}
void __cdecl ldap_add_ext_s() {}
void __cdecl ldap_add_ext_sA() {}
void __cdecl ldap_add_ext_sW() {}
void __cdecl ldap_add_s() {}
void __cdecl ldap_add_sA() {}
void __cdecl ldap_add_sW() {}
void __cdecl ldap_bind() {}
void __cdecl ldap_bindA() {}
void __cdecl ldap_bindW() {}
void __cdecl ldap_bind_s() {}
void __cdecl ldap_bind_sA() {}
void __cdecl ldap_bind_sW() {}
void __cdecl ldap_check_filterA() {}
void __cdecl ldap_check_filterW() {}
void __cdecl ldap_cleanup() {}
void __cdecl ldap_close_extended_op() {}
void __cdecl ldap_compare() {}
void __cdecl ldap_compareA() {}
void __cdecl ldap_compareW() {}
void __cdecl ldap_compare_ext() {}
void __cdecl ldap_compare_extA() {}
void __cdecl ldap_compare_extW() {}
void __cdecl ldap_compare_ext_s() {}
void __cdecl ldap_compare_ext_sA() {}
void __cdecl ldap_compare_ext_sW() {}
void __cdecl ldap_compare_s() {}
void __cdecl ldap_compare_sA() {}
void __cdecl ldap_compare_sW() {}
void __cdecl ldap_conn_from_msg() {}
void __cdecl ldap_connect() {}
void __cdecl ldap_control_free() {}
void __cdecl ldap_control_freeA() {}
void __cdecl ldap_control_freeW() {}
void __cdecl ldap_controls_free() {}
void __cdecl ldap_controls_freeA() {}
void __cdecl ldap_controls_freeW() {}
void __cdecl ldap_count_entries() {}
void __cdecl ldap_count_references() {}
void __cdecl ldap_count_values() {}
void __cdecl ldap_count_valuesA() {}
void __cdecl ldap_count_valuesW() {}
void __cdecl ldap_count_values_len() {}
void __cdecl ldap_create_page_control() {}
void __cdecl ldap_create_page_controlA() {}
void __cdecl ldap_create_page_controlW() {}
void __cdecl ldap_create_sort_control() {}
void __cdecl ldap_create_sort_controlA() {}
void __cdecl ldap_create_sort_controlW() {}
void __cdecl ldap_create_vlv_controlA() {}
void __cdecl ldap_create_vlv_controlW() {}
void __cdecl ldap_delete() {}
void __cdecl ldap_deleteA() {}
void __cdecl ldap_deleteW() {}
void __cdecl ldap_delete_ext() {}
void __cdecl ldap_delete_extA() {}
void __cdecl ldap_delete_extW() {}
void __cdecl ldap_delete_ext_s() {}
void __cdecl ldap_delete_ext_sA() {}
void __cdecl ldap_delete_ext_sW() {}
void __cdecl ldap_delete_s() {}
void __cdecl ldap_delete_sA() {}
void __cdecl ldap_delete_sW() {}
void __cdecl ldap_dn2ufn() {}
void __cdecl ldap_dn2ufnA() {}
void __cdecl ldap_dn2ufnW() {}
void __cdecl ldap_encode_sort_controlA() {}
void __cdecl ldap_encode_sort_controlW() {}
void __cdecl ldap_err2string() {}
void __cdecl ldap_err2stringA() {}
void __cdecl ldap_err2stringW() {}
void __cdecl ldap_escape_filter_element() {}
void __cdecl ldap_escape_filter_elementA() {}
void __cdecl ldap_escape_filter_elementW() {}
void __cdecl ldap_explode_dn() {}
void __cdecl ldap_explode_dnA() {}
void __cdecl ldap_explode_dnW() {}
void __cdecl ldap_extended_operation() {}
void __cdecl ldap_extended_operationA() {}
void __cdecl ldap_extended_operationW() {}
void __cdecl ldap_extended_operation_sA() {}
void __cdecl ldap_extended_operation_sW() {}
void __cdecl ldap_first_attribute() {}
void __cdecl ldap_first_attributeA() {}
void __cdecl ldap_first_attributeW() {}
void __cdecl ldap_first_entry() {}
void __cdecl ldap_first_reference() {}
void __cdecl ldap_free_controls() {}
void __cdecl ldap_free_controlsA() {}
void __cdecl ldap_free_controlsW() {}
void __cdecl ldap_get_dn() {}
void __cdecl ldap_get_dnA() {}
void __cdecl ldap_get_dnW() {}
void __cdecl ldap_get_next_page() {}
void __cdecl ldap_get_next_page_s() {}
void __cdecl ldap_get_option() {}
void __cdecl ldap_get_optionW() {}
void __cdecl ldap_get_paged_count() {}
void __cdecl ldap_get_values() {}
void __cdecl ldap_get_valuesA() {}
void __cdecl ldap_get_valuesW() {}
void __cdecl ldap_get_values_len() {}
void __cdecl ldap_get_values_lenA() {}
void __cdecl ldap_get_values_lenW() {}
void __cdecl ldap_init() {}
void __cdecl ldap_initA() {}
void __cdecl ldap_initW() {}
void __cdecl ldap_memfree() {}
void __cdecl ldap_memfreeA() {}
void __cdecl ldap_memfreeW() {}
void __cdecl ldap_modify() {}
void __cdecl ldap_modifyA() {}
void __cdecl ldap_modifyW() {}
void __cdecl ldap_modify_ext() {}
void __cdecl ldap_modify_extA() {}
void __cdecl ldap_modify_extW() {}
void __cdecl ldap_modify_ext_s() {}
void __cdecl ldap_modify_ext_sA() {}
void __cdecl ldap_modify_ext_sW() {}
void __cdecl ldap_modify_s() {}
void __cdecl ldap_modify_sA() {}
void __cdecl ldap_modify_sW() {}
void __cdecl ldap_modrdn() {}
void __cdecl ldap_modrdn2() {}
void __cdecl ldap_modrdn2A() {}
void __cdecl ldap_modrdn2W() {}
void __cdecl ldap_modrdn2_s() {}
void __cdecl ldap_modrdn2_sA() {}
void __cdecl ldap_modrdn2_sW() {}
void __cdecl ldap_modrdnA() {}
void __cdecl ldap_modrdnW() {}
void __cdecl ldap_modrdn_s() {}
void __cdecl ldap_modrdn_sA() {}
void __cdecl ldap_modrdn_sW() {}
void __cdecl ldap_msgfree() {}
void __cdecl ldap_next_attribute() {}
void __cdecl ldap_next_attributeA() {}
void __cdecl ldap_next_attributeW() {}
void __cdecl ldap_next_entry() {}
void __cdecl ldap_next_reference() {}
void __cdecl ldap_open() {}
void __cdecl ldap_openA() {}
void __cdecl ldap_openW() {}
void __cdecl ldap_parse_extended_resultA() {}
void __cdecl ldap_parse_extended_resultW() {}
void __cdecl ldap_parse_page_control() {}
void __cdecl ldap_parse_page_controlA() {}
void __cdecl ldap_parse_page_controlW() {}
void __cdecl ldap_parse_reference() {}
void __cdecl ldap_parse_referenceA() {}
void __cdecl ldap_parse_referenceW() {}
void __cdecl ldap_parse_result() {}
void __cdecl ldap_parse_resultA() {}
void __cdecl ldap_parse_resultW() {}
void __cdecl ldap_parse_sort_control() {}
void __cdecl ldap_parse_sort_controlA() {}
void __cdecl ldap_parse_sort_controlW() {}
void __cdecl ldap_parse_vlv_controlA() {}
void __cdecl ldap_parse_vlv_controlW() {}
void __cdecl ldap_perror() {}
void __cdecl ldap_rename_ext() {}
void __cdecl ldap_rename_extA() {}
void __cdecl ldap_rename_extW() {}
void __cdecl ldap_rename_ext_s() {}
void __cdecl ldap_rename_ext_sA() {}
void __cdecl ldap_rename_ext_sW() {}
void __cdecl ldap_result() {}
void __cdecl ldap_result2error() {}
void __cdecl ldap_sasl_bindA() {}
void __cdecl ldap_sasl_bindW() {}
void __cdecl ldap_sasl_bind_sA() {}
void __cdecl ldap_sasl_bind_sW() {}
void __cdecl ldap_search() {}
void __cdecl ldap_searchA() {}
void __cdecl ldap_searchW() {}
void __cdecl ldap_search_abandon_page() {}
void __cdecl ldap_search_ext() {}
void __cdecl ldap_search_extA() {}
void __cdecl ldap_search_extW() {}
void __cdecl ldap_search_ext_s() {}
void __cdecl ldap_search_ext_sA() {}
void __cdecl ldap_search_ext_sW() {}
void __cdecl ldap_search_init_page() {}
void __cdecl ldap_search_init_pageA() {}
void __cdecl ldap_search_init_pageW() {}
void __cdecl ldap_search_s() {}
void __cdecl ldap_search_sA() {}
void __cdecl ldap_search_sW() {}
void __cdecl ldap_search_st() {}
void __cdecl ldap_search_stA() {}
void __cdecl ldap_search_stW() {}
void __cdecl ldap_set_dbg_flags() {}
void __cdecl ldap_set_dbg_routine() {}
void __cdecl ldap_set_option() {}
void __cdecl ldap_set_optionW() {}
void __cdecl ldap_simple_bind() {}
void __cdecl ldap_simple_bindA() {}
void __cdecl ldap_simple_bindW() {}
void __cdecl ldap_simple_bind_s() {}
void __cdecl ldap_simple_bind_sA() {}
void __cdecl ldap_simple_bind_sW() {}
void __cdecl ldap_sslinit() {}
void __cdecl ldap_sslinitA() {}
void __cdecl ldap_sslinitW() {}
void __cdecl ldap_start_tls_sA() {}
void __cdecl ldap_start_tls_sW() {}
void __cdecl ldap_startup() {}
void __cdecl ldap_stop_tls_s() {}
void __cdecl ldap_ufn2dn() {}
void __cdecl ldap_ufn2dnA() {}
void __cdecl ldap_ufn2dnW() {}
void __cdecl ldap_unbind() {}
void __cdecl ldap_unbind_s() {}
void __cdecl ldap_value_free() {}
void __cdecl ldap_value_freeA() {}
void __cdecl ldap_value_freeW() {}
void __cdecl ldap_value_free_len() {}
