use std::fs;
use std::path::Path;

const OUTPUT: &str = "crates/libs/reactor-next/src/generated.rs";
const GENERATED: &str = "// Generated by `tool_reactor_next`. Do not edit.\n";

fn main() {
    let path = Path::new(OUTPUT);
    if !matches!(fs::read_to_string(path).as_deref(), Ok(current) if current == GENERATED) {
        fs::write(path, GENERATED).unwrap();
    }
}
