// Bindings generated by `windows-bindgen` 0.52.0

#![allow(
    non_snake_case,
    non_upper_case_globals,
    non_camel_case_types,
    dead_code,
    clippy::all
)]
pub const CMC_ADD_ATTRIBUTES: PCSTR = 63i32 as _;
pub const IDC_UPARROW: PCWSTR = 32516u16 as _;
pub type PCSTR = *const u8;
pub type PCWSTR = *const u16;
