// Bindings generated by `windows-bindgen` 0.48.0

#![allow(
    non_snake_case,
    non_upper_case_globals,
    non_camel_case_types,
    dead_code,
    clippy::all
)]
pub type PCWSTR = *const u16;
::windows_targets::link ! ( "kernel32.dll""system"  fn lstrlenW ( lpstring : PCWSTR ) -> i32 );
