pub const D3D10_1_SRV_DIMENSION_BUFFER: D3D_SRV_DIMENSION = 1;
pub const D3D10_1_SRV_DIMENSION_TEXTURE1D: D3D_SRV_DIMENSION = 2;
pub const D3D10_1_SRV_DIMENSION_TEXTURE1DARRAY: D3D_SRV_DIMENSION = 3;
pub const D3D10_1_SRV_DIMENSION_TEXTURE2D: D3D_SRV_DIMENSION = 4;
pub const D3D10_1_SRV_DIMENSION_TEXTURE2DARRAY: D3D_SRV_DIMENSION = 5;
pub const D3D10_1_SRV_DIMENSION_TEXTURE2DMS: D3D_SRV_DIMENSION = 6;
pub const D3D10_1_SRV_DIMENSION_TEXTURE2DMSARRAY: D3D_SRV_DIMENSION = 7;
pub const D3D10_1_SRV_DIMENSION_TEXTURE3D: D3D_SRV_DIMENSION = 8;
pub const D3D10_1_SRV_DIMENSION_TEXTURECUBE: D3D_SRV_DIMENSION = 9;
pub const D3D10_1_SRV_DIMENSION_TEXTURECUBEARRAY: D3D_SRV_DIMENSION = 10;
pub const D3D10_1_SRV_DIMENSION_UNKNOWN: D3D_SRV_DIMENSION = 0;
pub const D3D10_CBF_USERPACKED: D3D_SHADER_CBUFFER_FLAGS = 1;
pub const D3D10_CT_CBUFFER: D3D_CBUFFER_TYPE = 0;
pub const D3D10_CT_TBUFFER: D3D_CBUFFER_TYPE = 1;
pub const D3D10_INCLUDE_LOCAL: D3D_INCLUDE_TYPE = 0;
pub const D3D10_INCLUDE_SYSTEM: D3D_INCLUDE_TYPE = 1;
pub const D3D10_NAME_CLIP_DISTANCE: D3D_NAME = 2;
pub const D3D10_NAME_COVERAGE: D3D_NAME = 66;
pub const D3D10_NAME_CULL_DISTANCE: D3D_NAME = 3;
pub const D3D10_NAME_DEPTH: D3D_NAME = 65;
pub const D3D10_NAME_INSTANCE_ID: D3D_NAME = 8;
pub const D3D10_NAME_IS_FRONT_FACE: D3D_NAME = 9;
pub const D3D10_NAME_POSITION: D3D_NAME = 1;
pub const D3D10_NAME_PRIMITIVE_ID: D3D_NAME = 7;
pub const D3D10_NAME_RENDER_TARGET_ARRAY_INDEX: D3D_NAME = 4;
pub const D3D10_NAME_SAMPLE_INDEX: D3D_NAME = 10;
pub const D3D10_NAME_TARGET: D3D_NAME = 64;
pub const D3D10_NAME_UNDEFINED: D3D_NAME = 0;
pub const D3D10_NAME_VERTEX_ID: D3D_NAME = 6;
pub const D3D10_NAME_VIEWPORT_ARRAY_INDEX: D3D_NAME = 5;
pub const D3D10_PRIMITIVE_LINE: D3D_PRIMITIVE = 2;
pub const D3D10_PRIMITIVE_LINE_ADJ: D3D_PRIMITIVE = 6;
pub const D3D10_PRIMITIVE_POINT: D3D_PRIMITIVE = 1;
pub const D3D10_PRIMITIVE_TOPOLOGY_LINELIST: D3D_PRIMITIVE_TOPOLOGY = 2;
pub const D3D10_PRIMITIVE_TOPOLOGY_LINELIST_ADJ: D3D_PRIMITIVE_TOPOLOGY = 10;
pub const D3D10_PRIMITIVE_TOPOLOGY_LINESTRIP: D3D_PRIMITIVE_TOPOLOGY = 3;
pub const D3D10_PRIMITIVE_TOPOLOGY_LINESTRIP_ADJ: D3D_PRIMITIVE_TOPOLOGY = 11;
pub const D3D10_PRIMITIVE_TOPOLOGY_POINTLIST: D3D_PRIMITIVE_TOPOLOGY = 1;
pub const D3D10_PRIMITIVE_TOPOLOGY_TRIANGLELIST: D3D_PRIMITIVE_TOPOLOGY = 4;
pub const D3D10_PRIMITIVE_TOPOLOGY_TRIANGLELIST_ADJ: D3D_PRIMITIVE_TOPOLOGY = 12;
pub const D3D10_PRIMITIVE_TOPOLOGY_TRIANGLESTRIP: D3D_PRIMITIVE_TOPOLOGY = 5;
pub const D3D10_PRIMITIVE_TOPOLOGY_TRIANGLESTRIP_ADJ: D3D_PRIMITIVE_TOPOLOGY = 13;
pub const D3D10_PRIMITIVE_TOPOLOGY_UNDEFINED: D3D_PRIMITIVE_TOPOLOGY = 0;
pub const D3D10_PRIMITIVE_TRIANGLE: D3D_PRIMITIVE = 3;
pub const D3D10_PRIMITIVE_TRIANGLE_ADJ: D3D_PRIMITIVE = 7;
pub const D3D10_PRIMITIVE_UNDEFINED: D3D_PRIMITIVE = 0;
pub const D3D10_REGISTER_COMPONENT_FLOAT16: D3D_REGISTER_COMPONENT_TYPE = 6;
pub const D3D10_REGISTER_COMPONENT_FLOAT32: D3D_REGISTER_COMPONENT_TYPE = 3;
pub const D3D10_REGISTER_COMPONENT_FLOAT64: D3D_REGISTER_COMPONENT_TYPE = 9;
pub const D3D10_REGISTER_COMPONENT_SINT16: D3D_REGISTER_COMPONENT_TYPE = 5;
pub const D3D10_REGISTER_COMPONENT_SINT32: D3D_REGISTER_COMPONENT_TYPE = 2;
pub const D3D10_REGISTER_COMPONENT_SINT64: D3D_REGISTER_COMPONENT_TYPE = 8;
pub const D3D10_REGISTER_COMPONENT_UINT16: D3D_REGISTER_COMPONENT_TYPE = 4;
pub const D3D10_REGISTER_COMPONENT_UINT32: D3D_REGISTER_COMPONENT_TYPE = 1;
pub const D3D10_REGISTER_COMPONENT_UINT64: D3D_REGISTER_COMPONENT_TYPE = 7;
pub const D3D10_REGISTER_COMPONENT_UNKNOWN: D3D_REGISTER_COMPONENT_TYPE = 0;
pub const D3D10_RETURN_TYPE_FLOAT: D3D_RESOURCE_RETURN_TYPE = 5;
pub const D3D10_RETURN_TYPE_MIXED: D3D_RESOURCE_RETURN_TYPE = 6;
pub const D3D10_RETURN_TYPE_SINT: D3D_RESOURCE_RETURN_TYPE = 3;
pub const D3D10_RETURN_TYPE_SNORM: D3D_RESOURCE_RETURN_TYPE = 2;
pub const D3D10_RETURN_TYPE_UINT: D3D_RESOURCE_RETURN_TYPE = 4;
pub const D3D10_RETURN_TYPE_UNORM: D3D_RESOURCE_RETURN_TYPE = 1;
pub const D3D10_SIF_COMPARISON_SAMPLER: D3D_SHADER_INPUT_FLAGS = 2;
pub const D3D10_SIF_TEXTURE_COMPONENTS: D3D_SHADER_INPUT_FLAGS = 12;
pub const D3D10_SIF_TEXTURE_COMPONENT_0: D3D_SHADER_INPUT_FLAGS = 4;
pub const D3D10_SIF_TEXTURE_COMPONENT_1: D3D_SHADER_INPUT_FLAGS = 8;
pub const D3D10_SIF_USERPACKED: D3D_SHADER_INPUT_FLAGS = 1;
pub const D3D10_SIT_CBUFFER: D3D_SHADER_INPUT_TYPE = 0;
pub const D3D10_SIT_SAMPLER: D3D_SHADER_INPUT_TYPE = 3;
pub const D3D10_SIT_TBUFFER: D3D_SHADER_INPUT_TYPE = 1;
pub const D3D10_SIT_TEXTURE: D3D_SHADER_INPUT_TYPE = 2;
pub const D3D10_SRV_DIMENSION_BUFFER: D3D_SRV_DIMENSION = 1;
pub const D3D10_SRV_DIMENSION_TEXTURE1D: D3D_SRV_DIMENSION = 2;
pub const D3D10_SRV_DIMENSION_TEXTURE1DARRAY: D3D_SRV_DIMENSION = 3;
pub const D3D10_SRV_DIMENSION_TEXTURE2D: D3D_SRV_DIMENSION = 4;
pub const D3D10_SRV_DIMENSION_TEXTURE2DARRAY: D3D_SRV_DIMENSION = 5;
pub const D3D10_SRV_DIMENSION_TEXTURE2DMS: D3D_SRV_DIMENSION = 6;
pub const D3D10_SRV_DIMENSION_TEXTURE2DMSARRAY: D3D_SRV_DIMENSION = 7;
pub const D3D10_SRV_DIMENSION_TEXTURE3D: D3D_SRV_DIMENSION = 8;
pub const D3D10_SRV_DIMENSION_TEXTURECUBE: D3D_SRV_DIMENSION = 9;
pub const D3D10_SRV_DIMENSION_UNKNOWN: D3D_SRV_DIMENSION = 0;
pub const D3D10_SVC_MATRIX_COLUMNS: D3D_SHADER_VARIABLE_CLASS = 3;
pub const D3D10_SVC_MATRIX_ROWS: D3D_SHADER_VARIABLE_CLASS = 2;
pub const D3D10_SVC_OBJECT: D3D_SHADER_VARIABLE_CLASS = 4;
pub const D3D10_SVC_SCALAR: D3D_SHADER_VARIABLE_CLASS = 0;
pub const D3D10_SVC_STRUCT: D3D_SHADER_VARIABLE_CLASS = 5;
pub const D3D10_SVC_VECTOR: D3D_SHADER_VARIABLE_CLASS = 1;
pub const D3D10_SVF_USED: D3D_SHADER_VARIABLE_FLAGS = 2;
pub const D3D10_SVF_USERPACKED: D3D_SHADER_VARIABLE_FLAGS = 1;
pub const D3D10_SVT_BLEND: D3D_SHADER_VARIABLE_TYPE = 24;
pub const D3D10_SVT_BOOL: D3D_SHADER_VARIABLE_TYPE = 1;
pub const D3D10_SVT_BUFFER: D3D_SHADER_VARIABLE_TYPE = 25;
pub const D3D10_SVT_CBUFFER: D3D_SHADER_VARIABLE_TYPE = 26;
pub const D3D10_SVT_DEPTHSTENCIL: D3D_SHADER_VARIABLE_TYPE = 23;
pub const D3D10_SVT_DEPTHSTENCILVIEW: D3D_SHADER_VARIABLE_TYPE = 31;
pub const D3D10_SVT_FLOAT: D3D_SHADER_VARIABLE_TYPE = 3;
pub const D3D10_SVT_GEOMETRYSHADER: D3D_SHADER_VARIABLE_TYPE = 21;
pub const D3D10_SVT_INT: D3D_SHADER_VARIABLE_TYPE = 2;
pub const D3D10_SVT_PIXELFRAGMENT: D3D_SHADER_VARIABLE_TYPE = 17;
pub const D3D10_SVT_PIXELSHADER: D3D_SHADER_VARIABLE_TYPE = 15;
pub const D3D10_SVT_RASTERIZER: D3D_SHADER_VARIABLE_TYPE = 22;
pub const D3D10_SVT_RENDERTARGETVIEW: D3D_SHADER_VARIABLE_TYPE = 30;
pub const D3D10_SVT_SAMPLER: D3D_SHADER_VARIABLE_TYPE = 10;
pub const D3D10_SVT_SAMPLER1D: D3D_SHADER_VARIABLE_TYPE = 11;
pub const D3D10_SVT_SAMPLER2D: D3D_SHADER_VARIABLE_TYPE = 12;
pub const D3D10_SVT_SAMPLER3D: D3D_SHADER_VARIABLE_TYPE = 13;
pub const D3D10_SVT_SAMPLERCUBE: D3D_SHADER_VARIABLE_TYPE = 14;
pub const D3D10_SVT_STRING: D3D_SHADER_VARIABLE_TYPE = 4;
pub const D3D10_SVT_TBUFFER: D3D_SHADER_VARIABLE_TYPE = 27;
pub const D3D10_SVT_TEXTURE: D3D_SHADER_VARIABLE_TYPE = 5;
pub const D3D10_SVT_TEXTURE1D: D3D_SHADER_VARIABLE_TYPE = 6;
pub const D3D10_SVT_TEXTURE1DARRAY: D3D_SHADER_VARIABLE_TYPE = 28;
pub const D3D10_SVT_TEXTURE2D: D3D_SHADER_VARIABLE_TYPE = 7;
pub const D3D10_SVT_TEXTURE2DARRAY: D3D_SHADER_VARIABLE_TYPE = 29;
pub const D3D10_SVT_TEXTURE2DMS: D3D_SHADER_VARIABLE_TYPE = 32;
pub const D3D10_SVT_TEXTURE2DMSARRAY: D3D_SHADER_VARIABLE_TYPE = 33;
pub const D3D10_SVT_TEXTURE3D: D3D_SHADER_VARIABLE_TYPE = 8;
pub const D3D10_SVT_TEXTURECUBE: D3D_SHADER_VARIABLE_TYPE = 9;
pub const D3D10_SVT_TEXTURECUBEARRAY: D3D_SHADER_VARIABLE_TYPE = 34;
pub const D3D10_SVT_UINT: D3D_SHADER_VARIABLE_TYPE = 19;
pub const D3D10_SVT_UINT8: D3D_SHADER_VARIABLE_TYPE = 20;
pub const D3D10_SVT_VERTEXFRAGMENT: D3D_SHADER_VARIABLE_TYPE = 18;
pub const D3D10_SVT_VERTEXSHADER: D3D_SHADER_VARIABLE_TYPE = 16;
pub const D3D10_SVT_VOID: D3D_SHADER_VARIABLE_TYPE = 0;
pub const D3D11_CT_CBUFFER: D3D_CBUFFER_TYPE = 0;
pub const D3D11_CT_INTERFACE_POINTERS: D3D_CBUFFER_TYPE = 2;
pub const D3D11_CT_RESOURCE_BIND_INFO: D3D_CBUFFER_TYPE = 3;
pub const D3D11_CT_TBUFFER: D3D_CBUFFER_TYPE = 1;
pub const D3D11_NAME_DEPTH_GREATER_EQUAL: D3D_NAME = 67;
pub const D3D11_NAME_DEPTH_LESS_EQUAL: D3D_NAME = 68;
pub const D3D11_NAME_FINAL_LINE_DENSITY_TESSFACTOR: D3D_NAME = 16;
pub const D3D11_NAME_FINAL_LINE_DETAIL_TESSFACTOR: D3D_NAME = 15;
pub const D3D11_NAME_FINAL_QUAD_EDGE_TESSFACTOR: D3D_NAME = 11;
pub const D3D11_NAME_FINAL_QUAD_INSIDE_TESSFACTOR: D3D_NAME = 12;
pub const D3D11_NAME_FINAL_TRI_EDGE_TESSFACTOR: D3D_NAME = 13;
pub const D3D11_NAME_FINAL_TRI_INSIDE_TESSFACTOR: D3D_NAME = 14;
pub const D3D11_NAME_INNER_COVERAGE: D3D_NAME = 70;
pub const D3D11_NAME_STENCIL_REF: D3D_NAME = 69;
pub const D3D11_PRIMITIVE_10_CONTROL_POINT_PATCH: D3D_PRIMITIVE = 17;
pub const D3D11_PRIMITIVE_11_CONTROL_POINT_PATCH: D3D_PRIMITIVE = 18;
pub const D3D11_PRIMITIVE_12_CONTROL_POINT_PATCH: D3D_PRIMITIVE = 19;
pub const D3D11_PRIMITIVE_13_CONTROL_POINT_PATCH: D3D_PRIMITIVE = 20;
pub const D3D11_PRIMITIVE_14_CONTROL_POINT_PATCH: D3D_PRIMITIVE = 21;
pub const D3D11_PRIMITIVE_15_CONTROL_POINT_PATCH: D3D_PRIMITIVE = 22;
pub const D3D11_PRIMITIVE_16_CONTROL_POINT_PATCH: D3D_PRIMITIVE = 23;
pub const D3D11_PRIMITIVE_17_CONTROL_POINT_PATCH: D3D_PRIMITIVE = 24;
pub const D3D11_PRIMITIVE_18_CONTROL_POINT_PATCH: D3D_PRIMITIVE = 25;
pub const D3D11_PRIMITIVE_19_CONTROL_POINT_PATCH: D3D_PRIMITIVE = 26;
pub const D3D11_PRIMITIVE_1_CONTROL_POINT_PATCH: D3D_PRIMITIVE = 8;
pub const D3D11_PRIMITIVE_20_CONTROL_POINT_PATCH: D3D_PRIMITIVE = 27;
pub const D3D11_PRIMITIVE_21_CONTROL_POINT_PATCH: D3D_PRIMITIVE = 28;
pub const D3D11_PRIMITIVE_22_CONTROL_POINT_PATCH: D3D_PRIMITIVE = 29;
pub const D3D11_PRIMITIVE_23_CONTROL_POINT_PATCH: D3D_PRIMITIVE = 30;
pub const D3D11_PRIMITIVE_24_CONTROL_POINT_PATCH: D3D_PRIMITIVE = 31;
pub const D3D11_PRIMITIVE_25_CONTROL_POINT_PATCH: D3D_PRIMITIVE = 32;
pub const D3D11_PRIMITIVE_26_CONTROL_POINT_PATCH: D3D_PRIMITIVE = 33;
pub const D3D11_PRIMITIVE_27_CONTROL_POINT_PATCH: D3D_PRIMITIVE = 34;
pub const D3D11_PRIMITIVE_28_CONTROL_POINT_PATCH: D3D_PRIMITIVE = 35;
pub const D3D11_PRIMITIVE_29_CONTROL_POINT_PATCH: D3D_PRIMITIVE = 36;
pub const D3D11_PRIMITIVE_2_CONTROL_POINT_PATCH: D3D_PRIMITIVE = 9;
pub const D3D11_PRIMITIVE_30_CONTROL_POINT_PATCH: D3D_PRIMITIVE = 37;
pub const D3D11_PRIMITIVE_31_CONTROL_POINT_PATCH: D3D_PRIMITIVE = 38;
pub const D3D11_PRIMITIVE_32_CONTROL_POINT_PATCH: D3D_PRIMITIVE = 39;
pub const D3D11_PRIMITIVE_3_CONTROL_POINT_PATCH: D3D_PRIMITIVE = 10;
pub const D3D11_PRIMITIVE_4_CONTROL_POINT_PATCH: D3D_PRIMITIVE = 11;
pub const D3D11_PRIMITIVE_5_CONTROL_POINT_PATCH: D3D_PRIMITIVE = 12;
pub const D3D11_PRIMITIVE_6_CONTROL_POINT_PATCH: D3D_PRIMITIVE = 13;
pub const D3D11_PRIMITIVE_7_CONTROL_POINT_PATCH: D3D_PRIMITIVE = 14;
pub const D3D11_PRIMITIVE_8_CONTROL_POINT_PATCH: D3D_PRIMITIVE = 15;
pub const D3D11_PRIMITIVE_9_CONTROL_POINT_PATCH: D3D_PRIMITIVE = 16;
pub const D3D11_PRIMITIVE_LINE: D3D_PRIMITIVE = 2;
pub const D3D11_PRIMITIVE_LINE_ADJ: D3D_PRIMITIVE = 6;
pub const D3D11_PRIMITIVE_POINT: D3D_PRIMITIVE = 1;
pub const D3D11_PRIMITIVE_TOPOLOGY_10_CONTROL_POINT_PATCHLIST: D3D_PRIMITIVE_TOPOLOGY = 42;
pub const D3D11_PRIMITIVE_TOPOLOGY_11_CONTROL_POINT_PATCHLIST: D3D_PRIMITIVE_TOPOLOGY = 43;
pub const D3D11_PRIMITIVE_TOPOLOGY_12_CONTROL_POINT_PATCHLIST: D3D_PRIMITIVE_TOPOLOGY = 44;
pub const D3D11_PRIMITIVE_TOPOLOGY_13_CONTROL_POINT_PATCHLIST: D3D_PRIMITIVE_TOPOLOGY = 45;
pub const D3D11_PRIMITIVE_TOPOLOGY_14_CONTROL_POINT_PATCHLIST: D3D_PRIMITIVE_TOPOLOGY = 46;
pub const D3D11_PRIMITIVE_TOPOLOGY_15_CONTROL_POINT_PATCHLIST: D3D_PRIMITIVE_TOPOLOGY = 47;
pub const D3D11_PRIMITIVE_TOPOLOGY_16_CONTROL_POINT_PATCHLIST: D3D_PRIMITIVE_TOPOLOGY = 48;
pub const D3D11_PRIMITIVE_TOPOLOGY_17_CONTROL_POINT_PATCHLIST: D3D_PRIMITIVE_TOPOLOGY = 49;
pub const D3D11_PRIMITIVE_TOPOLOGY_18_CONTROL_POINT_PATCHLIST: D3D_PRIMITIVE_TOPOLOGY = 50;
pub const D3D11_PRIMITIVE_TOPOLOGY_19_CONTROL_POINT_PATCHLIST: D3D_PRIMITIVE_TOPOLOGY = 51;
pub const D3D11_PRIMITIVE_TOPOLOGY_1_CONTROL_POINT_PATCHLIST: D3D_PRIMITIVE_TOPOLOGY = 33;
pub const D3D11_PRIMITIVE_TOPOLOGY_20_CONTROL_POINT_PATCHLIST: D3D_PRIMITIVE_TOPOLOGY = 52;
pub const D3D11_PRIMITIVE_TOPOLOGY_21_CONTROL_POINT_PATCHLIST: D3D_PRIMITIVE_TOPOLOGY = 53;
pub const D3D11_PRIMITIVE_TOPOLOGY_22_CONTROL_POINT_PATCHLIST: D3D_PRIMITIVE_TOPOLOGY = 54;
pub const D3D11_PRIMITIVE_TOPOLOGY_23_CONTROL_POINT_PATCHLIST: D3D_PRIMITIVE_TOPOLOGY = 55;
pub const D3D11_PRIMITIVE_TOPOLOGY_24_CONTROL_POINT_PATCHLIST: D3D_PRIMITIVE_TOPOLOGY = 56;
pub const D3D11_PRIMITIVE_TOPOLOGY_25_CONTROL_POINT_PATCHLIST: D3D_PRIMITIVE_TOPOLOGY = 57;
pub const D3D11_PRIMITIVE_TOPOLOGY_26_CONTROL_POINT_PATCHLIST: D3D_PRIMITIVE_TOPOLOGY = 58;
pub const D3D11_PRIMITIVE_TOPOLOGY_27_CONTROL_POINT_PATCHLIST: D3D_PRIMITIVE_TOPOLOGY = 59;
pub const D3D11_PRIMITIVE_TOPOLOGY_28_CONTROL_POINT_PATCHLIST: D3D_PRIMITIVE_TOPOLOGY = 60;
pub const D3D11_PRIMITIVE_TOPOLOGY_29_CONTROL_POINT_PATCHLIST: D3D_PRIMITIVE_TOPOLOGY = 61;
pub const D3D11_PRIMITIVE_TOPOLOGY_2_CONTROL_POINT_PATCHLIST: D3D_PRIMITIVE_TOPOLOGY = 34;
pub const D3D11_PRIMITIVE_TOPOLOGY_30_CONTROL_POINT_PATCHLIST: D3D_PRIMITIVE_TOPOLOGY = 62;
pub const D3D11_PRIMITIVE_TOPOLOGY_31_CONTROL_POINT_PATCHLIST: D3D_PRIMITIVE_TOPOLOGY = 63;
pub const D3D11_PRIMITIVE_TOPOLOGY_32_CONTROL_POINT_PATCHLIST: D3D_PRIMITIVE_TOPOLOGY = 64;
pub const D3D11_PRIMITIVE_TOPOLOGY_3_CONTROL_POINT_PATCHLIST: D3D_PRIMITIVE_TOPOLOGY = 35;
pub const D3D11_PRIMITIVE_TOPOLOGY_4_CONTROL_POINT_PATCHLIST: D3D_PRIMITIVE_TOPOLOGY = 36;
pub const D3D11_PRIMITIVE_TOPOLOGY_5_CONTROL_POINT_PATCHLIST: D3D_PRIMITIVE_TOPOLOGY = 37;
pub const D3D11_PRIMITIVE_TOPOLOGY_6_CONTROL_POINT_PATCHLIST: D3D_PRIMITIVE_TOPOLOGY = 38;
pub const D3D11_PRIMITIVE_TOPOLOGY_7_CONTROL_POINT_PATCHLIST: D3D_PRIMITIVE_TOPOLOGY = 39;
pub const D3D11_PRIMITIVE_TOPOLOGY_8_CONTROL_POINT_PATCHLIST: D3D_PRIMITIVE_TOPOLOGY = 40;
pub const D3D11_PRIMITIVE_TOPOLOGY_9_CONTROL_POINT_PATCHLIST: D3D_PRIMITIVE_TOPOLOGY = 41;
pub const D3D11_PRIMITIVE_TOPOLOGY_LINELIST: D3D_PRIMITIVE_TOPOLOGY = 2;
pub const D3D11_PRIMITIVE_TOPOLOGY_LINELIST_ADJ: D3D_PRIMITIVE_TOPOLOGY = 10;
pub const D3D11_PRIMITIVE_TOPOLOGY_LINESTRIP: D3D_PRIMITIVE_TOPOLOGY = 3;
pub const D3D11_PRIMITIVE_TOPOLOGY_LINESTRIP_ADJ: D3D_PRIMITIVE_TOPOLOGY = 11;
pub const D3D11_PRIMITIVE_TOPOLOGY_POINTLIST: D3D_PRIMITIVE_TOPOLOGY = 1;
pub const D3D11_PRIMITIVE_TOPOLOGY_TRIANGLELIST: D3D_PRIMITIVE_TOPOLOGY = 4;
pub const D3D11_PRIMITIVE_TOPOLOGY_TRIANGLELIST_ADJ: D3D_PRIMITIVE_TOPOLOGY = 12;
pub const D3D11_PRIMITIVE_TOPOLOGY_TRIANGLESTRIP: D3D_PRIMITIVE_TOPOLOGY = 5;
pub const D3D11_PRIMITIVE_TOPOLOGY_TRIANGLESTRIP_ADJ: D3D_PRIMITIVE_TOPOLOGY = 13;
pub const D3D11_PRIMITIVE_TOPOLOGY_UNDEFINED: D3D_PRIMITIVE_TOPOLOGY = 0;
pub const D3D11_PRIMITIVE_TRIANGLE: D3D_PRIMITIVE = 3;
pub const D3D11_PRIMITIVE_TRIANGLE_ADJ: D3D_PRIMITIVE = 7;
pub const D3D11_PRIMITIVE_UNDEFINED: D3D_PRIMITIVE = 0;
pub const D3D11_RETURN_TYPE_CONTINUED: D3D_RESOURCE_RETURN_TYPE = 8;
pub const D3D11_RETURN_TYPE_DOUBLE: D3D_RESOURCE_RETURN_TYPE = 7;
pub const D3D11_RETURN_TYPE_FLOAT: D3D_RESOURCE_RETURN_TYPE = 5;
pub const D3D11_RETURN_TYPE_MIXED: D3D_RESOURCE_RETURN_TYPE = 6;
pub const D3D11_RETURN_TYPE_SINT: D3D_RESOURCE_RETURN_TYPE = 3;
pub const D3D11_RETURN_TYPE_SNORM: D3D_RESOURCE_RETURN_TYPE = 2;
pub const D3D11_RETURN_TYPE_UINT: D3D_RESOURCE_RETURN_TYPE = 4;
pub const D3D11_RETURN_TYPE_UNORM: D3D_RESOURCE_RETURN_TYPE = 1;
pub const D3D11_SIT_BYTEADDRESS: D3D_SHADER_INPUT_TYPE = 7;
pub const D3D11_SIT_STRUCTURED: D3D_SHADER_INPUT_TYPE = 5;
pub const D3D11_SIT_UAV_APPEND_STRUCTURED: D3D_SHADER_INPUT_TYPE = 9;
pub const D3D11_SIT_UAV_CONSUME_STRUCTURED: D3D_SHADER_INPUT_TYPE = 10;
pub const D3D11_SIT_UAV_RWBYTEADDRESS: D3D_SHADER_INPUT_TYPE = 8;
pub const D3D11_SIT_UAV_RWSTRUCTURED: D3D_SHADER_INPUT_TYPE = 6;
pub const D3D11_SIT_UAV_RWSTRUCTURED_WITH_COUNTER: D3D_SHADER_INPUT_TYPE = 11;
pub const D3D11_SIT_UAV_RWTYPED: D3D_SHADER_INPUT_TYPE = 4;
pub const D3D11_SRV_DIMENSION_BUFFER: D3D_SRV_DIMENSION = 1;
pub const D3D11_SRV_DIMENSION_BUFFEREX: D3D_SRV_DIMENSION = 11;
pub const D3D11_SRV_DIMENSION_TEXTURE1D: D3D_SRV_DIMENSION = 2;
pub const D3D11_SRV_DIMENSION_TEXTURE1DARRAY: D3D_SRV_DIMENSION = 3;
pub const D3D11_SRV_DIMENSION_TEXTURE2D: D3D_SRV_DIMENSION = 4;
pub const D3D11_SRV_DIMENSION_TEXTURE2DARRAY: D3D_SRV_DIMENSION = 5;
pub const D3D11_SRV_DIMENSION_TEXTURE2DMS: D3D_SRV_DIMENSION = 6;
pub const D3D11_SRV_DIMENSION_TEXTURE2DMSARRAY: D3D_SRV_DIMENSION = 7;
pub const D3D11_SRV_DIMENSION_TEXTURE3D: D3D_SRV_DIMENSION = 8;
pub const D3D11_SRV_DIMENSION_TEXTURECUBE: D3D_SRV_DIMENSION = 9;
pub const D3D11_SRV_DIMENSION_TEXTURECUBEARRAY: D3D_SRV_DIMENSION = 10;
pub const D3D11_SRV_DIMENSION_UNKNOWN: D3D_SRV_DIMENSION = 0;
pub const D3D11_SVC_INTERFACE_CLASS: D3D_SHADER_VARIABLE_CLASS = 6;
pub const D3D11_SVC_INTERFACE_POINTER: D3D_SHADER_VARIABLE_CLASS = 7;
pub const D3D11_SVF_INTERFACE_PARAMETER: D3D_SHADER_VARIABLE_FLAGS = 8;
pub const D3D11_SVF_INTERFACE_POINTER: D3D_SHADER_VARIABLE_FLAGS = 4;
pub const D3D11_SVT_APPEND_STRUCTURED_BUFFER: D3D_SHADER_VARIABLE_TYPE = 50;
pub const D3D11_SVT_BYTEADDRESS_BUFFER: D3D_SHADER_VARIABLE_TYPE = 46;
pub const D3D11_SVT_COMPUTESHADER: D3D_SHADER_VARIABLE_TYPE = 38;
pub const D3D11_SVT_CONSUME_STRUCTURED_BUFFER: D3D_SHADER_VARIABLE_TYPE = 51;
pub const D3D11_SVT_DOMAINSHADER: D3D_SHADER_VARIABLE_TYPE = 36;
pub const D3D11_SVT_DOUBLE: D3D_SHADER_VARIABLE_TYPE = 39;
pub const D3D11_SVT_HULLSHADER: D3D_SHADER_VARIABLE_TYPE = 35;
pub const D3D11_SVT_INTERFACE_POINTER: D3D_SHADER_VARIABLE_TYPE = 37;
pub const D3D11_SVT_RWBUFFER: D3D_SHADER_VARIABLE_TYPE = 45;
pub const D3D11_SVT_RWBYTEADDRESS_BUFFER: D3D_SHADER_VARIABLE_TYPE = 47;
pub const D3D11_SVT_RWSTRUCTURED_BUFFER: D3D_SHADER_VARIABLE_TYPE = 49;
pub const D3D11_SVT_RWTEXTURE1D: D3D_SHADER_VARIABLE_TYPE = 40;
pub const D3D11_SVT_RWTEXTURE1DARRAY: D3D_SHADER_VARIABLE_TYPE = 41;
pub const D3D11_SVT_RWTEXTURE2D: D3D_SHADER_VARIABLE_TYPE = 42;
pub const D3D11_SVT_RWTEXTURE2DARRAY: D3D_SHADER_VARIABLE_TYPE = 43;
pub const D3D11_SVT_RWTEXTURE3D: D3D_SHADER_VARIABLE_TYPE = 44;
pub const D3D11_SVT_STRUCTURED_BUFFER: D3D_SHADER_VARIABLE_TYPE = 48;
pub const D3D11_TESSELLATOR_DOMAIN_ISOLINE: D3D_TESSELLATOR_DOMAIN = 1;
pub const D3D11_TESSELLATOR_DOMAIN_QUAD: D3D_TESSELLATOR_DOMAIN = 3;
pub const D3D11_TESSELLATOR_DOMAIN_TRI: D3D_TESSELLATOR_DOMAIN = 2;
pub const D3D11_TESSELLATOR_DOMAIN_UNDEFINED: D3D_TESSELLATOR_DOMAIN = 0;
pub const D3D11_TESSELLATOR_OUTPUT_LINE: D3D_TESSELLATOR_OUTPUT_PRIMITIVE = 2;
pub const D3D11_TESSELLATOR_OUTPUT_POINT: D3D_TESSELLATOR_OUTPUT_PRIMITIVE = 1;
pub const D3D11_TESSELLATOR_OUTPUT_TRIANGLE_CCW: D3D_TESSELLATOR_OUTPUT_PRIMITIVE = 4;
pub const D3D11_TESSELLATOR_OUTPUT_TRIANGLE_CW: D3D_TESSELLATOR_OUTPUT_PRIMITIVE = 3;
pub const D3D11_TESSELLATOR_OUTPUT_UNDEFINED: D3D_TESSELLATOR_OUTPUT_PRIMITIVE = 0;
pub const D3D11_TESSELLATOR_PARTITIONING_FRACTIONAL_EVEN: D3D_TESSELLATOR_PARTITIONING = 4;
pub const D3D11_TESSELLATOR_PARTITIONING_FRACTIONAL_ODD: D3D_TESSELLATOR_PARTITIONING = 3;
pub const D3D11_TESSELLATOR_PARTITIONING_INTEGER: D3D_TESSELLATOR_PARTITIONING = 1;
pub const D3D11_TESSELLATOR_PARTITIONING_POW2: D3D_TESSELLATOR_PARTITIONING = 2;
pub const D3D11_TESSELLATOR_PARTITIONING_UNDEFINED: D3D_TESSELLATOR_PARTITIONING = 0;
pub const D3D12_NAME_BARYCENTRICS: D3D_NAME = 23;
pub const D3D12_NAME_CULLPRIMITIVE: D3D_NAME = 25;
pub const D3D12_NAME_SHADINGRATE: D3D_NAME = 24;
pub const D3DFCI_BIASED_FIXED_2_8: D3D_FORMAT_COMPONENT_INTERPRETATION = 3;
pub const D3DFCI_FLOAT: D3D_FORMAT_COMPONENT_INTERPRETATION = -4;
pub const D3DFCI_SINT: D3D_FORMAT_COMPONENT_INTERPRETATION = -1;
pub const D3DFCI_SNORM: D3D_FORMAT_COMPONENT_INTERPRETATION = -3;
pub const D3DFCI_TYPELESS: D3D_FORMAT_COMPONENT_INTERPRETATION = 0;
pub const D3DFCI_UINT: D3D_FORMAT_COMPONENT_INTERPRETATION = 1;
pub const D3DFCI_UNORM: D3D_FORMAT_COMPONENT_INTERPRETATION = -2;
pub const D3DFCI_UNORM_SRGB: D3D_FORMAT_COMPONENT_INTERPRETATION = 2;
pub const D3DFCN_A: D3D_FORMAT_COMPONENT_NAME = -1;
pub const D3DFCN_B: D3D_FORMAT_COMPONENT_NAME = -2;
pub const D3DFCN_D: D3D_FORMAT_COMPONENT_NAME = 0;
pub const D3DFCN_G: D3D_FORMAT_COMPONENT_NAME = -3;
pub const D3DFCN_R: D3D_FORMAT_COMPONENT_NAME = -4;
pub const D3DFCN_S: D3D_FORMAT_COMPONENT_NAME = 1;
pub const D3DFCN_X: D3D_FORMAT_COMPONENT_NAME = 2;
pub const D3DFL_CUSTOM: D3D_FORMAT_LAYOUT = -1;
pub const D3DFL_STANDARD: D3D_FORMAT_LAYOUT = 0;
pub const D3DFTL_FULL_TYPE: D3D_FORMAT_TYPE_LEVEL = -1;
pub const D3DFTL_NO_TYPE: D3D_FORMAT_TYPE_LEVEL = 0;
pub const D3DFTL_PARTIAL_TYPE: D3D_FORMAT_TYPE_LEVEL = -2;
pub const D3D_CBF_FORCE_DWORD: D3D_SHADER_CBUFFER_FLAGS = 2147483647;
pub const D3D_CBF_USERPACKED: D3D_SHADER_CBUFFER_FLAGS = 1;
pub type D3D_CBUFFER_TYPE = i32;
pub const D3D_COMPONENT_MASK_W: u32 = 8;
pub const D3D_COMPONENT_MASK_X: u32 = 1;
pub const D3D_COMPONENT_MASK_Y: u32 = 2;
pub const D3D_COMPONENT_MASK_Z: u32 = 4;
pub const D3D_CT_CBUFFER: D3D_CBUFFER_TYPE = 0;
pub const D3D_CT_INTERFACE_POINTERS: D3D_CBUFFER_TYPE = 2;
pub const D3D_CT_RESOURCE_BIND_INFO: D3D_CBUFFER_TYPE = 3;
pub const D3D_CT_TBUFFER: D3D_CBUFFER_TYPE = 1;
pub type D3D_DRIVER_TYPE = i32;
pub const D3D_DRIVER_TYPE_HARDWARE: D3D_DRIVER_TYPE = 1;
pub const D3D_DRIVER_TYPE_NULL: D3D_DRIVER_TYPE = 3;
pub const D3D_DRIVER_TYPE_REFERENCE: D3D_DRIVER_TYPE = 2;
pub const D3D_DRIVER_TYPE_SOFTWARE: D3D_DRIVER_TYPE = 4;
pub const D3D_DRIVER_TYPE_UNKNOWN: D3D_DRIVER_TYPE = 0;
pub const D3D_DRIVER_TYPE_WARP: D3D_DRIVER_TYPE = 5;
pub type D3D_FEATURE_LEVEL = i32;
pub const D3D_FEATURE_LEVEL_10_0: D3D_FEATURE_LEVEL = 40960;
pub const D3D_FEATURE_LEVEL_10_1: D3D_FEATURE_LEVEL = 41216;
pub const D3D_FEATURE_LEVEL_11_0: D3D_FEATURE_LEVEL = 45056;
pub const D3D_FEATURE_LEVEL_11_1: D3D_FEATURE_LEVEL = 45312;
pub const D3D_FEATURE_LEVEL_12_0: D3D_FEATURE_LEVEL = 49152;
pub const D3D_FEATURE_LEVEL_12_1: D3D_FEATURE_LEVEL = 49408;
pub const D3D_FEATURE_LEVEL_12_2: D3D_FEATURE_LEVEL = 49664;
pub const D3D_FEATURE_LEVEL_1_0_CORE: D3D_FEATURE_LEVEL = 4096;
pub const D3D_FEATURE_LEVEL_1_0_GENERIC: D3D_FEATURE_LEVEL = 256;
pub const D3D_FEATURE_LEVEL_9_1: D3D_FEATURE_LEVEL = 37120;
pub const D3D_FEATURE_LEVEL_9_2: D3D_FEATURE_LEVEL = 37376;
pub const D3D_FEATURE_LEVEL_9_3: D3D_FEATURE_LEVEL = 37632;
pub const D3D_FL9_1_DEFAULT_MAX_ANISOTROPY: u32 = 2;
pub const D3D_FL9_1_IA_PRIMITIVE_MAX_COUNT: u32 = 65535;
pub const D3D_FL9_1_MAX_TEXTURE_REPEAT: u32 = 128;
pub const D3D_FL9_1_REQ_TEXTURE1D_U_DIMENSION: u32 = 2048;
pub const D3D_FL9_1_REQ_TEXTURE2D_U_OR_V_DIMENSION: u32 = 2048;
pub const D3D_FL9_1_REQ_TEXTURE3D_U_V_OR_W_DIMENSION: u32 = 256;
pub const D3D_FL9_1_REQ_TEXTURECUBE_DIMENSION: u32 = 512;
pub const D3D_FL9_1_SIMULTANEOUS_RENDER_TARGET_COUNT: u32 = 1;
pub const D3D_FL9_2_IA_PRIMITIVE_MAX_COUNT: u32 = 1048575;
pub const D3D_FL9_2_MAX_TEXTURE_REPEAT: u32 = 2048;
pub const D3D_FL9_3_MAX_TEXTURE_REPEAT: u32 = 8192;
pub const D3D_FL9_3_REQ_TEXTURE1D_U_DIMENSION: u32 = 4096;
pub const D3D_FL9_3_REQ_TEXTURE2D_U_OR_V_DIMENSION: u32 = 4096;
pub const D3D_FL9_3_REQ_TEXTURECUBE_DIMENSION: u32 = 4096;
pub const D3D_FL9_3_SIMULTANEOUS_RENDER_TARGET_COUNT: u32 = 4;
pub type D3D_FORMAT_COMPONENT_INTERPRETATION = i32;
pub type D3D_FORMAT_COMPONENT_NAME = i32;
pub type D3D_FORMAT_LAYOUT = i32;
pub type D3D_FORMAT_TYPE_LEVEL = i32;
pub const D3D_INCLUDE_FORCE_DWORD: D3D_INCLUDE_TYPE = 2147483647;
pub const D3D_INCLUDE_LOCAL: D3D_INCLUDE_TYPE = 0;
pub const D3D_INCLUDE_SYSTEM: D3D_INCLUDE_TYPE = 1;
pub type D3D_INCLUDE_TYPE = i32;
pub const D3D_INTERPOLATION_CONSTANT: D3D_INTERPOLATION_MODE = 1;
pub const D3D_INTERPOLATION_LINEAR: D3D_INTERPOLATION_MODE = 2;
pub const D3D_INTERPOLATION_LINEAR_CENTROID: D3D_INTERPOLATION_MODE = 3;
pub const D3D_INTERPOLATION_LINEAR_NOPERSPECTIVE: D3D_INTERPOLATION_MODE = 4;
pub const D3D_INTERPOLATION_LINEAR_NOPERSPECTIVE_CENTROID: D3D_INTERPOLATION_MODE = 5;
pub const D3D_INTERPOLATION_LINEAR_NOPERSPECTIVE_SAMPLE: D3D_INTERPOLATION_MODE = 7;
pub const D3D_INTERPOLATION_LINEAR_SAMPLE: D3D_INTERPOLATION_MODE = 6;
pub type D3D_INTERPOLATION_MODE = i32;
pub const D3D_INTERPOLATION_UNDEFINED: D3D_INTERPOLATION_MODE = 0;
pub type D3D_MIN_PRECISION = i32;
pub const D3D_MIN_PRECISION_ANY_10: D3D_MIN_PRECISION = 241;
pub const D3D_MIN_PRECISION_ANY_16: D3D_MIN_PRECISION = 240;
pub const D3D_MIN_PRECISION_DEFAULT: D3D_MIN_PRECISION = 0;
pub const D3D_MIN_PRECISION_FLOAT_16: D3D_MIN_PRECISION = 1;
pub const D3D_MIN_PRECISION_FLOAT_2_8: D3D_MIN_PRECISION = 2;
pub const D3D_MIN_PRECISION_RESERVED: D3D_MIN_PRECISION = 3;
pub const D3D_MIN_PRECISION_SINT_16: D3D_MIN_PRECISION = 4;
pub const D3D_MIN_PRECISION_UINT_16: D3D_MIN_PRECISION = 5;
pub type D3D_NAME = i32;
pub const D3D_NAME_BARYCENTRICS: D3D_NAME = 23;
pub const D3D_NAME_CLIP_DISTANCE: D3D_NAME = 2;
pub const D3D_NAME_COVERAGE: D3D_NAME = 66;
pub const D3D_NAME_CULLPRIMITIVE: D3D_NAME = 25;
pub const D3D_NAME_CULL_DISTANCE: D3D_NAME = 3;
pub const D3D_NAME_DEPTH: D3D_NAME = 65;
pub const D3D_NAME_DEPTH_GREATER_EQUAL: D3D_NAME = 67;
pub const D3D_NAME_DEPTH_LESS_EQUAL: D3D_NAME = 68;
pub const D3D_NAME_FINAL_LINE_DENSITY_TESSFACTOR: D3D_NAME = 16;
pub const D3D_NAME_FINAL_LINE_DETAIL_TESSFACTOR: D3D_NAME = 15;
pub const D3D_NAME_FINAL_QUAD_EDGE_TESSFACTOR: D3D_NAME = 11;
pub const D3D_NAME_FINAL_QUAD_INSIDE_TESSFACTOR: D3D_NAME = 12;
pub const D3D_NAME_FINAL_TRI_EDGE_TESSFACTOR: D3D_NAME = 13;
pub const D3D_NAME_FINAL_TRI_INSIDE_TESSFACTOR: D3D_NAME = 14;
pub const D3D_NAME_INNER_COVERAGE: D3D_NAME = 70;
pub const D3D_NAME_INSTANCE_ID: D3D_NAME = 8;
pub const D3D_NAME_IS_FRONT_FACE: D3D_NAME = 9;
pub const D3D_NAME_POSITION: D3D_NAME = 1;
pub const D3D_NAME_PRIMITIVE_ID: D3D_NAME = 7;
pub const D3D_NAME_RENDER_TARGET_ARRAY_INDEX: D3D_NAME = 4;
pub const D3D_NAME_SAMPLE_INDEX: D3D_NAME = 10;
pub const D3D_NAME_SHADINGRATE: D3D_NAME = 24;
pub const D3D_NAME_STENCIL_REF: D3D_NAME = 69;
pub const D3D_NAME_TARGET: D3D_NAME = 64;
pub const D3D_NAME_UNDEFINED: D3D_NAME = 0;
pub const D3D_NAME_VERTEX_ID: D3D_NAME = 6;
pub const D3D_NAME_VIEWPORT_ARRAY_INDEX: D3D_NAME = 5;
pub const D3D_OPT_SHADER_FEATURE_REQUIRES_GROUP: u64 = 2199023255552;
pub const D3D_OPT_SHADER_FEATURE_USES_DERIVATIVES: u64 = 1099511627776;
pub type D3D_PARAMETER_FLAGS = i32;
pub const D3D_PF_FORCE_DWORD: D3D_PARAMETER_FLAGS = 2147483647;
pub const D3D_PF_IN: D3D_PARAMETER_FLAGS = 1;
pub const D3D_PF_NONE: D3D_PARAMETER_FLAGS = 0;
pub const D3D_PF_OUT: D3D_PARAMETER_FLAGS = 2;
pub type D3D_PRIMITIVE = i32;
pub const D3D_PRIMITIVE_10_CONTROL_POINT_PATCH: D3D_PRIMITIVE = 17;
pub const D3D_PRIMITIVE_11_CONTROL_POINT_PATCH: D3D_PRIMITIVE = 18;
pub const D3D_PRIMITIVE_12_CONTROL_POINT_PATCH: D3D_PRIMITIVE = 19;
pub const D3D_PRIMITIVE_13_CONTROL_POINT_PATCH: D3D_PRIMITIVE = 20;
pub const D3D_PRIMITIVE_14_CONTROL_POINT_PATCH: D3D_PRIMITIVE = 21;
pub const D3D_PRIMITIVE_15_CONTROL_POINT_PATCH: D3D_PRIMITIVE = 22;
pub const D3D_PRIMITIVE_16_CONTROL_POINT_PATCH: D3D_PRIMITIVE = 23;
pub const D3D_PRIMITIVE_17_CONTROL_POINT_PATCH: D3D_PRIMITIVE = 24;
pub const D3D_PRIMITIVE_18_CONTROL_POINT_PATCH: D3D_PRIMITIVE = 25;
pub const D3D_PRIMITIVE_19_CONTROL_POINT_PATCH: D3D_PRIMITIVE = 26;
pub const D3D_PRIMITIVE_1_CONTROL_POINT_PATCH: D3D_PRIMITIVE = 8;
pub const D3D_PRIMITIVE_20_CONTROL_POINT_PATCH: D3D_PRIMITIVE = 27;
pub const D3D_PRIMITIVE_21_CONTROL_POINT_PATCH: D3D_PRIMITIVE = 28;
pub const D3D_PRIMITIVE_22_CONTROL_POINT_PATCH: D3D_PRIMITIVE = 29;
pub const D3D_PRIMITIVE_23_CONTROL_POINT_PATCH: D3D_PRIMITIVE = 30;
pub const D3D_PRIMITIVE_24_CONTROL_POINT_PATCH: D3D_PRIMITIVE = 31;
pub const D3D_PRIMITIVE_25_CONTROL_POINT_PATCH: D3D_PRIMITIVE = 32;
pub const D3D_PRIMITIVE_26_CONTROL_POINT_PATCH: D3D_PRIMITIVE = 33;
pub const D3D_PRIMITIVE_27_CONTROL_POINT_PATCH: D3D_PRIMITIVE = 34;
pub const D3D_PRIMITIVE_28_CONTROL_POINT_PATCH: D3D_PRIMITIVE = 35;
pub const D3D_PRIMITIVE_29_CONTROL_POINT_PATCH: D3D_PRIMITIVE = 36;
pub const D3D_PRIMITIVE_2_CONTROL_POINT_PATCH: D3D_PRIMITIVE = 9;
pub const D3D_PRIMITIVE_30_CONTROL_POINT_PATCH: D3D_PRIMITIVE = 37;
pub const D3D_PRIMITIVE_31_CONTROL_POINT_PATCH: D3D_PRIMITIVE = 38;
pub const D3D_PRIMITIVE_32_CONTROL_POINT_PATCH: D3D_PRIMITIVE = 39;
pub const D3D_PRIMITIVE_3_CONTROL_POINT_PATCH: D3D_PRIMITIVE = 10;
pub const D3D_PRIMITIVE_4_CONTROL_POINT_PATCH: D3D_PRIMITIVE = 11;
pub const D3D_PRIMITIVE_5_CONTROL_POINT_PATCH: D3D_PRIMITIVE = 12;
pub const D3D_PRIMITIVE_6_CONTROL_POINT_PATCH: D3D_PRIMITIVE = 13;
pub const D3D_PRIMITIVE_7_CONTROL_POINT_PATCH: D3D_PRIMITIVE = 14;
pub const D3D_PRIMITIVE_8_CONTROL_POINT_PATCH: D3D_PRIMITIVE = 15;
pub const D3D_PRIMITIVE_9_CONTROL_POINT_PATCH: D3D_PRIMITIVE = 16;
pub const D3D_PRIMITIVE_LINE: D3D_PRIMITIVE = 2;
pub const D3D_PRIMITIVE_LINE_ADJ: D3D_PRIMITIVE = 6;
pub const D3D_PRIMITIVE_POINT: D3D_PRIMITIVE = 1;
pub type D3D_PRIMITIVE_TOPOLOGY = i32;
pub const D3D_PRIMITIVE_TOPOLOGY_10_CONTROL_POINT_PATCHLIST: D3D_PRIMITIVE_TOPOLOGY = 42;
pub const D3D_PRIMITIVE_TOPOLOGY_11_CONTROL_POINT_PATCHLIST: D3D_PRIMITIVE_TOPOLOGY = 43;
pub const D3D_PRIMITIVE_TOPOLOGY_12_CONTROL_POINT_PATCHLIST: D3D_PRIMITIVE_TOPOLOGY = 44;
pub const D3D_PRIMITIVE_TOPOLOGY_13_CONTROL_POINT_PATCHLIST: D3D_PRIMITIVE_TOPOLOGY = 45;
pub const D3D_PRIMITIVE_TOPOLOGY_14_CONTROL_POINT_PATCHLIST: D3D_PRIMITIVE_TOPOLOGY = 46;
pub const D3D_PRIMITIVE_TOPOLOGY_15_CONTROL_POINT_PATCHLIST: D3D_PRIMITIVE_TOPOLOGY = 47;
pub const D3D_PRIMITIVE_TOPOLOGY_16_CONTROL_POINT_PATCHLIST: D3D_PRIMITIVE_TOPOLOGY = 48;
pub const D3D_PRIMITIVE_TOPOLOGY_17_CONTROL_POINT_PATCHLIST: D3D_PRIMITIVE_TOPOLOGY = 49;
pub const D3D_PRIMITIVE_TOPOLOGY_18_CONTROL_POINT_PATCHLIST: D3D_PRIMITIVE_TOPOLOGY = 50;
pub const D3D_PRIMITIVE_TOPOLOGY_19_CONTROL_POINT_PATCHLIST: D3D_PRIMITIVE_TOPOLOGY = 51;
pub const D3D_PRIMITIVE_TOPOLOGY_1_CONTROL_POINT_PATCHLIST: D3D_PRIMITIVE_TOPOLOGY = 33;
pub const D3D_PRIMITIVE_TOPOLOGY_20_CONTROL_POINT_PATCHLIST: D3D_PRIMITIVE_TOPOLOGY = 52;
pub const D3D_PRIMITIVE_TOPOLOGY_21_CONTROL_POINT_PATCHLIST: D3D_PRIMITIVE_TOPOLOGY = 53;
pub const D3D_PRIMITIVE_TOPOLOGY_22_CONTROL_POINT_PATCHLIST: D3D_PRIMITIVE_TOPOLOGY = 54;
pub const D3D_PRIMITIVE_TOPOLOGY_23_CONTROL_POINT_PATCHLIST: D3D_PRIMITIVE_TOPOLOGY = 55;
pub const D3D_PRIMITIVE_TOPOLOGY_24_CONTROL_POINT_PATCHLIST: D3D_PRIMITIVE_TOPOLOGY = 56;
pub const D3D_PRIMITIVE_TOPOLOGY_25_CONTROL_POINT_PATCHLIST: D3D_PRIMITIVE_TOPOLOGY = 57;
pub const D3D_PRIMITIVE_TOPOLOGY_26_CONTROL_POINT_PATCHLIST: D3D_PRIMITIVE_TOPOLOGY = 58;
pub const D3D_PRIMITIVE_TOPOLOGY_27_CONTROL_POINT_PATCHLIST: D3D_PRIMITIVE_TOPOLOGY = 59;
pub const D3D_PRIMITIVE_TOPOLOGY_28_CONTROL_POINT_PATCHLIST: D3D_PRIMITIVE_TOPOLOGY = 60;
pub const D3D_PRIMITIVE_TOPOLOGY_29_CONTROL_POINT_PATCHLIST: D3D_PRIMITIVE_TOPOLOGY = 61;
pub const D3D_PRIMITIVE_TOPOLOGY_2_CONTROL_POINT_PATCHLIST: D3D_PRIMITIVE_TOPOLOGY = 34;
pub const D3D_PRIMITIVE_TOPOLOGY_30_CONTROL_POINT_PATCHLIST: D3D_PRIMITIVE_TOPOLOGY = 62;
pub const D3D_PRIMITIVE_TOPOLOGY_31_CONTROL_POINT_PATCHLIST: D3D_PRIMITIVE_TOPOLOGY = 63;
pub const D3D_PRIMITIVE_TOPOLOGY_32_CONTROL_POINT_PATCHLIST: D3D_PRIMITIVE_TOPOLOGY = 64;
pub const D3D_PRIMITIVE_TOPOLOGY_3_CONTROL_POINT_PATCHLIST: D3D_PRIMITIVE_TOPOLOGY = 35;
pub const D3D_PRIMITIVE_TOPOLOGY_4_CONTROL_POINT_PATCHLIST: D3D_PRIMITIVE_TOPOLOGY = 36;
pub const D3D_PRIMITIVE_TOPOLOGY_5_CONTROL_POINT_PATCHLIST: D3D_PRIMITIVE_TOPOLOGY = 37;
pub const D3D_PRIMITIVE_TOPOLOGY_6_CONTROL_POINT_PATCHLIST: D3D_PRIMITIVE_TOPOLOGY = 38;
pub const D3D_PRIMITIVE_TOPOLOGY_7_CONTROL_POINT_PATCHLIST: D3D_PRIMITIVE_TOPOLOGY = 39;
pub const D3D_PRIMITIVE_TOPOLOGY_8_CONTROL_POINT_PATCHLIST: D3D_PRIMITIVE_TOPOLOGY = 40;
pub const D3D_PRIMITIVE_TOPOLOGY_9_CONTROL_POINT_PATCHLIST: D3D_PRIMITIVE_TOPOLOGY = 41;
pub const D3D_PRIMITIVE_TOPOLOGY_LINELIST: D3D_PRIMITIVE_TOPOLOGY = 2;
pub const D3D_PRIMITIVE_TOPOLOGY_LINELIST_ADJ: D3D_PRIMITIVE_TOPOLOGY = 10;
pub const D3D_PRIMITIVE_TOPOLOGY_LINESTRIP: D3D_PRIMITIVE_TOPOLOGY = 3;
pub const D3D_PRIMITIVE_TOPOLOGY_LINESTRIP_ADJ: D3D_PRIMITIVE_TOPOLOGY = 11;
pub const D3D_PRIMITIVE_TOPOLOGY_POINTLIST: D3D_PRIMITIVE_TOPOLOGY = 1;
pub const D3D_PRIMITIVE_TOPOLOGY_TRIANGLEFAN: D3D_PRIMITIVE_TOPOLOGY = 6;
pub const D3D_PRIMITIVE_TOPOLOGY_TRIANGLELIST: D3D_PRIMITIVE_TOPOLOGY = 4;
pub const D3D_PRIMITIVE_TOPOLOGY_TRIANGLELIST_ADJ: D3D_PRIMITIVE_TOPOLOGY = 12;
pub const D3D_PRIMITIVE_TOPOLOGY_TRIANGLESTRIP: D3D_PRIMITIVE_TOPOLOGY = 5;
pub const D3D_PRIMITIVE_TOPOLOGY_TRIANGLESTRIP_ADJ: D3D_PRIMITIVE_TOPOLOGY = 13;
pub const D3D_PRIMITIVE_TOPOLOGY_UNDEFINED: D3D_PRIMITIVE_TOPOLOGY = 0;
pub const D3D_PRIMITIVE_TRIANGLE: D3D_PRIMITIVE = 3;
pub const D3D_PRIMITIVE_TRIANGLE_ADJ: D3D_PRIMITIVE = 7;
pub const D3D_PRIMITIVE_UNDEFINED: D3D_PRIMITIVE = 0;
pub const D3D_REGISTER_COMPONENT_FLOAT16: D3D_REGISTER_COMPONENT_TYPE = 6;
pub const D3D_REGISTER_COMPONENT_FLOAT32: D3D_REGISTER_COMPONENT_TYPE = 3;
pub const D3D_REGISTER_COMPONENT_FLOAT64: D3D_REGISTER_COMPONENT_TYPE = 9;
pub const D3D_REGISTER_COMPONENT_SINT16: D3D_REGISTER_COMPONENT_TYPE = 5;
pub const D3D_REGISTER_COMPONENT_SINT32: D3D_REGISTER_COMPONENT_TYPE = 2;
pub const D3D_REGISTER_COMPONENT_SINT64: D3D_REGISTER_COMPONENT_TYPE = 8;
pub type D3D_REGISTER_COMPONENT_TYPE = i32;
pub const D3D_REGISTER_COMPONENT_UINT16: D3D_REGISTER_COMPONENT_TYPE = 4;
pub const D3D_REGISTER_COMPONENT_UINT32: D3D_REGISTER_COMPONENT_TYPE = 1;
pub const D3D_REGISTER_COMPONENT_UINT64: D3D_REGISTER_COMPONENT_TYPE = 7;
pub const D3D_REGISTER_COMPONENT_UNKNOWN: D3D_REGISTER_COMPONENT_TYPE = 0;
pub type D3D_RESOURCE_RETURN_TYPE = i32;
pub const D3D_RETURN_TYPE_CONTINUED: D3D_RESOURCE_RETURN_TYPE = 8;
pub const D3D_RETURN_TYPE_DOUBLE: D3D_RESOURCE_RETURN_TYPE = 7;
pub const D3D_RETURN_TYPE_FLOAT: D3D_RESOURCE_RETURN_TYPE = 5;
pub const D3D_RETURN_TYPE_MIXED: D3D_RESOURCE_RETURN_TYPE = 6;
pub const D3D_RETURN_TYPE_SINT: D3D_RESOURCE_RETURN_TYPE = 3;
pub const D3D_RETURN_TYPE_SNORM: D3D_RESOURCE_RETURN_TYPE = 2;
pub const D3D_RETURN_TYPE_UINT: D3D_RESOURCE_RETURN_TYPE = 4;
pub const D3D_RETURN_TYPE_UNORM: D3D_RESOURCE_RETURN_TYPE = 1;
pub type D3D_SHADER_CBUFFER_FLAGS = i32;
pub const D3D_SHADER_FEATURE_11_1_DOUBLE_EXTENSIONS: u32 = 32;
pub const D3D_SHADER_FEATURE_11_1_SHADER_EXTENSIONS: u32 = 64;
pub const D3D_SHADER_FEATURE_64_UAVS: u32 = 8;
pub const D3D_SHADER_FEATURE_ADVANCED_TEXTURE_OPS: u32 = 536870912;
pub const D3D_SHADER_FEATURE_ATOMIC_INT64_ON_DESCRIPTOR_HEAP_RESOURCE: u32 = 268435456;
pub const D3D_SHADER_FEATURE_ATOMIC_INT64_ON_GROUP_SHARED: u32 = 8388608;
pub const D3D_SHADER_FEATURE_ATOMIC_INT64_ON_TYPED_RESOURCE: u32 = 4194304;
pub const D3D_SHADER_FEATURE_BARYCENTRICS: u32 = 131072;
pub const D3D_SHADER_FEATURE_COMPUTE_SHADERS_PLUS_RAW_AND_STRUCTURED_BUFFERS_VIA_SHADER_4_X: u32 = 2;
pub const D3D_SHADER_FEATURE_DERIVATIVES_IN_MESH_AND_AMPLIFICATION_SHADERS: u32 = 16777216;
pub const D3D_SHADER_FEATURE_DOUBLES: u32 = 1;
pub const D3D_SHADER_FEATURE_EXTENDED_COMMAND_INFO: u64 = 4294967296;
pub const D3D_SHADER_FEATURE_INNER_COVERAGE: u32 = 1024;
pub const D3D_SHADER_FEATURE_INT64_OPS: u32 = 32768;
pub const D3D_SHADER_FEATURE_LEVEL_9_COMPARISON_FILTERING: u32 = 128;
pub const D3D_SHADER_FEATURE_MINIMUM_PRECISION: u32 = 16;
pub const D3D_SHADER_FEATURE_NATIVE_16BIT_OPS: u32 = 262144;
pub const D3D_SHADER_FEATURE_RAYTRACING_TIER_1_1: u32 = 1048576;
pub const D3D_SHADER_FEATURE_RESOURCE_DESCRIPTOR_HEAP_INDEXING: u32 = 33554432;
pub const D3D_SHADER_FEATURE_ROVS: u32 = 4096;
pub const D3D_SHADER_FEATURE_SAMPLER_DESCRIPTOR_HEAP_INDEXING: u32 = 67108864;
pub const D3D_SHADER_FEATURE_SAMPLER_FEEDBACK: u32 = 2097152;
pub const D3D_SHADER_FEATURE_SAMPLE_CMP_GRADIENT_OR_BIAS: u32 = 2147483648;
pub const D3D_SHADER_FEATURE_SHADING_RATE: u32 = 524288;
pub const D3D_SHADER_FEATURE_STENCIL_REF: u32 = 512;
pub const D3D_SHADER_FEATURE_TILED_RESOURCES: u32 = 256;
pub const D3D_SHADER_FEATURE_TYPED_UAV_LOAD_ADDITIONAL_FORMATS: u32 = 2048;
pub const D3D_SHADER_FEATURE_UAVS_AT_EVERY_STAGE: u32 = 4;
pub const D3D_SHADER_FEATURE_VIEWPORT_AND_RT_ARRAY_INDEX_FROM_ANY_SHADER_FEEDING_RASTERIZER: u32 = 8192;
pub const D3D_SHADER_FEATURE_VIEW_ID: u32 = 65536;
pub const D3D_SHADER_FEATURE_WAVE_MMA: u32 = 134217728;
pub const D3D_SHADER_FEATURE_WAVE_OPS: u32 = 16384;
pub const D3D_SHADER_FEATURE_WRITEABLE_MSAA_TEXTURES: u32 = 1073741824;
pub type D3D_SHADER_INPUT_FLAGS = i32;
pub type D3D_SHADER_INPUT_TYPE = i32;
#[repr(C)]
#[derive(Clone, Copy, Debug, Default, PartialEq)]
pub struct D3D_SHADER_MACRO {
    pub Name: windows_core::PCSTR,
    pub Definition: windows_core::PCSTR,
}
pub type D3D_SHADER_VARIABLE_CLASS = i32;
pub type D3D_SHADER_VARIABLE_FLAGS = i32;
pub type D3D_SHADER_VARIABLE_TYPE = i32;
pub const D3D_SIF_COMPARISON_SAMPLER: D3D_SHADER_INPUT_FLAGS = 2;
pub const D3D_SIF_FORCE_DWORD: D3D_SHADER_INPUT_FLAGS = 2147483647;
pub const D3D_SIF_TEXTURE_COMPONENTS: D3D_SHADER_INPUT_FLAGS = 12;
pub const D3D_SIF_TEXTURE_COMPONENT_0: D3D_SHADER_INPUT_FLAGS = 4;
pub const D3D_SIF_TEXTURE_COMPONENT_1: D3D_SHADER_INPUT_FLAGS = 8;
pub const D3D_SIF_UNUSED: D3D_SHADER_INPUT_FLAGS = 16;
pub const D3D_SIF_USERPACKED: D3D_SHADER_INPUT_FLAGS = 1;
pub const D3D_SIT_BYTEADDRESS: D3D_SHADER_INPUT_TYPE = 7;
pub const D3D_SIT_CBUFFER: D3D_SHADER_INPUT_TYPE = 0;
pub const D3D_SIT_RTACCELERATIONSTRUCTURE: D3D_SHADER_INPUT_TYPE = 12;
pub const D3D_SIT_SAMPLER: D3D_SHADER_INPUT_TYPE = 3;
pub const D3D_SIT_STRUCTURED: D3D_SHADER_INPUT_TYPE = 5;
pub const D3D_SIT_TBUFFER: D3D_SHADER_INPUT_TYPE = 1;
pub const D3D_SIT_TEXTURE: D3D_SHADER_INPUT_TYPE = 2;
pub const D3D_SIT_UAV_APPEND_STRUCTURED: D3D_SHADER_INPUT_TYPE = 9;
pub const D3D_SIT_UAV_CONSUME_STRUCTURED: D3D_SHADER_INPUT_TYPE = 10;
pub const D3D_SIT_UAV_FEEDBACKTEXTURE: D3D_SHADER_INPUT_TYPE = 13;
pub const D3D_SIT_UAV_RWBYTEADDRESS: D3D_SHADER_INPUT_TYPE = 8;
pub const D3D_SIT_UAV_RWSTRUCTURED: D3D_SHADER_INPUT_TYPE = 6;
pub const D3D_SIT_UAV_RWSTRUCTURED_WITH_COUNTER: D3D_SHADER_INPUT_TYPE = 11;
pub const D3D_SIT_UAV_RWTYPED: D3D_SHADER_INPUT_TYPE = 4;
pub type D3D_SRV_DIMENSION = i32;
pub const D3D_SRV_DIMENSION_BUFFER: D3D_SRV_DIMENSION = 1;
pub const D3D_SRV_DIMENSION_BUFFEREX: D3D_SRV_DIMENSION = 11;
pub const D3D_SRV_DIMENSION_TEXTURE1D: D3D_SRV_DIMENSION = 2;
pub const D3D_SRV_DIMENSION_TEXTURE1DARRAY: D3D_SRV_DIMENSION = 3;
pub const D3D_SRV_DIMENSION_TEXTURE2D: D3D_SRV_DIMENSION = 4;
pub const D3D_SRV_DIMENSION_TEXTURE2DARRAY: D3D_SRV_DIMENSION = 5;
pub const D3D_SRV_DIMENSION_TEXTURE2DMS: D3D_SRV_DIMENSION = 6;
pub const D3D_SRV_DIMENSION_TEXTURE2DMSARRAY: D3D_SRV_DIMENSION = 7;
pub const D3D_SRV_DIMENSION_TEXTURE3D: D3D_SRV_DIMENSION = 8;
pub const D3D_SRV_DIMENSION_TEXTURECUBE: D3D_SRV_DIMENSION = 9;
pub const D3D_SRV_DIMENSION_TEXTURECUBEARRAY: D3D_SRV_DIMENSION = 10;
pub const D3D_SRV_DIMENSION_UNKNOWN: D3D_SRV_DIMENSION = 0;
pub const D3D_SVC_FORCE_DWORD: D3D_SHADER_VARIABLE_CLASS = 2147483647;
pub const D3D_SVC_INTERFACE_CLASS: D3D_SHADER_VARIABLE_CLASS = 6;
pub const D3D_SVC_INTERFACE_POINTER: D3D_SHADER_VARIABLE_CLASS = 7;
pub const D3D_SVC_MATRIX_COLUMNS: D3D_SHADER_VARIABLE_CLASS = 3;
pub const D3D_SVC_MATRIX_ROWS: D3D_SHADER_VARIABLE_CLASS = 2;
pub const D3D_SVC_OBJECT: D3D_SHADER_VARIABLE_CLASS = 4;
pub const D3D_SVC_SCALAR: D3D_SHADER_VARIABLE_CLASS = 0;
pub const D3D_SVC_STRUCT: D3D_SHADER_VARIABLE_CLASS = 5;
pub const D3D_SVC_VECTOR: D3D_SHADER_VARIABLE_CLASS = 1;
pub const D3D_SVF_FORCE_DWORD: D3D_SHADER_VARIABLE_FLAGS = 2147483647;
pub const D3D_SVF_INTERFACE_PARAMETER: D3D_SHADER_VARIABLE_FLAGS = 8;
pub const D3D_SVF_INTERFACE_POINTER: D3D_SHADER_VARIABLE_FLAGS = 4;
pub const D3D_SVF_USED: D3D_SHADER_VARIABLE_FLAGS = 2;
pub const D3D_SVF_USERPACKED: D3D_SHADER_VARIABLE_FLAGS = 1;
pub const D3D_SVT_APPEND_STRUCTURED_BUFFER: D3D_SHADER_VARIABLE_TYPE = 50;
pub const D3D_SVT_BLEND: D3D_SHADER_VARIABLE_TYPE = 24;
pub const D3D_SVT_BOOL: D3D_SHADER_VARIABLE_TYPE = 1;
pub const D3D_SVT_BUFFER: D3D_SHADER_VARIABLE_TYPE = 25;
pub const D3D_SVT_BYTEADDRESS_BUFFER: D3D_SHADER_VARIABLE_TYPE = 46;
pub const D3D_SVT_CBUFFER: D3D_SHADER_VARIABLE_TYPE = 26;
pub const D3D_SVT_COMPUTESHADER: D3D_SHADER_VARIABLE_TYPE = 38;
pub const D3D_SVT_CONSUME_STRUCTURED_BUFFER: D3D_SHADER_VARIABLE_TYPE = 51;
pub const D3D_SVT_DEPTHSTENCIL: D3D_SHADER_VARIABLE_TYPE = 23;
pub const D3D_SVT_DEPTHSTENCILVIEW: D3D_SHADER_VARIABLE_TYPE = 31;
pub const D3D_SVT_DOMAINSHADER: D3D_SHADER_VARIABLE_TYPE = 36;
pub const D3D_SVT_DOUBLE: D3D_SHADER_VARIABLE_TYPE = 39;
pub const D3D_SVT_FLOAT: D3D_SHADER_VARIABLE_TYPE = 3;
pub const D3D_SVT_FLOAT16: D3D_SHADER_VARIABLE_TYPE = 60;
pub const D3D_SVT_FORCE_DWORD: D3D_SHADER_VARIABLE_TYPE = 2147483647;
pub const D3D_SVT_GEOMETRYSHADER: D3D_SHADER_VARIABLE_TYPE = 21;
pub const D3D_SVT_HULLSHADER: D3D_SHADER_VARIABLE_TYPE = 35;
pub const D3D_SVT_INT: D3D_SHADER_VARIABLE_TYPE = 2;
pub const D3D_SVT_INT16: D3D_SHADER_VARIABLE_TYPE = 58;
pub const D3D_SVT_INT64: D3D_SHADER_VARIABLE_TYPE = 61;
pub const D3D_SVT_INTERFACE_POINTER: D3D_SHADER_VARIABLE_TYPE = 37;
pub const D3D_SVT_MIN10FLOAT: D3D_SHADER_VARIABLE_TYPE = 53;
pub const D3D_SVT_MIN12INT: D3D_SHADER_VARIABLE_TYPE = 55;
pub const D3D_SVT_MIN16FLOAT: D3D_SHADER_VARIABLE_TYPE = 54;
pub const D3D_SVT_MIN16INT: D3D_SHADER_VARIABLE_TYPE = 56;
pub const D3D_SVT_MIN16UINT: D3D_SHADER_VARIABLE_TYPE = 57;
pub const D3D_SVT_MIN8FLOAT: D3D_SHADER_VARIABLE_TYPE = 52;
pub const D3D_SVT_PIXELFRAGMENT: D3D_SHADER_VARIABLE_TYPE = 17;
pub const D3D_SVT_PIXELSHADER: D3D_SHADER_VARIABLE_TYPE = 15;
pub const D3D_SVT_RASTERIZER: D3D_SHADER_VARIABLE_TYPE = 22;
pub const D3D_SVT_RENDERTARGETVIEW: D3D_SHADER_VARIABLE_TYPE = 30;
pub const D3D_SVT_RWBUFFER: D3D_SHADER_VARIABLE_TYPE = 45;
pub const D3D_SVT_RWBYTEADDRESS_BUFFER: D3D_SHADER_VARIABLE_TYPE = 47;
pub const D3D_SVT_RWSTRUCTURED_BUFFER: D3D_SHADER_VARIABLE_TYPE = 49;
pub const D3D_SVT_RWTEXTURE1D: D3D_SHADER_VARIABLE_TYPE = 40;
pub const D3D_SVT_RWTEXTURE1DARRAY: D3D_SHADER_VARIABLE_TYPE = 41;
pub const D3D_SVT_RWTEXTURE2D: D3D_SHADER_VARIABLE_TYPE = 42;
pub const D3D_SVT_RWTEXTURE2DARRAY: D3D_SHADER_VARIABLE_TYPE = 43;
pub const D3D_SVT_RWTEXTURE3D: D3D_SHADER_VARIABLE_TYPE = 44;
pub const D3D_SVT_SAMPLER: D3D_SHADER_VARIABLE_TYPE = 10;
pub const D3D_SVT_SAMPLER1D: D3D_SHADER_VARIABLE_TYPE = 11;
pub const D3D_SVT_SAMPLER2D: D3D_SHADER_VARIABLE_TYPE = 12;
pub const D3D_SVT_SAMPLER3D: D3D_SHADER_VARIABLE_TYPE = 13;
pub const D3D_SVT_SAMPLERCUBE: D3D_SHADER_VARIABLE_TYPE = 14;
pub const D3D_SVT_STRING: D3D_SHADER_VARIABLE_TYPE = 4;
pub const D3D_SVT_STRUCTURED_BUFFER: D3D_SHADER_VARIABLE_TYPE = 48;
pub const D3D_SVT_TBUFFER: D3D_SHADER_VARIABLE_TYPE = 27;
pub const D3D_SVT_TEXTURE: D3D_SHADER_VARIABLE_TYPE = 5;
pub const D3D_SVT_TEXTURE1D: D3D_SHADER_VARIABLE_TYPE = 6;
pub const D3D_SVT_TEXTURE1DARRAY: D3D_SHADER_VARIABLE_TYPE = 28;
pub const D3D_SVT_TEXTURE2D: D3D_SHADER_VARIABLE_TYPE = 7;
pub const D3D_SVT_TEXTURE2DARRAY: D3D_SHADER_VARIABLE_TYPE = 29;
pub const D3D_SVT_TEXTURE2DMS: D3D_SHADER_VARIABLE_TYPE = 32;
pub const D3D_SVT_TEXTURE2DMSARRAY: D3D_SHADER_VARIABLE_TYPE = 33;
pub const D3D_SVT_TEXTURE3D: D3D_SHADER_VARIABLE_TYPE = 8;
pub const D3D_SVT_TEXTURECUBE: D3D_SHADER_VARIABLE_TYPE = 9;
pub const D3D_SVT_TEXTURECUBEARRAY: D3D_SHADER_VARIABLE_TYPE = 34;
pub const D3D_SVT_UINT: D3D_SHADER_VARIABLE_TYPE = 19;
pub const D3D_SVT_UINT16: D3D_SHADER_VARIABLE_TYPE = 59;
pub const D3D_SVT_UINT64: D3D_SHADER_VARIABLE_TYPE = 62;
pub const D3D_SVT_UINT8: D3D_SHADER_VARIABLE_TYPE = 20;
pub const D3D_SVT_VERTEXFRAGMENT: D3D_SHADER_VARIABLE_TYPE = 18;
pub const D3D_SVT_VERTEXSHADER: D3D_SHADER_VARIABLE_TYPE = 16;
pub const D3D_SVT_VOID: D3D_SHADER_VARIABLE_TYPE = 0;
pub type D3D_TESSELLATOR_DOMAIN = i32;
pub const D3D_TESSELLATOR_DOMAIN_ISOLINE: D3D_TESSELLATOR_DOMAIN = 1;
pub const D3D_TESSELLATOR_DOMAIN_QUAD: D3D_TESSELLATOR_DOMAIN = 3;
pub const D3D_TESSELLATOR_DOMAIN_TRI: D3D_TESSELLATOR_DOMAIN = 2;
pub const D3D_TESSELLATOR_DOMAIN_UNDEFINED: D3D_TESSELLATOR_DOMAIN = 0;
pub const D3D_TESSELLATOR_OUTPUT_LINE: D3D_TESSELLATOR_OUTPUT_PRIMITIVE = 2;
pub const D3D_TESSELLATOR_OUTPUT_POINT: D3D_TESSELLATOR_OUTPUT_PRIMITIVE = 1;
pub type D3D_TESSELLATOR_OUTPUT_PRIMITIVE = i32;
pub const D3D_TESSELLATOR_OUTPUT_TRIANGLE_CCW: D3D_TESSELLATOR_OUTPUT_PRIMITIVE = 4;
pub const D3D_TESSELLATOR_OUTPUT_TRIANGLE_CW: D3D_TESSELLATOR_OUTPUT_PRIMITIVE = 3;
pub const D3D_TESSELLATOR_OUTPUT_UNDEFINED: D3D_TESSELLATOR_OUTPUT_PRIMITIVE = 0;
pub type D3D_TESSELLATOR_PARTITIONING = i32;
pub const D3D_TESSELLATOR_PARTITIONING_FRACTIONAL_EVEN: D3D_TESSELLATOR_PARTITIONING = 4;
pub const D3D_TESSELLATOR_PARTITIONING_FRACTIONAL_ODD: D3D_TESSELLATOR_PARTITIONING = 3;
pub const D3D_TESSELLATOR_PARTITIONING_INTEGER: D3D_TESSELLATOR_PARTITIONING = 1;
pub const D3D_TESSELLATOR_PARTITIONING_POW2: D3D_TESSELLATOR_PARTITIONING = 2;
pub const D3D_TESSELLATOR_PARTITIONING_UNDEFINED: D3D_TESSELLATOR_PARTITIONING = 0;
pub const D3D_TEXTURE_LAYOUT_64KB_STANDARD_SWIZZLE: windows_core::GUID = windows_core::GUID::from_u128(0x4c0f29e3_3f5f_4d35_84c9_bc0983b62c28);
pub const D3D_TEXTURE_LAYOUT_ROW_MAJOR: windows_core::GUID = windows_core::GUID::from_u128(0xb5dc234f_72bb_4bec_9705_8cf258df6b6c);
windows_core::imp::define_interface!(ID3D10Blob, ID3D10Blob_Vtbl, 0x8ba5fb08_5195_40e2_ac58_0d989c3a0102);
windows_core::imp::interface_hierarchy!(ID3D10Blob, windows_core::IUnknown);
impl ID3D10Blob {
    pub unsafe fn GetBufferPointer(&self) -> *mut core::ffi::c_void {
        unsafe { (windows_core::Interface::vtable(self).GetBufferPointer)(windows_core::Interface::as_raw(self)) }
    }
    pub unsafe fn GetBufferSize(&self) -> usize {
        unsafe { (windows_core::Interface::vtable(self).GetBufferSize)(windows_core::Interface::as_raw(self)) }
    }
}
#[repr(C)]
#[doc(hidden)]
pub struct ID3D10Blob_Vtbl {
    pub base__: windows_core::IUnknown_Vtbl,
    pub GetBufferPointer: unsafe extern "system" fn(*mut core::ffi::c_void) -> *mut core::ffi::c_void,
    pub GetBufferSize: unsafe extern "system" fn(*mut core::ffi::c_void) -> usize,
}
pub trait ID3D10Blob_Impl: windows_core::IUnknownImpl {
    fn GetBufferPointer(&self) -> *mut core::ffi::c_void;
    fn GetBufferSize(&self) -> usize;
}
impl ID3D10Blob_Vtbl {
    pub const fn new<Identity: ID3D10Blob_Impl, const OFFSET: isize>() -> Self {
        unsafe extern "system" fn GetBufferPointer<Identity: ID3D10Blob_Impl, const OFFSET: isize>(this: *mut core::ffi::c_void) -> *mut core::ffi::c_void {
            unsafe {
                let this: &Identity = &*((this as *const *const ()).offset(OFFSET) as *const Identity);
                ID3D10Blob_Impl::GetBufferPointer(this)
            }
        }
        unsafe extern "system" fn GetBufferSize<Identity: ID3D10Blob_Impl, const OFFSET: isize>(this: *mut core::ffi::c_void) -> usize {
            unsafe {
                let this: &Identity = &*((this as *const *const ()).offset(OFFSET) as *const Identity);
                ID3D10Blob_Impl::GetBufferSize(this)
            }
        }
        Self {
            base__: windows_core::IUnknown_Vtbl::new::<Identity, OFFSET>(),
            GetBufferPointer: GetBufferPointer::<Identity, OFFSET>,
            GetBufferSize: GetBufferSize::<Identity, OFFSET>,
        }
    }
    pub fn matches(iid: &windows_core::GUID) -> bool {
        iid == &<ID3D10Blob as windows_core::Interface>::IID
    }
}
impl windows_core::RuntimeName for ID3D10Blob {}
windows_core::imp::define_interface!(ID3DDestructionNotifier, ID3DDestructionNotifier_Vtbl, 0xa06eb39a_50da_425b_8c31_4eecd6c270f3);
windows_core::imp::interface_hierarchy!(ID3DDestructionNotifier, windows_core::IUnknown);
impl ID3DDestructionNotifier {
    pub unsafe fn RegisterDestructionCallback(&self, callbackfn: PFN_DESTRUCTION_CALLBACK, pdata: *const core::ffi::c_void) -> windows_core::Result<u32> {
        unsafe {
            let mut result__ = core::mem::zeroed();
            (windows_core::Interface::vtable(self).RegisterDestructionCallback)(windows_core::Interface::as_raw(self), callbackfn, pdata, &mut result__).map(|| result__)
        }
    }
    pub unsafe fn UnregisterDestructionCallback(&self, callbackid: u32) -> windows_core::HRESULT {
        unsafe { (windows_core::Interface::vtable(self).UnregisterDestructionCallback)(windows_core::Interface::as_raw(self), callbackid) }
    }
}
#[repr(C)]
#[doc(hidden)]
pub struct ID3DDestructionNotifier_Vtbl {
    pub base__: windows_core::IUnknown_Vtbl,
    pub RegisterDestructionCallback: unsafe extern "system" fn(*mut core::ffi::c_void, PFN_DESTRUCTION_CALLBACK, *const core::ffi::c_void, *mut u32) -> windows_core::HRESULT,
    pub UnregisterDestructionCallback: unsafe extern "system" fn(*mut core::ffi::c_void, u32) -> windows_core::HRESULT,
}
pub trait ID3DDestructionNotifier_Impl: windows_core::IUnknownImpl {
    fn RegisterDestructionCallback(&self, callbackfn: PFN_DESTRUCTION_CALLBACK, pdata: *const core::ffi::c_void) -> windows_core::Result<u32>;
    fn UnregisterDestructionCallback(&self, callbackid: u32) -> windows_core::Result<()>;
}
impl ID3DDestructionNotifier_Vtbl {
    pub const fn new<Identity: ID3DDestructionNotifier_Impl, const OFFSET: isize>() -> Self {
        unsafe extern "system" fn RegisterDestructionCallback<Identity: ID3DDestructionNotifier_Impl, const OFFSET: isize>(this: *mut core::ffi::c_void, callbackfn: PFN_DESTRUCTION_CALLBACK, pdata: *const core::ffi::c_void, pcallbackid: *mut u32) -> windows_core::HRESULT {
            unsafe {
                let this: &Identity = &*((this as *const *const ()).offset(OFFSET) as *const Identity);
                match ID3DDestructionNotifier_Impl::RegisterDestructionCallback(this, core::mem::transmute_copy(&callbackfn), core::mem::transmute_copy(&pdata)) {
                    Ok(ok__) => {
                        pcallbackid.write(ok__);
                        windows_core::HRESULT(0)
                    }
                    Err(err) => err.into(),
                }
            }
        }
        unsafe extern "system" fn UnregisterDestructionCallback<Identity: ID3DDestructionNotifier_Impl, const OFFSET: isize>(this: *mut core::ffi::c_void, callbackid: u32) -> windows_core::HRESULT {
            unsafe {
                let this: &Identity = &*((this as *const *const ()).offset(OFFSET) as *const Identity);
                ID3DDestructionNotifier_Impl::UnregisterDestructionCallback(this, core::mem::transmute_copy(&callbackid)).into()
            }
        }
        Self {
            base__: windows_core::IUnknown_Vtbl::new::<Identity, OFFSET>(),
            RegisterDestructionCallback: RegisterDestructionCallback::<Identity, OFFSET>,
            UnregisterDestructionCallback: UnregisterDestructionCallback::<Identity, OFFSET>,
        }
    }
    pub fn matches(iid: &windows_core::GUID) -> bool {
        iid == &<ID3DDestructionNotifier as windows_core::Interface>::IID
    }
}
impl windows_core::RuntimeName for ID3DDestructionNotifier {}
windows_core::imp::define_interface!(ID3DInclude, ID3DInclude_Vtbl);
impl ID3DInclude {
    pub unsafe fn Open<P1>(&self, includetype: D3D_INCLUDE_TYPE, pfilename: P1, pparentdata: *const core::ffi::c_void, ppdata: *mut *mut core::ffi::c_void, pbytes: *mut u32) -> windows_core::HRESULT
    where
        P1: windows_core::Param<windows_core::PCSTR>,
    {
        unsafe { (windows_core::Interface::vtable(self).Open)(windows_core::Interface::as_raw(self), includetype, pfilename.param().abi(), pparentdata, ppdata as _, pbytes as _) }
    }
    pub unsafe fn Close(&self, pdata: *const core::ffi::c_void) -> windows_core::HRESULT {
        unsafe { (windows_core::Interface::vtable(self).Close)(windows_core::Interface::as_raw(self), pdata) }
    }
}
#[repr(C)]
#[doc(hidden)]
pub struct ID3DInclude_Vtbl {
    pub Open: unsafe extern "system" fn(*mut core::ffi::c_void, D3D_INCLUDE_TYPE, windows_core::PCSTR, *const core::ffi::c_void, *mut *mut core::ffi::c_void, *mut u32) -> windows_core::HRESULT,
    pub Close: unsafe extern "system" fn(*mut core::ffi::c_void, *const core::ffi::c_void) -> windows_core::HRESULT,
}
pub trait ID3DInclude_Impl {
    fn Open(&self, includetype: D3D_INCLUDE_TYPE, pfilename: &windows_core::PCSTR, pparentdata: *const core::ffi::c_void, ppdata: *mut *mut core::ffi::c_void, pbytes: *mut u32) -> windows_core::Result<()>;
    fn Close(&self, pdata: *const core::ffi::c_void) -> windows_core::Result<()>;
}
impl ID3DInclude_Vtbl {
    pub const fn new<Identity: ID3DInclude_Impl>() -> Self {
        unsafe extern "system" fn Open<Identity: ID3DInclude_Impl>(this: *mut core::ffi::c_void, includetype: D3D_INCLUDE_TYPE, pfilename: windows_core::PCSTR, pparentdata: *const core::ffi::c_void, ppdata: *mut *mut core::ffi::c_void, pbytes: *mut u32) -> windows_core::HRESULT {
            unsafe {
                let this = (this as *mut *mut core::ffi::c_void) as *const windows_core::ScopedHeap;
                let this = &*((*this).this as *const Identity);
                ID3DInclude_Impl::Open(this, core::mem::transmute_copy(&includetype), core::mem::transmute(&pfilename), core::mem::transmute_copy(&pparentdata), core::mem::transmute_copy(&ppdata), core::mem::transmute_copy(&pbytes)).into()
            }
        }
        unsafe extern "system" fn Close<Identity: ID3DInclude_Impl>(this: *mut core::ffi::c_void, pdata: *const core::ffi::c_void) -> windows_core::HRESULT {
            unsafe {
                let this = (this as *mut *mut core::ffi::c_void) as *const windows_core::ScopedHeap;
                let this = &*((*this).this as *const Identity);
                ID3DInclude_Impl::Close(this, core::mem::transmute_copy(&pdata)).into()
            }
        }
        Self { Open: Open::<Identity>, Close: Close::<Identity> }
    }
}
struct ID3DInclude_ImplVtbl<T: ID3DInclude_Impl>(core::marker::PhantomData<T>);
impl<T: ID3DInclude_Impl> ID3DInclude_ImplVtbl<T> {
    const VTABLE: ID3DInclude_Vtbl = ID3DInclude_Vtbl::new::<T>();
}
impl ID3DInclude {
    pub fn new<'a, T: ID3DInclude_Impl>(this: &'a T) -> windows_core::ScopedInterface<'a, Self> {
        let this = windows_core::ScopedHeap { vtable: &ID3DInclude_ImplVtbl::<T>::VTABLE as *const _ as *const _, this: this as *const _ as *const _ };
        let this = core::mem::ManuallyDrop::new(windows_core::imp::box_new(this));
        unsafe { windows_core::ScopedInterface::new(core::mem::transmute(&this.vtable)) }
    }
}
pub type LPD3D_SHADER_MACRO = *mut D3D_SHADER_MACRO;
pub type PFN_DESTRUCTION_CALLBACK = Option<unsafe extern "system" fn(pdata: *mut core::ffi::c_void)>;
pub const WKPDID_CommentStringW: windows_core::GUID = windows_core::GUID::from_u128(0xd0149dc0_90e8_4ec8_8144_e900ad266bb2);
pub const WKPDID_D3D12UniqueObjectId: windows_core::GUID = windows_core::GUID::from_u128(0x1b39de15_ec04_4bae_ba4d_8cef79fc04c1);
pub const WKPDID_D3DDebugObjectName: windows_core::GUID = windows_core::GUID::from_u128(0x429b8c22_9188_4b0c_8742_acb0bf85c200);
pub const WKPDID_D3DDebugObjectNameW: windows_core::GUID = windows_core::GUID::from_u128(0x4cca5fd8_921f_42c8_8566_70caf2a9b741);
