/// Shared helpers for the code generators.
use proc_macro2::{Ident, Span, TokenStream};

/// Create an `Ident` from a string.
pub fn ident(s: &str) -> Ident {
    Ident::new(s, Span::call_site())
}

/// Convert `PascalCase` to `snake_case`.
pub fn to_snake_case(s: &str) -> String {
    let mut out = String::with_capacity(s.len() + 4);
    for (i, ch) in s.chars().enumerate() {
        if ch.is_uppercase() && i > 0 {
            out.push('_');
        }
        out.push(ch.to_ascii_lowercase());
    }
    out
}

/// Format a `TokenStream` into a string with the auto-generated header.
pub fn format_generated(tokens: TokenStream) -> String {
    let code = tokens.to_string();
    format!("// This file is auto-generated by tool_reactor_codegen. Do not edit.\n\n{code}\n")
}
