use super::*;

impl Config<'_> {
    pub fn format(&self, tokens: &str) -> String {
        let preamble = if self.no_comment {
            String::new()
        } else {
            let version = std::env!("CARGO_PKG_VERSION");

            format!(
                r#"// Bindings generated by `windows-bindgen` {version}


"#
            )
        };

        let allow = if self.no_allow {
            ""
        } else {
            "#![allow(non_snake_case, non_upper_case_globals, non_camel_case_types, dead_code, clippy::all)]\n\n"
        };
        let tokens = format!("{preamble}{allow}{tokens}");

        windows_fmt::rust(tokens, self.rustfmt)
    }
}
