//
// Copyright (c) Microsoft Corporation.  All rights reserved.
//

cpp_quote("#include <winapifamily.h>")

cpp_quote("#if WINAPI_FAMILY_PARTITION(WINAPI_PARTITION_DESKTOP | WINAPI_PARTITION_SYSTEM)")

cpp_quote("#if (NTDDI_VERSION >= NTDDI_WIN10)")

import "oaidl.idl";

typedef struct NOTIFICATION_USER_INPUT_DATA
{
    LPCWSTR Key;
    LPCWSTR Value;
} NOTIFICATION_USER_INPUT_DATA;

[
    object,
    uuid("53E31837-6600-4A81-9395-75CFFE746F94"),
    pointer_default(ref)
]
interface INotificationActivationCallback : IUnknown
{
    HRESULT Activate(
        [in, string] LPCWSTR appUserModelId,
        [in, string, unique] LPCWSTR invokedArgs,
        [in, size_is(count), unique] const NOTIFICATION_USER_INPUT_DATA* data,
        [in] ULONG count);
};

cpp_quote("#endif // NTDDI_WIN10")

cpp_quote("#endif /* WINAPI_FAMILY_PARTITION(WINAPI_PARTITION_DESKTOP | WINAPI_PARTITION_SYSTEM) */")
