pub type AUTHENTICATION_LEVEL = i32;
pub const INCOMING_AUTHENTICATION_REQUIRED: AUTHENTICATION_LEVEL = 1;
pub const MUTUAL_AUTHENTICATION_REQUIRED: AUTHENTICATION_LEVEL = 2;
pub const NO_AUTHENTICATION_REQUIRED: AUTHENTICATION_LEVEL = 0;
