[package]
name = "tool_reactor_next"
version = "0.0.0"
edition = "2024"
rust-version = "1.95"
publish = false

[dependencies]
proc-macro2 = { workspace = true }
quote = { workspace = true }
serde = { workspace = true, features = ["derive"] }
toml = "0.8"
tool_reactor = { path = "../reactor" }
windows-bindgen = { workspace = true }

[lints]
workspace = true
