#[cfg(feature = "Win32_accctrl")]
pub mod accctrl;
#[cfg(feature = "Win32_aclapi")]
pub mod aclapi;
#[cfg(feature = "Win32_activation")]
pub mod activation;
#[cfg(feature = "Win32_adshlp")]
pub mod adshlp;
#[cfg(feature = "Win32_adtgen")]
pub mod adtgen;
#[cfg(feature = "Win32_afunix")]
pub mod afunix;
#[cfg(feature = "Win32_amsi")]
pub mod amsi;
#[cfg(feature = "Win32_amvideo")]
pub mod amvideo;
#[cfg(feature = "Win32_appmodel")]
pub mod appmodel;
#[cfg(feature = "Win32_appxpackaging")]
pub mod appxpackaging;
#[cfg(feature = "Win32_asferr")]
pub mod asferr;
#[cfg(feature = "Win32_audevcod")]
pub mod audevcod;
#[cfg(feature = "Win32_audioclient")]
pub mod audioclient;
#[cfg(feature = "Win32_audioclientactivationparams")]
pub mod audioclientactivationparams;
#[cfg(feature = "Win32_audiosessiontypes")]
pub mod audiosessiontypes;
#[cfg(feature = "Win32_authz")]
pub mod authz;
#[cfg(feature = "Win32_avrt")]
pub mod avrt;
#[cfg(feature = "Win32_basetsd")]
pub mod basetsd;
#[cfg(feature = "Win32_batclass")]
pub mod batclass;
#[cfg(feature = "Win32_bcrypt")]
pub mod bcrypt;
#[cfg(feature = "Win32_bdaiface")]
pub mod bdaiface;
#[cfg(feature = "Win32_bdatypes")]
pub mod bdatypes;
#[cfg(feature = "Win32_bits")]
pub mod bits;
#[cfg(feature = "Win32_bits10_1")]
pub mod bits10_1;
#[cfg(feature = "Win32_bits10_2")]
pub mod bits10_2;
#[cfg(feature = "Win32_bits10_3")]
pub mod bits10_3;
#[cfg(feature = "Win32_bits1_5")]
pub mod bits1_5;
#[cfg(feature = "Win32_bits2_0")]
pub mod bits2_0;
#[cfg(feature = "Win32_bits2_5")]
pub mod bits2_5;
#[cfg(feature = "Win32_bits3_0")]
pub mod bits3_0;
#[cfg(feature = "Win32_bits4_0")]
pub mod bits4_0;
#[cfg(feature = "Win32_bits5_0")]
pub mod bits5_0;
#[cfg(feature = "Win32_bitsmsg")]
pub mod bitsmsg;
#[cfg(feature = "Win32_bluetoothapis")]
pub mod bluetoothapis;
#[cfg(feature = "Win32_bthdef")]
pub mod bthdef;
#[cfg(feature = "Win32_bthledef")]
pub mod bthledef;
#[cfg(feature = "Win32_bthsdpdef")]
pub mod bthsdpdef;
#[cfg(feature = "Win32_cderr")]
pub mod cderr;
#[cfg(feature = "Win32_certadm")]
pub mod certadm;
#[cfg(feature = "Win32_certbase")]
pub mod certbase;
#[cfg(feature = "Win32_certbcli")]
pub mod certbcli;
#[cfg(feature = "Win32_certcli")]
pub mod certcli;
#[cfg(feature = "Win32_certenc")]
pub mod certenc;
#[cfg(feature = "Win32_certenroll")]
pub mod certenroll;
#[cfg(feature = "Win32_certexit")]
pub mod certexit;
#[cfg(feature = "Win32_certif")]
pub mod certif;
#[cfg(feature = "Win32_certmod")]
pub mod certmod;
#[cfg(feature = "Win32_certpol")]
pub mod certpol;
#[cfg(feature = "Win32_certsrv")]
pub mod certsrv;
#[cfg(feature = "Win32_certview")]
pub mod certview;
#[cfg(feature = "Win32_cfapi")]
pub mod cfapi;
#[cfg(feature = "Win32_cfg")]
pub mod cfg;
#[cfg(feature = "Win32_cfgmgr32")]
pub mod cfgmgr32;
#[cfg(feature = "Win32_clfs")]
pub mod clfs;
#[cfg(feature = "Win32_clfsw32")]
pub mod clfsw32;
#[cfg(feature = "Win32_clusapi")]
pub mod clusapi;
#[cfg(feature = "Win32_codecapi")]
pub mod codecapi;
#[cfg(feature = "Win32_comadmin")]
pub mod comadmin;
#[cfg(feature = "Win32_combaseapi")]
pub mod combaseapi;
#[cfg(feature = "Win32_comcat")]
pub mod comcat;
#[cfg(feature = "Win32_coml2api")]
pub mod coml2api;
#[cfg(feature = "Win32_commctrl")]
pub mod commctrl;
#[cfg(feature = "Win32_commdlg")]
pub mod commdlg;
#[cfg(feature = "Win32_commoncontrols")]
pub mod commoncontrols;
#[cfg(feature = "Win32_compressapi")]
pub mod compressapi;
#[cfg(feature = "Win32_compstui")]
pub mod compstui;
#[cfg(feature = "Win32_comsvcs")]
pub mod comsvcs;
#[cfg(feature = "Win32_consoleapi")]
pub mod consoleapi;
#[cfg(feature = "Win32_consoleapi2")]
pub mod consoleapi2;
#[cfg(feature = "Win32_consoleapi3")]
pub mod consoleapi3;
#[cfg(feature = "Win32_control")]
pub mod control;
#[cfg(feature = "Win32_corecrt")]
pub mod corecrt;
#[cfg(feature = "Win32_corecrt_wstdio")]
pub mod corecrt_wstdio;
#[cfg(feature = "Win32_corewindow")]
pub mod corewindow;
#[cfg(feature = "Win32_credentialprovider")]
pub mod credentialprovider;
#[cfg(feature = "Win32_cryptuiapi")]
pub mod cryptuiapi;
#[cfg(feature = "Win32_cryptxml")]
pub mod cryptxml;
#[cfg(feature = "Win32_ctfutb")]
pub mod ctfutb;
#[cfg(feature = "Win32_d2d1")]
pub mod d2d1;
#[cfg(feature = "Win32_d2d1_1")]
pub mod d2d1_1;
#[cfg(feature = "Win32_d2d1_2")]
pub mod d2d1_2;
#[cfg(feature = "Win32_d2d1_3")]
pub mod d2d1_3;
#[cfg(feature = "Win32_d2d1effects")]
pub mod d2d1effects;
#[cfg(feature = "Win32_d2d1effects_1")]
pub mod d2d1effects_1;
#[cfg(feature = "Win32_d2d1effects_2")]
pub mod d2d1effects_2;
#[cfg(feature = "Win32_d2d1svg")]
pub mod d2d1svg;
#[cfg(feature = "Win32_d2dbasetypes")]
pub mod d2dbasetypes;
#[cfg(feature = "Win32_d2derr")]
pub mod d2derr;
#[cfg(feature = "Win32_d3d10")]
pub mod d3d10;
#[cfg(feature = "Win32_d3d10_1")]
pub mod d3d10_1;
#[cfg(feature = "Win32_d3d10_1shader")]
pub mod d3d10_1shader;
#[cfg(feature = "Win32_d3d10effect")]
pub mod d3d10effect;
#[cfg(feature = "Win32_d3d10misc")]
pub mod d3d10misc;
#[cfg(feature = "Win32_d3d10sdklayers")]
pub mod d3d10sdklayers;
#[cfg(feature = "Win32_d3d10shader")]
pub mod d3d10shader;
#[cfg(feature = "Win32_d3d11")]
pub mod d3d11;
#[cfg(feature = "Win32_d3d11_1")]
pub mod d3d11_1;
#[cfg(feature = "Win32_d3d11_2")]
pub mod d3d11_2;
#[cfg(feature = "Win32_d3d11_3")]
pub mod d3d11_3;
#[cfg(feature = "Win32_d3d11_4")]
pub mod d3d11_4;
#[cfg(feature = "Win32_d3d11on12")]
pub mod d3d11on12;
#[cfg(feature = "Win32_d3d11sdklayers")]
pub mod d3d11sdklayers;
#[cfg(feature = "Win32_d3d11shader")]
pub mod d3d11shader;
#[cfg(feature = "Win32_d3d12")]
pub mod d3d12;
#[cfg(feature = "Win32_d3d12sdklayers")]
pub mod d3d12sdklayers;
#[cfg(feature = "Win32_d3d12shader")]
pub mod d3d12shader;
#[cfg(feature = "Win32_d3d12video")]
pub mod d3d12video;
#[cfg(feature = "Win32_d3d9")]
pub mod d3d9;
#[cfg(feature = "Win32_d3d9caps")]
pub mod d3d9caps;
#[cfg(feature = "Win32_d3d9types")]
pub mod d3d9types;
#[cfg(feature = "Win32_d3dcommon")]
pub mod d3dcommon;
#[cfg(feature = "Win32_d3dcompiler")]
pub mod d3dcompiler;
#[cfg(feature = "Win32_d3dkmdt")]
pub mod d3dkmdt;
#[cfg(feature = "Win32_d3dkmthk")]
pub mod d3dkmthk;
#[cfg(feature = "Win32_d3dukmdt")]
pub mod d3dukmdt;
#[cfg(feature = "Win32_datetimeapi")]
pub mod datetimeapi;
#[cfg(feature = "Win32_dbgeng")]
pub mod dbgeng;
#[cfg(feature = "Win32_dbghelp")]
pub mod dbghelp;
#[cfg(feature = "Win32_dcommon")]
pub mod dcommon;
#[cfg(feature = "Win32_dcomp")]
pub mod dcomp;
#[cfg(feature = "Win32_dcompanimation")]
pub mod dcompanimation;
#[cfg(feature = "Win32_dcomptypes")]
pub mod dcomptypes;
#[cfg(feature = "Win32_dde")]
pub mod dde;
#[cfg(feature = "Win32_ddeml")]
pub mod ddeml;
#[cfg(feature = "Win32_ddraw")]
pub mod ddraw;
#[cfg(feature = "Win32_debugapi")]
pub mod debugapi;
#[cfg(feature = "Win32_devpropdef")]
pub mod devpropdef;
#[cfg(feature = "Win32_dhcpsapi")]
pub mod dhcpsapi;
#[cfg(feature = "Win32_dinput")]
pub mod dinput;
#[cfg(feature = "Win32_directmanipulation")]
pub mod directmanipulation;
#[cfg(feature = "Win32_directml")]
pub mod directml;
#[cfg(feature = "Win32_dispex")]
pub mod dispex;
#[cfg(feature = "Win32_dlgs")]
pub mod dlgs;
#[cfg(feature = "Win32_dmoreg")]
pub mod dmoreg;
#[cfg(feature = "Win32_dmort")]
pub mod dmort;
#[cfg(feature = "Win32_docobj")]
pub mod docobj;
#[cfg(feature = "Win32_dpa_dsa")]
pub mod dpa_dsa;
#[cfg(feature = "Win32_dpapi")]
pub mod dpapi;
#[cfg(feature = "Win32_dsgetdc")]
pub mod dsgetdc;
#[cfg(feature = "Win32_dshow")]
pub mod dshow;
#[cfg(feature = "Win32_dsound")]
pub mod dsound;
#[cfg(feature = "Win32_dsparse")]
pub mod dsparse;
#[cfg(feature = "Win32_dsrole")]
pub mod dsrole;
#[cfg(feature = "Win32_dvdevcod")]
pub mod dvdevcod;
#[cfg(feature = "Win32_dwmapi")]
pub mod dwmapi;
#[cfg(feature = "Win32_dwrite")]
pub mod dwrite;
#[cfg(feature = "Win32_dwrite_1")]
pub mod dwrite_1;
#[cfg(feature = "Win32_dwrite_2")]
pub mod dwrite_2;
#[cfg(feature = "Win32_dwrite_3")]
pub mod dwrite_3;
#[cfg(feature = "Win32_dxcore")]
pub mod dxcore;
#[cfg(feature = "Win32_dxcore_interface")]
pub mod dxcore_interface;
#[cfg(feature = "Win32_dxgi")]
pub mod dxgi;
#[cfg(feature = "Win32_dxgi1_2")]
pub mod dxgi1_2;
#[cfg(feature = "Win32_dxgi1_3")]
pub mod dxgi1_3;
#[cfg(feature = "Win32_dxgi1_4")]
pub mod dxgi1_4;
#[cfg(feature = "Win32_dxgi1_5")]
pub mod dxgi1_5;
#[cfg(feature = "Win32_dxgi1_6")]
pub mod dxgi1_6;
#[cfg(feature = "Win32_dxgicommon")]
pub mod dxgicommon;
#[cfg(feature = "Win32_dxgidebug")]
pub mod dxgidebug;
#[cfg(feature = "Win32_dxgiformat")]
pub mod dxgiformat;
#[cfg(feature = "Win32_dxgitype")]
pub mod dxgitype;
#[cfg(feature = "Win32_dxva2api")]
pub mod dxva2api;
#[cfg(feature = "Win32_eaptypes")]
pub mod eaptypes;
#[cfg(feature = "Win32_edevdefs")]
pub mod edevdefs;
#[cfg(feature = "Win32_enclaveapi")]
pub mod enclaveapi;
#[cfg(feature = "Win32_errhandlingapi")]
pub mod errhandlingapi;
#[cfg(feature = "Win32_errors")]
pub mod errors;
#[cfg(feature = "Win32_esent")]
pub mod esent;
#[cfg(feature = "Win32_evcode")]
pub mod evcode;
#[cfg(feature = "Win32_evntcons")]
pub mod evntcons;
#[cfg(feature = "Win32_evntprov")]
pub mod evntprov;
#[cfg(feature = "Win32_evntrace")]
pub mod evntrace;
#[cfg(feature = "Win32_evr")]
pub mod evr;
#[cfg(feature = "Win32_excpt")]
pub mod excpt;
#[cfg(feature = "Win32_exdisp")]
pub mod exdisp;
#[cfg(feature = "Win32_exdispid")]
pub mod exdispid;
#[cfg(feature = "Win32_fhcfg")]
pub mod fhcfg;
#[cfg(feature = "Win32_fibersapi")]
pub mod fibersapi;
#[cfg(feature = "Win32_fileapi")]
pub mod fileapi;
#[cfg(feature = "Win32_fileapifromapp")]
pub mod fileapifromapp;
#[cfg(feature = "Win32_filter")]
pub mod filter;
#[cfg(feature = "Win32_filtereg")]
pub mod filtereg;
#[cfg(feature = "Win32_fltuser")]
pub mod fltuser;
#[cfg(feature = "Win32_fltuserstructures")]
pub mod fltuserstructures;
#[cfg(feature = "Win32_fsrm")]
pub mod fsrm;
#[cfg(feature = "Win32_fsrmenums")]
pub mod fsrmenums;
#[cfg(feature = "Win32_fsrmpipeline")]
pub mod fsrmpipeline;
#[cfg(feature = "Win32_functiondiscoveryapi")]
pub mod functiondiscoveryapi;
#[cfg(feature = "Win32_functiondiscoverycategories")]
pub mod functiondiscoverycategories;
#[cfg(feature = "Win32_functiondiscoveryconstraints")]
pub mod functiondiscoveryconstraints;
#[cfg(feature = "Win32_functiondiscoveryerror")]
pub mod functiondiscoveryerror;
#[cfg(feature = "Win32_functiondiscoverykeys")]
pub mod functiondiscoverykeys;
#[cfg(feature = "Win32_functiondiscoverynotification")]
pub mod functiondiscoverynotification;
#[cfg(feature = "Win32_functiondiscoveryserviceids")]
pub mod functiondiscoveryserviceids;
#[cfg(feature = "Win32_fwpmtypes")]
pub mod fwpmtypes;
#[cfg(feature = "Win32_fwpmu")]
pub mod fwpmu;
#[cfg(feature = "Win32_fwptypes")]
pub mod fwptypes;
#[cfg(feature = "Win32_gameux")]
pub mod gameux;
#[cfg(feature = "Win32_gl")]
pub mod gl;
#[cfg(feature = "Win32_gpedit")]
pub mod gpedit;
#[cfg(feature = "Win32_guiddef")]
pub mod guiddef;
#[cfg(feature = "Win32_handleapi")]
pub mod handleapi;
#[cfg(feature = "Win32_hashtypes")]
pub mod hashtypes;
#[cfg(feature = "Win32_heapapi")]
pub mod heapapi;
#[cfg(feature = "Win32_hidclass")]
pub mod hidclass;
#[cfg(feature = "Win32_hidpi")]
pub mod hidpi;
#[cfg(feature = "Win32_hidsdi")]
pub mod hidsdi;
#[cfg(feature = "Win32_hidusage")]
pub mod hidusage;
#[cfg(feature = "Win32_hlink")]
pub mod hlink;
#[cfg(feature = "Win32_hstring")]
pub mod hstring;
#[cfg(feature = "Win32_http")]
pub mod http;
#[cfg(feature = "Win32_httpext")]
pub mod httpext;
#[cfg(feature = "Win32_httpfilt")]
pub mod httpfilt;
#[cfg(feature = "Win32_iads")]
pub mod iads;
#[cfg(feature = "Win32_icm")]
pub mod icm;
#[cfg(feature = "Win32_icmpapi")]
pub mod icmpapi;
#[cfg(feature = "Win32_icu")]
pub mod icu;
#[cfg(feature = "Win32_ifdef")]
pub mod ifdef;
#[cfg(feature = "Win32_ifmib")]
pub mod ifmib;
#[cfg(feature = "Win32_iiscnfg")]
pub mod iiscnfg;
#[cfg(feature = "Win32_iketypes")]
pub mod iketypes;
#[cfg(feature = "Win32_imapi2")]
pub mod imapi2;
#[cfg(feature = "Win32_imapi2fs")]
pub mod imapi2fs;
#[cfg(feature = "Win32_ime_cmodes")]
pub mod ime_cmodes;
#[cfg(feature = "Win32_imm")]
pub mod imm;
#[cfg(feature = "Win32_in6addr")]
pub mod in6addr;
#[cfg(feature = "Win32_inaddr")]
pub mod inaddr;
#[cfg(feature = "Win32_inspectable")]
pub mod inspectable;
#[cfg(feature = "Win32_interlockedapi")]
pub mod interlockedapi;
#[cfg(feature = "Win32_intsafe")]
pub mod intsafe;
#[cfg(feature = "Win32_intshcut")]
pub mod intshcut;
#[cfg(feature = "Win32_ioapiset")]
pub mod ioapiset;
#[cfg(feature = "Win32_ioctltypes")]
pub mod ioctltypes;
#[cfg(feature = "Win32_ipexport")]
pub mod ipexport;
#[cfg(feature = "Win32_iphlpapi")]
pub mod iphlpapi;
#[cfg(feature = "Win32_ipifcons")]
pub mod ipifcons;
#[cfg(feature = "Win32_ipmib")]
pub mod ipmib;
#[cfg(feature = "Win32_iprtrmib")]
pub mod iprtrmib;
#[cfg(feature = "Win32_ipsectypes")]
pub mod ipsectypes;
#[cfg(feature = "Win32_iptypes")]
pub mod iptypes;
#[cfg(feature = "Win32_isguids")]
pub mod isguids;
#[cfg(feature = "Win32_jobapi")]
pub mod jobapi;
#[cfg(feature = "Win32_jobapi2")]
pub mod jobapi2;
#[cfg(feature = "Win32_joystickapi")]
pub mod joystickapi;
#[cfg(feature = "Win32_kernelspecs")]
pub mod kernelspecs;
#[cfg(feature = "Win32_ks")]
pub mod ks;
#[cfg(feature = "Win32_ksmedia")]
pub mod ksmedia;
#[cfg(feature = "Win32_ktmtypes")]
pub mod ktmtypes;
#[cfg(feature = "Win32_ktmw32")]
pub mod ktmw32;
#[cfg(feature = "Win32_l2cmn")]
pub mod l2cmn;
#[cfg(feature = "Win32_libloaderapi")]
pub mod libloaderapi;
#[cfg(feature = "Win32_lmaccess")]
pub mod lmaccess;
#[cfg(feature = "Win32_lmalert")]
pub mod lmalert;
#[cfg(feature = "Win32_lmat")]
pub mod lmat;
#[cfg(feature = "Win32_lmconfig")]
pub mod lmconfig;
#[cfg(feature = "Win32_lmcons")]
pub mod lmcons;
#[cfg(feature = "Win32_lmjoin")]
pub mod lmjoin;
#[cfg(feature = "Win32_lmmsg")]
pub mod lmmsg;
#[cfg(feature = "Win32_lmremutl")]
pub mod lmremutl;
#[cfg(feature = "Win32_lmrepl")]
pub mod lmrepl;
#[cfg(feature = "Win32_lmserver")]
pub mod lmserver;
#[cfg(feature = "Win32_lmshare")]
pub mod lmshare;
#[cfg(feature = "Win32_lmstats")]
pub mod lmstats;
#[cfg(feature = "Win32_lmsvc")]
pub mod lmsvc;
#[cfg(feature = "Win32_lmuse")]
pub mod lmuse;
#[cfg(feature = "Win32_lmuseflg")]
pub mod lmuseflg;
#[cfg(feature = "Win32_lmwksta")]
pub mod lmwksta;
#[cfg(feature = "Win32_locationapi")]
pub mod locationapi;
#[cfg(feature = "Win32_lsalookup")]
pub mod lsalookup;
#[cfg(feature = "Win32_lzexpand")]
pub mod lzexpand;
#[cfg(feature = "Win32_magnification")]
pub mod magnification;
#[cfg(feature = "Win32_mciapi")]
pub mod mciapi;
#[cfg(feature = "Win32_mcx")]
pub mod mcx;
#[cfg(feature = "Win32_mediaobj")]
pub mod mediaobj;
#[cfg(feature = "Win32_memoryapi")]
pub mod memoryapi;
#[cfg(feature = "Win32_memorybuffer")]
pub mod memorybuffer;
#[cfg(feature = "Win32_mfapi")]
pub mod mfapi;
#[cfg(feature = "Win32_mfcaptureengine")]
pub mod mfcaptureengine;
#[cfg(feature = "Win32_mfcontentdecryptionmodule")]
pub mod mfcontentdecryptionmodule;
#[cfg(feature = "Win32_mfd3d12")]
pub mod mfd3d12;
#[cfg(feature = "Win32_mferror")]
pub mod mferror;
#[cfg(feature = "Win32_mfidl")]
pub mod mfidl;
#[cfg(feature = "Win32_mfmediaengine")]
pub mod mfmediaengine;
#[cfg(feature = "Win32_mfobjects")]
pub mod mfobjects;
#[cfg(feature = "Win32_mfplay")]
pub mod mfplay;
#[cfg(feature = "Win32_mfreadwrite")]
pub mod mfreadwrite;
#[cfg(feature = "Win32_mfspatialaudio")]
pub mod mfspatialaudio;
#[cfg(feature = "Win32_mftransform")]
pub mod mftransform;
#[cfg(feature = "Win32_mfvirtualcamera")]
pub mod mfvirtualcamera;
#[cfg(feature = "Win32_minappmodel")]
pub mod minappmodel;
#[cfg(feature = "Win32_minidumpapiset")]
pub mod minidumpapiset;
#[cfg(feature = "Win32_minschannel")]
pub mod minschannel;
#[cfg(feature = "Win32_minwinbase")]
pub mod minwinbase;
#[cfg(feature = "Win32_minwindef")]
pub mod minwindef;
#[cfg(feature = "Win32_mlang")]
pub mod mlang;
#[cfg(feature = "Win32_mmdeviceapi")]
pub mod mmdeviceapi;
#[cfg(feature = "Win32_mmeapi")]
pub mod mmeapi;
#[cfg(feature = "Win32_mmiscapi")]
pub mod mmiscapi;
#[cfg(feature = "Win32_mmiscapi2")]
pub mod mmiscapi2;
#[cfg(feature = "Win32_mmreg")]
pub mod mmreg;
#[cfg(feature = "Win32_mmsyscom")]
pub mod mmsyscom;
#[cfg(feature = "Win32_mmsystem")]
pub mod mmsystem;
#[cfg(feature = "Win32_mprapi")]
pub mod mprapi;
#[cfg(feature = "Win32_mprapidef")]
pub mod mprapidef;
#[cfg(feature = "Win32_mq")]
pub mod mq;
#[cfg(feature = "Win32_msacm")]
pub mod msacm;
#[cfg(feature = "Win32_mscat")]
pub mod mscat;
#[cfg(feature = "Win32_msctf")]
pub mod msctf;
#[cfg(feature = "Win32_msctfmonitorapi")]
pub mod msctfmonitorapi;
#[cfg(feature = "Win32_msdrm")]
pub mod msdrm;
#[cfg(feature = "Win32_msdrmdefs")]
pub mod msdrmdefs;
#[cfg(feature = "Win32_msi")]
pub mod msi;
#[cfg(feature = "Win32_msinkaut")]
pub mod msinkaut;
#[cfg(feature = "Win32_msiquery")]
pub mod msiquery;
#[cfg(feature = "Win32_msopc")]
pub mod msopc;
#[cfg(feature = "Win32_mssip")]
pub mod mssip;
#[cfg(feature = "Win32_mstcpip")]
pub mod mstcpip;
#[cfg(feature = "Win32_mswsock")]
pub mod mswsock;
#[cfg(feature = "Win32_mswsockdef")]
pub mod mswsockdef;
#[cfg(feature = "Win32_msxml")]
pub mod msxml;
#[cfg(feature = "Win32_msxml6")]
pub mod msxml6;
#[cfg(feature = "Win32_msxml6did")]
pub mod msxml6did;
#[cfg(feature = "Win32_namedpipeapi")]
pub mod namedpipeapi;
#[cfg(feature = "Win32_namespaceapi")]
pub mod namespaceapi;
#[cfg(feature = "Win32_nb30")]
pub mod nb30;
#[cfg(feature = "Win32_ncrypt")]
pub mod ncrypt;
#[cfg(feature = "Win32_ncryptprotect")]
pub mod ncryptprotect;
#[cfg(feature = "Win32_ndisport")]
pub mod ndisport;
#[cfg(feature = "Win32_netioapi")]
pub mod netioapi;
#[cfg(feature = "Win32_netlistmgr")]
pub mod netlistmgr;
#[cfg(feature = "Win32_newdev")]
pub mod newdev;
#[cfg(feature = "Win32_nldef")]
pub mod nldef;
#[cfg(feature = "Win32_nserror")]
pub mod nserror;
#[cfg(feature = "Win32_ntddcdrm")]
pub mod ntddcdrm;
#[cfg(feature = "Win32_ntddkbd")]
pub mod ntddkbd;
#[cfg(feature = "Win32_ntddmmc")]
pub mod ntddmmc;
#[cfg(feature = "Win32_ntddmou")]
pub mod ntddmou;
#[cfg(feature = "Win32_ntddndis")]
pub mod ntddndis;
#[cfg(feature = "Win32_ntddscsi")]
pub mod ntddscsi;
#[cfg(feature = "Win32_ntddser")]
pub mod ntddser;
#[cfg(feature = "Win32_ntddstor")]
pub mod ntddstor;
#[cfg(feature = "Win32_ntddtape")]
pub mod ntddtape;
#[cfg(feature = "Win32_ntddvol")]
pub mod ntddvol;
#[cfg(feature = "Win32_ntdsapi")]
pub mod ntdsapi;
#[cfg(feature = "Win32_ntquery")]
pub mod ntquery;
#[cfg(feature = "Win32_ntsecapi")]
pub mod ntsecapi;
#[cfg(feature = "Win32_ntsecpkg")]
pub mod ntsecpkg;
#[cfg(feature = "Win32_ntstatus")]
pub mod ntstatus;
#[cfg(feature = "Win32_nvme")]
pub mod nvme;
#[cfg(feature = "Win32_oaidl")]
pub mod oaidl;
#[cfg(feature = "Win32_objbase")]
pub mod objbase;
#[cfg(feature = "Win32_objectarray")]
pub mod objectarray;
#[cfg(feature = "Win32_objectheader")]
pub mod objectheader;
#[cfg(feature = "Win32_objidl")]
pub mod objidl;
#[cfg(feature = "Win32_objidlbase")]
pub mod objidlbase;
#[cfg(feature = "Win32_ocidl")]
pub mod ocidl;
#[cfg(feature = "Win32_offloadtypes")]
pub mod offloadtypes;
#[cfg(feature = "Win32_oidtypes")]
pub mod oidtypes;
#[cfg(feature = "Win32_ole2")]
pub mod ole2;
#[cfg(feature = "Win32_oleacc")]
pub mod oleacc;
#[cfg(feature = "Win32_oleauto")]
pub mod oleauto;
#[cfg(feature = "Win32_olectl")]
pub mod olectl;
#[cfg(feature = "Win32_oledb")]
pub mod oledb;
#[cfg(feature = "Win32_oleidl")]
pub mod oleidl;
#[cfg(feature = "Win32_patchapi")]
pub mod patchapi;
#[cfg(feature = "Win32_pciprop")]
pub mod pciprop;
#[cfg(feature = "Win32_pdh")]
pub mod pdh;
#[cfg(feature = "Win32_peninputpanel")]
pub mod peninputpanel;
#[cfg(feature = "Win32_pla")]
pub mod pla;
#[cfg(feature = "Win32_playsoundapi")]
pub mod playsoundapi;
#[cfg(feature = "Win32_poclass")]
pub mod poclass;
#[cfg(feature = "Win32_portabledevice")]
pub mod portabledevice;
#[cfg(feature = "Win32_portabledeviceapi")]
pub mod portabledeviceapi;
#[cfg(feature = "Win32_portabledevicetypes")]
pub mod portabledevicetypes;
#[cfg(feature = "Win32_powerbase")]
pub mod powerbase;
#[cfg(feature = "Win32_powersetting")]
pub mod powersetting;
#[cfg(feature = "Win32_powrprof")]
pub mod powrprof;
#[cfg(feature = "Win32_prntvpt")]
pub mod prntvpt;
#[cfg(feature = "Win32_processenv")]
pub mod processenv;
#[cfg(feature = "Win32_processthreadsapi")]
pub mod processthreadsapi;
#[cfg(feature = "Win32_processtopologyapi")]
pub mod processtopologyapi;
#[cfg(feature = "Win32_profileapi")]
pub mod profileapi;
#[cfg(feature = "Win32_profinfo")]
pub mod profinfo;
#[cfg(feature = "Win32_propidl")]
pub mod propidl;
#[cfg(feature = "Win32_propidlbase")]
pub mod propidlbase;
#[cfg(feature = "Win32_propkey")]
pub mod propkey;
#[cfg(feature = "Win32_propsys")]
pub mod propsys;
#[cfg(feature = "Win32_prsht")]
pub mod prsht;
#[cfg(feature = "Win32_psapi")]
pub mod psapi;
#[cfg(feature = "Win32_qos")]
pub mod qos;
#[cfg(feature = "Win32_qos2")]
pub mod qos2;
#[cfg(feature = "Win32_qosobjs")]
pub mod qosobjs;
#[cfg(feature = "Win32_ras")]
pub mod ras;
#[cfg(feature = "Win32_rasdlg")]
pub mod rasdlg;
#[cfg(feature = "Win32_realtimeapiset")]
pub mod realtimeapiset;
#[cfg(feature = "Win32_reason")]
pub mod reason;
#[cfg(feature = "Win32_regbag")]
pub mod regbag;
#[cfg(feature = "Win32_regstr")]
pub mod regstr;
#[cfg(feature = "Win32_restartmanager")]
pub mod restartmanager;
#[cfg(feature = "Win32_restrictederrorinfo")]
pub mod restrictederrorinfo;
#[cfg(feature = "Win32_richedit")]
pub mod richedit;
#[cfg(feature = "Win32_richole")]
pub mod richole;
#[cfg(feature = "Win32_roapi")]
pub mod roapi;
#[cfg(feature = "Win32_robuffer")]
pub mod robuffer;
#[cfg(feature = "Win32_roerrorapi")]
pub mod roerrorapi;
#[cfg(feature = "Win32_rometadata")]
pub mod rometadata;
#[cfg(feature = "Win32_roparameterizediid")]
pub mod roparameterizediid;
#[cfg(feature = "Win32_rpc")]
pub mod rpc;
#[cfg(feature = "Win32_rpcasync")]
pub mod rpcasync;
#[cfg(feature = "Win32_rpcdce")]
pub mod rpcdce;
#[cfg(feature = "Win32_rpcdcep")]
pub mod rpcdcep;
#[cfg(feature = "Win32_rpcndr")]
pub mod rpcndr;
#[cfg(feature = "Win32_rpcnsi")]
pub mod rpcnsi;
#[cfg(feature = "Win32_rpcnsip")]
pub mod rpcnsip;
#[cfg(feature = "Win32_rpcnterr")]
pub mod rpcnterr;
#[cfg(feature = "Win32_rtworkq")]
pub mod rtworkq;
#[cfg(feature = "Win32_sal")]
pub mod sal;
#[cfg(feature = "Win32_sapi")]
pub mod sapi;
#[cfg(feature = "Win32_schannel")]
pub mod schannel;
#[cfg(feature = "Win32_schedule")]
pub mod schedule;
#[cfg(feature = "Win32_sddl")]
pub mod sddl;
#[cfg(feature = "Win32_sdkddkver")]
pub mod sdkddkver;
#[cfg(feature = "Win32_searchapi")]
pub mod searchapi;
#[cfg(feature = "Win32_secext")]
pub mod secext;
#[cfg(feature = "Win32_securityappcontainer")]
pub mod securityappcontainer;
#[cfg(feature = "Win32_securitybaseapi")]
pub mod securitybaseapi;
#[cfg(feature = "Win32_sensapi")]
pub mod sensapi;
#[cfg(feature = "Win32_sensorsapi")]
pub mod sensorsapi;
#[cfg(feature = "Win32_servprov")]
pub mod servprov;
#[cfg(feature = "Win32_setupapi")]
pub mod setupapi;
#[cfg(feature = "Win32_shcore")]
pub mod shcore;
#[cfg(feature = "Win32_shdeprecated")]
pub mod shdeprecated;
#[cfg(feature = "Win32_shdispid")]
pub mod shdispid;
#[cfg(feature = "Win32_shellapi")]
pub mod shellapi;
#[cfg(feature = "Win32_shellscalingapi")]
pub mod shellscalingapi;
#[cfg(feature = "Win32_sherrors")]
pub mod sherrors;
#[cfg(feature = "Win32_shldisp")]
pub mod shldisp;
#[cfg(feature = "Win32_shlguid")]
pub mod shlguid;
#[cfg(feature = "Win32_shlobj")]
pub mod shlobj;
#[cfg(feature = "Win32_shlobj_core")]
pub mod shlobj_core;
#[cfg(feature = "Win32_shlwapi")]
pub mod shlwapi;
#[cfg(feature = "Win32_shobjidl")]
pub mod shobjidl;
#[cfg(feature = "Win32_shobjidl_core")]
pub mod shobjidl_core;
#[cfg(feature = "Win32_shtypes")]
pub mod shtypes;
#[cfg(feature = "Win32_slpublic")]
pub mod slpublic;
#[cfg(feature = "Win32_spapidef")]
pub mod spapidef;
#[cfg(feature = "Win32_spatialaudioclient")]
pub mod spatialaudioclient;
#[cfg(feature = "Win32_spatialaudiometadata")]
pub mod spatialaudiometadata;
#[cfg(feature = "Win32_spellcheck")]
pub mod spellcheck;
#[cfg(feature = "Win32_sql")]
pub mod sql;
#[cfg(feature = "Win32_sqlext")]
pub mod sqlext;
#[cfg(feature = "Win32_sqltypes")]
pub mod sqltypes;
#[cfg(feature = "Win32_sqlucode")]
pub mod sqlucode;
#[cfg(feature = "Win32_sspi")]
pub mod sspi;
#[cfg(feature = "Win32_stgprop")]
pub mod stgprop;
#[cfg(feature = "Win32_sti")]
pub mod sti;
#[cfg(feature = "Win32_stierr")]
pub mod stierr;
#[cfg(feature = "Win32_stireg")]
pub mod stireg;
#[cfg(feature = "Win32_stralign")]
pub mod stralign;
#[cfg(feature = "Win32_stringapiset")]
pub mod stringapiset;
#[cfg(feature = "Win32_strmif")]
pub mod strmif;
#[cfg(feature = "Win32_strsafe")]
pub mod strsafe;
#[cfg(feature = "Win32_structuredquery")]
pub mod structuredquery;
#[cfg(feature = "Win32_structuredquerycondition")]
pub mod structuredquerycondition;
#[cfg(feature = "Win32_synchapi")]
pub mod synchapi;
#[cfg(feature = "Win32_sysinfoapi")]
pub mod sysinfoapi;
#[cfg(feature = "Win32_systemtopologyapi")]
pub mod systemtopologyapi;
#[cfg(feature = "Win32_t2embapi")]
pub mod t2embapi;
#[cfg(feature = "Win32_taskschd")]
pub mod taskschd;
#[cfg(feature = "Win32_tcpestats")]
pub mod tcpestats;
#[cfg(feature = "Win32_tcpmib")]
pub mod tcpmib;
#[cfg(feature = "Win32_tdh")]
pub mod tdh;
#[cfg(feature = "Win32_textserv")]
pub mod textserv;
#[cfg(feature = "Win32_textstor")]
pub mod textstor;
#[cfg(feature = "Win32_threadpoolapiset")]
pub mod threadpoolapiset;
#[cfg(feature = "Win32_threadpoollegacyapiset")]
pub mod threadpoollegacyapiset;
#[cfg(feature = "Win32_timeapi")]
pub mod timeapi;
#[cfg(feature = "Win32_timezoneapi")]
pub mod timezoneapi;
#[cfg(feature = "Win32_tlhelp32")]
pub mod tlhelp32;
#[cfg(feature = "Win32_tlogstg")]
pub mod tlogstg;
#[cfg(feature = "Win32_tom")]
pub mod tom;
#[cfg(feature = "Win32_tpcerror")]
pub mod tpcerror;
#[cfg(feature = "Win32_tpcshrd")]
pub mod tpcshrd;
#[cfg(feature = "Win32_traffic")]
pub mod traffic;
#[cfg(feature = "Win32_transact")]
pub mod transact;
#[cfg(feature = "Win32_tuner")]
pub mod tuner;
#[cfg(feature = "Win32_tvout")]
pub mod tvout;
#[cfg(feature = "Win32_txcoord")]
pub mod txcoord;
#[cfg(feature = "Win32_txdtc")]
pub mod txdtc;
#[cfg(feature = "Win32_txfw32")]
pub mod txfw32;
#[cfg(feature = "Win32_types")]
pub mod types;
#[cfg(feature = "Win32_udpmib")]
pub mod udpmib;
#[cfg(feature = "Win32_uianimation")]
pub mod uianimation;
#[cfg(feature = "Win32_uiautomationclient")]
pub mod uiautomationclient;
#[cfg(feature = "Win32_uiautomationcore")]
pub mod uiautomationcore;
#[cfg(feature = "Win32_unknwnbase")]
pub mod unknwnbase;
#[cfg(feature = "Win32_urlmon")]
pub mod urlmon;
#[cfg(feature = "Win32_usb")]
pub mod usb;
#[cfg(feature = "Win32_usbioctl")]
pub mod usbioctl;
#[cfg(feature = "Win32_usbiodef")]
pub mod usbiodef;
#[cfg(feature = "Win32_usbspec")]
pub mod usbspec;
#[cfg(feature = "Win32_userenv")]
pub mod userenv;
#[cfg(feature = "Win32_usp10")]
pub mod usp10;
#[cfg(feature = "Win32_utilapiset")]
pub mod utilapiset;
#[cfg(feature = "Win32_uxtheme")]
pub mod uxtheme;
#[cfg(feature = "Win32_vadefs")]
pub mod vadefs;
#[cfg(feature = "Win32_vds")]
pub mod vds;
#[cfg(feature = "Win32_vdserr")]
pub mod vdserr;
#[cfg(feature = "Win32_vdslun")]
pub mod vdslun;
#[cfg(feature = "Win32_verrsrc")]
pub mod verrsrc;
#[cfg(feature = "Win32_version")]
pub mod version;
#[cfg(feature = "Win32_vfw")]
pub mod vfw;
#[cfg(feature = "Win32_vfwmsgs")]
pub mod vfwmsgs;
#[cfg(feature = "Win32_vhf")]
pub mod vhf;
#[cfg(feature = "Win32_virtdisk")]
pub mod virtdisk;
#[cfg(feature = "Win32_vsbackup")]
pub mod vsbackup;
#[cfg(feature = "Win32_vss")]
pub mod vss;
#[cfg(feature = "Win32_vsserror")]
pub mod vsserror;
#[cfg(feature = "Win32_vswriter")]
pub mod vswriter;
#[cfg(feature = "Win32_wbemcli")]
pub mod wbemcli;
#[cfg(feature = "Win32_wbemdisp")]
pub mod wbemdisp;
#[cfg(feature = "Win32_wbemprov")]
pub mod wbemprov;
#[cfg(feature = "Win32_wbemtran")]
pub mod wbemtran;
#[cfg(feature = "Win32_wcmapi")]
pub mod wcmapi;
#[cfg(feature = "Win32_wdbgexts")]
pub mod wdbgexts;
#[cfg(feature = "Win32_weakreference")]
pub mod weakreference;
#[cfg(feature = "Win32_webauthn")]
pub mod webauthn;
#[cfg(feature = "Win32_webservices")]
pub mod webservices;
#[cfg(feature = "Win32_websocket")]
pub mod websocket;
#[cfg(feature = "Win32_werapi")]
pub mod werapi;
#[cfg(feature = "Win32_wia_lh")]
pub mod wia_lh;
#[cfg(feature = "Win32_wiadef")]
pub mod wiadef;
#[cfg(feature = "Win32_winapifamily")]
pub mod winapifamily;
#[cfg(feature = "Win32_winbase")]
pub mod winbase;
#[cfg(feature = "Win32_winbio")]
pub mod winbio;
#[cfg(feature = "Win32_winbio_err")]
pub mod winbio_err;
#[cfg(feature = "Win32_winbio_types")]
pub mod winbio_types;
#[cfg(feature = "Win32_wincodec")]
pub mod wincodec;
#[cfg(feature = "Win32_wincodecsdk")]
pub mod wincodecsdk;
#[cfg(feature = "Win32_wincon")]
pub mod wincon;
#[cfg(feature = "Win32_wincontypes")]
pub mod wincontypes;
#[cfg(feature = "Win32_wincred")]
pub mod wincred;
#[cfg(feature = "Win32_wincrypt")]
pub mod wincrypt;
#[cfg(feature = "Win32_windef")]
pub mod windef;
#[cfg(feature = "Win32_windns")]
pub mod windns;
#[cfg(feature = "Win32_windnsdef")]
pub mod windnsdef;
#[cfg(feature = "Win32_windot11")]
pub mod windot11;
#[cfg(feature = "Win32_windowsx")]
pub mod windowsx;
#[cfg(feature = "Win32_winefs")]
pub mod winefs;
#[cfg(feature = "Win32_winerror")]
pub mod winerror;
#[cfg(feature = "Win32_winevt")]
pub mod winevt;
#[cfg(feature = "Win32_wingdi")]
pub mod wingdi;
#[cfg(feature = "Win32_winhttp")]
pub mod winhttp;
#[cfg(feature = "Win32_winhvplatform")]
pub mod winhvplatform;
#[cfg(feature = "Win32_winhvplatformdefs")]
pub mod winhvplatformdefs;
#[cfg(feature = "Win32_wininet")]
pub mod wininet;
#[cfg(feature = "Win32_winioctl")]
pub mod winioctl;
#[cfg(feature = "Win32_winldap")]
pub mod winldap;
#[cfg(feature = "Win32_winnetwk")]
pub mod winnetwk;
#[cfg(feature = "Win32_winnls")]
pub mod winnls;
#[cfg(feature = "Win32_winnt")]
pub mod winnt;
#[cfg(feature = "Win32_winpackagefamily")]
pub mod winpackagefamily;
#[cfg(feature = "Win32_winperf")]
pub mod winperf;
#[cfg(feature = "Win32_winreg")]
pub mod winreg;
#[cfg(feature = "Win32_winsafer")]
pub mod winsafer;
#[cfg(feature = "Win32_winscard")]
pub mod winscard;
#[cfg(feature = "Win32_winsmcrd")]
pub mod winsmcrd;
#[cfg(feature = "Win32_winsock2")]
pub mod winsock2;
#[cfg(feature = "Win32_winspool")]
pub mod winspool;
#[cfg(feature = "Win32_winstring")]
pub mod winstring;
#[cfg(feature = "Win32_winsvc")]
pub mod winsvc;
#[cfg(feature = "Win32_winternl")]
pub mod winternl;
#[cfg(feature = "Win32_wintrust")]
pub mod wintrust;
#[cfg(feature = "Win32_winusb")]
pub mod winusb;
#[cfg(feature = "Win32_winusbio")]
pub mod winusbio;
#[cfg(feature = "Win32_winuser")]
pub mod winuser;
#[cfg(feature = "Win32_winver")]
pub mod winver;
#[cfg(feature = "Win32_wlanapi")]
pub mod wlanapi;
#[cfg(feature = "Win32_wlantypes")]
pub mod wlantypes;
#[cfg(feature = "Win32_wmcodecdsp")]
pub mod wmcodecdsp;
#[cfg(feature = "Win32_wmistr")]
pub mod wmistr;
#[cfg(feature = "Win32_wmiutils")]
pub mod wmiutils;
#[cfg(feature = "Win32_wmp")]
pub mod wmp;
#[cfg(feature = "Win32_wmpids")]
pub mod wmpids;
#[cfg(feature = "Win32_wmsbuffer")]
pub mod wmsbuffer;
#[cfg(feature = "Win32_wmsdkidl")]
pub mod wmsdkidl;
#[cfg(feature = "Win32_wnnc")]
pub mod wnnc;
#[cfg(feature = "Win32_wow64apiset")]
pub mod wow64apiset;
#[cfg(feature = "Win32_wpcapi")]
pub mod wpcapi;
#[cfg(feature = "Win32_ws2bth")]
pub mod ws2bth;
#[cfg(feature = "Win32_ws2def")]
pub mod ws2def;
#[cfg(feature = "Win32_ws2ipdef")]
pub mod ws2ipdef;
#[cfg(feature = "Win32_ws2tcpip")]
pub mod ws2tcpip;
#[cfg(feature = "Win32_wscapi")]
pub mod wscapi;
#[cfg(feature = "Win32_wsdattachment")]
pub mod wsdattachment;
#[cfg(feature = "Win32_wsdbase")]
pub mod wsdbase;
#[cfg(feature = "Win32_wsdclient")]
pub mod wsdclient;
#[cfg(feature = "Win32_wsddisco")]
pub mod wsddisco;
#[cfg(feature = "Win32_wsdhost")]
pub mod wsdhost;
#[cfg(feature = "Win32_wsdns")]
pub mod wsdns;
#[cfg(feature = "Win32_wsdtypes")]
pub mod wsdtypes;
#[cfg(feature = "Win32_wsdutil")]
pub mod wsdutil;
#[cfg(feature = "Win32_wsdxml")]
pub mod wsdxml;
#[cfg(feature = "Win32_wsdxmldom")]
pub mod wsdxmldom;
#[cfg(feature = "Win32_wsmandisp")]
pub mod wsmandisp;
#[cfg(feature = "Win32_wtsapi32")]
pub mod wtsapi32;
#[cfg(feature = "Win32_wtypes")]
pub mod wtypes;
#[cfg(feature = "Win32_wtypesbase")]
pub mod wtypesbase;
#[cfg(feature = "Win32_wuapi")]
pub mod wuapi;
#[cfg(feature = "Win32_xaudio2")]
pub mod xaudio2;
#[cfg(feature = "Win32_xinput")]
pub mod xinput;
#[cfg(feature = "Win32_xmllite")]
pub mod xmllite;
#[cfg(feature = "Win32_xpsobjectmodel")]
pub mod xpsobjectmodel;
#[cfg(feature = "Win32_xpsprint")]
pub mod xpsprint;
