[package]
name = "pickers-standalone"
version = "0.0.0"
edition = "2024"
publish = false

[dependencies]
windows = { workspace = true, features = ["combaseapi", "objbase"] }
windows-pickers = { workspace = true, features = ["system"] }
windows-window = { workspace = true }

[lints]
workspace = true
