#[cfg(feature = "Win32_Foundation")]
::windows_targets::link!("ntdll.dll" "system" #[doc = "*Required features: `\"Wdk_System_SystemInformation\"`, `\"Win32_Foundation\"`*"] fn NtQuerySystemInformation(systeminformationclass : SYSTEM_INFORMATION_CLASS, systeminformation : *mut ::core::ffi::c_void, systeminformationlength : u32, returnlength : *mut u32) -> super::super::super::Win32::Foundation:: NTSTATUS);
#[cfg(feature = "Win32_Foundation")]
::windows_targets::link!("ntdll.dll" "system" #[doc = "*Required features: `\"Wdk_System_SystemInformation\"`, `\"Win32_Foundation\"`*"] fn NtQuerySystemTime(systemtime : *mut i64) -> super::super::super::Win32::Foundation:: NTSTATUS);
#[cfg(feature = "Win32_Foundation")]
::windows_targets::link!("ntdll.dll" "system" #[doc = "*Required features: `\"Wdk_System_SystemInformation\"`, `\"Win32_Foundation\"`*"] fn NtQueryTimerResolution(maximumtime : *mut u32, minimumtime : *mut u32, currenttime : *mut u32) -> super::super::super::Win32::Foundation:: NTSTATUS);
#[doc = "*Required features: `\"Wdk_System_SystemInformation\"`*"]
pub type SYSTEM_INFORMATION_CLASS = i32;
#[doc = "*Required features: `\"Wdk_System_SystemInformation\"`*"]
pub const SystemBasicInformation: SYSTEM_INFORMATION_CLASS = 0i32;
#[doc = "*Required features: `\"Wdk_System_SystemInformation\"`*"]
pub const SystemPerformanceInformation: SYSTEM_INFORMATION_CLASS = 2i32;
#[doc = "*Required features: `\"Wdk_System_SystemInformation\"`*"]
pub const SystemTimeOfDayInformation: SYSTEM_INFORMATION_CLASS = 3i32;
#[doc = "*Required features: `\"Wdk_System_SystemInformation\"`*"]
pub const SystemProcessInformation: SYSTEM_INFORMATION_CLASS = 5i32;
#[doc = "*Required features: `\"Wdk_System_SystemInformation\"`*"]
pub const SystemProcessorPerformanceInformation: SYSTEM_INFORMATION_CLASS = 8i32;
#[doc = "*Required features: `\"Wdk_System_SystemInformation\"`*"]
pub const SystemInterruptInformation: SYSTEM_INFORMATION_CLASS = 23i32;
#[doc = "*Required features: `\"Wdk_System_SystemInformation\"`*"]
pub const SystemExceptionInformation: SYSTEM_INFORMATION_CLASS = 33i32;
#[doc = "*Required features: `\"Wdk_System_SystemInformation\"`*"]
pub const SystemRegistryQuotaInformation: SYSTEM_INFORMATION_CLASS = 37i32;
#[doc = "*Required features: `\"Wdk_System_SystemInformation\"`*"]
pub const SystemLookasideInformation: SYSTEM_INFORMATION_CLASS = 45i32;
#[doc = "*Required features: `\"Wdk_System_SystemInformation\"`*"]
pub const SystemCodeIntegrityInformation: SYSTEM_INFORMATION_CLASS = 103i32;
#[doc = "*Required features: `\"Wdk_System_SystemInformation\"`*"]
pub const SystemPolicyInformation: SYSTEM_INFORMATION_CLASS = 134i32;
