name: linux

permissions:
  contents: read

on:
  pull_request:
    paths-ignore:
      - '.github/ISSUE_TEMPLATE/**'
      - '.github/workflows/web.yml'
      - 'crates/libs/rdl/rdl.md'
      - 'web/**'
  push:
    paths-ignore:
      - '.github/ISSUE_TEMPLATE/**'
      - '.github/workflows/web.yml'
      - 'crates/libs/rdl/rdl.md'
      - 'web/**'
    branches:
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/master' }}

jobs:
  linux:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Update toolchain
        run: rustup update --no-self-update stable && rustup default stable
      - name: Run test_linux
        run: cargo test -p test_linux --target x86_64-unknown-linux-gnu
      - name: Run test_clang
        run: cargo test -p test_clang --target x86_64-unknown-linux-gnu
      - name: Run test_rdl
        run: cargo test -p test_rdl --target x86_64-unknown-linux-gnu
