name: msrv

permissions:
  contents: read

on:
  pull_request:
    paths-ignore:
      - '.github/ISSUE_TEMPLATE/**'
      - '.github/workflows/web.yml'
      - 'crates/libs/rdl/rdl.md'
      - 'web/**'
  push:
    paths-ignore:
      - '.github/ISSUE_TEMPLATE/**'
      - '.github/workflows/web.yml'
      - 'crates/libs/rdl/rdl.md'
      - 'web/**'
    branches:
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/master' }}

jobs:
  msrv:
    runs-on: windows-2025
    strategy:
      matrix:
        include:
# generated - run `cargo run -p tool_yml` to update
          - crate: cppwinrt
            version: "1.74"
          - crate: riddle
            version: "1.82"
          - crate: windows
            version: "1.82"
          - crate: windows-bindgen
            version: "1.82"
          - crate: windows-collections
            version: "1.82"
          - crate: windows-core
            version: "1.82"
          - crate: windows-future
            version: "1.82"
          - crate: windows-implement
            version: "1.74"
          - crate: windows-interface
            version: "1.74"
          - crate: windows-link
            version: "1.71"
          - crate: windows-metadata
            version: "1.82"
          - crate: windows-numerics
            version: "1.82"
          - crate: windows-rdl
            version: "1.82"
          - crate: windows-registry
            version: "1.82"
          - crate: windows-result
            version: "1.82"
          - crate: windows-services
            version: "1.82"
          - crate: windows-strings
            version: "1.82"
          - crate: windows-sys
            version: "1.71"
          - crate: windows-targets
            version: "1.71"
          - crate: windows-threading
            version: "1.82"
          - crate: windows-version
            version: "1.74"
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Cache rustup
        uses: actions/cache@v4
        with:
          path: ~/.rustup/toolchains
          key: rustup-${{ runner.os }}-${{ matrix.version }}
      - name: Update toolchain
        run: rustup update --no-self-update ${{ matrix.version }} && rustup default ${{ matrix.version }}
      - name: Check
        run:  cargo check -p ${{ matrix.crate }} --all-features
