name: publish

permissions:
  contents: read

on:
  push:
    paths-ignore:
      - '.github/ISSUE_TEMPLATE/**'
      - '.github/workflows/web.yml'
      - 'crates/libs/rdl/rdl.md'
      - 'web/**'
    branches:
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/master' }}

jobs:
  publish:
    runs-on: windows-2025-vs2026
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Update toolchain
        run: rustup update --no-self-update stable && rustup default stable
      - uses: Swatinem/rust-cache@v2
      - name: Check
        run: cargo publish --workspace --dry-run
