name: web

on:
  push:
    branches: [master]
    paths:
      - "web/**"
      - ".github/workflows/web.yml"
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Get sources
        uses: actions/checkout@v7

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v5
        with:
          path: ./web

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
