namespace Component
{
    namespace Simple
    {
        runtimeclass Class
        {
            Class();
            void Method();
        }

        interface IInterface
        {
            void Method();
        };

        delegate void Delegate();

        struct Struct
        {
            Int32 First;
            Int32 Second;
        };

        enum Enum
        {
            First,
            Second,
        };
    }

    namespace Enum
    {
        enum Signed
        {
            Three = 3,
            Two = 2,
            One = 1,
        };

        [flags]
        enum Unsigned
        {
            Three = 0x100,
            Two   = 0x010,
            One   = 0x001
        };
    }
}
